# GitLab CI/CD configuration file for ngen repository
include:
  - template: Jobs/Container-Scanning.gitlab-ci.yml

variables:
    GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - unit_test
  - sonarqube
  - test
  - deploy
  - release

image: registry.sh.nextgenwaterprediction.com/infrastructure/docker/docker:latest

variables:
    DOCKER_IMAGE_NAME: $CI_REGISTRY_IMAGE
    DOCKER_IMAGE_TAG: $CI_COMMIT_REF_NAME-test

build:
  stage: build
  before_script:
    - git config --global url."https://oauth2:${GITLAB_TOKEN}@gitlab.sh.nextgenwaterprediction.com/".insteadOf "https://gitlab.sh.nextgenwaterprediction.com/"
    - chown -R `whoami` .
    - git fetch --unshallow || true  # In case we’re in a shallow clone
    - git fetch --prune --prune-tags # Ensures tags are accurate and old ones are removed
    - git submodule update --init --recursive
    - |
      # Prune tags/branches in all submodules
      git submodule foreach --recursive sh -c "
        echo \"Fetching latest with prune in \$name\"
        url=\$(git config --get remote.origin.url)
        git remote set-url origin \${url/https:\/\//https:\/\/oauth2:${GITLAB_TOKEN}@}
        git fetch --prune --prune-tags || echo \"Warning: fetch failed for \$name\"
      "
    - |
      if [[ "$CI_COMMIT_BRANCH" == "release-candidate" ]] || [[ "$CI_COMMIT_BRANCH" == "master" ]]; then
        git submodule set-branch --branch "$CI_COMMIT_BRANCH" extern/cfe/cfe
        git submodule set-branch --branch "$CI_COMMIT_BRANCH" extern/SoilFreezeThaw/SoilFreezeThaw
        git submodule set-branch --branch "$CI_COMMIT_BRANCH" extern/SoilMoistureProfiles/SoilMoistureProfiles
        git submodule set-branch --branch "$CI_COMMIT_BRANCH" extern/evapotranspiration/evapotranspiration
        git submodule set-branch --branch "$CI_COMMIT_BRANCH" extern/noah-owp-modular/noah-owp-modular
        git submodule set-branch --branch "$CI_COMMIT_BRANCH" extern/topmodel/topmodel
        git submodule set-branch --branch "$CI_COMMIT_BRANCH" extern/t-route
        git submodule set-branch --branch "$CI_COMMIT_BRANCH" extern/sloth
        git submodule set-branch --branch "$CI_COMMIT_BRANCH" extern/LASAM
        git submodule set-branch --branch "$CI_COMMIT_BRANCH" extern/snow17
        git submodule set-branch --branch "$CI_COMMIT_BRANCH" extern/sac-sma/sac-sma
        git submodule set-branch --branch "$CI_COMMIT_BRANCH" extern/ueb-bmi
        git submodule set-branch --branch "$CI_COMMIT_BRANCH" extern/lstm
      fi

  script:
    - echo "Logging in to Gitlab Container Registry..."
    - echo $CI_JOB_TOKEN | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - echo "Building ${CI_PROJECT_NAME} docker image.. "
    - docker build --build-arg CI_COMMIT_REF_NAME=${CI_COMMIT_REF_NAME} --tag "$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG" .
    - docker push $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG
    - docker logout

unit-test:
  stage: unit_test
  image: $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG
  script:
    - echo "Running Unit Tests..."
    - cd /ngen-app/ngen/cmake_build
    - ctest || {
        echo "Tests failed. Rerunning failed tests with verbose output...";
        export CTEST_OUTPUT_ON_FAILURE=1;
        ctest --rerun-failed --output-on-failure --verbose;
        exit 1;
      }

sonarqube:
  stage: sonarqube
  image:
    name: registry.sh.nextgenwaterprediction.com/infrastructure/sonar-scanner-cli/sonar-scanner-cli:5.0.1
    entrypoint: [""]
  variables:
    # Defines the location of the analysis task cache
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    # Shallow cloning needs to be disabled.
    # See https://docs.sonarqube.org/latest/analysis/gitlab-cicd/.
    GIT_DEPTH: 0
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - sonar-scanner -X -Dsonar.verbose=true
  allow_failure: true # FIXME

container_scanning:
  stage: test
  needs:
    - build
  variables:
    SECURE_LOG_LEVEL: info
    CS_SEVERITY_THRESHOLD: UNKNOWN
    CS_IMAGE: $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG

deploy:
  stage: deploy
  script:
    - echo "Logging in to Gitlab Container Registry to push the image..."
    - echo $CI_JOB_TOKEN | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - echo "Pushing to the docker registry"
    - docker tag $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG $DOCKER_IMAGE_NAME:latest
    - docker push $DOCKER_IMAGE_NAME:latest
    - docker logout
  rules:
    - if: '$CI_COMMIT_BRANCH == "development"'

release:
  stage: release
  script:
    - echo "Logging in to Gitlab Container Registry to push the image..."
    - echo $CI_JOB_TOKEN | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - echo "Pushing to the docker registry"
    - docker tag $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG $DOCKER_IMAGE_NAME:$CI_COMMIT_TAG
    - docker push $DOCKER_IMAGE_NAME:$CI_COMMIT_TAG
    - docker logout
  rules:
    - if: $CI_COMMIT_TAG
    