image:
  file: .gitpod.Dockerfile
tasks:
  - name: Prebuild
    before: export PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"
    init: |
      python -m venv .venv
      . .venv/bin/activate
      git submodule update --init --recursive extern/
      cmake -S extern/iso_c_fortran_bmi/ -B extern/iso_c_fortran_bmi/cmake_build
      cmake -S extern/test_bmi_c -B extern/test_bmi_c/cmake_build
      cmake -S extern/test_bmi_fortran/ -B extern/test_bmi_fortran/cmake_build
      cmake -S extern/evapotranspiration/ -B extern/evapotranspiration/cmake_build
      cmake -S extern/noah-owp-modular/ -B extern/noah-owp-modular/cmake_build
      cmake -S extern/cfe/ -B extern/cfe/cmake_build
      cmake -S extern/topmodel/ -B extern/topmodel/cmake_build
      cmake --build extern/iso_c_fortran_bmi/cmake_build/ --target all
      cmake --build extern/test_bmi_c/cmake_build/ --target all
      cmake --build extern/test_bmi_fortran/cmake_build/ --target all
      cmake --build extern/evapotranspiration/cmake_build/ --target all
      cmake --build extern/noah-owp-modular/cmake_build/ --target all
      cmake --build extern/cfe/cmake_build/ --target all
      cmake --build extern/topmodel/cmake_build/ --target all
      pip install -r extern/t-route/requirements.txt
      pip install -e extern/t-route/src/ngen_routing
      pip install -e extern/t-route/src/nwm_routing
      pushd extern/t-route/src/python_routing_v02
      ./compiler.sh
      popd
      cmake -S . -B cmake_build -DBMI_C_LIB_ACTIVE=1 -DBMI_FORTRAN_ACTIVE=1
      cmake --build cmake_build --target all
  - name: Workshell
    before: |
      export PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"
      . .venv/bin/activate

    