NGen: hymod_kernel Class Reference
hymod_kernel Class Reference
Hymod kernel class.
#include <Hymod.h>
Static Public Member Functions
static double calc_et (double soil_m, void *et_params)
stub function to simulate losses due to evapotransportation
static int run (double dt, hymod_params params, hymod_state state, hymod_state &new_state, hymod_fluxes &fluxes, double input_flux_meters, void *et_params)
run one time step of hymod
static int mass_check (const hymod_params &params, const hymod_state &current_state, const hymod_state &next_state, const hymod_fluxes &calculated_fluxes, double timestep_seconds)
Detailed Description
Hymod kernel class.
This class implements the hymod hydrological model
Member Function Documentation
calc_et()
static double hymod_kernel::calc_et (double soil_m, void * et_params) inline static
stub function to simulate losses due to evapotransportation
References pdm03_struct::final_height_reservoir.
Referenced by run().
mass_check()
static int hymod_kernel::mass_check (const hymod_params & params, const hymod_state & current_state, const hymod_state & next_state, const hymod_fluxes & calculated_fluxes, double timestep_seconds) inline static
References hymod_fluxes::et_loss_meters, hymod_state::groundwater_storage_meters, hymod_params::n, hymod_fluxes::runoff_meters_per_second, hymod_fluxes::slow_flow_meters_per_second, hymod_state::Sr, and hymod_state::storage_meters.
Referenced by run().
run()
static int hymod_kernel::run (double dt, hymod_params params, hymod_state state, hymod_state & new_state, hymod_fluxes & fluxes, double input_flux_meters, void * et_params) inline static
run one time step of hymod
Parameters
params static parameters for hymod
state model state
new_state model state struct to hold new model state
fluxes model flux object to hold calculated fluxes
input_flux_meters the amount water entering the system this time step
et_params parameters for the et function
References hymod_params::a, hymod_params::activation_threshold_meters_groundwater_reservoir, hymod_params::activation_threshold_meters_nash_cascade_reservoir, hymod_params::b, calc_et(), hymod_fluxes::et_loss_meters, Reservoir::Explicit_Time::Reservoir::get_storage_height_meters(), hymod_state::groundwater_storage_meters, hymod_params::gw_max_storage_meters, hymod_params::Kq, hymod_params::Ks, mass_check(), hymod_params::min_storage_meters, hymod_params::n, hymod_params::nash_max_storage_meters, hymod_params::reservoir_max_velocity_meters_per_second, Reservoir::Explicit_Time::Reservoir::response_meters_per_second(), hymod_fluxes::runoff_meters_per_second, hymod_fluxes::slow_flow_meters_per_second, hymod_params::smax, hymod_state::Sr, and hymod_state::storage_meters.
Referenced by Simple_Lumped_Model_Realization::get_response().
The documentation for this class was generated from the following file:
models/hymod/include/Hymod.h