NGen: bmi::Bmi Class Reference
bmi::Bmi Class Reference abstract
#include <bmi.hpp>
Public Member Functions
virtual void Initialize (std::string config_file)=0
virtual void Update ()=0
virtual void UpdateUntil (double time)=0
virtual void Finalize ()=0
virtual std::string GetComponentName ()=0
virtual int GetInputItemCount ()=0
virtual int GetOutputItemCount ()=0
virtual std::vector< std::string > GetInputVarNames ()=0
virtual std::vector< std::string > GetOutputVarNames ()=0
virtual int GetVarGrid (std::string name)=0
virtual std::string GetVarType (std::string name)=0
virtual std::string GetVarUnits (std::string name)=0
virtual int GetVarItemsize (std::string name)=0
virtual int GetVarNbytes (std::string name)=0
virtual std::string GetVarLocation (std::string name)=0
virtual double GetCurrentTime ()=0
virtual double GetStartTime ()=0
virtual double GetEndTime ()=0
virtual std::string GetTimeUnits ()=0
virtual double GetTimeStep ()=0
virtual void GetValue (std::string name, void *dest)=0
virtual void * GetValuePtr (std::string name)=0
virtual void GetValueAtIndices (std::string name, void *dest, int *inds, int count)=0
virtual void SetValue (std::string name, void *src)=0
virtual void SetValueAtIndices (std::string name, int *inds, int count, void *src)=0
virtual int GetGridRank (const int grid)=0
virtual int GetGridSize (const int grid)=0
virtual std::string GetGridType (const int grid)=0
virtual void GetGridShape (const int grid, int *shape)=0
virtual void GetGridSpacing (const int grid, double *spacing)=0
virtual void GetGridOrigin (const int grid, double *origin)=0
virtual void GetGridX (const int grid, double *x)=0
virtual void GetGridY (const int grid, double *y)=0
virtual void GetGridZ (const int grid, double *z)=0
virtual int GetGridNodeCount (const int grid)=0
virtual int GetGridEdgeCount (const int grid)=0
virtual int GetGridFaceCount (const int grid)=0
virtual void GetGridEdgeNodes (const int grid, int *edge_nodes)=0
virtual void GetGridFaceEdges (const int grid, int *face_edges)=0
virtual void GetGridFaceNodes (const int grid, int *face_nodes)=0
virtual void GetGridNodesPerFace (const int grid, int *nodes_per_face)=0
Member Function Documentation
Finalize()
virtual void bmi::Bmi::Finalize () pure virtual
Implemented in models::bmi::AbstractCLibBmiAdapter< C >, models::bmi::AbstractCLibBmiAdapter< C_Bmi >, models::bmi::AbstractCLibBmiAdapter< Cpp_Bmi >, models::bmi::Bmi_C_Adapter, and models::bmi::Bmi_Cpp_Adapter.
GetComponentName()
virtual std::string bmi::Bmi::GetComponentName () pure virtual
Implemented in models::bmi::Bmi_C_Adapter, and models::bmi::Bmi_Cpp_Adapter.
GetCurrentTime()
virtual double bmi::Bmi::GetCurrentTime () pure virtual
Implemented in models::bmi::Bmi_C_Adapter, and models::bmi::Bmi_Cpp_Adapter.
GetEndTime()
virtual double bmi::Bmi::GetEndTime () pure virtual
Implemented in models::bmi::Bmi_C_Adapter, and models::bmi::Bmi_Cpp_Adapter.
GetGridEdgeCount()
virtual int bmi::Bmi::GetGridEdgeCount (const int grid) pure virtual
Implemented in models::bmi::Bmi_C_Adapter, and models::bmi::Bmi_Cpp_Adapter.
GetGridEdgeNodes()
virtual void bmi::Bmi::GetGridEdgeNodes (const int grid, int * edge_nodes) pure virtual
Implemented in models::bmi::Bmi_C_Adapter, and models::bmi::Bmi_Cpp_Adapter.
GetGridFaceCount()
virtual int bmi::Bmi::GetGridFaceCount (const int grid) pure virtual
Implemented in models::bmi::Bmi_C_Adapter, and models::bmi::Bmi_Cpp_Adapter.
GetGridFaceEdges()
virtual void bmi::Bmi::GetGridFaceEdges (const int grid, int * face_edges) pure virtual
Implemented in models::bmi::Bmi_C_Adapter, and models::bmi::Bmi_Cpp_Adapter.
GetGridFaceNodes()
virtual void bmi::Bmi::GetGridFaceNodes (const int grid, int * face_nodes) pure virtual
Implemented in models::bmi::Bmi_C_Adapter, and models::bmi::Bmi_Cpp_Adapter.
GetGridNodeCount()
virtual int bmi::Bmi::GetGridNodeCount (const int grid) pure virtual
Implemented in models::bmi::Bmi_C_Adapter, and models::bmi::Bmi_Cpp_Adapter.
GetGridNodesPerFace()
virtual void bmi::Bmi::GetGridNodesPerFace (const int grid, int * nodes_per_face) pure virtual
Implemented in models::bmi::Bmi_C_Adapter, and models::bmi::Bmi_Cpp_Adapter.
GetGridOrigin()
virtual void bmi::Bmi::GetGridOrigin (const int grid, double * origin) pure virtual
Implemented in models::bmi::Bmi_C_Adapter, and models::bmi::Bmi_Cpp_Adapter.
GetGridRank()
virtual int bmi::Bmi::GetGridRank (const int grid) pure virtual
Implemented in models::bmi::Bmi_C_Adapter, and models::bmi::Bmi_Cpp_Adapter.
GetGridShape()
virtual void bmi::Bmi::GetGridShape (const int grid, int * shape) pure virtual
Implemented in models::bmi::Bmi_C_Adapter, and models::bmi::Bmi_Cpp_Adapter.
GetGridSize()
virtual int bmi::Bmi::GetGridSize (const int grid) pure virtual
Implemented in models::bmi::Bmi_C_Adapter, and models::bmi::Bmi_Cpp_Adapter.
GetGridSpacing()
virtual void bmi::Bmi::GetGridSpacing (const int grid, double * spacing) pure virtual
Implemented in models::bmi::Bmi_C_Adapter, and models::bmi::Bmi_Cpp_Adapter.
GetGridType()
virtual std::string bmi::Bmi::GetGridType (const int grid) pure virtual
Implemented in models::bmi::Bmi_C_Adapter, and models::bmi::Bmi_Cpp_Adapter.
GetGridX()
virtual void bmi::Bmi::GetGridX (const int grid, double * x) pure virtual
Implemented in models::bmi::Bmi_C_Adapter, and models::bmi::Bmi_Cpp_Adapter.
GetGridY()
virtual void bmi::Bmi::GetGridY (const int grid, double * y) pure virtual
Implemented in models::bmi::Bmi_C_Adapter, and models::bmi::Bmi_Cpp_Adapter.
GetGridZ()
virtual void bmi::Bmi::GetGridZ (const int grid, double * z) pure virtual
Implemented in models::bmi::Bmi_C_Adapter, and models::bmi::Bmi_Cpp_Adapter.
GetInputItemCount()
virtual int bmi::Bmi::GetInputItemCount () pure virtual
Implemented in models::bmi::Bmi_C_Adapter, and models::bmi::Bmi_Cpp_Adapter.
GetInputVarNames()
virtual std::vector< std::string > bmi::Bmi::GetInputVarNames () pure virtual
Implemented in models::bmi::Bmi_C_Adapter, and models::bmi::Bmi_Cpp_Adapter.
GetOutputItemCount()
virtual int bmi::Bmi::GetOutputItemCount () pure virtual
Implemented in models::bmi::Bmi_C_Adapter, and models::bmi::Bmi_Cpp_Adapter.
GetOutputVarNames()
virtual std::vector< std::string > bmi::Bmi::GetOutputVarNames () pure virtual
Implemented in models::bmi::Bmi_C_Adapter, and models::bmi::Bmi_Cpp_Adapter.
GetStartTime()
virtual double bmi::Bmi::GetStartTime () pure virtual
Implemented in models::bmi::Bmi_C_Adapter, and models::bmi::Bmi_Cpp_Adapter.
GetTimeStep()
virtual double bmi::Bmi::GetTimeStep () pure virtual
Implemented in models::bmi::Bmi_C_Adapter, and models::bmi::Bmi_Cpp_Adapter.
GetTimeUnits()
virtual std::string bmi::Bmi::GetTimeUnits () pure virtual
Implemented in models::bmi::Bmi_C_Adapter, and models::bmi::Bmi_Cpp_Adapter.
Referenced by models::bmi::Bmi_Adapter< T >::acquire_time_conversion_factor().
GetValue()
virtual void bmi::Bmi::GetValue (std::string name, void * dest) pure virtual
Implemented in models::bmi::Bmi_C_Adapter, and models::bmi::Bmi_Cpp_Adapter.
Referenced by models::bmi::GetValue().
GetValueAtIndices()
virtual void bmi::Bmi::GetValueAtIndices (std::string name, void * dest, int * inds, int count) pure virtual
Implemented in models::bmi::Bmi_C_Adapter, and models::bmi::Bmi_Cpp_Adapter.
GetValuePtr()
virtual void * bmi::Bmi::GetValuePtr (std::string name) pure virtual
Implemented in models::bmi::Bmi_C_Adapter, and models::bmi::Bmi_Cpp_Adapter.
GetVarGrid()
virtual int bmi::Bmi::GetVarGrid (std::string name) pure virtual
Implemented in models::bmi::Bmi_C_Adapter, and models::bmi::Bmi_Cpp_Adapter.
GetVarItemsize()
virtual int bmi::Bmi::GetVarItemsize (std::string name) pure virtual
Implemented in models::bmi::Bmi_C_Adapter, and models::bmi::Bmi_Cpp_Adapter.
Referenced by models::bmi::GetValue().
GetVarLocation()
virtual std::string bmi::Bmi::GetVarLocation (std::string name) pure virtual
Implemented in models::bmi::Bmi_C_Adapter, and models::bmi::Bmi_Cpp_Adapter.
GetVarNbytes()
virtual int bmi::Bmi::GetVarNbytes (std::string name) pure virtual
Implemented in models::bmi::Bmi_C_Adapter, and models::bmi::Bmi_Cpp_Adapter.
Referenced by models::bmi::GetValue().
GetVarType()
virtual std::string bmi::Bmi::GetVarType (std::string name) pure virtual
Implemented in models::bmi::Bmi_C_Adapter, and models::bmi::Bmi_Cpp_Adapter.
Referenced by models::bmi::GetValue().
GetVarUnits()
virtual std::string bmi::Bmi::GetVarUnits (std::string name) pure virtual
Implemented in models::bmi::Bmi_C_Adapter, and models::bmi::Bmi_Cpp_Adapter.
Initialize()
virtual void bmi::Bmi::Initialize (std::string config_file) pure virtual
Implemented in models::bmi::Bmi_Adapter< T >.
SetValue()
virtual void bmi::Bmi::SetValue (std::string name, void * src) pure virtual
Implemented in models::bmi::Bmi_C_Adapter, and models::bmi::Bmi_Cpp_Adapter.
SetValueAtIndices()
virtual void bmi::Bmi::SetValueAtIndices (std::string name, int * inds, int count, void * src) pure virtual
Implemented in models::bmi::Bmi_C_Adapter, and models::bmi::Bmi_Cpp_Adapter.
Update()
virtual void bmi::Bmi::Update () pure virtual
Implemented in models::bmi::Bmi_C_Adapter, and models::bmi::Bmi_Cpp_Adapter.
UpdateUntil()
virtual void bmi::Bmi::UpdateUntil (double time) pure virtual
Implemented in models::bmi::Bmi_C_Adapter, and models::bmi::Bmi_Cpp_Adapter.
The documentation for this class was generated from the following file:
include/bmi.hpp