NGen: MultiLayerParserTest Class Reference
MultiLayerParserTest Class Reference
Protected Member Functions
MultiLayerParserTest ()
~MultiLayerParserTest () override
void SetUp () override
void TearDown () override
Protected Attributes
std::vector< std::string > path_options
geojson::GeoJSON nexus_collection
geojson::GeoJSON catchment_collection
std::shared_ptr< realization::Formulation_Manager > manager
std::string nexus_data_path
std::string catchment_data_path
std::string realization_config_path
Static Private Member Functions
static std::string find_file (std::vector< std::string > dir_opts, const std::string &basename)
Constructor & Destructor Documentation
MultiLayerParserTest()
MultiLayerParserTest::MultiLayerParserTest () inline protected
References catchment_data_path, find_file(), nexus_data_path, path_options, and realization_config_path.
~MultiLayerParserTest()
MultiLayerParserTest::~MultiLayerParserTest () inline override protected
Member Function Documentation
find_file()
static std::string MultiLayerParserTest::find_file (std::vector< std::string > dir_opts, const std::string & basename) inline static private
References utils::FileChecker::find_first_readable().
Referenced by MultiLayerParserTest().
SetUp()
void MultiLayerParserTest::SetUp () inline override protected
References catchment_collection, catchment_data_path, nexus_collection, nexus_data_path, and geojson::read().
TearDown()
void MultiLayerParserTest::TearDown () inline override protected
Member Data Documentation
catchment_collection
geojson::GeoJSON MultiLayerParserTest::catchment_collection protected
Referenced by SetUp().
catchment_data_path
std::string MultiLayerParserTest::catchment_data_path protected
Referenced by MultiLayerParserTest(), and SetUp().
manager
std::shared_ptr<realization::Formulation_Manager> MultiLayerParserTest::manager protected
nexus_collection
geojson::GeoJSON MultiLayerParserTest::nexus_collection protected
Referenced by SetUp().
nexus_data_path
std::string MultiLayerParserTest::nexus_data_path protected
Referenced by MultiLayerParserTest(), and SetUp().
path_options
std::vector<std::string> MultiLayerParserTest::path_options protected
Initial value:
= {
            "",
            "../",
            "../../",
            "./test/",
            "../test/",
            "../../test/"
        }
Referenced by MultiLayerParserTest().
realization_config_path
std::string MultiLayerParserTest::realization_config_path protected
Referenced by MultiLayerParserTest().
The documentation for this class was generated from the following file:
test/core/multilayer/MultiLayerParserTest.cpp