NGen: data_access::DataProvider< data_type, selection_type > Class Template Reference
data_access::DataProvider< data_type, selection_type > Class Template Reference abstract
#include <DataProvider.hpp>
Public Member Functions
virtual ~DataProvider ()=default
This class provides a generic interface to data services.
virtual const std::vector< std::string > & get_available_variable_names ()=0
Return the variables that are accessable by this data provider.
virtual long get_data_start_time ()=0
Return the first valid time for which data from the request variable can be requested.
virtual long get_data_stop_time ()=0
Return the last valid time for which data from the requested variable can be requested.
virtual long record_duration ()=0
Return the stride in the time dimension.
virtual size_t get_ts_index_for_time (const time_t &epoch_time)=0
Get the index of the data time step that contains the given point in time.
virtual data_type get_value (const selection_type &selector, ReSampleMethod m=SUM)=0
Get the value of a forcing property for an arbitrary time period, converting units if needed.
virtual std::vector< data_type > get_values (const selection_type &selector, ReSampleMethod m=SUM)=0
Get the values of a forcing property for an arbitrary time period, converting units if needed.
virtual bool is_property_sum_over_time_step (const std::string &name)
Constructor & Destructor Documentation
~DataProvider()
template<class data_type , class selection_type > virtual data_access::DataProvider< data_type, selection_type >::~DataProvider () virtual default
This class provides a generic interface to data services.
Member Function Documentation
get_available_variable_names()
template<class data_type , class selection_type > virtual const std::vector< std::string > & data_access::DataProvider< data_type, selection_type >::get_available_variable_names () pure virtual
Return the variables that are accessable by this data provider.
Implemented in data_access::DeferredWrappedProvider, CsvPerFeatureForcingProvider, data_access::WrappedDataProvider, realization::Bmi_Module_Formulation< M >, realization::Bmi_Module_Formulation< models::bmi::Bmi_C_Adapter >, realization::Bmi_Module_Formulation< models::bmi::Bmi_Cpp_Adapter >, and realization::Bmi_Multi_Formulation.
Referenced by data_access::WrappedDataProvider::get_available_variable_names(), data_access::OptionalWrappedDataProvider::isSuppliedByProvider(), and data_access::DeferredWrappedProvider::setWrappedProvider().
get_data_start_time()
template<class data_type , class selection_type > virtual long data_access::DataProvider< data_type, selection_type >::get_data_start_time () pure virtual
Return the first valid time for which data from the request variable can be requested.
Implemented in CsvPerFeatureForcingProvider, data_access::WrappedDataProvider, realization::Bmi_Module_Formulation< M >, realization::Bmi_Module_Formulation< models::bmi::Bmi_C_Adapter >, realization::Bmi_Module_Formulation< models::bmi::Bmi_Cpp_Adapter >, and realization::Bmi_Multi_Formulation.
Referenced by data_access::WrappedDataProvider::get_data_start_time().
get_data_stop_time()
template<class data_type , class selection_type > virtual long data_access::DataProvider< data_type, selection_type >::get_data_stop_time () pure virtual
Return the last valid time for which data from the requested variable can be requested.
Implemented in CsvPerFeatureForcingProvider, data_access::WrappedDataProvider, realization::Bmi_Module_Formulation< M >, realization::Bmi_Module_Formulation< models::bmi::Bmi_C_Adapter >, realization::Bmi_Module_Formulation< models::bmi::Bmi_Cpp_Adapter >, and realization::Bmi_Multi_Formulation.
Referenced by data_access::WrappedDataProvider::get_data_stop_time().
get_ts_index_for_time()
template<class data_type , class selection_type > virtual size_t data_access::DataProvider< data_type, selection_type >::get_ts_index_for_time (const time_t & epoch_time) pure virtual
Get the index of the data time step that contains the given point in time.
An std::out_of_range exception should be thrown if the time is not in any time step.
Parameters
epoch_time The point in time, as a seconds-based epoch time.
Returns
The index of the forcing time step that contains the given point in time.
Exceptions
std::out_of_range If the given point is not in any time step.
Implemented in CsvPerFeatureForcingProvider, data_access::WrappedDataProvider, realization::Bmi_Module_Formulation< M >, realization::Bmi_Module_Formulation< models::bmi::Bmi_C_Adapter >, realization::Bmi_Module_Formulation< models::bmi::Bmi_Cpp_Adapter >, and realization::Bmi_Multi_Formulation.
Referenced by data_access::WrappedDataProvider::get_ts_index_for_time().
get_value()
template<class data_type , class selection_type > virtual data_type data_access::DataProvider< data_type, selection_type >::get_value (const selection_type & selector, ReSampleMethod m = SUM) pure virtual
Get the value of a forcing property for an arbitrary time period, converting units if needed.
An std::out_of_range exception should be thrown if the data for the time period is not available.
Parameters
selector Data required to establish what subset of the stored data should be accessed
m How data is to be resampled if there is a mismatch in data alignment or repeat rate
Returns
The value of the forcing property for the described time period, with units converted if needed.
Exceptions
std::out_of_range If data for the time period is not available.
Implemented in CsvPerFeatureForcingProvider, data_access::OptionalWrappedDataProvider, realization::Bmi_Module_Formulation< M >, realization::Bmi_Module_Formulation< models::bmi::Bmi_C_Adapter >, realization::Bmi_Module_Formulation< models::bmi::Bmi_Cpp_Adapter >, realization::Bmi_Multi_Formulation, and data_access::WrappedDataProvider.
Referenced by data_access::OptionalWrappedDataProvider::get_value(), data_access::WrappedDataProvider::get_value(), and realization::Bmi_Module_Formulation< M >::set_model_inputs_prior_to_update().
get_values()
template<class data_type , class selection_type > virtual std::vector< data_type > data_access::DataProvider< data_type, selection_type >::get_values (const selection_type & selector, ReSampleMethod m = SUM) pure virtual
Get the values of a forcing property for an arbitrary time period, converting units if needed.
An std::out_of_range exception should be thrown if the data for the time period is not available.
If a provider doesn't implement this function, then by default, get_values will be a simple proxy to get_value with the result wrapped in a std::vector<double>
Parameters
output_name The name of the forcing property of interest.
init_time_epoch The epoch time (in seconds) of the start of the time period.
duration_seconds The length of the time period, in seconds.
output_units The expected units of the desired output value.
Returns
std::vector<double> The vector of values of the forcing property for the described time period, with units converted if needed.
Exceptions
std::out_of_range If data for the time period is not available.
Implemented in CsvPerFeatureForcingProvider, realization::Bmi_Multi_Formulation, realization::Bmi_Module_Formulation< M >, realization::Bmi_Module_Formulation< models::bmi::Bmi_C_Adapter >, realization::Bmi_Module_Formulation< models::bmi::Bmi_Cpp_Adapter >, and data_access::WrappedDataProvider.
Referenced by data_access::WrappedDataProvider::get_values(), and realization::Bmi_Module_Formulation< M >::set_model_inputs_prior_to_update().
is_property_sum_over_time_step()
template<class data_type , class selection_type > virtual bool data_access::DataProvider< data_type, selection_type >::is_property_sum_over_time_step (const std::string & name) inline virtual
Reimplemented in CsvPerFeatureForcingProvider, data_access::WrappedDataProvider, realization::Bmi_Module_Formulation< M >, realization::Bmi_Module_Formulation< models::bmi::Bmi_C_Adapter >, realization::Bmi_Module_Formulation< models::bmi::Bmi_Cpp_Adapter >, and realization::Bmi_Multi_Formulation.
Referenced by data_access::WrappedDataProvider::is_property_sum_over_time_step().
record_duration()
template<class data_type , class selection_type > virtual long data_access::DataProvider< data_type, selection_type >::record_duration () pure virtual
Return the stride in the time dimension.
Implemented in CsvPerFeatureForcingProvider, data_access::WrappedDataProvider, realization::Bmi_Module_Formulation< M >, realization::Bmi_Module_Formulation< models::bmi::Bmi_C_Adapter >, realization::Bmi_Module_Formulation< models::bmi::Bmi_Cpp_Adapter >, and realization::Bmi_Multi_Formulation.
Referenced by data_access::WrappedDataProvider::record_duration().
The documentation for this class was generated from the following file:
include/forcing/DataProvider.hpp