NGen: nexus::Nexus_Manager Class Reference
nexus::Nexus_Manager Class Reference
#include <Nexus_Manager.hpp>
Public Member Functions
Nexus_Manager (geojson::GeoJSON nexus)
virtual ~Nexus_Manager ()
virtual void add_nexus (std::shared_ptr< HY_HydroNexus > formulation)
virtual std::shared_ptr< Formulation > get_nexus (std::string id) const
virtual bool contains (std::string identifier) const
virtual int get_size ()
virtual bool is_empty ()
virtual std::map< std::string, std::shared_ptr< HY_HydroNexus > >::const_iterator begin () const
virtual std::map< std::string, std::shared_ptr< HY_HydroNexus > >::const_iterator end () const
Protected Member Functions
std::shared_ptr< HY_HydroNexus > construct_nexus (geojson::Feature nexus_feature, utils::StreamHandler output_stream)
std::shared_ptr< Formulation > construct_missing_formulation (std::string identifier, utils::StreamHandler output_stream, simulation_time_params &simulation_time_config)
Protected Attributes
std::map< std::string, std::shared_ptr< HY_HydroNexus > > nexuses
Constructor & Destructor Documentation
Nexus_Manager()
nexus::Nexus_Manager::Nexus_Manager (geojson::GeoJSON nexus) inline
References add_nexus(), and construct_nexus().
~Nexus_Manager()
virtual nexus::Nexus_Manager::~Nexus_Manager () inline virtual
Member Function Documentation
add_nexus()
virtual void nexus::Nexus_Manager::add_nexus (std::shared_ptr< HY_HydroNexus > formulation) inline virtual
References nexuses.
Referenced by Nexus_Manager().
begin()
virtual std::map< std::string, std::shared_ptr< HY_HydroNexus > >::const_iterator nexus::Nexus_Manager::begin () const inline virtual
References nexuses.
construct_missing_formulation()
std::shared_ptr< Formulation > nexus::Nexus_Manager::construct_missing_formulation (std::string identifier, utils::StreamHandler output_stream, simulation_time_params & simulation_time_config) inline protected
construct_nexus()
std::shared_ptr< HY_HydroNexus > nexus::Nexus_Manager::construct_nexus (geojson::Feature nexus_feature, utils::StreamHandler output_stream) inline protected
References geojson::JSONProperty::as_string(), geojson::JSONProperty::at(), and geojson::JSONProperty::has_key().
Referenced by Nexus_Manager().
contains()
virtual bool nexus::Nexus_Manager::contains (std::string identifier) const inline virtual
References nexuses.
end()
virtual std::map< std::string, std::shared_ptr< HY_HydroNexus > >::const_iterator nexus::Nexus_Manager::end () const inline virtual
References nexuses.
get_nexus()
virtual std::shared_ptr< Formulation > nexus::Nexus_Manager::get_nexus (std::string id) const inline virtual
References nexuses.
get_size()
virtual int nexus::Nexus_Manager::get_size () inline virtual
Returns
The number of elements within the collection
References nexuses.
is_empty()
virtual bool nexus::Nexus_Manager::is_empty () inline virtual
Returns
Whether or not the collection is empty
References nexuses.
Member Data Documentation
nexuses
std::map<std::string, std::shared_ptr<HY_HydroNexus> > nexus::Nexus_Manager::nexuses protected
Referenced by add_nexus(), begin(), contains(), end(), get_nexus(), get_size(), and is_empty().
The documentation for this class was generated from the following file:
include/realizations/nexus/Nexus_Manager.hpp