NGen: tshirt::tshirt_model Class Reference
tshirt::tshirt_model Class Reference
Tshirt model class.
#include <Tshirt.h>
Public Member Functions
tshirt_model (tshirt_params model_params, const shared_ptr< tshirt_state > &initial_state)
Constructor for model object based on model parameters and initial state.
tshirt_model (tshirt_params model_params)
Constructor for model object with parameters only.
double calc_evapotranspiration (double soil_m, shared_ptr< pdm03_struct > et_params)
Calculate losses due to evapotranspiration.
double calc_soil_field_capacity_storage_threshold ()
Calculate soil field capacity storage threshold, the level at which free drainage stops (i.e., "Sfc").
shared_ptr< tshirt_state > get_current_state ()
Return the smart pointer to the tshirt::tshirt_model struct for holding this object's current state.
shared_ptr< tshirt_fluxes > get_fluxes ()
Return the shared pointer to the tshirt::tshirt_fluxes struct for holding this object's current fluxes.
double get_mass_check_error_bound ()
Get the size of the error bound that is acceptable when performing mass check calculations.
int mass_check (double input_storage_m, double timestep_s)
Check that mass was conserved by the model's calculations of the current time step.
int run (double dt, double input_storage_m, shared_ptr< pdm03_struct > et_params)
Run the model to one time step, after performing initial housekeeping steps via a call to manage_state_before_next_time_step_run.
Protected Member Functions
virtual void manage_state_before_next_time_step_run ()
Perform necessary steps prior to the execution of model calculations for a new time step, for managing member variables that contain model state.
void set_mass_check_error_bound (double error_bound)
Set the mass_check_error_bound member to the absolute value of the given parameter.
Private Member Functions
void check_valid ()
Check that the current state of this model object (which could be its provided initial state) is valid, printing a message and raising an error if not.
void initialize_groundwater_reservoir ()
Initialize the subsurface groundwater reservoir for the model, in the groundwater_reservoir member field.
void initialize_soil_reservoir ()
Initialize the subsurface soil reservoir for the model, in the soil_reservoir member field.
void initialize_subsurface_lateral_flow_nash_cascade ()
Initialize the Nash Cascade reservoirs applied to the subsurface soil reservoir's lateral flow outlet.
Private Attributes
shared_ptr< tshirt_state > current_state
Model state for the "current" time step, which may not be calculated yet.
tshirt_params model_params
Model execution parameters.
shared_ptr< tshirt_state > previous_state
Model state from that previous time step before the current.
vector< unique_ptr< Reservoir::Explicit_Time::Reservoir > > soil_lf_nash_res
A collection of reservoirs for a Nash Cascade at the end of the lateral flow output from the subsurface soil reservoir.
int lf_outlet_index = 1
The index of the subsurface lateral flow outlet in the soil reservoir.
int perc_outlet_index = 0
The index of the percolation flow outlet in the soil reservoir.
Reservoir::Explicit_Time::Reservoir soil_reservoir
Reservoir::Explicit_Time::Reservoir groundwater_reservoir
shared_ptr< tshirt_fluxes > fluxes
double mass_check_error_bound
The size of the error bound that is acceptable when performing mass check calculations.
double soil_field_capacity_storage_threshold
Soil field capacity storage threshold, or the level at which free drainage stops (i.e., "Sfc").
Detailed Description
Tshirt model class.
Object oriented implementation of the Tshirt hydrological model, as documented at: https://github.com/NOAA-OWP/ngen/blob/master/doc/T-shirt_model_description.pdf
The core logic for the model is implemented within the run function. The resulting state calculated by a call to run is stored by a struct referenced via the current_state member. A previous_state member also exists for holding the state prior to the most recent call to run. Calculated fluxes are held by the fluxes member, for which there is not 'previous' analog.
How state members are adjusted at the start of a call to run should be controlled via the implementation of manage_state_before_next_time_step_run.
Calls to run will return the result of a nested call to mass_check, which performs mass balance verification on the calculated state at the end of a call to run. The amount of acceptable difference is accessible with the get_mass_check_error_bound function. It is also possible to change the value of this (hard-coded in the default implementation) with the protected set_mass_check_error_bound function.
Constructor & Destructor Documentation
tshirt_model() [1/2]
tshirt::tshirt_model::tshirt_model (tshirt_params model_params, const shared_ptr< tshirt_state > & initial_state)
Constructor for model object based on model parameters and initial state.
Parameters
model_params Model parameters tshirt_params struct.
initial_state Shared smart pointer to tshirt_state struct hold initial state values
References calc_soil_field_capacity_storage_threshold(), check_valid(), fluxes, initialize_groundwater_reservoir(), initialize_soil_reservoir(), initialize_subsurface_lateral_flow_nash_cascade(), mass_check_error_bound, and soil_field_capacity_storage_threshold.
tshirt_model() [2/2]
tshirt::tshirt_model::tshirt_model (tshirt_params model_params)
Constructor for model object with parameters only.
Constructor creates a "default" initial state, with soil_storage_meters and groundwater_storage_meters set to 0.0, and then otherwise proceeds as the constructor accepting the second parameter for initial state.
Parameters
model_params Model parameters tshirt_params struct.
Member Function Documentation
calc_evapotranspiration()
double tshirt::tshirt_model::calc_evapotranspiration (double soil_m, shared_ptr< pdm03_struct > et_params)
Calculate losses due to evapotranspiration.
Parameters
soil_m
et_params
Returns
Parameters
soil_m The soil moisture measured in meters.
et_params A shared pointer to the struct holding the ET parameters.
Returns
The calculated loss value due to evapotranspiration.
Referenced by run().
calc_soil_field_capacity_storage_threshold()
double tshirt::tshirt_model::calc_soil_field_capacity_storage_threshold ()
Calculate soil field capacity storage threshold, the level at which free drainage stops (i.e., "Sfc").
Returns
The calculated soil field capacity storage.
References tshirt::tshirt_params::alpha_fc, tshirt::tshirt_params::b, tshirt::tshirt_params::depth, tshirt::tshirt_params::maxsmc, model_params, and tshirt::tshirt_params::satpsi.
Referenced by tshirt_model().
check_valid()
void tshirt::tshirt_model::check_valid () private
Check that the current state of this model object (which could be its provided initial state) is valid, printing a message and raising an error if not.
The model parameter for Nash Cascade size, nash_n, must correspond appropriately to the size of referenced current_state->nash_cascade_storeage_meters vector. The latter holds the storage values of the individual reservoirs within the Nash Cascade. Note that the function will interpret any nash_n greater than 0 as valid if the vector itself is empty, and initialize such a vector to the correct size with all 0.0 values.
References current_state, model_params, and tshirt::tshirt_params::nash_n.
Referenced by tshirt_model().
get_current_state()
shared_ptr< tshirt_state > tshirt::tshirt_model::get_current_state ()
Return the smart pointer to the tshirt::tshirt_model struct for holding this object's current state.
Returns
The smart pointer to the tshirt_model struct for holding this object's current state.
References current_state.
get_fluxes()
shared_ptr< tshirt_fluxes > tshirt::tshirt_model::get_fluxes ()
Return the shared pointer to the tshirt::tshirt_fluxes struct for holding this object's current fluxes.
Returns
The shared pointer to the tshirt_fluxes struct for holding this object's current fluxes.
References fluxes.
get_mass_check_error_bound()
double tshirt::tshirt_model::get_mass_check_error_bound ()
Get the size of the error bound that is acceptable when performing mass check calculations.
Returns
The size of the error bound that is acceptable when performing mass check calculations.
See also
tshirt_model::mass_check
References mass_check_error_bound.
Referenced by mass_check().
initialize_groundwater_reservoir()
void tshirt::tshirt_model::initialize_groundwater_reservoir () private
Initialize the subsurface groundwater reservoir for the model, in the groundwater_reservoir member field.
Initialize the subsurface groundwater reservoir for the model as a Reservoir object, creating the reservoir with a single outlet. In particular, this is a Reservoir_Exponential_Outlet object, since the outlet requires the following be used to calculate discharge flow:
 Cgw * ( exp(expon * S / S_max) - 1 );
Note that this function should only be used during object construction.
See also
Reservoir
Reservoir_Exponential_Outlet
References tshirt::tshirt_params::Cgw, tshirt::tshirt_params::expon, groundwater_reservoir, tshirt::tshirt_params::max_groundwater_storage_meters, model_params, and previous_state.
Referenced by tshirt_model().
initialize_soil_reservoir()
void tshirt::tshirt_model::initialize_soil_reservoir () private
Initialize the subsurface soil reservoir for the model, in the soil_reservoir member field.
Initialize the subsurface soil reservoir for the model as a Reservoir object, creating the reservoir with outlets for both the subsurface lateral flow and the percolation flow. This should only be used during object construction.
Per the class type of the reservoir, outlets have an associated index value within a reservoir, and certain outlet-specific functionality requires having appropriate outlet index. These outlet indexes are maintained in for the lateral flow and percolation flow outlets are maintained this class within the lf_outlet_index and perc_outlet_index member variables respectively.
See also
Reservoir
References tshirt::tshirt_params::Klf, lf_outlet_index, tshirt::tshirt_params::max_lateral_flow, tshirt::tshirt_params::max_soil_storage_meters, model_params, perc_outlet_index, previous_state, tshirt::tshirt_params::satdk, tshirt::tshirt_params::slope, soil_field_capacity_storage_threshold, and soil_reservoir.
Referenced by tshirt_model().
initialize_subsurface_lateral_flow_nash_cascade()
void tshirt::tshirt_model::initialize_subsurface_lateral_flow_nash_cascade () private
Initialize the Nash Cascade reservoirs applied to the subsurface soil reservoir's lateral flow outlet.
Initialize the soil_lf_nash_res member, containing the collection of Reservoir objects used to create the Nash Cascade for soil_reservoir lateral flow outlet. The analogous values for Nash Cascade storage from previous_state are used for current storage of reservoirs at each given index.
References tshirt::tshirt_params::Kn, tshirt::tshirt_params::max_lateral_flow, tshirt::tshirt_params::max_soil_storage_meters, model_params, tshirt::tshirt_params::nash_n, previous_state, and soil_lf_nash_res.
Referenced by tshirt_model().
manage_state_before_next_time_step_run()
void tshirt::tshirt_model::manage_state_before_next_time_step_run () protected virtual
Perform necessary steps prior to the execution of model calculations for a new time step, for managing member variables that contain model state.
This function is intended to be run only at the start of a new execution of the tshirt_model::run method. It performs three housekeeping tasks needed before running the next group of time step modeling operations:
 * the initial maintained `current_state` is moved to `previous_state`
 * a new `current_state` is created
 * a new `fluxes` is created
References current_state, fluxes, model_params, tshirt::tshirt_params::nash_n, and previous_state.
Referenced by run().
mass_check()
int tshirt::tshirt_model::mass_check (double input_storage_m, double timestep_s)
Check that mass was conserved by the model's calculations of the current time step.
Parameters
input_storage_m The amount of water input to the system at the time step, in meters.
timestep_s The size of the time step, in seconds.
Returns
The appropriate code value indicating whether mass was conserved in the current time step's calculations.
References current_state, fluxes, get_mass_check_error_bound(), previous_state, tshirt::TSHIRT_MASS_BALANCE_ERROR, and tshirt::TSHIRT_NO_ERROR.
Referenced by run().
run()
int tshirt::tshirt_model::run (double dt, double input_storage_m, shared_ptr< pdm03_struct > et_params)
Run the model to one time step, after performing initial housekeeping steps via a call to manage_state_before_next_time_step_run.
Parameters
dt the time step
input_storage_m the amount water entering the system this time step, in meters
et_params ET parameters struct
Returns
Parameters
dt the time step size in seconds
input_storage_m the amount water entering the system this time step, in meters
Returns
References calc_evapotranspiration(), tshirt::tshirt_params::Cschaake, current_state, fluxes, Reservoir::Explicit_Time::Reservoir::get_storage_height_meters(), groundwater_reservoir, lf_outlet_index, manage_state_before_next_time_step_run(), mass_check(), tshirt::tshirt_params::max_soil_storage_meters, model_params, perc_outlet_index, previous_state, Reservoir::Explicit_Time::Reservoir::response_meters_per_second(), soil_lf_nash_res, soil_reservoir, and Reservoir::Explicit_Time::Reservoir::velocity_meters_per_second_for_outlet().
set_mass_check_error_bound()
void tshirt::tshirt_model::set_mass_check_error_bound (double error_bound) protected
Set the mass_check_error_bound member to the absolute value of the given parameter.
Parameters
error_bound The value used to set the mass_check_error_bound member.
References mass_check_error_bound.
Member Data Documentation
current_state
shared_ptr<tshirt_state> tshirt::tshirt_model::current_state private
Model state for the "current" time step, which may not be calculated yet.
Referenced by check_valid(), get_current_state(), manage_state_before_next_time_step_run(), mass_check(), and run().
fluxes
shared_ptr<tshirt_fluxes> tshirt::tshirt_model::fluxes private
Referenced by tshirt_model(), get_fluxes(), manage_state_before_next_time_step_run(), mass_check(), and run().
groundwater_reservoir
Reservoir::Explicit_Time::Reservoir tshirt::tshirt_model::groundwater_reservoir private
Referenced by initialize_groundwater_reservoir(), and run().
lf_outlet_index
int tshirt::tshirt_model::lf_outlet_index = 1 private
The index of the subsurface lateral flow outlet in the soil reservoir.
Referenced by initialize_soil_reservoir(), and run().
mass_check_error_bound
double tshirt::tshirt_model::mass_check_error_bound private
The size of the error bound that is acceptable when performing mass check calculations.
Referenced by tshirt_model(), get_mass_check_error_bound(), and set_mass_check_error_bound().
model_params
tshirt_params tshirt::tshirt_model::model_params private
Model execution parameters.
Referenced by calc_soil_field_capacity_storage_threshold(), check_valid(), initialize_groundwater_reservoir(), initialize_soil_reservoir(), initialize_subsurface_lateral_flow_nash_cascade(), manage_state_before_next_time_step_run(), and run().
perc_outlet_index
int tshirt::tshirt_model::perc_outlet_index = 0 private
The index of the percolation flow outlet in the soil reservoir.
Referenced by initialize_soil_reservoir(), and run().
previous_state
shared_ptr<tshirt_state> tshirt::tshirt_model::previous_state private
Model state from that previous time step before the current.
Referenced by initialize_groundwater_reservoir(), initialize_soil_reservoir(), initialize_subsurface_lateral_flow_nash_cascade(), manage_state_before_next_time_step_run(), mass_check(), and run().
soil_field_capacity_storage_threshold
double tshirt::tshirt_model::soil_field_capacity_storage_threshold private
Soil field capacity storage threshold, or the level at which free drainage stops (i.e., "Sfc").
Referenced by tshirt_model(), and initialize_soil_reservoir().
soil_lf_nash_res
vector<unique_ptr<Reservoir::Explicit_Time::Reservoir> > tshirt::tshirt_model::soil_lf_nash_res private
A collection of reservoirs for a Nash Cascade at the end of the lateral flow output from the subsurface soil reservoir.
Referenced by initialize_subsurface_lateral_flow_nash_cascade(), and run().
soil_reservoir
Reservoir::Explicit_Time::Reservoir tshirt::tshirt_model::soil_reservoir private
Referenced by initialize_soil_reservoir(), and run().
The documentation for this class was generated from the following files:
models/tshirt/include/Tshirt.h
src/models/tshirt/Tshirt.cpp