NGen: geopackage::sqlite_iter Class Reference
geopackage::sqlite_iter Class Reference
SQLite3 row iterator.
#include <NGen_SQLite.hpp>
Public Member Functions
sqlite_iter (stmt_t stmt)
bool done () const noexcept
Check if a row iterator is finished.
sqlite_iter & next ()
Step into the next row of a SQLite query.
sqlite_iter & restart ()
Restart an iteration to its initial state.
int current_row () const noexcept
Get the current row index for the iterator.
int num_columns () const noexcept
Get the number of columns within this iterator.
int column_index (const std::string &name) const noexcept
Return the column index for a named column.
const std::vector< std::string > & columns () const noexcept
Get a vector of column names.
const std::vector< int > & types () const noexcept
Get a vector of column types.
template<typename T >
T get (int col) const
Get a column value from a row iterator by index.
template<typename T >
T get (const std::string &) const
Get a column value from a row iterator by name.
template<>
double get (int col) const
template<>
int get (int col) const
Private Member Functions
sqlite3_stmt * ptr () const noexcept
void handle_get_index (int) const
Private Attributes
stmt_t stmt
int iteration_step = -1
bool iteration_finished = false
int column_count
std::vector< std::string > column_names
std::vector< int > column_types
Detailed Description
SQLite3 row iterator.
Provides a simple iterator-like implementation over rows of a SQLite3 query.
Constructor & Destructor Documentation
sqlite_iter()
sqlite_iter::sqlite_iter (stmt_t stmt)
References column_count, column_names, column_types, next(), ptr(), and restart().
Member Function Documentation
column_index()
int sqlite_iter::column_index (const std::string & name) const noexcept
Return the column index for a named column.
Parameters
name column name to search for
Returns
int index of given column name, or -1 if not found.
Referenced by get().
columns()
const std::vector< std::string > & geopackage::sqlite_iter::columns () const inline noexcept
Get a vector of column names.
Returns
const std::vector<std::string>& column names as a vector of strings
References column_names.
Referenced by geopackage::build_properties().
current_row()
int sqlite_iter::current_row () const noexcept
Get the current row index for the iterator.
Returns
int the current row index, or -1 if next() hasn't been called
References iteration_step.
Referenced by handle_get_index().
done()
bool sqlite_iter::done () const noexcept
Check if a row iterator is finished.
Returns
true if next() returned SQLITE_DONE
false if there is more rows available
References iteration_finished.
Referenced by handle_get_index(), and next().
get() [1/4]
template<typename T > T geopackage::sqlite_iter::get (const std::string & name) const inline
Get a column value from a row iterator by name.
Template Parameters
T Type to parse value as, i.e. int
Returns
T value at the named column
References column_index().
get() [2/4]
template<typename T > T geopackage::sqlite_iter::get (int col) const
Get a column value from a row iterator by index.
Template Parameters
T Type to parse value as, i.e. int
Parameters
col Column index to parse
Returns
T value at column col
Referenced by geopackage::build_feature(), and geopackage::build_geometry().
get() [3/4]
template<> double geopackage::sqlite_iter::get (int col) const
References handle_get_index(), and ptr().
get() [4/4]
template<> int geopackage::sqlite_iter::get (int col) const
References handle_get_index(), and ptr().
handle_get_index()
void sqlite_iter::handle_get_index (int col) const private
References column_count, current_row(), and done().
Referenced by get().
next()
sqlite_iter & sqlite_iter::next ()
Step into the next row of a SQLite query.
If the query is finished, next() acts idempotently, but will change done() to return true.
Returns
sqlite_iter& returns itself
References done(), iteration_finished, iteration_step, and ptr().
Referenced by sqlite_iter().
num_columns()
int sqlite_iter::num_columns () const noexcept
Get the number of columns within this iterator.
Returns
int number of columns in query
References column_count.
ptr()
sqlite3_stmt * sqlite_iter::ptr () const private noexcept
References stmt.
Referenced by sqlite_iter(), get(), next(), and restart().
restart()
sqlite_iter & sqlite_iter::restart ()
Restart an iteration to its initial state.
next() must be called after calling this.
Returns
sqlite_iter& returns itself
References iteration_finished, iteration_step, and ptr().
Referenced by sqlite_iter().
types()
const std::vector< int > & geopackage::sqlite_iter::types () const inline noexcept
Get a vector of column types.
See https://www.sqlite.org/datatype3.html for type values. The integers are the affinity for data types.
Returns
const std::vector<int>& column types as a vector of ints
References column_types.
Referenced by geopackage::build_properties().
Member Data Documentation
column_count
int geopackage::sqlite_iter::column_count private
Referenced by sqlite_iter(), handle_get_index(), and num_columns().
column_names
std::vector<std::string> geopackage::sqlite_iter::column_names private
Referenced by sqlite_iter(), and columns().
column_types
std::vector<int> geopackage::sqlite_iter::column_types private
Referenced by sqlite_iter(), and types().
iteration_finished
bool geopackage::sqlite_iter::iteration_finished = false private
Referenced by done(), next(), and restart().
iteration_step
int geopackage::sqlite_iter::iteration_step = -1 private
Referenced by current_row(), next(), and restart().
stmt
stmt_t geopackage::sqlite_iter::stmt private
Referenced by ptr().
The documentation for this class was generated from the following files:
include/geopackage/NGen_SQLite.hpp
src/geopackage/sqlite/iterator.cpp