NGen: realization::Raw_Realization_Config_Reader Class Reference
realization::Raw_Realization_Config_Reader Class Reference
#include <Realization_Config_Reader.hpp>
Public Member Functions
Raw_Realization_Config_Reader (boost::property_tree::ptree &tree)
void read ()
Realization_Config get_global_configuration ()
virtual ~Raw_Realization_Config_Reader ()
Destructor.
Realization_Config get (std::string identifier) const
bool contains (std::string identifier) const
int get_size ()
bool is_empty ()
std::map< std::string, Realization_Config >::const_iterator begin () const
std::map< std::string, Realization_Config >::const_iterator end () const
Private Attributes
boost::property_tree::ptree tree
std::map< std::string, realization::Realization_Config > realization_configs
realization::Realization_Config global_realization_config = nullptr
Constructor & Destructor Documentation
Raw_Realization_Config_Reader()
realization::Raw_Realization_Config_Reader::Raw_Realization_Config_Reader (boost::property_tree::ptree & tree) inline
~Raw_Realization_Config_Reader()
virtual realization::Raw_Realization_Config_Reader::~Raw_Realization_Config_Reader () inline virtual
Destructor.
Member Function Documentation
begin()
std::map< std::string, Realization_Config >::const_iterator Raw_Realization_Config_Reader::begin () const
References realization_configs.
contains()
bool Raw_Realization_Config_Reader::contains (std::string identifier) const
References realization_configs.
Referenced by get().
end()
std::map< std::string, Realization_Config >::const_iterator Raw_Realization_Config_Reader::end () const
References realization_configs.
get()
Realization_Config Raw_Realization_Config_Reader::get (std::string identifier) const
References contains(), global_realization_config, and realization_configs.
get_global_configuration()
Realization_Config realization::Raw_Realization_Config_Reader::get_global_configuration () inline
References global_realization_config.
get_size()
int Raw_Realization_Config_Reader::get_size ()
Returns
The number of elements within the collection
References realization_configs.
Referenced by is_empty().
is_empty()
bool Raw_Realization_Config_Reader::is_empty ()
Returns
Whether or not the collection is empty
References get_size().
read()
void Raw_Realization_Config_Reader::read ()
References realization::get_realizationconfig(), global_realization_config, realization_configs, and tree.
Member Data Documentation
global_realization_config
realization::Realization_Config realization::Raw_Realization_Config_Reader::global_realization_config = nullptr private
Referenced by get(), get_global_configuration(), and read().
realization_configs
std::map<std::string, realization::Realization_Config> realization::Raw_Realization_Config_Reader::realization_configs private
Referenced by begin(), contains(), end(), get(), get_size(), and read().
tree
boost::property_tree::ptree realization::Raw_Realization_Config_Reader::tree private
Referenced by read().
The documentation for this class was generated from the following files:
include/realizations/catchment/Realization_Config_Reader.hpp
src/realizations/catchment/Realization_Config_Reader.cpp