NGen: data_access::WrappedForcingProvider Class Reference
data_access::WrappedForcingProvider Class Reference
Simple implementation that basically wraps another instance.
#include <WrappedForcingProvider.hpp>
Public Member Functions
WrappedForcingProvider (GenericDataProvider *provider)
Primary constructor for instances.
WrappedForcingProvider (WrappedForcingProvider &provider_to_copy)
Copy constructor.
WrappedForcingProvider (WrappedForcingProvider &&provider_to_move)
Move constructor.
const std::vector< std::string > & get_available_forcing_outputs ()
const std::vector< std::string > & get_avaliable_variable_names () override
Get the avaliable variable names object.
time_t get_forcing_output_time_begin (const std::string &output_name)
Get the inclusive beginning of the period of time over which this instance can provide data for this forcing.
long get_data_start_time () override
Get the inclusive beginning of the period of time over which this instance can provide data for this forcing.
time_t get_forcing_output_time_end (const std::string &output_name)
Get the exclusive ending of the period of time over which this instance can provide data for this forcing.
long get_data_stop_time () override
Get the exclusive ending of the period of time over which this instance can provide data for this forcing.
long record_duration () override
Return the stride in the time dimension.
size_t get_ts_index_for_time (const time_t &epoch_time) override
Get the index of the forcing time step that contains the given point in time.
double get_value (const CatchmentAggrDataSelector &selector, ReSampleMethod m) override
Get the value of a forcing property for an arbitrary time period, converting units if needed.
std::vector< double > get_values (const CatchmentAggrDataSelector &selector, ReSampleMethod m) override
Get the values of a forcing property for an arbitrary time period, converting units if needed.
bool is_property_sum_over_time_step (const std::string &name) override
Get whether a property's per-time-step values are each an aggregate sum over the entire time step.
Protected Attributes
GenericDataProvider * wrapped_provider
Detailed Description
Simple implementation that basically wraps another instance.
The primary purpose is to support self-referencing as a forcing provider (e.g., for ET) without introducing any circular references in smart pointers.
Instances of this type must be used carefully, as they do not contain any mechanisms for making sure they actually point to a valid backing object.
Constructor & Destructor Documentation
WrappedForcingProvider() [1/3]
data_access::WrappedForcingProvider::WrappedForcingProvider (GenericDataProvider * provider) inline explicit
Primary constructor for instances.
Parameters
provider Simple pointer to some existing ForcingProvider object for this new instance to wrap.
WrappedForcingProvider() [2/3]
data_access::WrappedForcingProvider::WrappedForcingProvider (WrappedForcingProvider & provider_to_copy) inline
Copy constructor.
Parameters
provider_to_copy
WrappedForcingProvider() [3/3]
data_access::WrappedForcingProvider::WrappedForcingProvider (WrappedForcingProvider && provider_to_move) inline
Move constructor.
Parameters
provider_to_move
Member Function Documentation
get_available_forcing_outputs()
const std::vector< std::string > & data_access::WrappedForcingProvider::get_available_forcing_outputs () inline
References data_access::DataProvider< data_type, selection_type >::get_avaliable_variable_names(), and wrapped_provider.
get_avaliable_variable_names()
const std::vector< std::string > & data_access::WrappedForcingProvider::get_avaliable_variable_names () inline override virtual
Get the avaliable variable names object.
Returns
const std::vector<std::string>& the names of avaliable data variables
Implements data_access::DataProvider< double, CatchmentAggrDataSelector >.
References data_access::DataProvider< data_type, selection_type >::get_avaliable_variable_names(), and wrapped_provider.
get_data_start_time()
long data_access::WrappedForcingProvider::get_data_start_time () inline override virtual
Get the inclusive beginning of the period of time over which this instance can provide data for this forcing.
Returns
The inclusive beginning of the period of time over which this instance can provide this data.
Implements data_access::DataProvider< double, CatchmentAggrDataSelector >.
References data_access::DataProvider< data_type, selection_type >::get_data_start_time(), and wrapped_provider.
get_data_stop_time()
long data_access::WrappedForcingProvider::get_data_stop_time () inline override virtual
Get the exclusive ending of the period of time over which this instance can provide data for this forcing.
Returns
The exclusive ending of the period of time over which this instance can provide this data.
Implements data_access::DataProvider< double, CatchmentAggrDataSelector >.
References data_access::DataProvider< data_type, selection_type >::get_data_stop_time(), and wrapped_provider.
get_forcing_output_time_begin()
time_t data_access::WrappedForcingProvider::get_forcing_output_time_begin (const std::string & output_name) inline
Get the inclusive beginning of the period of time over which this instance can provide data for this forcing.
Returns
The inclusive beginning of the period of time over which this instance can provide this data.
References data_access::DataProvider< data_type, selection_type >::get_data_start_time(), and wrapped_provider.
get_forcing_output_time_end()
time_t data_access::WrappedForcingProvider::get_forcing_output_time_end (const std::string & output_name) inline
Get the exclusive ending of the period of time over which this instance can provide data for this forcing.
Returns
The exclusive ending of the period of time over which this instance can provide this data.
References data_access::DataProvider< data_type, selection_type >::get_data_stop_time(), and wrapped_provider.
get_ts_index_for_time()
size_t data_access::WrappedForcingProvider::get_ts_index_for_time (const time_t & epoch_time) inline override virtual
Get the index of the forcing time step that contains the given point in time.
An std::out_of_range exception should be thrown if the time is not in any time step.
Parameters
epoch_time The point in time, as a seconds-based epoch time.
Returns
The index of the forcing time step that contains the given point in time.
Exceptions
std::out_of_range If the given point is not in any time step.
Implements data_access::DataProvider< double, CatchmentAggrDataSelector >.
References data_access::DataProvider< data_type, selection_type >::get_ts_index_for_time(), and wrapped_provider.
get_value()
double data_access::WrappedForcingProvider::get_value (const CatchmentAggrDataSelector & selector, ReSampleMethod m) inline override virtual
Get the value of a forcing property for an arbitrary time period, converting units if needed.
An std::out_of_range exception should be thrown if the data for the time period is not available.
Parameters
output_name The name of the forcing property of interest.
init_time_epoch The epoch time (in seconds) of the start of the time period.
duration_seconds The length of the time period, in seconds.
output_units The expected units of the desired output value.
Returns
The value of the forcing property for the described time period, with units converted if needed.
Exceptions
std::out_of_range If data for the time period is not available.
Implements data_access::DataProvider< double, CatchmentAggrDataSelector >.
References data_access::DataProvider< data_type, selection_type >::get_value(), and wrapped_provider.
get_values()
std::vector< double > data_access::WrappedForcingProvider::get_values (const CatchmentAggrDataSelector & selector, ReSampleMethod m) inline override virtual
Get the values of a forcing property for an arbitrary time period, converting units if needed.
An std::out_of_range exception should be thrown if the data for the time period is not available.
If a provider doesn't implement this function, then by default, get_values will be a simple proxy to get_value with the result wrapped in a std::vector<double>
Parameters
output_name The name of the forcing property of interest.
init_time_epoch The epoch time (in seconds) of the start of the time period.
duration_seconds The length of the time period, in seconds.
output_units The expected units of the desired output value.
Returns
std::vector<double> The vector of values of the forcing property for the described time period, with units converted if needed.
Exceptions
std::out_of_range If data for the time period is not available.
Implements data_access::DataProvider< double, CatchmentAggrDataSelector >.
References data_access::DataProvider< data_type, selection_type >::get_values(), and wrapped_provider.
is_property_sum_over_time_step()
bool data_access::WrappedForcingProvider::is_property_sum_over_time_step (const std::string & name) inline override virtual
Get whether a property's per-time-step values are each an aggregate sum over the entire time step.
Certain properties, like rain fall, are aggregated sums over an entire time step. Others, such as pressure, are not such sums and instead something else like an instantaneous reading or an average value.
It may be the case that forcing data is needed for some discretization different than the forcing time step. This aspect must be known in such cases to perform the appropriate value interpolation.
Parameters
name The name of the forcing property for which the current value is desired.
Returns
Whether the property's value is an aggregate sum.
Reimplemented from data_access::DataProvider< double, CatchmentAggrDataSelector >.
References data_access::DataProvider< data_type, selection_type >::is_property_sum_over_time_step(), and wrapped_provider.
record_duration()
long data_access::WrappedForcingProvider::record_duration () inline override virtual
Return the stride in the time dimension.
Implements data_access::DataProvider< double, CatchmentAggrDataSelector >.
References data_access::DataProvider< data_type, selection_type >::record_duration(), and wrapped_provider.
Member Data Documentation
wrapped_provider
GenericDataProvider* data_access::WrappedForcingProvider::wrapped_provider protected
Referenced by data_access::DeferredWrappedProvider::DeferredWrappedProvider(), data_access::OptionalWrappedProvider::OptionalWrappedProvider(), get_available_forcing_outputs(), get_avaliable_variable_names(), get_data_start_time(), get_data_stop_time(), get_forcing_output_time_begin(), get_forcing_output_time_end(), get_ts_index_for_time(), data_access::OptionalWrappedProvider::get_value(), get_value(), get_values(), is_property_sum_over_time_step(), data_access::OptionalWrappedProvider::isSuppliedByWrappedProvider(), data_access::DeferredWrappedProvider::isWrappedProviderSet(), record_duration(), data_access::DeferredWrappedProvider::setWrappedProvider(), and data_access::OptionalWrappedProvider::setWrappedProvider().
The documentation for this class was generated from the following file:
include/forcing/WrappedForcingProvider.hpp