NGen: forcing::ForcingProvider Class Reference
forcing::ForcingProvider Class Reference abstract
An abstraction interface for types that provides forcing data.
#include <ForcingProvider.hpp>
Public Member Functions
virtual const std::vector< std::string > & get_available_forcing_outputs ()=0
virtual time_t get_forcing_output_time_begin (const std::string &output_name)=0
Get the inclusive beginning of the period of time over which this instance can provide data for this forcing.
virtual time_t get_forcing_output_time_end (const std::string &output_name)=0
Get the exclusive ending of the period of time over which this instance can provide data for this forcing.
virtual size_t get_ts_index_for_time (const time_t &epoch_time)=0
Get the index of the forcing time step that contains the given point in time.
virtual double get_value (const std::string &output_name, const time_t &init_time, const long &duration_s, const std::string &output_units)=0
Get the value of a forcing property for an arbitrary time period, converting units if needed.
virtual bool is_property_sum_over_time_step (const std::string &name)=0
Get whether a property's per-time-step values are each an aggregate sum over the entire time step.
Detailed Description
An abstraction interface for types that provides forcing data.
Data may be pre-provided from some external source, internally calculated by the implementing type, or some combination of both.
Member Function Documentation
get_available_forcing_outputs()
virtual const std::vector<std::string>& forcing::ForcingProvider::get_available_forcing_outputs () pure virtual
Implemented in realization::Bmi_Module_Formulation< M >, realization::Bmi_Module_Formulation< models::bmi::Bmi_C_Adapter >, forcing::WrappedForcingProvider, and Forcing.
Referenced by forcing::WrappedForcingProvider::get_available_forcing_outputs().
get_forcing_output_time_begin()
virtual time_t forcing::ForcingProvider::get_forcing_output_time_begin (const std::string & output_name) pure virtual
Get the inclusive beginning of the period of time over which this instance can provide data for this forcing.
Returns
The inclusive beginning of the period of time over which this instance can provide this data.
Implemented in forcing::WrappedForcingProvider, Forcing, realization::Bmi_Multi_Formulation, realization::Bmi_Module_Formulation< M >, and realization::Bmi_Module_Formulation< models::bmi::Bmi_C_Adapter >.
Referenced by forcing::WrappedForcingProvider::get_forcing_output_time_begin().
get_forcing_output_time_end()
virtual time_t forcing::ForcingProvider::get_forcing_output_time_end (const std::string & output_name) pure virtual
Get the exclusive ending of the period of time over which this instance can provide data for this forcing.
Returns
The exclusive ending of the period of time over which this instance can provide this data.
Implemented in realization::Bmi_Module_Formulation< M >, realization::Bmi_Module_Formulation< models::bmi::Bmi_C_Adapter >, forcing::WrappedForcingProvider, Forcing, and realization::Bmi_Multi_Formulation.
Referenced by forcing::WrappedForcingProvider::get_forcing_output_time_end().
get_ts_index_for_time()
virtual size_t forcing::ForcingProvider::get_ts_index_for_time (const time_t & epoch_time) pure virtual
Get the index of the forcing time step that contains the given point in time.
An std::out_of_range exception should be thrown if the time is not in any time step.
Parameters
epoch_time The point in time, as a seconds-based epoch time.
Returns
The index of the forcing time step that contains the given point in time.
Exceptions
std::out_of_range If the given point is not in any time step.
Implemented in forcing::WrappedForcingProvider, Forcing, realization::Bmi_Multi_Formulation, realization::Bmi_Module_Formulation< M >, and realization::Bmi_Module_Formulation< models::bmi::Bmi_C_Adapter >.
Referenced by forcing::WrappedForcingProvider::get_ts_index_for_time().
get_value()
virtual double forcing::ForcingProvider::get_value (const std::string & output_name, const time_t & init_time, const long & duration_s, const std::string & output_units) pure virtual
Get the value of a forcing property for an arbitrary time period, converting units if needed.
An std::out_of_range exception should be thrown if the data for the time period is not available.
Parameters
output_name The name of the forcing property of interest.
init_time_epoch The epoch time (in seconds) of the start of the time period.
duration_seconds The length of the time period, in seconds.
output_units The expected units of the desired output value.
Returns
The value of the forcing property for the described time period, with units converted if needed.
Exceptions
std::out_of_range If data for the time period is not available.
Implemented in forcing::WrappedForcingProvider, Forcing, realization::Bmi_Multi_Formulation, realization::Bmi_Module_Formulation< M >, and realization::Bmi_Module_Formulation< models::bmi::Bmi_C_Adapter >.
Referenced by forcing::WrappedForcingProvider::get_value(), and realization::Bmi_Module_Formulation< M >::set_model_inputs_prior_to_update().
is_property_sum_over_time_step()
virtual bool forcing::ForcingProvider::is_property_sum_over_time_step (const std::string & name) pure virtual
Get whether a property's per-time-step values are each an aggregate sum over the entire time step.
Certain properties, like rain fall, are aggregated sums over an entire time step. Others, such as pressure, are not such sums and instead something else like an instantaneous reading or an average value.
It may be the case that forcing data is needed for some discretization different than the forcing time step. This aspect must be known in such cases to perform the appropriate value interpolation.
Parameters
name The name of the forcing property for which the current value is desired.
Returns
Whether the property's value is an aggregate sum.
Implemented in realization::Bmi_Module_Formulation< M >, realization::Bmi_Module_Formulation< models::bmi::Bmi_C_Adapter >, forcing::WrappedForcingProvider, and Forcing.
Referenced by forcing::WrappedForcingProvider::is_property_sum_over_time_step().
The documentation for this class was generated from the following file:
include/forcing/ForcingProvider.hpp