NGen: geojson::FeatureVisitor Class Reference
geojson::FeatureVisitor Class Reference abstract
An abstract class used to operate on the children of FeatureBase.
#include <FeatureVisitor.hpp>
Public Member Functions
virtual void visit (PointFeature *feature)=0
Perform an action on a PointFeature.
virtual void visit (LineStringFeature *feature)=0
virtual void visit (PolygonFeature *feature)=0
virtual void visit (MultiPointFeature *feature)=0
virtual void visit (MultiLineStringFeature *feature)=0
virtual void visit (MultiPolygonFeature *feature)=0
virtual void visit (CollectionFeature *feature)=0
Detailed Description
An abstract class used to operate on the children of FeatureBase.
Member Function Documentation
visit() [1/7]
virtual void geojson::FeatureVisitor::visit (CollectionFeature * feature) pure virtual
Implemented in Visitor.
visit() [2/7]
virtual void geojson::FeatureVisitor::visit (LineStringFeature * feature) pure virtual
Implemented in Visitor.
visit() [3/7]
virtual void geojson::FeatureVisitor::visit (MultiLineStringFeature * feature) pure virtual
Implemented in Visitor.
visit() [4/7]
virtual void geojson::FeatureVisitor::visit (MultiPointFeature * feature) pure virtual
Implemented in Visitor.
visit() [5/7]
virtual void geojson::FeatureVisitor::visit (MultiPolygonFeature * feature) pure virtual
Implemented in Visitor.
visit() [6/7]
virtual void geojson::FeatureVisitor::visit (PointFeature * feature) pure virtual
Perform an action on a PointFeature.
Parameters
feature A pointer to the point feature to operate upon
Implemented in Visitor.
Referenced by geojson::CollectionFeature::visit(), geojson::LineStringFeature::visit(), geojson::MultiLineStringFeature::visit(), geojson::MultiPointFeature::visit(), geojson::MultiPolygonFeature::visit(), geojson::PointFeature::visit(), and geojson::PolygonFeature::visit().
visit() [7/7]
virtual void geojson::FeatureVisitor::visit (PolygonFeature * feature) pure virtual
Implemented in Visitor.
The documentation for this class was generated from the following file:
include/geojson/FeatureVisitor.hpp