NGen: Network_Test1 Class Reference
Network_Test1 Class Reference
Public Member Functions
Network_Test1 ()
void SetUp () override
~Network_Test1 ()
Protected Member Functions
void add_catchment (std::string id, std::string to_id)
void add_nexus (std::string id, std::string to_id={})
std::shared_ptr< geojson::FeatureCollection > get_fabric ()
Protected Attributes
std::shared_ptr< geojson::FeatureCollection > catchments = std::make_shared<geojson::FeatureCollection>()
std::shared_ptr< geojson::FeatureCollection > nexuses = std::make_shared<geojson::FeatureCollection>()
std::string link_key = "toid"
Network n
Constructor & Destructor Documentation
Network_Test1()
Network_Test1::Network_Test1 () inline
~Network_Test1()
Network_Test1::~Network_Test1 () inline
Member Function Documentation
add_catchment()
void Network_Test::add_catchment (std::string id, std::string to_id) inline protected inherited
References Network_Test::catchments, Network_Test::link_key, and geojson::polygon().
Referenced by SetUp(), and Network_Test2::SetUp().
add_nexus()
void Network_Test::add_nexus (std::string id, std::string to_id = {}) inline protected inherited
Referenced by SetUp(), and Network_Test2::SetUp().
get_fabric()
std::shared_ptr< geojson::FeatureCollection > Network_Test::get_fabric () inline protected inherited
References Network_Test::catchments, Network_Test::link_key, and Network_Test::nexuses.
Referenced by SetUp(), and Network_Test2::SetUp().
SetUp()
void Network_Test1::SetUp () inline override
References Network_Test::add_catchment(), Network_Test::add_nexus(), Network_Test::catchments, Network_Test::get_fabric(), Network_Test::link_key, and Network_Test::n.
Member Data Documentation
catchments
std::shared_ptr<geojson::FeatureCollection> Network_Test::catchments = std::make_shared<geojson::FeatureCollection>() protected inherited
Referenced by Network_Test::add_catchment(), Network_Test::get_fabric(), and SetUp().
link_key
std::string Network_Test::link_key = "toid" protected inherited
Referenced by Network_Test::add_catchment(), Network_Test::get_fabric(), and SetUp().
n
Network Network_Test::n protected inherited
Referenced by SetUp(), and Network_Test2::SetUp().
nexuses
std::shared_ptr<geojson::FeatureCollection> Network_Test::nexuses = std::make_shared<geojson::FeatureCollection>() protected inherited
Referenced by Network_Test::get_fabric().
The documentation for this class was generated from the following file:
test/core/NetworkTests.cpp