NGen: Forcing Class Reference
Forcing Class Reference
Forcing class providing time-series precipiation forcing data to the model.
#include <Forcing.h>
Public Types
typedef struct tm time_type
Public Member Functions
Forcing ()
Default Constructor building an empty Forcing object.
Forcing (forcing_params forcing_config)
Forcing (double air_temperature_fahrenheit, double catchment_id, string forcing_file_name, std::shared_ptr< time_type > start_date_time, std::shared_ptr< time_type > end_date_time)
Parameterized Constuctor that builds a Forcing object and reads an input forcing CSV into a vector.
struct AORC_data get_aorc_for_index (size_t index)
const std::vector< std::string > & get_available_forcing_outputs () override
double get_converted_value_for_param_in_units (const std::string &name, const std::string &units_str, int index)
Placeholder implementation for function to return the given param adjusted to be in the supplied units.
double get_converted_value_for_param_in_units (const std::string &name, const std::string &units_str)
Placeholder implementation for function to return the given param adjusted to be in the supplied units.
time_t get_forcing_output_time_begin (const std::string &output_name) override
Get the inclusive beginning of the period of time over which this instance can provide data for this forcing.
time_t get_forcing_output_time_end (const std::string &output_name) override
Get the exclusive ending of the period of time over which this instance can provide data for this forcing.
size_t get_ts_index_for_time (const time_t &epoch_time) override
Get the index of the forcing time step that contains the given point in time.
double get_value (const std::string &output_name, const time_t &init_time, const long &duration_s, const std::string &output_units) override
Get the value of a forcing property for an arbitrary time period, converting units if needed.
double get_value_for_param_name (const std::string &name, int index)
Get the current value of a forcing param identified by its name.
void check_forcing_vector_index_bounds ()
Checks forcing vector index bounds and adjusts index if out of vector bounds ///.
double get_current_hourly_precipitation_meters_per_second ()
Gets current hourly precipitation in meters per second Precipitation frequency is assumed to be hourly for now.
double get_next_hourly_precipitation_meters_per_second ()
Gets next hourly precipitation in meters per second Increments pointer in forcing vector by one timestep Precipitation frequency is assumed to be hourly for now.
int get_day_of_year ()
Gets day of year integer.
time_t get_time_epoch ()
Accessor to time epoch.
time_t get_time_step_size ()
Get the time step size, based on epoch vector, assuming the last ts is equal to the next to last.
AORC_data get_AORC_data ()
Accessor to AORC data struct.
double get_AORC_APCP_surface_kg_per_meters_squared ()
Accessor to AORC APCP_surface_kg_per_meters_squared.
double get_AORC_DLWRF_surface_W_per_meters_squared ()
Accessor to AORC DLWRF_surface_W_per_meters_squared.
double get_AORC_DSWRF_surface_W_per_meters_squared ()
Accessor to AORC DSWRF_surface_W_per_meters_squared.
double get_AORC_PRES_surface_Pa ()
Accessor to AORC PRES_surface_Pa.
double get_AORC_SPFH_2maboveground_kg_per_kg ()
Accessor to AORC SPFH_2maboveground_kg_per_kg.
double get_AORC_TMP_2maboveground_K ()
Accessor to AORC TMP_2maboveground_K.
double get_AORC_UGRD_10maboveground_meters_per_second ()
Accessor to AORC UGRD_10maboveground_meters_per_second.
double get_AORC_VGRD_10maboveground_meters_per_second ()
Accessor to AORC VGRD_10maboveground_meters_per_second.
bool is_aorc_forcing ()
bool is_param_sum_over_time_step (const std::string &name)
Get whether a param's value is an aggregate sum over the entire time step.
bool is_property_sum_over_time_step (const std::string &name) override
Get whether a property's per-time-step values are each an aggregate sum over the entire time step.
Static Public Member Functions
static std::shared_ptr< std::set< std::string > > get_forcing_field_names ()
Get supported standard names for forcing fields.
Private Member Functions
void read_forcing (string file_name)
Read Forcing Data from CSV Reads only data within the specified model start and end date-times and adds to precipiation vector.
void read_forcing_aorc (string file_name)
Read Forcing Data from AORC CSV Reads only data within the specified model start and end date-times and adds to precipiation vector.
Private Attributes
std::vector< std::string > available_forcings
vector< AORC_data > AORC_vector
bool is_aorc_data = false
Whether this forcing instance has read in full AORC data or just precipitation_rate_meters_per_second_vector.
vector< double > precipitation_rate_meters_per_second_vector
vector< time_t > time_epoch_vector
int forcing_vector_index
double precipitation_rate_meters_per_second
double air_temperature_fahrenheit
double latitude
double longitude
int catchment_id
int day_of_year
string forcing_file_name
std::shared_ptr< time_type > start_date_time
std::shared_ptr< time_type > end_date_time
time_t start_date_time_epoch
time_t end_date_time_epoch
time_t current_date_time_epoch
Detailed Description
Forcing class providing time-series precipiation forcing data to the model.
Member Typedef Documentation
time_type
typedef struct tm Forcing::time_type
Constructor & Destructor Documentation
Forcing() [1/3]
Forcing::Forcing () inline
Default Constructor building an empty Forcing object.
Forcing() [2/3]
Forcing::Forcing (forcing_params forcing_config) inline
References forcing_params::path, and read_forcing_aorc().
Forcing() [3/3]
Forcing::Forcing (double air_temperature_fahrenheit, double catchment_id, string forcing_file_name, std::shared_ptr< time_type > start_date_time, std::shared_ptr< time_type > end_date_time) inline
Parameterized Constuctor that builds a Forcing object and reads an input forcing CSV into a vector.
Parameters
air_temperature_fahrenheit Air temperatrure in Fahrenheit
catchment_id Catchment ID
forcing_file_name Forcing file name
start_date_time Start date-time of model to select start of forcing time window of data
end_date_time End date-time of model to select end of forcing time window of data ///
Todo:
: when using catchment_id parameter, need to enforce their explicit inclusion when calling constructors instead of allowing default ID of 0.
References current_date_time_epoch, end_date_time, end_date_time_epoch, forcing_file_name, forcing_vector_index, read_forcing_aorc(), start_date_time, and start_date_time_epoch.
Member Function Documentation
check_forcing_vector_index_bounds()
void Forcing::check_forcing_vector_index_bounds () inline
Checks forcing vector index bounds and adjusts index if out of vector bounds ///.
Todo:
: Bounds checking is based on precipitation vector.
Consider potential for vectors of different sizes and indices.
Todo:
: Return appropriate warning
Todo:
: Return appropriate warning
References forcing_vector_index, and precipitation_rate_meters_per_second_vector.
Referenced by get_AORC_APCP_surface_kg_per_meters_squared(), get_AORC_data(), get_AORC_DLWRF_surface_W_per_meters_squared(), get_AORC_DSWRF_surface_W_per_meters_squared(), get_AORC_PRES_surface_Pa(), get_AORC_SPFH_2maboveground_kg_per_kg(), get_AORC_TMP_2maboveground_K(), get_AORC_UGRD_10maboveground_meters_per_second(), get_AORC_VGRD_10maboveground_meters_per_second(), get_converted_value_for_param_in_units(), get_current_hourly_precipitation_meters_per_second(), get_day_of_year(), get_time_epoch(), and get_time_step_size().
get_AORC_APCP_surface_kg_per_meters_squared()
double Forcing::get_AORC_APCP_surface_kg_per_meters_squared () inline
Accessor to AORC APCP_surface_kg_per_meters_squared.
Returns
APCP_surface_kg_per_meters_squared
References AORC_vector, check_forcing_vector_index_bounds(), and forcing_vector_index.
get_AORC_data()
AORC_data Forcing::get_AORC_data () inline
Accessor to AORC data struct.
Returns
AORC_data
References AORC_vector, check_forcing_vector_index_bounds(), and forcing_vector_index.
get_AORC_DLWRF_surface_W_per_meters_squared()
double Forcing::get_AORC_DLWRF_surface_W_per_meters_squared () inline
Accessor to AORC DLWRF_surface_W_per_meters_squared.
Returns
DLWRF_surface_W_per_meters_squared
References AORC_vector, check_forcing_vector_index_bounds(), and forcing_vector_index.
get_AORC_DSWRF_surface_W_per_meters_squared()
double Forcing::get_AORC_DSWRF_surface_W_per_meters_squared () inline
Accessor to AORC DSWRF_surface_W_per_meters_squared.
Returns
DSWRF_surface_W_per_meters_squared
References AORC_vector, check_forcing_vector_index_bounds(), and forcing_vector_index.
get_aorc_for_index()
struct AORC_data Forcing::get_aorc_for_index (size_t index) inline
get_AORC_PRES_surface_Pa()
double Forcing::get_AORC_PRES_surface_Pa () inline
Accessor to AORC PRES_surface_Pa.
Returns
PRES_surface_Pa
References AORC_vector, check_forcing_vector_index_bounds(), and forcing_vector_index.
get_AORC_SPFH_2maboveground_kg_per_kg()
double Forcing::get_AORC_SPFH_2maboveground_kg_per_kg () inline
Accessor to AORC SPFH_2maboveground_kg_per_kg.
Returns
SPFH_2maboveground_kg_per_kg
References AORC_vector, check_forcing_vector_index_bounds(), and forcing_vector_index.
get_AORC_TMP_2maboveground_K()
double Forcing::get_AORC_TMP_2maboveground_K () inline
Accessor to AORC TMP_2maboveground_K.
Returns
TMP_2maboveground_K
References AORC_vector, check_forcing_vector_index_bounds(), and forcing_vector_index.
get_AORC_UGRD_10maboveground_meters_per_second()
double Forcing::get_AORC_UGRD_10maboveground_meters_per_second () inline
Accessor to AORC UGRD_10maboveground_meters_per_second.
Returns
UGRD_10maboveground_meters_per_second
References AORC_vector, check_forcing_vector_index_bounds(), and forcing_vector_index.
get_AORC_VGRD_10maboveground_meters_per_second()
double Forcing::get_AORC_VGRD_10maboveground_meters_per_second () inline
Accessor to AORC VGRD_10maboveground_meters_per_second.
Returns
VGRD_10maboveground_meters_per_second
References AORC_vector, check_forcing_vector_index_bounds(), and forcing_vector_index.
get_available_forcing_outputs()
const std::vector<std::string>& Forcing::get_available_forcing_outputs () inline override virtual
Implements forcing::ForcingProvider.
References available_forcings, and get_forcing_field_names().
get_converted_value_for_param_in_units() [1/2]
double Forcing::get_converted_value_for_param_in_units (const std::string & name, const std::string & units_str) inline
Placeholder implementation for function to return the given param adjusted to be in the supplied units.
At present this just returns the param's internal value.
Parameters
name The name of the desired parameter.
units_str A string represented the units for conversion, using standard abbreviations.
Returns
For now, just the param value, but in the future, the value converted.
References check_forcing_vector_index_bounds(), forcing_vector_index, and get_converted_value_for_param_in_units().
get_converted_value_for_param_in_units() [2/2]
double Forcing::get_converted_value_for_param_in_units (const std::string & name, const std::string & units_str, int index) inline
Placeholder implementation for function to return the given param adjusted to be in the supplied units.
At present this just returns the param's internal value.
Parameters
name The name of the desired parameter.
units_str A string represented the units for conversion, using standard abbreviations.
Returns
For now, just the param value, but in the future, the value converted.
References get_value_for_param_name().
Referenced by get_converted_value_for_param_in_units().
get_current_hourly_precipitation_meters_per_second()
double Forcing::get_current_hourly_precipitation_meters_per_second () inline
Gets current hourly precipitation in meters per second Precipitation frequency is assumed to be hourly for now.
///
Todo:
: Add input for dt (delta time) for different frequencies in the data than the model frequency.
Returns
the current hourly precipitation in meters per second
References check_forcing_vector_index_bounds(), forcing_vector_index, and precipitation_rate_meters_per_second_vector.
Referenced by get_next_hourly_precipitation_meters_per_second().
get_day_of_year()
int Forcing::get_day_of_year () inline
Gets day of year integer.
Returns
day of year integer
Todo:
: Sort out using local versus UTC time
References check_forcing_vector_index_bounds(), current_date_time_epoch, forcing_vector_index, and time_epoch_vector.
get_forcing_field_names()
static std::shared_ptr<std::set<std::string> > Forcing::get_forcing_field_names () inline static
Get supported standard names for forcing fields.
Returns
Referenced by get_available_forcing_outputs().
get_forcing_output_time_begin()
time_t Forcing::get_forcing_output_time_begin (const std::string & output_name) inline override virtual
Get the inclusive beginning of the period of time over which this instance can provide data for this forcing.
Returns
The inclusive beginning of the period of time over which this instance can provide this data.
Implements forcing::ForcingProvider.
References start_date_time_epoch.
get_forcing_output_time_end()
time_t Forcing::get_forcing_output_time_end (const std::string & output_name) inline override virtual
Get the exclusive ending of the period of time over which this instance can provide data for this forcing.
Returns
The exclusive ending of the period of time over which this instance can provide this data.
Implements forcing::ForcingProvider.
References end_date_time_epoch.
get_next_hourly_precipitation_meters_per_second()
double Forcing::get_next_hourly_precipitation_meters_per_second () inline
Gets next hourly precipitation in meters per second Increments pointer in forcing vector by one timestep Precipitation frequency is assumed to be hourly for now.
///
Todo:
: Add input for dt (delta time) for different frequencies in the data than the model frequency. ///
: Reconsider incrementing the forcing_vector_index because other functions rely on this, and it could have side effects
Returns
the current hourly precipitation in meters per second after pointer is incremented by one timestep
Todo:
: Return appropriate warning
References forcing_vector_index, get_current_hourly_precipitation_meters_per_second(), and precipitation_rate_meters_per_second_vector.
Referenced by realization::Tshirt_C_Realization::get_response(), and realization::Tshirt_Realization::get_response().
get_time_epoch()
time_t Forcing::get_time_epoch () inline
Accessor to time epoch.
Returns
current_date_time_epoch
References check_forcing_vector_index_bounds(), current_date_time_epoch, forcing_vector_index, and time_epoch_vector.
get_time_step_size()
time_t Forcing::get_time_step_size () inline
Get the time step size, based on epoch vector, assuming the last ts is equal to the next to last.
Returns
References check_forcing_vector_index_bounds(), forcing_vector_index, and time_epoch_vector.
get_ts_index_for_time()
size_t Forcing::get_ts_index_for_time (const time_t & epoch_time) inline override virtual
Get the index of the forcing time step that contains the given point in time.
An std::out_of_range exception should be thrown if the time is not in any time step.
Parameters
epoch_time The point in time, as a seconds-based epoch time.
Returns
The index of the forcing time step that contains the given point in time.
Exceptions
std::out_of_range If the given point is not in any time step.
Implements forcing::ForcingProvider.
References end_date_time_epoch, and start_date_time_epoch.
Referenced by get_value().
get_value()
double Forcing::get_value (const std::string & output_name, const time_t & init_time, const long & duration_s, const std::string & output_units) inline override virtual
Get the value of a forcing property for an arbitrary time period, converting units if needed.
An std::out_of_range exception should be thrown if the data for the time period is not available.
Parameters
output_name The name of the forcing property of interest.
init_time_epoch The epoch time (in seconds) of the start of the time period.
duration_seconds The length of the time period, in seconds.
output_units The expected units of the desired output value.
Returns
The value of the forcing property for the described time period, with units converted if needed.
Exceptions
std::out_of_range If data for the time period is not available.
Implements forcing::ForcingProvider.
References get_ts_index_for_time(), get_value_for_param_name(), is_param_sum_over_time_step(), and start_date_time_epoch.
get_value_for_param_name()
double Forcing::get_value_for_param_name (const std::string & name, int index) inline
Get the current value of a forcing param identified by its name.
Parameters
name The name of the forcing param for which the current value is desired.
index The index of the desired forcing time step from which to obtain the value.
Returns
The particular param's value at the given forcing time step.
References AORC_vector, and precipitation_rate_meters_per_second_vector.
Referenced by get_converted_value_for_param_in_units(), and get_value().
is_aorc_forcing()
bool Forcing::is_aorc_forcing () inline
References is_aorc_data.
is_param_sum_over_time_step()
bool Forcing::is_param_sum_over_time_step (const std::string & name) inline
Get whether a param's value is an aggregate sum over the entire time step.
Certain params, like rain fall, are aggregated sums over an entire time step. Others, such as pressure, are not such sums and instead something else like an instantaneous reading or an average value over the time step.
It may be the case that forcing data is needed for some discretization different than the forcing time step. These values can be calculated (or at least approximated), but doing so requires knowing which values are summed versus not.
Parameters
name The name of the forcing param for which the current value is desired.
Returns
Whether the param's value is an aggregate sum.
Referenced by get_value(), and is_property_sum_over_time_step().
is_property_sum_over_time_step()
bool Forcing::is_property_sum_over_time_step (const std::string & name) inline override virtual
Get whether a property's per-time-step values are each an aggregate sum over the entire time step.
Certain properties, like rain fall, are aggregated sums over an entire time step. Others, such as pressure, are not such sums and instead something else like an instantaneous reading or an average value.
It may be the case that forcing data is needed for some discretization different than the forcing time step. This aspect must be known in such cases to perform the appropriate value interpolation.
Parameters
name The name of the forcing property for which the current value is desired.
Returns
Whether the property's value is an aggregate sum.
Implements forcing::ForcingProvider.
References is_param_sum_over_time_step().
read_forcing()
void Forcing::read_forcing (string file_name) inline private
Read Forcing Data from CSV Reads only data within the specified model start and end date-times and adds to precipiation vector.
Parameters
file_name Forcing file name
References end_date_time_epoch, CSVReader::getData(), precipitation_rate_meters_per_second_vector, and start_date_time_epoch.
read_forcing_aorc()
void Forcing::read_forcing_aorc (string file_name) inline private
Read Forcing Data from AORC CSV Reads only data within the specified model start and end date-times and adds to precipiation vector.
Parameters
file_name Forcing file name
Todo:
TODO: Return appropriate error
Todo:
TODO: Return appropriate error
References AORC_vector, AORC_data::APCP_surface_kg_per_meters_squared, AORC_data::DLWRF_surface_W_per_meters_squared, AORC_data::DSWRF_surface_W_per_meters_squared, end_date_time_epoch, CSVReader::getData(), is_aorc_data, precipitation_rate_meters_per_second_vector, AORC_data::PRES_surface_Pa, AORC_data::SPFH_2maboveground_kg_per_kg, start_date_time_epoch, time_epoch_vector, AORC_data::TMP_2maboveground_K, AORC_data::UGRD_10maboveground_meters_per_second, and AORC_data::VGRD_10maboveground_meters_per_second.
Referenced by Forcing().
Member Data Documentation
air_temperature_fahrenheit
double Forcing::air_temperature_fahrenheit private
AORC_vector
vector<AORC_data> Forcing::AORC_vector private
Referenced by get_AORC_APCP_surface_kg_per_meters_squared(), get_AORC_data(), get_AORC_DLWRF_surface_W_per_meters_squared(), get_AORC_DSWRF_surface_W_per_meters_squared(), get_AORC_PRES_surface_Pa(), get_AORC_SPFH_2maboveground_kg_per_kg(), get_AORC_TMP_2maboveground_K(), get_AORC_UGRD_10maboveground_meters_per_second(), get_AORC_VGRD_10maboveground_meters_per_second(), get_value_for_param_name(), and read_forcing_aorc().
available_forcings
std::vector<std::string> Forcing::available_forcings private
Referenced by get_available_forcing_outputs().
catchment_id
int Forcing::catchment_id private
current_date_time_epoch
time_t Forcing::current_date_time_epoch private
Referenced by Forcing(), get_day_of_year(), and get_time_epoch().
day_of_year
int Forcing::day_of_year private
end_date_time
std::shared_ptr<time_type> Forcing::end_date_time private
Referenced by Forcing().
end_date_time_epoch
time_t Forcing::end_date_time_epoch private
Referenced by Forcing(), get_forcing_output_time_end(), get_ts_index_for_time(), read_forcing(), and read_forcing_aorc().
forcing_file_name
string Forcing::forcing_file_name private
Referenced by Forcing().
forcing_vector_index
int Forcing::forcing_vector_index private
Referenced by Forcing(), check_forcing_vector_index_bounds(), get_AORC_APCP_surface_kg_per_meters_squared(), get_AORC_data(), get_AORC_DLWRF_surface_W_per_meters_squared(), get_AORC_DSWRF_surface_W_per_meters_squared(), get_AORC_PRES_surface_Pa(), get_AORC_SPFH_2maboveground_kg_per_kg(), get_AORC_TMP_2maboveground_K(), get_AORC_UGRD_10maboveground_meters_per_second(), get_AORC_VGRD_10maboveground_meters_per_second(), get_converted_value_for_param_in_units(), get_current_hourly_precipitation_meters_per_second(), get_day_of_year(), get_next_hourly_precipitation_meters_per_second(), get_time_epoch(), and get_time_step_size().
is_aorc_data
bool Forcing::is_aorc_data = false private
Whether this forcing instance has read in full AORC data or just precipitation_rate_meters_per_second_vector.
Referenced by is_aorc_forcing(), and read_forcing_aorc().
latitude
double Forcing::latitude private
longitude
double Forcing::longitude private
precipitation_rate_meters_per_second
double Forcing::precipitation_rate_meters_per_second private
precipitation_rate_meters_per_second_vector
vector<double> Forcing::precipitation_rate_meters_per_second_vector private
Todo:
: Look into aggregation of data, relevant libraries, and storing frequency information
Referenced by check_forcing_vector_index_bounds(), get_current_hourly_precipitation_meters_per_second(), get_next_hourly_precipitation_meters_per_second(), get_value_for_param_name(), read_forcing(), and read_forcing_aorc().
start_date_time
std::shared_ptr<time_type> Forcing::start_date_time private
Referenced by Forcing().
start_date_time_epoch
time_t Forcing::start_date_time_epoch private
Referenced by Forcing(), get_forcing_output_time_begin(), get_ts_index_for_time(), get_value(), read_forcing(), and read_forcing_aorc().
time_epoch_vector
vector<time_t> Forcing::time_epoch_vector private
Todo:
: Consider making epoch time the iterator
Referenced by get_day_of_year(), get_time_epoch(), get_time_step_size(), and read_forcing_aorc().
The documentation for this class was generated from the following file:
include/forcing/Forcing.h