NGen: ReservoirTimelessKernelTest Class Reference
ReservoirTimelessKernelTest Class Reference
Protected Member Functions
void SetUp () override
void TearDown () override
void setupNoOutletReservoir ()
void setupNoOutletReservoir2 ()
void setupOneOutletReservoir ()
void setupOneOutletHighStorageReservoir ()
void setupMultipleOutletReservoir ()
void setupMultipleOutletSameActivationHeightReservoir ()
void setupMultipleOutletReservoirTooLargeActivationThreshold ()
void setupMultipleOutletOutOfOrderReservoir ()
void setupExponentialOutletReservoir ()
Protected Attributes
std::shared_ptr< Reservoir::Implicit_Time::Reservoir > NoOutletReservoir
std::shared_ptr< Reservoir::Implicit_Time::Reservoir > NoOutletReservoir2
std::shared_ptr< Reservoir::Implicit_Time::Reservoir > NoOutletReservoir3
std::shared_ptr< Reservoir::Implicit_Time::Reservoir > OneOutletReservoir
std::shared_ptr< Reservoir::Implicit_Time::Reservoir > OneOutletHighStorageReservoir
std::shared_ptr< Reservoir::Implicit_Time::Reservoir > MultipleOutletReservoir
std::shared_ptr< Reservoir::Implicit_Time::Reservoir > MultipleOutletReservoirTooLargeActivationThreshold
std::shared_ptr< Reservoir::Implicit_Time::Reservoir > MultipleOutletOutOfOrderReservoir
std::shared_ptr< Reservoir::Implicit_Time::Reservoir > MultipleOutletSameActivationHeightReservoir
std::shared_ptr< Reservoir::Implicit_Time::Reservoir > SingleExponentialOutletReservoir
std::shared_ptr< Reservoir::Implicit_Time::Reservoir_Outlet > ReservoirOutlet1
std::shared_ptr< Reservoir::Implicit_Time::Reservoir_Outlet > ReservoirOutlet2
std::shared_ptr< Reservoir::Implicit_Time::Reservoir_Outlet > ReservoirOutlet3
std::shared_ptr< Reservoir::Implicit_Time::Reservoir_Outlet > ReservoirOutlet4
std::shared_ptr< Reservoir::Implicit_Time::Reservoir_Outlet > ReservoirOutlet5
std::shared_ptr< Reservoir::Implicit_Time::Reservoir_Outlet > ReservoirOutlet6
std::shared_ptr< Reservoir::Implicit_Time::Reservoir_Outlet > ReservoirOutlet7
std::shared_ptr< Reservoir::Implicit_Time::Reservoir_Outlet > ReservoirExponentialOutlet
std::shared_ptr< Reservoir::Implicit_Time::Reservoir_Outlet > ReservoirLinearOutlet
std::vector< std::shared_ptr< Reservoir::Implicit_Time::Reservoir_Outlet > > ReservoirOutletsVector
std::vector< std::shared_ptr< Reservoir::Implicit_Time::Reservoir_Outlet > > ReservoirOutletsVector2
std::vector< std::shared_ptr< Reservoir::Implicit_Time::Reservoir_Outlet > > ReservoirOutletsVector3
std::vector< std::shared_ptr< Reservoir::Implicit_Time::Reservoir_Outlet > > ReservoirOutletsVectorOutOfOrder
std::vector< std::shared_ptr< Reservoir::Implicit_Time::Reservoir_Outlet > > ReservoirExponentialSingleOutletVector
std::vector< std::shared_ptr< Reservoir::Implicit_Time::Reservoir_Outlet > > ReservoirOutletsVectorMultipleTypes
Member Function Documentation
SetUp()
void ReservoirTimelessKernelTest::SetUp () override protected
References setupExponentialOutletReservoir(), setupMultipleOutletOutOfOrderReservoir(), setupMultipleOutletReservoir(), setupMultipleOutletReservoirTooLargeActivationThreshold(), setupMultipleOutletSameActivationHeightReservoir(), setupNoOutletReservoir(), setupNoOutletReservoir2(), setupOneOutletHighStorageReservoir(), and setupOneOutletReservoir().
setupExponentialOutletReservoir()
void ReservoirTimelessKernelTest::setupExponentialOutletReservoir () protected
References ReservoirExponentialOutlet, ReservoirExponentialSingleOutletVector, ReservoirOutlet1, ReservoirOutletsVectorMultipleTypes, and SingleExponentialOutletReservoir.
Referenced by SetUp().
setupMultipleOutletOutOfOrderReservoir()
void ReservoirTimelessKernelTest::setupMultipleOutletOutOfOrderReservoir () protected
References MultipleOutletOutOfOrderReservoir, ReservoirOutlet1, ReservoirOutlet2, ReservoirOutlet3, and ReservoirOutletsVectorOutOfOrder.
Referenced by SetUp().
setupMultipleOutletReservoir()
void ReservoirTimelessKernelTest::setupMultipleOutletReservoir () protected
References MultipleOutletReservoir, ReservoirOutlet1, ReservoirOutlet2, ReservoirOutlet3, and ReservoirOutletsVector.
Referenced by SetUp().
setupMultipleOutletReservoirTooLargeActivationThreshold()
void ReservoirTimelessKernelTest::setupMultipleOutletReservoirTooLargeActivationThreshold () protected
References ReservoirOutlet6, ReservoirOutlet7, and ReservoirOutletsVector3.
Referenced by SetUp().
setupMultipleOutletSameActivationHeightReservoir()
void ReservoirTimelessKernelTest::setupMultipleOutletSameActivationHeightReservoir () protected
References MultipleOutletSameActivationHeightReservoir, ReservoirOutlet4, ReservoirOutlet5, and ReservoirOutletsVector2.
Referenced by SetUp().
setupNoOutletReservoir()
void ReservoirTimelessKernelTest::setupNoOutletReservoir () protected
References NoOutletReservoir.
Referenced by SetUp().
setupNoOutletReservoir2()
void ReservoirTimelessKernelTest::setupNoOutletReservoir2 () protected
References NoOutletReservoir2, and ReservoirLinearOutlet.
Referenced by SetUp().
setupOneOutletHighStorageReservoir()
void ReservoirTimelessKernelTest::setupOneOutletHighStorageReservoir () protected
References OneOutletHighStorageReservoir.
Referenced by SetUp().
setupOneOutletReservoir()
void ReservoirTimelessKernelTest::setupOneOutletReservoir () protected
References OneOutletReservoir.
Referenced by SetUp().
TearDown()
void ReservoirTimelessKernelTest::TearDown () override protected
Member Data Documentation
MultipleOutletOutOfOrderReservoir
std::shared_ptr<Reservoir::Implicit_Time::Reservoir> ReservoirTimelessKernelTest::MultipleOutletOutOfOrderReservoir protected
Referenced by setupMultipleOutletOutOfOrderReservoir().
MultipleOutletReservoir
std::shared_ptr<Reservoir::Implicit_Time::Reservoir> ReservoirTimelessKernelTest::MultipleOutletReservoir protected
Referenced by setupMultipleOutletReservoir().
MultipleOutletReservoirTooLargeActivationThreshold
std::shared_ptr<Reservoir::Implicit_Time::Reservoir> ReservoirTimelessKernelTest::MultipleOutletReservoirTooLargeActivationThreshold protected
MultipleOutletSameActivationHeightReservoir
std::shared_ptr<Reservoir::Implicit_Time::Reservoir> ReservoirTimelessKernelTest::MultipleOutletSameActivationHeightReservoir protected
Referenced by setupMultipleOutletSameActivationHeightReservoir().
NoOutletReservoir
std::shared_ptr<Reservoir::Implicit_Time::Reservoir> ReservoirTimelessKernelTest::NoOutletReservoir protected
Referenced by setupNoOutletReservoir().
NoOutletReservoir2
std::shared_ptr<Reservoir::Implicit_Time::Reservoir> ReservoirTimelessKernelTest::NoOutletReservoir2 protected
Referenced by setupNoOutletReservoir2().
NoOutletReservoir3
std::shared_ptr<Reservoir::Implicit_Time::Reservoir> ReservoirTimelessKernelTest::NoOutletReservoir3 protected
OneOutletHighStorageReservoir
std::shared_ptr<Reservoir::Implicit_Time::Reservoir> ReservoirTimelessKernelTest::OneOutletHighStorageReservoir protected
Referenced by setupOneOutletHighStorageReservoir().
OneOutletReservoir
std::shared_ptr<Reservoir::Implicit_Time::Reservoir> ReservoirTimelessKernelTest::OneOutletReservoir protected
Referenced by setupOneOutletReservoir().
ReservoirExponentialOutlet
std::shared_ptr<Reservoir::Implicit_Time::Reservoir_Outlet> ReservoirTimelessKernelTest::ReservoirExponentialOutlet protected
Referenced by setupExponentialOutletReservoir().
ReservoirExponentialSingleOutletVector
std::vector<std::shared_ptr<Reservoir::Implicit_Time::Reservoir_Outlet> > ReservoirTimelessKernelTest::ReservoirExponentialSingleOutletVector protected
Referenced by setupExponentialOutletReservoir().
ReservoirLinearOutlet
std::shared_ptr<Reservoir::Implicit_Time::Reservoir_Outlet> ReservoirTimelessKernelTest::ReservoirLinearOutlet protected
Referenced by setupNoOutletReservoir2().
ReservoirOutlet1
std::shared_ptr<Reservoir::Implicit_Time::Reservoir_Outlet> ReservoirTimelessKernelTest::ReservoirOutlet1 protected
Referenced by setupExponentialOutletReservoir(), setupMultipleOutletOutOfOrderReservoir(), and setupMultipleOutletReservoir().
ReservoirOutlet2
std::shared_ptr<Reservoir::Implicit_Time::Reservoir_Outlet> ReservoirTimelessKernelTest::ReservoirOutlet2 protected
Referenced by setupMultipleOutletOutOfOrderReservoir(), and setupMultipleOutletReservoir().
ReservoirOutlet3
std::shared_ptr<Reservoir::Implicit_Time::Reservoir_Outlet> ReservoirTimelessKernelTest::ReservoirOutlet3 protected
Referenced by setupMultipleOutletOutOfOrderReservoir(), and setupMultipleOutletReservoir().
ReservoirOutlet4
std::shared_ptr<Reservoir::Implicit_Time::Reservoir_Outlet> ReservoirTimelessKernelTest::ReservoirOutlet4 protected
Referenced by setupMultipleOutletSameActivationHeightReservoir().
ReservoirOutlet5
std::shared_ptr<Reservoir::Implicit_Time::Reservoir_Outlet> ReservoirTimelessKernelTest::ReservoirOutlet5 protected
Referenced by setupMultipleOutletSameActivationHeightReservoir().
ReservoirOutlet6
std::shared_ptr<Reservoir::Implicit_Time::Reservoir_Outlet> ReservoirTimelessKernelTest::ReservoirOutlet6 protected
Referenced by setupMultipleOutletReservoirTooLargeActivationThreshold().
ReservoirOutlet7
std::shared_ptr<Reservoir::Implicit_Time::Reservoir_Outlet> ReservoirTimelessKernelTest::ReservoirOutlet7 protected
Referenced by setupMultipleOutletReservoirTooLargeActivationThreshold().
ReservoirOutletsVector
std::vector<std::shared_ptr<Reservoir::Implicit_Time::Reservoir_Outlet> > ReservoirTimelessKernelTest::ReservoirOutletsVector protected
Referenced by setupMultipleOutletReservoir().
ReservoirOutletsVector2
std::vector<std::shared_ptr<Reservoir::Implicit_Time::Reservoir_Outlet> > ReservoirTimelessKernelTest::ReservoirOutletsVector2 protected
Referenced by setupMultipleOutletSameActivationHeightReservoir().
ReservoirOutletsVector3
std::vector<std::shared_ptr<Reservoir::Implicit_Time::Reservoir_Outlet> > ReservoirTimelessKernelTest::ReservoirOutletsVector3 protected
Referenced by setupMultipleOutletReservoirTooLargeActivationThreshold().
ReservoirOutletsVectorMultipleTypes
std::vector<std::shared_ptr<Reservoir::Implicit_Time::Reservoir_Outlet> > ReservoirTimelessKernelTest::ReservoirOutletsVectorMultipleTypes protected
Referenced by setupExponentialOutletReservoir().
ReservoirOutletsVectorOutOfOrder
std::vector<std::shared_ptr<Reservoir::Implicit_Time::Reservoir_Outlet> > ReservoirTimelessKernelTest::ReservoirOutletsVectorOutOfOrder protected
Referenced by setupMultipleOutletOutOfOrderReservoir().
SingleExponentialOutletReservoir
std::shared_ptr<Reservoir::Implicit_Time::Reservoir> ReservoirTimelessKernelTest::SingleExponentialOutletReservoir protected
Referenced by setupExponentialOutletReservoir().
The documentation for this class was generated from the following file:
test/models/hymod/include/Reservoir_Timeless_Test.cpp