NGen: geojson::MultiLineStringFeature Class Reference
geojson::MultiLineStringFeature Class Reference
#include <MultiLineStringFeature.hpp>
Public Member Functions
MultiLineStringFeature (const FeatureBase &feature)
MultiLineStringFeature (const MultiLineStringFeature &feature)
MultiLineStringFeature (multilinestring_t multilinestring, std::string new_id="", PropertyMap new_properties=PropertyMap(), std::vector< double > new_bounding_box=std::vector< double >(), std::vector< FeatureBase * > upstream_features=std::vector< FeatureBase * >(), std::vector< FeatureBase * > downstream_features=std::vector< FeatureBase * >(), std::map< std::string, JSONProperty > members=std::map< std::string, JSONProperty >())
multilinestring_t geometry () const
void visit (FeatureVisitor &visitor) override
FeatureType get_type () const
Retrieve an indicator as to what type of feature this is.
virtual void add_origination_feature (FeatureBase *feature, bool connect=true)
Set a separate feature as upstream from this instance.
virtual void add_destination_feature (FeatureBase *feature, bool connect=true)
Set a separate feature as destination from this instance.
virtual void assign_neighbors ()
Searches for features that share common destinations and links them.
virtual void add_neighbor_feature (FeatureBase *feature, bool connect=true)
Links this feature to a feature that shares a common destination.
virtual JSONProperty get_property (const std::string &key) const
Get a value from the set of properties.
virtual void set_id (const std::string &new_id)
Sets the ID for the Feature.
virtual JSONProperty get (const std::string &key) const
Get a foreign member value by name.
virtual void set (const std::string &key, short value)
Sets a foreign member value.
virtual void set (const std::string &key, int value)
Sets a foreign member value.
virtual void set (const std::string &key, long value)
Sets a foreign member value.
virtual void set (const std::string &key, float value)
Sets a foreign member value.
virtual void set (const std::string &key, double value)
Sets a foreign member value.
virtual void set (const std::string &key, std::string value)
Sets a foreign member value.
virtual void set (const std::string &key, JSONProperty property)
Sets a foreign member value.
virtual bool has_key (const std::string &key)
virtual std::vector< std::string > keys () const
Retrieves a listing of all foreign member keys.
virtual std::vector< std::string > property_keys () const
Retireves a listing of all property keys.
virtual bool has_property (std::string property_name) const
virtual std::vector< geojson::geometry > get_geometry_collection () const
Collects a collection of everything held within the inner geometry collection.
std::vector< double > get_bounding_box () const
Collects all values describing the bounds of this feature.
const PropertyMap & get_properties () const
PropertyMap & get_properties ()
std::string get_id () const
std::string get_id (std::string alt_id) const
int get_number_of_destination_features ()
int get_number_of_origination_features ()
int get_number_of_neighbors ()
FeatureBase * get_destination_feature (std::string id)
FeatureBase * get_origination_feature (std::string id)
std::vector< FeatureBase * > origination_features () const
std::vector< FeatureBase * > destination_features () const
std::vector< FeatureBase * > neighbor_features () const
int get_origination_length ()
int get_destination_length ()
int get_contributor_count ()
bool is_leaf ()
bool is_root ()
template<class T >
T geometry (int index) const
bool operator== (const FeatureBase &rhs)
bool operator!= (const FeatureBase &other)
Protected Member Functions
virtual void break_links ()
virtual void remove_destination (FeatureBase *feature)
virtual void remove_origination (FeatureBase *feature)
virtual void remove_neighbor (FeatureBase *feature)
Protected Attributes
FeatureType type
::geojson::geometry geom
std::vector<::geojson::geometry > geometry_collection
PropertyMap properties
std::vector< double > bounding_box
PropertyMap foreign_members
std::string id
std::vector< FeatureBase * > origination
std::vector< FeatureBase * > destination
std::vector< FeatureBase * > neighbors
Constructor & Destructor Documentation
MultiLineStringFeature() [1/3]
geojson::MultiLineStringFeature::MultiLineStringFeature (const FeatureBase & feature) inline
MultiLineStringFeature() [2/3]
geojson::MultiLineStringFeature::MultiLineStringFeature (const MultiLineStringFeature & feature) inline
References geojson::FeatureBase::geom, geometry(), geojson::FeatureBase::get_type(), and geojson::FeatureBase::type.
MultiLineStringFeature() [3/3]
geojson::MultiLineStringFeature::MultiLineStringFeature (multilinestring_t multilinestring, std::string new_id = "", PropertyMap new_properties = PropertyMap(), std::vector< double > new_bounding_box = std::vector<double>(), std::vector< FeatureBase * > upstream_features = std::vector<FeatureBase*>(), std::vector< FeatureBase * > downstream_features = std::vector<FeatureBase*>(), std::map< std::string, JSONProperty > members = std::map<std::string, JSONProperty>()) inline
References geojson::FeatureBase::geom, geojson::MultiLineString, geojson::multilinestring(), and geojson::FeatureBase::type.
Member Function Documentation
add_destination_feature()
virtual void geojson::FeatureBase::add_destination_feature (FeatureBase * feature, bool connect = true) inline virtual inherited
Set a separate feature as destination from this instance.
Parameters
feature The feature to link to that is destination from this instance
connect Whether or not to set this instance as upstream from the newly attached destination feature
References geojson::FeatureBase::add_origination_feature(), geojson::contains(), and geojson::FeatureBase::destination.
Referenced by geojson::FeatureBase::FeatureBase(), and geojson::FeatureBase::add_origination_feature().
add_neighbor_feature()
virtual void geojson::FeatureBase::add_neighbor_feature (FeatureBase * feature, bool connect = true) inline virtual inherited
Links this feature to a feature that shares a common destination.
Parameters
feature A feature with a common destination
connect Whether or not this feature should be linked to the neighbor as well
References geojson::FeatureBase::add_neighbor_feature(), geojson::contains(), and geojson::FeatureBase::neighbors.
Referenced by geojson::FeatureBase::add_neighbor_feature(), and geojson::FeatureBase::assign_neighbors().
add_origination_feature()
virtual void geojson::FeatureBase::add_origination_feature (FeatureBase * feature, bool connect = true) inline virtual inherited
Set a separate feature as upstream from this instance.
Parameters
feature The feature to link to that is upstream from this instance
connect Whether or not to set this instance as downsteam from the newly attached upstream feature
References geojson::FeatureBase::add_destination_feature(), and geojson::FeatureBase::origination.
Referenced by geojson::FeatureBase::FeatureBase(), and geojson::FeatureBase::add_destination_feature().
assign_neighbors()
virtual void geojson::FeatureBase::assign_neighbors () inline virtual inherited
Searches for features that share common destinations and links them.
References geojson::FeatureBase::add_neighbor_feature(), geojson::FeatureBase::destination, and geojson::FeatureBase::destination_features().
break_links()
virtual void geojson::FeatureBase::break_links () inline protected virtual inherited
References geojson::FeatureBase::destination, geojson::FeatureBase::neighbors, and geojson::FeatureBase::origination.
Referenced by geojson::FeatureBase::~FeatureBase().
destination_features()
std::vector< FeatureBase * > geojson::FeatureBase::destination_features () const inline inherited
References geojson::FeatureBase::destination.
Referenced by geojson::FeatureBase::FeatureBase(), geojson::FeatureBase::FeatureBase(), and geojson::FeatureBase::assign_neighbors().
geometry() [1/2]
multilinestring_t geojson::MultiLineStringFeature::geometry () const inline
References geojson::FeatureBase::geom.
Referenced by MultiLineStringFeature().
geometry() [2/2]
template<class T > T geojson::FeatureBase::geometry (int index) const inline inherited
References geojson::FeatureBase::geometry_collection, and geojson::get_geometry_type().
get()
virtual JSONProperty geojson::FeatureBase::get (const std::string & key) const inline virtual inherited
Get a foreign member value by name.
Parameters
key The name of the foreign member whose value to look for
Returns
The member value identified by the key
References geojson::JSONProperty::at(), and geojson::FeatureBase::foreign_members.
Referenced by geojson::FeatureBase::FeatureBase(), and geojson::FeatureBase::operator==().
get_bounding_box()
std::vector< double > geojson::FeatureBase::get_bounding_box () const inline inherited
Collects all values describing the bounds of this feature.
Returns
A collection of double values describing the bounds for this feature
References geojson::FeatureBase::bounding_box.
Referenced by geojson::FeatureBase::FeatureBase().
get_contributor_count()
int geojson::FeatureBase::get_contributor_count () inline inherited
References geojson::contains(), and geojson::FeatureBase::origination.
get_destination_feature()
FeatureBase * geojson::FeatureBase::get_destination_feature (std::string id) inline inherited
References geojson::FeatureBase::destination, and geojson::FeatureBase::id.
get_destination_length()
int geojson::FeatureBase::get_destination_length () inline inherited
References geojson::FeatureBase::destination, and geojson::FeatureBase::is_leaf().
get_geometry_collection()
virtual std::vector< geojson::geometry > geojson::FeatureBase::get_geometry_collection () const inline virtual inherited
Collects a collection of everything held within the inner geometry collection.
Returns
A collection of boost geometry objects
Exceptions
Runtime Error if this feature isn't a collection type
References geojson::FeatureBase::geometry_collection, geojson::GeometryCollection, and geojson::FeatureBase::type.
Referenced by geojson::CollectionFeature::CollectionFeature(), and geojson::FeatureBase::FeatureBase().
get_id() [1/2]
std::string geojson::FeatureBase::get_id () const inline inherited
References geojson::FeatureBase::id.
Referenced by geojson::FeatureBase::FeatureBase(), and geojson::FeatureBase::operator==().
get_id() [2/2]
std::string geojson::FeatureBase::get_id (std::string alt_id) const inline inherited
References geojson::JSONProperty::as_string(), geojson::FeatureBase::get_property(), and geojson::FeatureBase::id.
get_number_of_destination_features()
int geojson::FeatureBase::get_number_of_destination_features () inline inherited
References geojson::FeatureBase::destination.
get_number_of_neighbors()
int geojson::FeatureBase::get_number_of_neighbors () inline inherited
References geojson::FeatureBase::neighbors.
get_number_of_origination_features()
int geojson::FeatureBase::get_number_of_origination_features () inline inherited
References geojson::FeatureBase::origination.
get_origination_feature()
FeatureBase * geojson::FeatureBase::get_origination_feature (std::string id) inline inherited
References geojson::FeatureBase::id, and geojson::FeatureBase::origination.
get_origination_length()
int geojson::FeatureBase::get_origination_length () inline inherited
References geojson::FeatureBase::is_root(), and geojson::FeatureBase::origination.
get_properties() [1/2]
PropertyMap & geojson::FeatureBase::get_properties () inline inherited
References geojson::FeatureBase::properties.
get_properties() [2/2]
const PropertyMap & geojson::FeatureBase::get_properties () const inline inherited
References geojson::FeatureBase::properties.
Referenced by geojson::FeatureBase::FeatureBase().
get_property()
virtual JSONProperty geojson::FeatureBase::get_property (const std::string & key) const inline virtual inherited
Get a value from the set of properties.
Parameters
key The name of the property to get
Returns
The property identified by the key
References geojson::FeatureBase::properties.
Referenced by geojson::FeatureBase::get_id(), and geojson::FeatureBase::operator==().
get_type()
FeatureType geojson::FeatureBase::get_type () const inline inherited
Retrieve an indicator as to what type of feature this is.
Returns
The type of feature for this instance
References geojson::FeatureBase::type.
Referenced by geojson::FeatureBase::FeatureBase(), geojson::LineStringFeature::LineStringFeature(), MultiLineStringFeature(), geojson::MultiPointFeature::MultiPointFeature(), geojson::PointFeature::PointFeature(), and geojson::FeatureBase::operator==().
has_key()
virtual bool geojson::FeatureBase::has_key (const std::string & key) inline virtual inherited
References geojson::FeatureBase::keys().
has_property()
virtual bool geojson::FeatureBase::has_property (std::string property_name) const inline virtual inherited
References geojson::FeatureBase::property_keys().
is_leaf()
bool geojson::FeatureBase::is_leaf () inline inherited
References geojson::FeatureBase::destination.
Referenced by geojson::FeatureBase::get_destination_length().
is_root()
bool geojson::FeatureBase::is_root () inline inherited
References geojson::FeatureBase::origination.
Referenced by geojson::FeatureBase::get_origination_length().
keys()
virtual std::vector< std::string > geojson::FeatureBase::keys () const inline virtual inherited
Retrieves a listing of all foreign member keys.
Returns
A list of all the names of foreign member values
References geojson::FeatureBase::foreign_members.
Referenced by geojson::FeatureBase::FeatureBase(), geojson::FeatureBase::has_key(), and geojson::FeatureBase::operator==().
neighbor_features()
std::vector< FeatureBase * > geojson::FeatureBase::neighbor_features () const inline inherited
References geojson::FeatureBase::neighbors.
operator!=()
bool geojson::FeatureBase::operator!= (const FeatureBase & other) inline inherited
References geojson::FeatureBase::operator==().
operator==()
bool geojson::FeatureBase::operator== (const FeatureBase & rhs) inline inherited
References geojson::FeatureBase::bounding_box, geojson::contains(), geojson::FeatureBase::destination, geojson::FeatureBase::geom, geojson::FeatureBase::geometry_collection, geojson::GeometryCollection, geojson::FeatureBase::get(), geojson::FeatureBase::get_id(), geojson::FeatureBase::get_property(), geojson::FeatureBase::get_type(), geojson::FeatureBase::keys(), geojson::FeatureBase::neighbors, geojson::FeatureBase::origination, and geojson::FeatureBase::property_keys().
Referenced by geojson::FeatureBase::operator!=().
origination_features()
std::vector< FeatureBase * > geojson::FeatureBase::origination_features () const inline inherited
References geojson::FeatureBase::origination.
Referenced by geojson::FeatureBase::FeatureBase(), and geojson::FeatureBase::FeatureBase().
property_keys()
virtual std::vector< std::string > geojson::FeatureBase::property_keys () const inline virtual inherited
Retireves a listing of all property keys.
Returns
A list of all the names of the properties for this feature
References geojson::FeatureBase::properties, and geojson::FeatureBase::property_keys().
Referenced by geojson::FeatureBase::has_property(), geojson::FeatureBase::operator==(), and geojson::FeatureBase::property_keys().
remove_destination()
virtual void geojson::FeatureBase::remove_destination (FeatureBase * feature) inline protected virtual inherited
References geojson::FeatureBase::destination.
remove_neighbor()
virtual void geojson::FeatureBase::remove_neighbor (FeatureBase * feature) inline protected virtual inherited
References geojson::FeatureBase::neighbors.
remove_origination()
virtual void geojson::FeatureBase::remove_origination (FeatureBase * feature) inline protected virtual inherited
References geojson::FeatureBase::origination.
set() [1/7]
virtual void geojson::FeatureBase::set (const std::string & key, double value) inline virtual inherited
Sets a foreign member value.
Parameters
key The name of the value to set
value The value to set
References geojson::FeatureBase::foreign_members.
set() [2/7]
virtual void geojson::FeatureBase::set (const std::string & key, float value) inline virtual inherited
Sets a foreign member value.
Parameters
key The name of the value to set
value The value to set
References geojson::FeatureBase::foreign_members.
set() [3/7]
virtual void geojson::FeatureBase::set (const std::string & key, int value) inline virtual inherited
Sets a foreign member value.
Parameters
key The name of the value to set
value The value to set
References geojson::FeatureBase::foreign_members.
set() [4/7]
virtual void geojson::FeatureBase::set (const std::string & key, JSONProperty property) inline virtual inherited
Sets a foreign member value.
Parameters
key The name of the value to set
value The value to set
References geojson::FeatureBase::foreign_members.
set() [5/7]
virtual void geojson::FeatureBase::set (const std::string & key, long value) inline virtual inherited
Sets a foreign member value.
Parameters
key The name of the value to set
value The value to set
References geojson::FeatureBase::foreign_members.
set() [6/7]
virtual void geojson::FeatureBase::set (const std::string & key, short value) inline virtual inherited
Sets a foreign member value.
Parameters
key The name of the value to set
value The value to set
References geojson::FeatureBase::foreign_members.
Referenced by geojson::FeatureBase::FeatureBase().
set() [7/7]
virtual void geojson::FeatureBase::set (const std::string & key, std::string value) inline virtual inherited
Sets a foreign member value.
Parameters
key The name of the value to set
value The value to set
References geojson::FeatureBase::foreign_members.
set_id()
virtual void geojson::FeatureBase::set_id (const std::string & new_id) inline virtual inherited
Sets the ID for the Feature.
Parameters
new_id The new identifier for this feature
visit()
void geojson::MultiLineStringFeature::visit (FeatureVisitor & visitor) inline override virtual
Implements geojson::FeatureBase.
References geojson::FeatureVisitor::visit().
Member Data Documentation
bounding_box
std::vector<double> geojson::FeatureBase::bounding_box protected inherited
Referenced by geojson::FeatureBase::FeatureBase(), geojson::FeatureBase::FeatureBase(), geojson::FeatureBase::get_bounding_box(), and geojson::FeatureBase::operator==().
destination
std::vector<FeatureBase*> geojson::FeatureBase::destination protected inherited
Referenced by geojson::FeatureBase::FeatureBase(), geojson::FeatureBase::add_destination_feature(), geojson::FeatureBase::assign_neighbors(), geojson::FeatureBase::break_links(), geojson::FeatureBase::destination_features(), geojson::FeatureBase::get_destination_feature(), geojson::FeatureBase::get_destination_length(), geojson::FeatureBase::get_number_of_destination_features(), geojson::FeatureBase::is_leaf(), geojson::FeatureBase::operator==(), and geojson::FeatureBase::remove_destination().
foreign_members
PropertyMap geojson::FeatureBase::foreign_members protected inherited
Referenced by geojson::FeatureBase::FeatureBase(), geojson::FeatureBase::get(), geojson::FeatureBase::keys(), geojson::FeatureBase::set(), geojson::FeatureBase::set(), geojson::FeatureBase::set(), geojson::FeatureBase::set(), geojson::FeatureBase::set(), geojson::FeatureBase::set(), and geojson::FeatureBase::set().
geom
::geojson::geometry geojson::FeatureBase::geom protected inherited
Referenced by geojson::FeatureBase::FeatureBase(), geojson::LineStringFeature::LineStringFeature(), geojson::LineStringFeature::LineStringFeature(), MultiLineStringFeature(), MultiLineStringFeature(), geojson::MultiPointFeature::MultiPointFeature(), geojson::MultiPointFeature::MultiPointFeature(), geojson::MultiPolygonFeature::MultiPolygonFeature(), geojson::MultiPolygonFeature::MultiPolygonFeature(), geojson::PointFeature::PointFeature(), geojson::PointFeature::PointFeature(), geojson::PolygonFeature::PolygonFeature(), geojson::FeatureBase::geometry(), geojson::LineStringFeature::geometry(), geometry(), geojson::MultiPointFeature::geometry(), geojson::MultiPolygonFeature::geometry(), geojson::PointFeature::geometry(), geojson::PolygonFeature::geometry(), and geojson::FeatureBase::operator==().
geometry_collection
std::vector<::geojson::geometry> geojson::FeatureBase::geometry_collection protected inherited
Referenced by geojson::CollectionFeature::CollectionFeature(), geojson::CollectionFeature::CollectionFeature(), geojson::FeatureBase::FeatureBase(), geojson::FeatureBase::geometry(), geojson::FeatureBase::get_geometry_collection(), geojson::CollectionFeature::linestrings(), geojson::CollectionFeature::multilinestrings(), geojson::CollectionFeature::multipoints(), geojson::CollectionFeature::multipolygons(), geojson::FeatureBase::operator==(), geojson::CollectionFeature::points(), and geojson::CollectionFeature::polygons().
id
std::string geojson::FeatureBase::id protected inherited
Referenced by geojson::FeatureBase::get_destination_feature(), geojson::FeatureBase::get_id(), geojson::FeatureBase::get_id(), and geojson::FeatureBase::get_origination_feature().
neighbors
std::vector<FeatureBase*> geojson::FeatureBase::neighbors protected inherited
Referenced by geojson::FeatureBase::add_neighbor_feature(), geojson::FeatureBase::break_links(), geojson::FeatureBase::get_number_of_neighbors(), geojson::FeatureBase::neighbor_features(), geojson::FeatureBase::operator==(), and geojson::FeatureBase::remove_neighbor().
origination
std::vector<FeatureBase*> geojson::FeatureBase::origination protected inherited
Referenced by geojson::FeatureBase::FeatureBase(), geojson::FeatureBase::add_origination_feature(), geojson::FeatureBase::break_links(), geojson::FeatureBase::get_contributor_count(), geojson::FeatureBase::get_number_of_origination_features(), geojson::FeatureBase::get_origination_feature(), geojson::FeatureBase::get_origination_length(), geojson::FeatureBase::is_root(), geojson::FeatureBase::operator==(), geojson::FeatureBase::origination_features(), and geojson::FeatureBase::remove_origination().
properties
PropertyMap geojson::FeatureBase::properties protected inherited
Referenced by geojson::FeatureBase::FeatureBase(), geojson::FeatureBase::FeatureBase(), geojson::FeatureBase::get_properties(), geojson::FeatureBase::get_properties(), geojson::FeatureBase::get_property(), and geojson::FeatureBase::property_keys().
type
FeatureType geojson::FeatureBase::type protected inherited
Referenced by geojson::CollectionFeature::CollectionFeature(), geojson::CollectionFeature::CollectionFeature(), geojson::FeatureBase::FeatureBase(), geojson::LineStringFeature::LineStringFeature(), geojson::LineStringFeature::LineStringFeature(), MultiLineStringFeature(), MultiLineStringFeature(), geojson::MultiPointFeature::MultiPointFeature(), geojson::MultiPointFeature::MultiPointFeature(), geojson::MultiPolygonFeature::MultiPolygonFeature(), geojson::MultiPolygonFeature::MultiPolygonFeature(), geojson::PointFeature::PointFeature(), geojson::PointFeature::PointFeature(), geojson::PolygonFeature::PolygonFeature(), geojson::FeatureBase::get_geometry_collection(), and geojson::FeatureBase::get_type().
The documentation for this class was generated from the following file:
include/geojson/features/MultiLineStringFeature.hpp