NGen: Reservoir::Implicit_Time::Reservoir Class Reference
Reservoir::Implicit_Time::Reservoir Class Reference
Reservoir that has zero, one, or multiple outlets and no time dimension.
#include <Reservoir_Timeless.hpp>
Public Types
typedef std::vector< std::shared_ptr< Reservoir_Outlet > > outlet_vector_type
typedef std::shared_ptr< Reservoir_Outlet > outlet_type
Public Member Functions
Reservoir (double minimum_storage_meters=0.0, double maximum_storage_meters=1.0, double current_storage_height_meters=0.0)
Default Constructor building a reservoir with no outlets.
Reservoir (double minimum_storage_meters, double maximum_storage_meters, double current_storage_height_meters, double a, double b, double activation_threshold_meters, double max_flux_meters)
Parameterized Constructor building a reservoir with only one standard base outlet.
Reservoir (double minimum_storage_meters, double maximum_storage_meters, double current_storage_height_meters, double a, double activation_threshold_meters, double max_flux_meters)
Parameterized Constructor building a reservoir with only one linear outlet.
Reservoir (double minimum_storage_meters, double maximum_storage_meters, double current_storage_height_meters, outlet_vector_type &outlets)
Parameterized Constructor building a reservoir with one or multiple outlets of the base standard and/or exponential type.
double response_meters (double in_flux_meters, double &excess_water_meters)
Function to update the reservoir storage in meters and return a response in meters to an influx.
void add_outlet (outlet_type &outlet)
Adds a preconstructed outlet of any type to the reservoir.
void add_outlet (double a, double b, double activation_threshold_meters, double max_flux_meters)
Adds a parameterized standard nonlinear outlet to the reservoir.
void add_outlet (double a, double activation_threshold_meters, double max_flux_meters)
Adds a parameterized linear outlet to the reservoir.
void sort_outlets ()
Sorts the outlets from lowest to highest acitivation threshold height.
void check_highest_outlet_against_max_storage ()
Ensures that the activation threshold is less than the maximum storage by checking the highest outlet.
double get_storage_height_meters ()
Accessor to return storage.
double flux_meters_for_outlet (int outlet_index)
Return flux in meters of discharge through the specified outlet.
Private Attributes
reservoir_parameters parameters
///
reservoir_state state
outlet_vector_type outlets
Detailed Description
Reservoir that has zero, one, or multiple outlets and no time dimension.
The reservoir has parameters of minimum and maximum storage height in meters and a state variable of current storage height in meters. A vector will be created that stores pointers to the reservoir outlet objects. This class will also sort multiple outlets from lowest to highest activation thresholds in the vector. The response_meters function takes an inflow and cycles through the outlets from lowest to highest activation thresholds and calls the outlet's function to return the discharge flux in meters through the outlet. The reservoir's storage is updated from fluxes of each outlet.
Member Typedef Documentation
outlet_type
typedef std::shared_ptr<Reservoir_Outlet> Reservoir::Implicit_Time::Reservoir::outlet_type
outlet_vector_type
typedef std::vector<std::shared_ptr<Reservoir_Outlet> > Reservoir::Implicit_Time::Reservoir::outlet_vector_type
Constructor & Destructor Documentation
Reservoir() [1/4]
Reservoir::Implicit_Time::Reservoir::Reservoir (double minimum_storage_meters = 0.0, double maximum_storage_meters = 1.0, double current_storage_height_meters = 0.0)
Default Constructor building a reservoir with no outlets.
Parameters
minimum_storage_meters
maximum_storage_meters
current_storage_height_meters
References reservoir_state::current_storage_height_meters, reservoir_parameters::maximum_storage_meters, reservoir_parameters::minimum_storage_meters, parameters, and state.
Reservoir() [2/4]
Reservoir::Implicit_Time::Reservoir::Reservoir (double minimum_storage_meters, double maximum_storage_meters, double current_storage_height_meters, double a, double b, double activation_threshold_meters, double max_flux_meters)
Parameterized Constructor building a reservoir with only one standard base outlet.
Parameters
minimum_storage_meters minimum storage in meters
maximum_storage_meters maximum storage in meters
current_storage_height_meters current storage height in meters
a outlet flux calculation coefficient
b outlet flux calculation exponent
activation_threshold_meters meters from the bottom of the reservoir to the bottom of the outlet
max_flux_meters max outlet flux in meters
Todo:
TODO: Return appropriate error
References outlets.
Reservoir() [3/4]
Reservoir::Implicit_Time::Reservoir::Reservoir (double minimum_storage_meters, double maximum_storage_meters, double current_storage_height_meters, double a, double activation_threshold_meters, double max_flux_meters)
Parameterized Constructor building a reservoir with only one linear outlet.
Parameters
minimum_storage_meters minimum storage in meters
maximum_storage_meters maximum storage in meters
current_storage_height_meters current storage height in meters
a outlet flux calculation coefficient
activation_threshold_meters meters from the bottom of the reservoir to the bottom of the outlet
max_flux_meters max outlet flux in meters
Todo:
TODO: Return appropriate error
References outlets.
Reservoir() [4/4]
Reservoir::Implicit_Time::Reservoir::Reservoir (double minimum_storage_meters, double maximum_storage_meters, double current_storage_height_meters, outlet_vector_type & outlets)
Parameterized Constructor building a reservoir with one or multiple outlets of the base standard and/or exponential type.
A reservoir with an exponential outlet can only be instantiated with this constructor.
Parameters
minimum_storage_meters minimum storage in meters
maximum_storage_meters maximum storage in meters
current_storage_height_meters current storage height in meters
outlets vector of reservoir outlets
References check_highest_outlet_against_max_storage(), outlets, and sort_outlets().
Member Function Documentation
add_outlet() [1/3]
void Reservoir::Implicit_Time::Reservoir::add_outlet (double a, double activation_threshold_meters, double max_flux_meters)
Adds a parameterized linear outlet to the reservoir.
Parameters
a outlet flux calculation coefficient
activation_threshold_meters meters from the bottom of the reservoir to the bottom of the outlet
max_flux_meters max outlet flux in meters
References check_highest_outlet_against_max_storage(), outlets, and sort_outlets().
add_outlet() [2/3]
void Reservoir::Implicit_Time::Reservoir::add_outlet (double a, double b, double activation_threshold_meters, double max_flux_meters)
Adds a parameterized standard nonlinear outlet to the reservoir.
Parameters
a outlet flux calculation coefficient
b outlet flux calculation exponent
activation_threshold_meters meters from the bottom of the reservoir to the bottom of the outlet
max_flux_meters max outlet flux in meters
References check_highest_outlet_against_max_storage(), outlets, and sort_outlets().
add_outlet() [3/3]
void Reservoir::Implicit_Time::Reservoir::add_outlet (outlet_type & outlet)
Adds a preconstructed outlet of any type to the reservoir.
Parameters
outlet single reservoir outlet
References check_highest_outlet_against_max_storage(), outlets, and sort_outlets().
check_highest_outlet_against_max_storage()
void Reservoir::Implicit_Time::Reservoir::check_highest_outlet_against_max_storage ()
Ensures that the activation threshold is less than the maximum storage by checking the highest outlet.
Todo:
TODO: Return appropriate error
References reservoir_parameters::maximum_storage_meters, outlets, and parameters.
Referenced by Reservoir(), and add_outlet().
flux_meters_for_outlet()
double Reservoir::Implicit_Time::Reservoir::flux_meters_for_outlet (int outlet_index)
Return flux in meters of discharge through the specified outlet.
Essentially a wrapper for Reservoir_Outlet#flux_meters, where the args for that come from the reservoir anyway.
Parameters
outlet_index The index of the desired outlet in this instance's vector of outlets
Returns
Todo:
: Implement unordered_map outlet_map
References outlets.
get_storage_height_meters()
double Reservoir::Implicit_Time::Reservoir::get_storage_height_meters ()
Accessor to return storage.
Returns
state.current_storage_height_meters current storage height in meters
References reservoir_state::current_storage_height_meters, and state.
response_meters()
double Reservoir::Implicit_Time::Reservoir::response_meters (double in_flux_meters, double & excess_water_meters)
Function to update the reservoir storage in meters and return a response in meters to an influx.
Parameters
in_flux_meters influx in meters
excess_water_meters excess water in meters
Returns
sum_of_outlet_fluxes_meters sum of the outlet fluxes in meters
Note that the function also takes a reference parameter for holding the amount of excess water for the reservoir beyond its maximum storage after accounting for the input amount. All calls to this function will initialize this parameter, without accounting for any previous value, so any usage should ensure the passed reference does not contain a value that is still needed but not stored elsewhere.
Parameters
in_flux_meters influx in meters
excess_water_meters Reference to an amount of excess water in meters, after considering input and max storage.
Returns
sum_of_outlet_fluxes_meters sum of the outlet fluxes in meters
Todo:
TODO: Return appropriate warning
Todo:
TODO: Return appropriate warning
Todo:
TODO: Return appropriate error
References reservoir_state::current_storage_height_meters, reservoir_parameters::maximum_storage_meters, reservoir_parameters::minimum_storage_meters, outlets, parameters, and state.
sort_outlets()
void Reservoir::Implicit_Time::Reservoir::sort_outlets ()
Sorts the outlets from lowest to highest acitivation threshold height.
Sorts the outlets from lowest to highest activation threshold height.
References outlets.
Referenced by Reservoir(), and add_outlet().
Member Data Documentation
outlets
outlet_vector_type Reservoir::Implicit_Time::Reservoir::outlets private
Referenced by Reservoir(), add_outlet(), check_highest_outlet_against_max_storage(), flux_meters_for_outlet(), response_meters(), and sort_outlets().
parameters
reservoir_parameters Reservoir::Implicit_Time::Reservoir::parameters private
///
Todo:
TODO: Potential Additions
Local sub-timestep to see if storage level crosses threshold below activation height of an outlet or above top of outlet.
Correct for water level falling below an activation threshold and return a flag to possibly call another function that calls a partial timestep.
Return total flux or individual outlet fluxes and these would be multiplied by a watershed area to get discharge in cubic meters.
Referenced by Reservoir(), check_highest_outlet_against_max_storage(), and response_meters().
state
reservoir_state Reservoir::Implicit_Time::Reservoir::state private
Referenced by Reservoir(), get_storage_height_meters(), and response_meters().
The documentation for this class was generated from the following files:
models/kernels/reservoir/Reservoir_Timeless.hpp
src/models/kernels/reservoir/Reservoir_Timeless.cpp