NGen: BMIDataSelector Class Reference
BMIDataSelector Class Reference
#include <DataProviderSelectors.hpp>
Public Member Functions
BMIDataSelector (std::string var, time_t start, long dur, std::string units)
std::string get_variable_name () const
Get the variable name for this selector.
time_t get_init_time () const
Get the initial time for this selector.
long get_duration_secs () const
Get the duration in seconds that is requested by this selector.
std::string get_output_units () const
Get the output units that is requested by this selector.
void set_variable_name (std::string var)
Set the variable name for this selector.
void set_init_time (time_t start)
Set the init time for this selector.
void set_duration_secs (long dur)
Set the duration in secs for the query represented by this selector.
void set_output_units (std::string units)
Set the output units for the data to be returned with this selector.
std::string get_id () const
Get the id string for this NetCDF Data Selector.
void set_id (std::string s)
Set the id string for this NetCDF Data Selector.
Private Attributes
std::string variable_name
The variable name that should be queried.
time_t init_time
The inital time to query the requested variable.
long duration_s
The duration of the query.
std::string output_units
required units for the result to be return in
std::string id_str
Constructor & Destructor Documentation
BMIDataSelector()
BMIDataSelector::BMIDataSelector (std::string var, time_t start, long dur, std::string units) inline
Member Function Documentation
get_duration_secs()
long CatchmentAggrDataSelector::get_duration_secs () const inline inherited
Get the duration in seconds that is requested by this selector.
Returns
long
References CatchmentAggrDataSelector::duration_s.
Referenced by CsvPerFeatureForcingProvider::get_value(), data_access::OptionalWrappedDataProvider::get_value(), realization::Bmi_Module_Formulation< M >::get_value(), realization::Bmi_Multi_Formulation::get_value(), realization::Bmi_Multi_Formulation::get_values(), and realization::Bmi_Module_Formulation< M >::get_values().
get_id()
std::string CatchmentAggrDataSelector::get_id () const inline inherited
Get the id string for this NetCDF Data Selector.
Returns
std::string
References CatchmentAggrDataSelector::id_str.
get_init_time()
time_t CatchmentAggrDataSelector::get_init_time () const inline inherited
Get the initial time for this selector.
Returns
time_t
References CatchmentAggrDataSelector::init_time.
Referenced by CsvPerFeatureForcingProvider::get_value(), data_access::OptionalWrappedDataProvider::get_value(), realization::Bmi_Module_Formulation< M >::get_value(), realization::Bmi_Multi_Formulation::get_value(), realization::Bmi_Multi_Formulation::get_values(), and realization::Bmi_Module_Formulation< M >::get_values().
get_output_units()
std::string CatchmentAggrDataSelector::get_output_units () const inline inherited
Get the output units that is requested by this selector.
Returns
std::string
References CatchmentAggrDataSelector::output_units.
Referenced by CsvPerFeatureForcingProvider::get_value(), data_access::OptionalWrappedDataProvider::get_value(), realization::Bmi_Module_Formulation< M >::get_value(), realization::Bmi_Multi_Formulation::get_value(), realization::Bmi_Multi_Formulation::get_values(), and realization::Bmi_Module_Formulation< M >::get_values().
get_variable_name()
std::string CatchmentAggrDataSelector::get_variable_name () const inline inherited
Get the variable name for this selector.
Returns
std::string
References CatchmentAggrDataSelector::variable_name.
Referenced by CsvPerFeatureForcingProvider::get_value(), data_access::OptionalWrappedDataProvider::get_value(), realization::Bmi_Module_Formulation< M >::get_value(), realization::Bmi_Multi_Formulation::get_value(), realization::Bmi_Multi_Formulation::get_values(), and realization::Bmi_Module_Formulation< M >::get_values().
set_duration_secs()
void CatchmentAggrDataSelector::set_duration_secs (long dur) inline inherited
Set the duration in secs for the query represented by this selector.
Parameters
dur the duration of the query in seconds
References CatchmentAggrDataSelector::duration_s.
set_id()
void CatchmentAggrDataSelector::set_id (std::string s) inline inherited
Set the id string for this NetCDF Data Selector.
Parameters
s
References CatchmentAggrDataSelector::id_str.
set_init_time()
void CatchmentAggrDataSelector::set_init_time (time_t start) inline inherited
Set the init time for this selector.
Parameters
start The inital time for this query
References CatchmentAggrDataSelector::init_time.
set_output_units()
void CatchmentAggrDataSelector::set_output_units (std::string units) inline inherited
Set the output units for the data to be returned with this selector.
Parameters
units The units of the output
References CatchmentAggrDataSelector::output_units.
set_variable_name()
void CatchmentAggrDataSelector::set_variable_name (std::string var) inline inherited
Set the variable name for this selector.
Parameters
var The name of the variable to access
References CatchmentAggrDataSelector::variable_name.
Member Data Documentation
duration_s
long CatchmentAggrDataSelector::duration_s private inherited
The duration of the query.
Referenced by CatchmentAggrDataSelector::get_duration_secs(), and CatchmentAggrDataSelector::set_duration_secs().
id_str
std::string CatchmentAggrDataSelector::id_str private inherited
Referenced by CatchmentAggrDataSelector::get_id(), and CatchmentAggrDataSelector::set_id().
init_time
time_t CatchmentAggrDataSelector::init_time private inherited
The inital time to query the requested variable.
Referenced by CatchmentAggrDataSelector::get_init_time(), and CatchmentAggrDataSelector::set_init_time().
output_units
std::string CatchmentAggrDataSelector::output_units private inherited
required units for the result to be return in
Referenced by CatchmentAggrDataSelector::get_output_units(), and CatchmentAggrDataSelector::set_output_units().
variable_name
std::string CatchmentAggrDataSelector::variable_name private inherited
The variable name that should be queried.
Referenced by CatchmentAggrDataSelector::get_variable_name(), and CatchmentAggrDataSelector::set_variable_name().
The documentation for this class was generated from the following file:
include/forcing/DataProviderSelectors.hpp