NGen: realization::Bmi_Formulation Class Reference
realization::Bmi_Formulation Class Reference abstract
Abstraction of formulation with backing model object(s) that implements the BMI.
#include <Bmi_Formulation.hpp>
Public Types
typedef long time_step_t
Public Member Functions
Bmi_Formulation (std::string id, std::shared_ptr< data_access::GenericDataProvider > forcing, utils::StreamHandler output_stream)
Minimal constructor for objects initialize using the Formulation_Manager and subsequent calls to create_formulation.
virtual ~Bmi_Formulation ()
virtual time_t convert_model_time (const double &model_time)=0
Convert a time value from the model to an epoch time in seconds.
virtual const bool & get_allow_model_exceed_end_time () const =0
Get whether a model may perform updates beyond its end_time.
virtual const vector< string > get_bmi_input_variables ()=0
const string & get_bmi_main_output_var () const
virtual const time_t & get_bmi_model_start_time_forcing_offset_s ()=0
virtual const vector< string > get_bmi_output_variables ()=0
virtual const std::string & get_config_mapped_variable_name (const std::string &model_var_name)=0
When possible, translate a variable name for a BMI model to an internally recognized name.
virtual const double get_model_current_time ()=0
Get the current time for the backing BMI model in its native format and units.
virtual const double get_model_end_time ()=0
Get the end time for the backing BMI model in its native format and units.
virtual const string & get_forcing_file_path () const =0
std::string get_model_type_name ()
Get the name of the specific type of the backing model object.
const vector< std::string > & get_output_header_fields () const
Get the values making up the header line from get_output_header_line(), but organized as a vector of strings.
string get_output_header_line (string delimiter) override
Get a header line appropriate for a file made up of entries from this type's implementation of get_output_line_for_timestep.
const vector< string > & get_output_variable_names () const
Get the names of variables in formulation output.
const vector< std::string > & get_required_parameters () override
virtual bool is_bmi_input_variable (const string &var_name)=0
virtual bool is_bmi_model_time_step_fixed ()=0
Test whether backing model has fixed time step size.
virtual bool is_bmi_output_variable (const string &var_name)=0
virtual bool is_bmi_using_forcing_file () const =0
Whether the backing model uses/reads the forcing file directly for getting input data.
virtual bool is_model_initialized ()=0
Test whether the backing model has been initialize using the BMI standard Initialize function.
void set_output_precision (int precision)
Set the precision of output values when converted to text.
double get_response (time_step_t t_index, time_step_t t_delta) override=0
Execute the backing model formulation for the given time step, where it is of the specified size, and return the response output.
void create_formulation (boost::property_tree::ptree &config, geojson::PropertyMap *global=nullptr) override=0
void create_formulation (geojson::PropertyMap properties) override=0
virtual std::string get_formulation_type ()=0
virtual void add_time (time_t t, double n)
std::string get_id () const
virtual std::string get_output_line_for_timestep (int timestep, std::string delimiter=DEFAULT_FORMULATION_OUTPUT_DELIMITER)=0
Get a formatted line of output values for the given time step as a delimited string.
virtual bool is_et_params_set ()=0
Test whether ET params have been set.
bool is_et_params_set () override
Test whether ET params have been set.
virtual void set_et_params (std::shared_ptr< pdm03_struct > params)=0
Accept a reference for an appropriate object for holding ET parameters for use when executing the model calculations, if maintained by the type.
void set_et_params (std::shared_ptr< pdm03_struct > params) override
Set a reference for an appropriate object for holding ET parameters for use when executing the model calculations.
void set_output_stream (std::string file_path)
void write_output (std::string out)
virtual double calc_et ()=0
virtual const pdm03_struct & get_et_params ()
Get a reference to the appropriate object holding ET parameters for use when executing the model calculations.
virtual const std::vector< std::string > & get_avaliable_variable_names ()=0
Return the variables that are accessable by this data provider.
virtual long get_data_start_time ()=0
Return the first valid time for which data from the request variable can be requested.
virtual long get_data_stop_time ()=0
Return the last valid time for which data from the requested variable can be requested.
virtual long record_duration ()=0
Return the stride in the time dimension.
virtual size_t get_ts_index_for_time (const time_t &epoch_time)=0
Get the index of the data time step that contains the given point in time.
virtual double get_value (const CatchmentAggrDataSelector &selector, ReSampleMethod m=SUM)=0
Get the value of a forcing property for an arbitrary time period, converting units if needed.
virtual std::vector< double > get_values (const CatchmentAggrDataSelector &selector, ReSampleMethod m=SUM)=0
Get the values of a forcing property for an arbitrary time period, converting units if needed.
virtual bool is_property_sum_over_time_step (const std::string &name)
Static Public Member Functions
static void config_pattern_substitution (geojson::PropertyMap &properties, const std::string &key, const std::string &pattern, const std::string &replacement)
Perform in-place substitution on the given config property item, if the item and the pattern are present.
Protected Member Functions
int get_output_precision ()
void set_bmi_main_output_var (const string &main_output_var)
virtual void set_model_type_name (std::string type_name)
Set the name of the specific type of the backing model object.
void set_output_header_fields (const vector< std::string > &output_headers)
void set_output_variable_names (const vector< string > &out_var_names)
Set the names of variables in formulation output.
std::string get_catchment_id () override
void set_catchment_id (std::string cat_id) override
virtual geojson::PropertyMap interpret_parameters (boost::property_tree::ptree &config, geojson::PropertyMap *global=nullptr)
virtual void validate_parameters (geojson::PropertyMap options)
virtual std::shared_ptr< pdm03_struct > get_et_params_ptr ()
Protected Attributes
std::shared_ptr< std::ostringstream > output_text_stream
Object to help with converting numeric output values to text.
std::string id
polygon_t bounds
utils::StreamHandler output
shared_ptr< HY_Catchment > realized_catchment
unsigned long id_number
std::shared_ptr< data_access::GenericDataProvider > forcing
Private Attributes
std::string bmi_main_output_var
std::string model_type_name
std::vector< std::string > output_header_fields
Output header field strings corresponding to the variables output by the realization, as defined in output_variable_names.
std::vector< std::string > output_variable_names
Names of the variables to include in the output from this formulation, which will be some ordered subset of the BMI module output variables accessible to the instance.
int output_precision
The degree of precision in output values when converting to text.
std::vector< std::string > OPTIONAL_PARAMETERS
std::vector< std::string > REQUIRED_PARAMETERS
std::string cat_id
std::shared_ptr< pdm03_struct > et_params
Friends
class ::Bmi_Formulation_Test
class ::Bmi_C_Formulation_Test
Detailed Description
Abstraction of formulation with backing model object(s) that implements the BMI.
Member Typedef Documentation
time_step_t
typedef long realization::Formulation::time_step_t inherited
Constructor & Destructor Documentation
Bmi_Formulation()
realization::Bmi_Formulation::Bmi_Formulation (std::string id, std::shared_ptr< data_access::GenericDataProvider > forcing, utils::StreamHandler output_stream) inline
Minimal constructor for objects initialize using the Formulation_Manager and subsequent calls to create_formulation.
Parameters
id
forcing
output_stream
References set_output_precision().
~Bmi_Formulation()
virtual realization::Bmi_Formulation::~Bmi_Formulation () inline virtual
Member Function Documentation
add_time()
virtual void realization::Formulation::add_time (time_t t, double n) inline virtual inherited
Reimplemented in Simple_Lumped_Model_Realization.
calc_et()
virtual double realization::Et_Accountable::calc_et () pure virtual inherited
Implemented in realization::Bmi_Module_Formulation< M >, realization::Bmi_Module_Formulation< models::bmi::Bmi_C_Adapter >, realization::Bmi_Module_Formulation< models::bmi::Bmi_Cpp_Adapter >, realization::Bmi_Multi_Formulation, Simple_Lumped_Model_Realization, realization::Tshirt_C_Realization, and realization::Tshirt_Realization.
config_pattern_substitution()
static void realization::Catchment_Formulation::config_pattern_substitution (geojson::PropertyMap & properties, const std::string & key, const std::string & pattern, const std::string & replacement) inline static inherited
Perform in-place substitution on the given config property item, if the item and the pattern are present.
Any and all instances of the substring pattern are replaced by replacement, if key maps to a present string-type property value.
Parameters
properties A reference to the properties config object to be altered.
key The key for the configuration property to potentially adjust.
pattern The pattern substring to search for that, when present, should be replaced.
replacement The replacement substring to potentially insert.
References geojson::String.
Referenced by realization::Formulation_Manager::construct_missing_formulation(), and realization::Bmi_Multi_Formulation::init_nested_module().
convert_model_time()
virtual time_t realization::Bmi_Formulation::convert_model_time (const double & model_time) pure virtual
Convert a time value from the model to an epoch time in seconds.
Model time values are typically (though not always) 0-based totals count upward as time progresses. The units are not necessarily seconds. This performs the necessary lookup and conversion for such units, and then shifts the value appropriately for epoch time representation.
Parameters
model_time
Returns
Implemented in realization::Bmi_C_Formulation, realization::Bmi_Cpp_Formulation, and realization::Bmi_Multi_Formulation.
Referenced by realization::Bmi_Module_Formulation< M >::calc_et(), realization::Bmi_Module_Formulation< M >::determine_model_time_offset(), and realization::Bmi_Module_Formulation< M >::set_model_inputs_prior_to_update().
create_formulation() [1/2]
void realization::Catchment_Formulation::create_formulation (boost::property_tree::ptree & config, geojson::PropertyMap * global = nullptr) override pure virtual inherited
Implements realization::Formulation.
Implemented in realization::Bmi_Module_Formulation< M >, realization::Bmi_Module_Formulation< models::bmi::Bmi_C_Adapter >, realization::Bmi_Module_Formulation< models::bmi::Bmi_Cpp_Adapter >, realization::Bmi_Multi_Formulation, Simple_Lumped_Model_Realization, realization::Tshirt_C_Realization, and realization::Tshirt_Realization.
create_formulation() [2/2]
void realization::Catchment_Formulation::create_formulation (geojson::PropertyMap properties) override pure virtual inherited
Implements realization::Formulation.
Implemented in realization::Bmi_Module_Formulation< M >, realization::Bmi_Module_Formulation< models::bmi::Bmi_C_Adapter >, realization::Bmi_Module_Formulation< models::bmi::Bmi_Cpp_Adapter >, realization::Bmi_Multi_Formulation, Simple_Lumped_Model_Realization, realization::Tshirt_C_Realization, and realization::Tshirt_Realization.
get_allow_model_exceed_end_time()
virtual const bool & realization::Bmi_Formulation::get_allow_model_exceed_end_time () const pure virtual
Get whether a model may perform updates beyond its end_time.
Get whether model Update calls are allowed and handled in some way by the backing model for time steps after the model's end_time. Implementations of this type should use this function to safeguard against entering either an invalid or otherwise undesired state as a result of attempting to process a model beyond its available data.
As mentioned, even for models that are capable of validly handling processing beyond end time, it may be desired that they do not for some reason (e.g., the way they account for the lack of input data leads to valid but incorrect results for a specific application). Because of this, whether models are allowed to process beyond their end time is configuration-based.
Returns
Whether a model may perform updates beyond its end_time.
Implemented in realization::Bmi_Module_Formulation< M >, realization::Bmi_Module_Formulation< models::bmi::Bmi_C_Adapter >, realization::Bmi_Module_Formulation< models::bmi::Bmi_Cpp_Adapter >, and realization::Bmi_Multi_Formulation.
get_avaliable_variable_names()
virtual const std::vector< std::string > & data_access::DataProvider< double , CatchmentAggrDataSelector >::get_avaliable_variable_names () pure virtual inherited
Return the variables that are accessable by this data provider.
Implemented in data_access::DeferredWrappedProvider, CsvPerFeatureForcingProvider, data_access::WrappedDataProvider, realization::Bmi_Module_Formulation< M >, realization::Bmi_Module_Formulation< models::bmi::Bmi_C_Adapter >, realization::Bmi_Module_Formulation< models::bmi::Bmi_Cpp_Adapter >, and realization::Bmi_Multi_Formulation.
get_bmi_input_variables()
virtual const vector< string > realization::Bmi_Formulation::get_bmi_input_variables () pure virtual
Implemented in realization::Bmi_Module_Formulation< M >, realization::Bmi_Module_Formulation< models::bmi::Bmi_C_Adapter >, realization::Bmi_Module_Formulation< models::bmi::Bmi_Cpp_Adapter >, and realization::Bmi_Multi_Formulation.
get_bmi_main_output_var()
const string & realization::Bmi_Formulation::get_bmi_main_output_var () const inline
References bmi_main_output_var.
Referenced by realization::Bmi_C_Formulation::get_response(), realization::Bmi_Cpp_Formulation::get_response(), and realization::Bmi_Multi_Formulation::get_response().
get_bmi_model_start_time_forcing_offset_s()
virtual const time_t & realization::Bmi_Formulation::get_bmi_model_start_time_forcing_offset_s () pure virtual
Implemented in realization::Bmi_Module_Formulation< M >, realization::Bmi_Module_Formulation< models::bmi::Bmi_C_Adapter >, realization::Bmi_Module_Formulation< models::bmi::Bmi_Cpp_Adapter >, and realization::Bmi_Multi_Formulation.
get_bmi_output_variables()
virtual const vector< string > realization::Bmi_Formulation::get_bmi_output_variables () pure virtual
Implemented in realization::Bmi_Module_Formulation< M >, realization::Bmi_Module_Formulation< models::bmi::Bmi_C_Adapter >, realization::Bmi_Module_Formulation< models::bmi::Bmi_Cpp_Adapter >, and realization::Bmi_Multi_Formulation.
get_catchment_id()
std::string realization::Catchment_Formulation::get_catchment_id () inline override protected virtual inherited
Implements HY_CatchmentRealization.
References realization::Catchment_Formulation::cat_id.
Referenced by realization::Bmi_Multi_Formulation::create_multi_formulation(), realization::Bmi_Multi_Formulation::get_value(), realization::Bmi_Multi_Formulation::get_values(), realization::Bmi_Multi_Formulation::get_var_value_as_double(), and realization::Bmi_Module_Formulation< M >::set_model_inputs_prior_to_update().
get_config_mapped_variable_name()
virtual const std::string & realization::Bmi_Formulation::get_config_mapped_variable_name (const std::string & model_var_name) pure virtual
When possible, translate a variable name for a BMI model to an internally recognized name.
Parameters
model_var_name The BMI variable name to translate so its purpose is recognized internally.
Returns
Either the translated equivalent variable name, or the provided name if there is not a mapping entry.
Implemented in realization::Bmi_Module_Formulation< M >, realization::Bmi_Module_Formulation< models::bmi::Bmi_C_Adapter >, realization::Bmi_Module_Formulation< models::bmi::Bmi_Cpp_Adapter >, and realization::Bmi_Multi_Formulation.
get_data_start_time()
virtual long data_access::DataProvider< double , CatchmentAggrDataSelector >::get_data_start_time () pure virtual inherited
Return the first valid time for which data from the request variable can be requested.
Implemented in CsvPerFeatureForcingProvider, data_access::WrappedDataProvider, realization::Bmi_Module_Formulation< M >, realization::Bmi_Module_Formulation< models::bmi::Bmi_C_Adapter >, realization::Bmi_Module_Formulation< models::bmi::Bmi_Cpp_Adapter >, and realization::Bmi_Multi_Formulation.
get_data_stop_time()
virtual long data_access::DataProvider< double , CatchmentAggrDataSelector >::get_data_stop_time () pure virtual inherited
Return the last valid time for which data from the requested variable can be requested.
Implemented in CsvPerFeatureForcingProvider, data_access::WrappedDataProvider, realization::Bmi_Module_Formulation< M >, realization::Bmi_Module_Formulation< models::bmi::Bmi_C_Adapter >, realization::Bmi_Module_Formulation< models::bmi::Bmi_Cpp_Adapter >, and realization::Bmi_Multi_Formulation.
get_et_params()
virtual const pdm03_struct & realization::Et_Accountable::get_et_params () inline virtual inherited
Get a reference to the appropriate object holding ET parameters for use when executing the model calculations.
Returns
A reference object for model ET parameters.
References realization::Et_Accountable::et_params.
Referenced by Simple_Lumped_Model_Realization::get_response().
get_et_params_ptr()
virtual std::shared_ptr< pdm03_struct > realization::Et_Accountable::get_et_params_ptr () inline protected virtual inherited
References realization::Et_Accountable::et_params.
Referenced by realization::Tshirt_Realization::get_response().
get_forcing_file_path()
virtual const string & realization::Bmi_Formulation::get_forcing_file_path () const pure virtual
Implemented in realization::Bmi_Module_Formulation< M >, realization::Bmi_Module_Formulation< models::bmi::Bmi_C_Adapter >, realization::Bmi_Module_Formulation< models::bmi::Bmi_Cpp_Adapter >, and realization::Bmi_Multi_Formulation.
get_formulation_type()
virtual std::string realization::Formulation::get_formulation_type () pure virtual inherited
Implemented in realization::Bmi_C_Formulation, realization::Bmi_Cpp_Formulation, realization::Bmi_Multi_Formulation, Simple_Lumped_Model_Realization, realization::Tshirt_C_Realization, and realization::Tshirt_Realization.
Referenced by realization::Bmi_Module_Formulation< M >::check_internal_providers(), realization::Bmi_Module_Formulation< M >::get_value(), realization::Bmi_Module_Formulation< M >::get_values(), and realization::Formulation::validate_parameters().
get_id()
std::string realization::Formulation::get_id () const inline inherited
References realization::Formulation::id.
Referenced by realization::Tshirt_C_Realization::create_formulation(), and realization::Tshirt_Realization::create_formulation().
get_model_current_time()
virtual const double realization::Bmi_Formulation::get_model_current_time () pure virtual
Get the current time for the backing BMI model in its native format and units.
Returns
The current time for the backing BMI model in its native format and units.
Implemented in realization::Bmi_Module_Formulation< M >, realization::Bmi_Module_Formulation< models::bmi::Bmi_C_Adapter >, realization::Bmi_Module_Formulation< models::bmi::Bmi_Cpp_Adapter >, and realization::Bmi_Multi_Formulation.
get_model_end_time()
virtual const double realization::Bmi_Formulation::get_model_end_time () pure virtual
Get the end time for the backing BMI model in its native format and units.
Returns
The end time for the backing BMI model in its native format and units.
Implemented in realization::Bmi_Module_Formulation< M >, realization::Bmi_Module_Formulation< models::bmi::Bmi_C_Adapter >, realization::Bmi_Module_Formulation< models::bmi::Bmi_Cpp_Adapter >, and realization::Bmi_Multi_Formulation.
get_model_type_name()
std::string realization::Bmi_Formulation::get_model_type_name () inline
Get the name of the specific type of the backing model object.
Returns
The name of the backing model object's type.
References model_type_name.
Referenced by realization::Bmi_C_Formulation::construct_model(), realization::Bmi_Cpp_Formulation::construct_model(), realization::Bmi_Module_Formulation< M >::get_value_as_type(), realization::Bmi_Module_Formulation< M >::get_values_as_type(), realization::Bmi_C_Formulation::get_var_value_as_double(), and realization::Bmi_Cpp_Formulation::get_var_value_as_double().
get_output_header_fields()
const vector< std::string > & realization::Bmi_Formulation::get_output_header_fields () const inline
Get the values making up the header line from get_output_header_line(), but organized as a vector of strings.
Returns
The values making up the header line from get_output_header_line() organized as a vector.
References output_header_fields.
Referenced by realization::Bmi_C_Formulation::get_output_header_line(), realization::Bmi_Cpp_Formulation::get_output_header_line(), and get_output_header_line().
get_output_header_line()
string realization::Bmi_Formulation::get_output_header_line (string delimiter) inline override virtual
Get a header line appropriate for a file made up of entries from this type's implementation of get_output_line_for_timestep.
Note that like the output generating function, this line does not include anything for time step.
Returns
An appropriate header line for this type.
Implements realization::Formulation.
References get_output_header_fields().
get_output_line_for_timestep()
virtual std::string realization::Formulation::get_output_line_for_timestep (int timestep, std::string delimiter = DEFAULT_FORMULATION_OUTPUT_DELIMITER) pure virtual inherited
Get a formatted line of output values for the given time step as a delimited string.
This method is useful for preparing calculated data in a representation useful for output files, such as CSV files.
The resulting string will contain calculated values for applicable output variables for the particular formulation, as determined for the given time step. However, the string will not contain any representation of the time step itself.
An empty string is returned if the time step value is not in the range of valid time steps for which there are calculated values for all variables.
Parameters
timestep The time step for which data is desired.
delimiter The value delimiter for the string.
Returns
A delimited string with all the output variable values for the given time step.
Implemented in realization::Bmi_C_Formulation, realization::Bmi_Cpp_Formulation, realization::Bmi_Multi_Formulation, Simple_Lumped_Model_Realization, realization::Tshirt_C_Realization, and realization::Tshirt_Realization.
get_output_precision()
int realization::Bmi_Formulation::get_output_precision () inline protected
References output_precision.
get_output_variable_names()
const vector< string > & realization::Bmi_Formulation::get_output_variable_names () const inline
Get the names of variables in formulation output.
Get the names of the variables to include in the output from this formulation, which should be some ordered subset of the BMI module output variables accessible to this instance.
Returns
References output_variable_names.
Referenced by realization::Bmi_Multi_Formulation::create_multi_formulation(), realization::Bmi_C_Formulation::get_output_line_for_timestep(), realization::Bmi_Cpp_Formulation::get_output_line_for_timestep(), realization::Bmi_Multi_Formulation::get_output_line_for_timestep(), and realization::Bmi_Module_Formulation< M >::inner_create_formulation().
get_required_parameters()
const vector< std::string > & realization::Bmi_Formulation::get_required_parameters () inline override virtual
Implements realization::Catchment_Formulation.
Reimplemented in realization::Bmi_Module_Formulation< M >, realization::Bmi_Module_Formulation< models::bmi::Bmi_C_Adapter >, and realization::Bmi_Module_Formulation< models::bmi::Bmi_Cpp_Adapter >.
References REQUIRED_PARAMETERS.
get_response()
double realization::Catchment_Formulation::get_response (time_step_t t_index, time_step_t t_delta) override pure virtual inherited
Execute the backing model formulation for the given time step, where it is of the specified size, and return the response output.
Any inputs and additional parameters must be made available as instance members.
Types should clearly document the details of their particular response output.
Parameters
t_index The index of the time step for which to run model calculations.
d_delta_s The duration, in seconds, of the time step for which to run model calculations.
Returns
The response output of the model for this time step.
Implements realization::Formulation.
Implemented in Simple_Lumped_Model_Realization, realization::Bmi_C_Formulation, realization::Bmi_Cpp_Formulation, realization::Bmi_Multi_Formulation, realization::Tshirt_C_Realization, and realization::Tshirt_Realization.
get_ts_index_for_time()
virtual size_t data_access::DataProvider< double , CatchmentAggrDataSelector >::get_ts_index_for_time (const time_t & epoch_time) pure virtual inherited
Get the index of the data time step that contains the given point in time.
An std::out_of_range exception should be thrown if the time is not in any time step.
Parameters
epoch_time The point in time, as a seconds-based epoch time.
Returns
The index of the forcing time step that contains the given point in time.
Exceptions
std::out_of_range If the given point is not in any time step.
Implemented in CsvPerFeatureForcingProvider, data_access::WrappedDataProvider, realization::Bmi_Module_Formulation< M >, realization::Bmi_Module_Formulation< models::bmi::Bmi_C_Adapter >, realization::Bmi_Module_Formulation< models::bmi::Bmi_Cpp_Adapter >, and realization::Bmi_Multi_Formulation.
get_value()
virtual double data_access::DataProvider< double , CatchmentAggrDataSelector >::get_value (const CatchmentAggrDataSelector & selector, ReSampleMethod m = SUM) pure virtual inherited
Get the value of a forcing property for an arbitrary time period, converting units if needed.
An std::out_of_range exception should be thrown if the data for the time period is not available.
Parameters
selector Data required to establish what subset of the stored data should be accessed
m How data is to be resampled if there is a mismatch in data alignment or repeat rate
Returns
The value of the forcing property for the described time period, with units converted if needed.
Exceptions
std::out_of_range If data for the time period is not available.
Implemented in CsvPerFeatureForcingProvider, data_access::OptionalWrappedDataProvider, realization::Bmi_Module_Formulation< M >, realization::Bmi_Module_Formulation< models::bmi::Bmi_C_Adapter >, realization::Bmi_Module_Formulation< models::bmi::Bmi_Cpp_Adapter >, realization::Bmi_Multi_Formulation, and data_access::WrappedDataProvider.
get_values()
virtual std::vector< double > data_access::DataProvider< double , CatchmentAggrDataSelector >::get_values (const CatchmentAggrDataSelector & selector, ReSampleMethod m = SUM) pure virtual inherited
Get the values of a forcing property for an arbitrary time period, converting units if needed.
An std::out_of_range exception should be thrown if the data for the time period is not available.
If a provider doesn't implement this function, then by default, get_values will be a simple proxy to get_value with the result wrapped in a std::vector<double>
Parameters
output_name The name of the forcing property of interest.
init_time_epoch The epoch time (in seconds) of the start of the time period.
duration_seconds The length of the time period, in seconds.
output_units The expected units of the desired output value.
Returns
std::vector<double> The vector of values of the forcing property for the described time period, with units converted if needed.
Exceptions
std::out_of_range If data for the time period is not available.
Implemented in CsvPerFeatureForcingProvider, realization::Bmi_Multi_Formulation, realization::Bmi_Module_Formulation< M >, realization::Bmi_Module_Formulation< models::bmi::Bmi_C_Adapter >, realization::Bmi_Module_Formulation< models::bmi::Bmi_Cpp_Adapter >, and data_access::WrappedDataProvider.
interpret_parameters()
virtual geojson::PropertyMap realization::Formulation::interpret_parameters (boost::property_tree::ptree & config, geojson::PropertyMap * global = nullptr) inline protected virtual inherited
References realization::Formulation::validate_parameters().
Referenced by realization::Bmi_Module_Formulation< M >::create_formulation(), realization::Bmi_Multi_Formulation::create_formulation(), Simple_Lumped_Model_Realization::create_formulation(), realization::Tshirt_C_Realization::create_formulation(), and realization::Tshirt_Realization::create_formulation().
is_bmi_input_variable()
virtual bool realization::Bmi_Formulation::is_bmi_input_variable (const string & var_name) pure virtual
Implemented in realization::Bmi_C_Formulation, realization::Bmi_Cpp_Formulation, realization::Bmi_Module_Formulation< M >, realization::Bmi_Module_Formulation< models::bmi::Bmi_C_Adapter >, realization::Bmi_Module_Formulation< models::bmi::Bmi_Cpp_Adapter >, and realization::Bmi_Multi_Formulation.
is_bmi_model_time_step_fixed()
virtual bool realization::Bmi_Formulation::is_bmi_model_time_step_fixed () pure virtual
Test whether backing model has fixed time step size.
Returns
Whether backing model has fixed time step size.
Implemented in realization::Bmi_Module_Formulation< M >, realization::Bmi_Module_Formulation< models::bmi::Bmi_C_Adapter >, realization::Bmi_Module_Formulation< models::bmi::Bmi_Cpp_Adapter >, and realization::Bmi_Multi_Formulation.
is_bmi_output_variable()
virtual bool realization::Bmi_Formulation::is_bmi_output_variable (const string & var_name) pure virtual
Implemented in realization::Bmi_C_Formulation, realization::Bmi_Cpp_Formulation, realization::Bmi_Module_Formulation< M >, realization::Bmi_Module_Formulation< models::bmi::Bmi_C_Adapter >, realization::Bmi_Module_Formulation< models::bmi::Bmi_Cpp_Adapter >, and realization::Bmi_Multi_Formulation.
is_bmi_using_forcing_file()
virtual bool realization::Bmi_Formulation::is_bmi_using_forcing_file () const pure virtual
Whether the backing model uses/reads the forcing file directly for getting input data.
Returns
Whether the backing model uses/reads the forcing file directly for getting input data.
Implemented in realization::Bmi_Module_Formulation< M >, realization::Bmi_Module_Formulation< models::bmi::Bmi_C_Adapter >, realization::Bmi_Module_Formulation< models::bmi::Bmi_Cpp_Adapter >, and realization::Bmi_Multi_Formulation.
is_et_params_set() [1/2]
bool realization::Et_Accountable::is_et_params_set () inline override virtual inherited
Test whether ET params have been set.
Returns
Whether ET params have been set.
Implements realization::Et_Aware.
References realization::Et_Accountable::et_params.
is_et_params_set() [2/2]
virtual bool realization::Et_Aware::is_et_params_set () pure virtual inherited
Test whether ET params have been set.
Returns
Whether ET params have been set.
Implemented in realization::Et_Accountable.
is_model_initialized()
virtual bool realization::Bmi_Formulation::is_model_initialized () pure virtual
Test whether the backing model has been initialize using the BMI standard Initialize function.
Returns
Whether backing model has been initialize using the BMI standard Initialize function.
Implemented in realization::Bmi_C_Formulation, realization::Bmi_Cpp_Formulation, realization::Bmi_Module_Formulation< M >, realization::Bmi_Module_Formulation< models::bmi::Bmi_C_Adapter >, realization::Bmi_Module_Formulation< models::bmi::Bmi_Cpp_Adapter >, and realization::Bmi_Multi_Formulation.
is_property_sum_over_time_step()
virtual bool data_access::DataProvider< double , CatchmentAggrDataSelector >::is_property_sum_over_time_step (const std::string & name) inline virtual inherited
Reimplemented in CsvPerFeatureForcingProvider, data_access::WrappedDataProvider, realization::Bmi_Module_Formulation< M >, realization::Bmi_Module_Formulation< models::bmi::Bmi_C_Adapter >, realization::Bmi_Module_Formulation< models::bmi::Bmi_Cpp_Adapter >, and realization::Bmi_Multi_Formulation.
record_duration()
virtual long data_access::DataProvider< double , CatchmentAggrDataSelector >::record_duration () pure virtual inherited
Return the stride in the time dimension.
Implemented in CsvPerFeatureForcingProvider, data_access::WrappedDataProvider, realization::Bmi_Module_Formulation< M >, realization::Bmi_Module_Formulation< models::bmi::Bmi_C_Adapter >, realization::Bmi_Module_Formulation< models::bmi::Bmi_Cpp_Adapter >, and realization::Bmi_Multi_Formulation.
set_bmi_main_output_var()
void realization::Bmi_Formulation::set_bmi_main_output_var (const string & main_output_var) inline protected
References bmi_main_output_var.
Referenced by realization::Bmi_Multi_Formulation::create_multi_formulation(), and realization::Bmi_Module_Formulation< M >::inner_create_formulation().
set_catchment_id()
void realization::Catchment_Formulation::set_catchment_id (std::string cat_id) inline override protected virtual inherited
Implements HY_CatchmentRealization.
References realization::Catchment_Formulation::cat_id.
Referenced by realization::Catchment_Formulation::Catchment_Formulation().
set_et_params() [1/2]
void realization::Et_Accountable::set_et_params (std::shared_ptr< pdm03_struct > params) inline override virtual inherited
Set a reference for an appropriate object for holding ET parameters for use when executing the model calculations.
Implements realization::Et_Aware.
References realization::Et_Accountable::et_params.
set_et_params() [2/2]
virtual void realization::Et_Aware::set_et_params (std::shared_ptr< pdm03_struct > params) pure virtual inherited
Accept a reference for an appropriate object for holding ET parameters for use when executing the model calculations, if maintained by the type.
Implemented in realization::Et_Accountable.
set_model_type_name()
virtual void realization::Bmi_Formulation::set_model_type_name (std::string type_name) inline protected virtual
Set the name of the specific type of the backing model object.
Parameters
type_name The name of the backing model object's type.
References model_type_name.
Referenced by realization::Bmi_Multi_Formulation::create_multi_formulation(), and realization::Bmi_Module_Formulation< M >::inner_create_formulation().
set_output_header_fields()
void realization::Bmi_Formulation::set_output_header_fields (const vector< std::string > & output_headers) inline protected
References output_header_fields.
Referenced by realization::Bmi_Multi_Formulation::create_multi_formulation(), and realization::Bmi_Module_Formulation< M >::inner_create_formulation().
set_output_precision()
void realization::Bmi_Formulation::set_output_precision (int precision) inline
Set the precision of output values when converted to text.
Parameters
precision The desired precision, as a number of decimal places.
References output_precision, and output_text_stream.
Referenced by Bmi_Formulation(), realization::Bmi_Multi_Formulation::create_multi_formulation(), and realization::Bmi_Module_Formulation< M >::inner_create_formulation().
set_output_stream()
void HY_CatchmentArea::set_output_stream (std::string file_path) inline inherited
References HY_CatchmentArea::output.
set_output_variable_names()
void realization::Bmi_Formulation::set_output_variable_names (const vector< string > & out_var_names) inline protected
Set the names of variables in formulation output.
Set the names of the variables to include in the output from this formulation, which should be some ordered subset of the output variables from the model.
Parameters
out_var_names the names of variables in formulation output, in the order they should appear.
References output_variable_names.
Referenced by realization::Bmi_Multi_Formulation::create_multi_formulation(), and realization::Bmi_Module_Formulation< M >::inner_create_formulation().
validate_parameters()
virtual void realization::Formulation::validate_parameters (geojson::PropertyMap options) inline protected virtual inherited
References realization::Formulation::get_formulation_type(), and realization::Formulation::get_required_parameters().
Referenced by Simple_Lumped_Model_Realization::create_formulation(), realization::Tshirt_C_Realization::create_formulation(), realization::Tshirt_Realization::create_formulation(), realization::Bmi_Multi_Formulation::create_multi_formulation(), realization::Bmi_Module_Formulation< M >::inner_create_formulation(), and realization::Formulation::interpret_parameters().
write_output()
void HY_CatchmentArea::write_output (std::string out) inline inherited
References HY_CatchmentArea::output.
Friends And Related Function Documentation
::Bmi_C_Formulation_Test
friend class ::Bmi_C_Formulation_Test friend
::Bmi_Formulation_Test
friend class ::Bmi_Formulation_Test friend
Member Data Documentation
bmi_main_output_var
std::string realization::Bmi_Formulation::bmi_main_output_var private
Referenced by get_bmi_main_output_var(), and set_bmi_main_output_var().
bounds
polygon_t HY_CatchmentArea::bounds protected inherited
cat_id
std::string realization::Catchment_Formulation::cat_id private inherited
Referenced by realization::Catchment_Formulation::get_catchment_id(), and realization::Catchment_Formulation::set_catchment_id().
et_params
std::shared_ptr<pdm03_struct> realization::Et_Accountable::et_params private inherited
Referenced by realization::Bmi_Module_Formulation< M >::calc_et(), realization::Et_Accountable::get_et_params(), realization::Et_Accountable::get_et_params_ptr(), realization::Et_Accountable::is_et_params_set(), and realization::Et_Accountable::set_et_params().
forcing
std::shared_ptr<data_access::GenericDataProvider> HY_CatchmentRealization::forcing protected inherited
Referenced by realization::Bmi_Module_Formulation< M >::calc_et(), realization::Bmi_Multi_Formulation::create_multi_formulation(), realization::Bmi_Module_Formulation< M >::determine_model_time_offset(), Simple_Lumped_Model_Realization::get_response(), realization::Tshirt_C_Realization::get_response(), realization::Tshirt_Realization::get_response(), and realization::Bmi_Module_Formulation< M >::set_model_inputs_prior_to_update().
id
std::string realization::Formulation::id protected inherited
Referenced by realization::Formulation::get_id().
id_number
unsigned long HY_CatchmentRealization::id_number protected inherited
model_type_name
std::string realization::Bmi_Formulation::model_type_name private
Referenced by get_model_type_name(), and set_model_type_name().
OPTIONAL_PARAMETERS
std::vector<std::string> realization::Bmi_Formulation::OPTIONAL_PARAMETERS private
Initial value:
= {
                BMI_REALIZATION_CFG_PARAM_OPT__FORCING_FILE,
                BMI_REALIZATION_CFG_PARAM_OPT__VAR_STD_NAMES,
                BMI_REALIZATION_CFG_PARAM_OPT__OUT_VARS,
                BMI_REALIZATION_CFG_PARAM_OPT__OUT_HEADER_FIELDS,
                BMI_REALIZATION_CFG_PARAM_OPT__ALLOW_EXCEED_END,
                BMI_REALIZATION_CFG_PARAM_OPT__FIXED_TIME_STEP,
                BMI_REALIZATION_CFG_PARAM_OPT__LIB_FILE
        }
output
utils::StreamHandler HY_CatchmentArea::output protected inherited
Referenced by realization::Bmi_C_Formulation::construct_model(), realization::Bmi_Cpp_Formulation::construct_model(), realization::Bmi_Multi_Formulation::init_nested_module(), HY_CatchmentArea::set_output_stream(), and HY_CatchmentArea::write_output().
output_header_fields
std::vector<std::string> realization::Bmi_Formulation::output_header_fields private
Output header field strings corresponding to the variables output by the realization, as defined in output_variable_names.
Referenced by get_output_header_fields(), and set_output_header_fields().
output_precision
int realization::Bmi_Formulation::output_precision private
The degree of precision in output values when converting to text.
Referenced by get_output_precision(), and set_output_precision().
output_text_stream
std::shared_ptr<std::ostringstream> realization::Bmi_Formulation::output_text_stream protected
Object to help with converting numeric output values to text.
Referenced by realization::Bmi_C_Formulation::get_output_line_for_timestep(), realization::Bmi_Multi_Formulation::get_output_line_for_timestep(), and set_output_precision().
output_variable_names
std::vector<std::string> realization::Bmi_Formulation::output_variable_names private
Names of the variables to include in the output from this formulation, which will be some ordered subset of the BMI module output variables accessible to the instance.
Referenced by get_output_variable_names(), and set_output_variable_names().
realized_catchment
shared_ptr<HY_Catchment> HY_CatchmentRealization::realized_catchment protected inherited
REQUIRED_PARAMETERS
std::vector<std::string> realization::Bmi_Formulation::REQUIRED_PARAMETERS private
Initial value:
= {
                BMI_REALIZATION_CFG_PARAM_REQ__INIT_CONFIG,
                BMI_REALIZATION_CFG_PARAM_REQ__MAIN_OUT_VAR,
                BMI_REALIZATION_CFG_PARAM_REQ__MODEL_TYPE,
                BMI_REALIZATION_CFG_PARAM_REQ__USES_FORCINGS
        }
Referenced by get_required_parameters().
The documentation for this class was generated from the following file:
include/realizations/catchment/Bmi_Formulation.hpp