NGen: realization::Bmi_Module_Formulation< M > Class Template Reference
realization::Bmi_Module_Formulation< M > Class Template Reference abstract
Abstraction of a formulation with a single backing model object that implements the BMI.
#include <Bmi_Module_Formulation.hpp>
Public Types
typedef long time_step_t
Public Member Functions
Bmi_Module_Formulation (std::string id, std::unique_ptr< forcing::ForcingProvider > forcing_provider, utils::StreamHandler output_stream)
Minimal constructor for objects initialize using the Formulation_Manager and subsequent calls to create_formulation.
virtual ~Bmi_Module_Formulation ()
double calc_et () override
Perform (potential) ET calculation, getting input params from instance's backing model as needed.
double calc_et (struct AORC_data raw_aorc)
struct et::aorc_forcing_data convert_aorc_structs (struct AORC_data &aorc_data)
void create_formulation (boost::property_tree::ptree &config, geojson::PropertyMap *global=nullptr) override
void create_formulation (geojson::PropertyMap properties) override
const vector< std::string > & get_available_forcing_outputs () override
Get the collection of forcing output property names this instance can provide.
time_t get_forcing_output_time_begin (const std::string &forcing_name) override
Get the inclusive beginning of the period of time over which this instance can provide data for this forcing.
time_t get_forcing_output_time_end (const std::string &output_name) override
Get the exclusive ending of the period of time over which this instance can provide data for this forcing.
const double get_model_current_time () override
Get the current time for the backing BMI model in its native format and units.
const double get_model_end_time () override
Get the end time for the backing BMI model in its native format and units.
const vector< std::string > & get_required_parameters () override
const std::string & get_config_mapped_variable_name (const std::string &model_var_name) override
When possible, translate a variable name for a BMI model to an internally recognized name.
size_t get_ts_index_for_time (const time_t &epoch_time) override
Get the index of the forcing time step that contains the given point in time.
double get_value (const std::string &output_name, const time_t &init_time, const long &duration_s, const std::string &output_units) override
Get the value of a forcing property for an arbitrary time period, converting units if needed.
bool is_bmi_input_variable (const std::string &var_name) override
bool is_bmi_output_variable (const std::string &var_name) override
bool is_var_name_in_collection (const std::vector< std::string > &all_names, const std::string &var_name)
bool is_property_sum_over_time_step (const std::string &name) override
Get whether a property's per-time-step values are each an aggregate sum over the entire time step.
const vector< string > get_bmi_input_variables () override
const vector< string > get_bmi_output_variables () override
virtual time_t convert_model_time (const double &model_time)=0
Convert a time value from the model to an epoch time in seconds.
const string & get_bmi_main_output_var () const
std::string get_model_type_name ()
Get the name of the specific type of the backing model object.
const vector< std::string > & get_output_header_fields () const
Get the values making up the header line from get_output_header_line(), but organized as a vector of strings.
string get_output_header_line (string delimiter) override
Get a header line appropriate for a file made up of entries from this type's implementation of get_output_line_for_timestep.
const vector< string > & get_output_variable_names () const
Get the names of variables in formulation output.
double get_response (time_step_t t_index, time_step_t t_delta) override=0
Execute the backing model formulation for the given time step, where it is of the specified size, and return the response output.
virtual std::string get_formulation_type ()=0
virtual void add_time (time_t t, double n)
std::string get_id () const
virtual std::string get_output_line_for_timestep (int timestep, std::string delimiter=DEFAULT_FORMULATION_OUTPUT_DELIMITER)=0
Get a formatted line of output values for the given time step as a delimited string.
virtual bool is_et_params_set ()=0
Test whether ET params have been set.
bool is_et_params_set () override
Test whether ET params have been set.
virtual void set_et_params (std::shared_ptr< pdm03_struct > params)=0
Accept a reference for an appropriate object for holding ET parameters for use when executing the model calculations, if maintained by the type.
void set_et_params (std::shared_ptr< pdm03_struct > params) override
Set a reference for an appropriate object for holding ET parameters for use when executing the model calculations.
void set_output_stream (std::string file_path)
void write_output (std::string out)
virtual const pdm03_struct & get_et_params ()
Get a reference to the appropriate object holding ET parameters for use when executing the model calculations.
Static Public Member Functions
static void config_pattern_substitution (geojson::PropertyMap &properties, const std::string &key, const std::string &pattern, const std::string &replacement)
Perform in-place substitution on the given config property item, if the item and the pattern are present.
Protected Member Functions
virtual std::shared_ptr< M > construct_model (const geojson::PropertyMap &properties)=0
Construct model and its shared pointer, potentially supplying input variable values from config.
void determine_model_time_offset ()
Determine and set the offset time of the model in seconds, compared to forcing data.
const bool & get_allow_model_exceed_end_time () const override
Get whether a model may perform updates beyond its end_time.
const string & get_bmi_init_config () const
std::shared_ptr< M > get_bmi_model ()
Get the backing model object implementing the BMI.
const string & get_forcing_file_path () const override
const time_t & get_bmi_model_start_time_forcing_offset_s () override
virtual double get_var_value_as_double (const std::string &var_name)=0
Get value for some BMI model variable.
virtual double get_var_value_as_double (const int &index, const std::string &var_name)=0
Get value for some BMI model variable at a specific index.
void inner_create_formulation (geojson::PropertyMap properties, bool needs_param_validation)
Universal logic applied when creating a BMI-backed formulation from NGen config.
bool is_bmi_model_time_step_fixed () override
Test whether backing model has fixed time step size.
bool is_bmi_using_forcing_file () const override
Whether the backing model uses/reads the forcing file directly for getting input data.
bool is_model_initialized () override
Test whether the backing model object has been initialize using the BMI standard Initialize function.
void set_allow_model_exceed_end_time (bool allow_exceed_end)
void set_bmi_init_config (const string &init_config)
void set_bmi_model (std::shared_ptr< M > model)
Set the backing model object implementing the BMI.
void set_bmi_model_start_time_forcing_offset_s (const time_t &offset_s)
void set_bmi_model_time_step_fixed (bool is_fix_time_step)
void set_bmi_using_forcing_file (bool uses_forcing_file)
Set whether the backing model uses/reads the forcing file directly for getting input data.
void set_forcing_file_path (const string &forcing_path)
virtual void set_model_initialized (bool is_initialized)
Set whether the backing model object has been initialize using the BMI standard Initialize function.
template<typename T >
std::shared_ptr< void > get_value_as_type (std::string type, T value)
void set_model_inputs_prior_to_update (const double &model_init_time, time_step_t t_delta)
Set BMI input variable values for the model appropriately prior to calling its BMIupdate()``.
void set_bmi_main_output_var (const string &main_output_var)
virtual void set_model_type_name (std::string type_name)
Set the name of the specific type of the backing model object.
void set_output_header_fields (const vector< std::string > &output_headers)
void set_output_variable_names (const vector< string > &out_var_names)
Set the names of variables in formulation output.
std::string get_catchment_id () override
void set_catchment_id (std::string cat_id) override
void _link_legacy_forcing ()
virtual geojson::PropertyMap interpret_parameters (boost::property_tree::ptree &config, geojson::PropertyMap *global=nullptr)
virtual void validate_parameters (geojson::PropertyMap options)
virtual std::shared_ptr< pdm03_struct > get_et_params_ptr ()
Protected Attributes
time_step_t last_model_response_delta = 0
The delta of the last model update execution (typically, this is time step size).
time_t last_model_response_start_time = 0
The epoch time of the model at the beginning of its last update.
std::map< std::string, std::shared_ptr< forcing::ForcingProvider > > input_forcing_providers
Forcing legacy_forcing
std::string id
polygon_t bounds
utils::StreamHandler output
shared_ptr< HY_Catchment > realized_catchment
unsigned long id_number
std::unique_ptr< forcing::ForcingProvider > forcing
Private Attributes
bool allow_model_exceed_end_time = false
Whether model Update calls are allowed and handled in some way by the backing model for time steps after the model's end_time.
std::vector< std::string > available_forcings
The set of available "forcings" (output variables, plus their mapped aliases) that the model can provide.
std::string bmi_init_config
std::shared_ptr< M > bmi_model
bool bmi_model_time_step_fixed = true
Whether backing model has fixed time step size.
time_t bmi_model_start_time_forcing_offset_s
The offset, converted to seconds, from the model's start time to the start time of the initial forcing time step.
std::map< std::string, std::string > bmi_var_names_map
A configured mapping of BMI model variable names to standard names for use inside the framework.
bool bmi_using_forcing_file
Whether the backing model uses/reads the forcing file directly for getting input data.
std::string forcing_file_path
bool model_initialized = false
std::vector< std::string > OPTIONAL_PARAMETERS
std::vector< std::string > REQUIRED_PARAMETERS
std::string bmi_main_output_var
std::string model_type_name
std::vector< std::string > output_header_fields
Output header field strings corresponding to the variables output by the realization, as defined in output_variable_names.
std::vector< std::string > output_variable_names
Names of the variables to include in the output from this formulation, which will be some ordered subset of the BMI module output variables accessible to the instance.
std::shared_ptr< pdm03_struct > et_params
Friends
class Bmi_Multi_Formulation
class ::Bmi_Formulation_Test
class ::Bmi_C_Formulation_Test
Detailed Description
template<class M>
class realization::Bmi_Module_Formulation< M >
Abstraction of a formulation with a single backing model object that implements the BMI.
Template Parameters
M The type for the backing BMI model object.
Member Typedef Documentation
time_step_t
typedef long realization::Formulation::time_step_t inherited
Constructor & Destructor Documentation
Bmi_Module_Formulation()
template<class M > realization::Bmi_Module_Formulation< M >::Bmi_Module_Formulation (std::string id, std::unique_ptr< forcing::ForcingProvider > forcing_provider, utils::StreamHandler output_stream) inline
Minimal constructor for objects initialize using the Formulation_Manager and subsequent calls to create_formulation.
Parameters
id
forcing_provider
output_stream
~Bmi_Module_Formulation()
template<class M > virtual realization::Bmi_Module_Formulation< M >::~Bmi_Module_Formulation () inline virtual
Member Function Documentation
_link_legacy_forcing()
void realization::Catchment_Formulation::_link_legacy_forcing () inline protected inherited
Referenced by realization::Tshirt_C_Realization::Tshirt_C_Realization(), and realization::Tshirt_Realization::Tshirt_Realization().
add_time()
virtual void realization::Formulation::add_time (time_t t, double n) inline virtual inherited
Reimplemented in Simple_Lumped_Model_Realization.
calc_et() [1/2]
template<class M > double realization::Bmi_Module_Formulation< M >::calc_et () inline override virtual
Perform (potential) ET calculation, getting input params from instance's backing model as needed.
Function uses forcings from the "current" time step.
Returns
Calculated ET or potential ET, or 0.0 if required parameters could not be obtained.
Implements realization::Et_Accountable.
References AORC_data::APCP_surface_kg_per_meters_squared, realization::Bmi_Formulation::convert_model_time(), AORC_data::DLWRF_surface_W_per_meters_squared, AORC_data::DSWRF_surface_W_per_meters_squared, realization::Bmi_Module_Formulation< M >::get_bmi_model(), realization::Bmi_Module_Formulation< M >::get_bmi_model_start_time_forcing_offset_s(), AORC_data::PRES_surface_Pa, AORC_data::SPFH_2maboveground_kg_per_kg, AORC_data::TMP_2maboveground_K, AORC_data::UGRD_10maboveground_meters_per_second, and AORC_data::VGRD_10maboveground_meters_per_second.
Referenced by realization::Bmi_Module_Formulation< M >::get_value().
calc_et() [2/2]
template<class M > double realization::Bmi_Module_Formulation< M >::calc_et (struct AORC_data raw_aorc) inline
References et::evapotranspiration_forcing::air_pressure_Pa, et::evapotranspiration_forcing::air_temperature_C, et::surface_radiation_forcing::air_temperature_C, et::calc_air_saturation_vapor_pressure_Pa(), et::calculate_net_radiation_W_per_sq_m(), et::evapotranspiration_forcing::canopy_resistance_sec_per_m, AORC_data::DLWRF_surface_W_per_meters_squared, AORC_data::DSWRF_surface_W_per_meters_squared, realization::Et_Accountable::et_params, et::combined::evapotranspiration_combination_method(), et::evapotranspiration_forcing::ground_heat_flux_W_per_sq_m, et::surface_radiation_forcing::incoming_longwave_radiation_W_per_sq_m, et::surface_radiation_forcing::incoming_shortwave_radiation_W_per_sq_m, et::evapotranspiration_forcing::net_radiation_W_per_sq_m, AORC_data::PRES_surface_Pa, et::evapotranspiration_forcing::relative_humidity_percent, et::surface_radiation_forcing::relative_humidity_percent, et::evapotranspiration_forcing::specific_humidity_2m_kg_per_kg, AORC_data::SPFH_2maboveground_kg_per_kg, et::surface_radiation_params::surface_longwave_emissivity, et::surface_radiation_params::surface_shortwave_albedo, et::surface_radiation_forcing::surface_skin_temperature_C, AORC_data::TMP_2maboveground_K, AORC_data::UGRD_10maboveground_meters_per_second, et::evapotranspiration_options::use_aerodynamic_method, et::evapotranspiration_options::use_combination_method, et::evapotranspiration_options::use_energy_balance_method, et::evapotranspiration_options::use_penman_monteith_method, et::evapotranspiration_options::use_priestley_taylor_method, AORC_data::VGRD_10maboveground_meters_per_second, et::evapotranspiration_forcing::water_temperature_C, et::evapotranspiration_forcing::wind_speed_m_per_s, and et::evapotranspiration_options::yes_aorc.
config_pattern_substitution()
static void realization::Catchment_Formulation::config_pattern_substitution (geojson::PropertyMap & properties, const std::string & key, const std::string & pattern, const std::string & replacement) inline static inherited
Perform in-place substitution on the given config property item, if the item and the pattern are present.
Any and all instances of the substring pattern are replaced by replacement, if key maps to a present string-type property value.
Parameters
properties A reference to the properties config object to be altered.
key The key for the configuration property to potentially adjust.
pattern The pattern substring to search for that, when present, should be replaced.
replacement The replacement substring to potentially insert.
References geojson::String.
Referenced by realization::Formulation_Manager::construct_missing_formulation().
construct_model()
template<class M > virtual std::shared_ptr<M> realization::Bmi_Module_Formulation< M >::construct_model (const geojson::PropertyMap & properties) protected pure virtual
Construct model and its shared pointer, potentially supplying input variable values from config.
Construct a model (and a shared pointer to it), checking whether additional input variable values are present in the configuration properties and need to be used during model construction.
Parameters
properties Configuration properties for the formulation, potentially containing values for input variables
Returns
A shared pointer to a newly constructed model object
Implemented in realization::Bmi_C_Formulation.
Referenced by realization::Bmi_Module_Formulation< M >::inner_create_formulation().
convert_aorc_structs()
template<class M > struct et::aorc_forcing_data realization::Bmi_Module_Formulation< M >::convert_aorc_structs (struct AORC_data & aorc_data) inline
convert_model_time()
virtual time_t realization::Bmi_Formulation::convert_model_time (const double & model_time) pure virtual inherited
Convert a time value from the model to an epoch time in seconds.
Model time values are typically (though not always) 0-based totals count upward as time progresses. The units are not necessarily seconds. This performs the necessary lookup and conversion for such units, and then shifts the value appropriately for epoch time representation.
Parameters
model_time
Returns
Implemented in realization::Bmi_Multi_Formulation, and realization::Bmi_C_Formulation.
Referenced by realization::Bmi_Module_Formulation< M >::calc_et(), realization::Bmi_Module_Formulation< M >::determine_model_time_offset(), and realization::Bmi_Module_Formulation< M >::set_model_inputs_prior_to_update().
create_formulation() [1/2]
template<class M > void realization::Bmi_Module_Formulation< M >::create_formulation (boost::property_tree::ptree & config, geojson::PropertyMap * global = nullptr) inline override virtual
Implements realization::Catchment_Formulation.
References realization::Bmi_Module_Formulation< M >::inner_create_formulation(), and realization::Formulation::interpret_parameters().
create_formulation() [2/2]
template<class M > void realization::Bmi_Module_Formulation< M >::create_formulation (geojson::PropertyMap properties) inline override virtual
Implements realization::Catchment_Formulation.
References realization::Bmi_Module_Formulation< M >::inner_create_formulation().
determine_model_time_offset()
template<class M > void realization::Bmi_Module_Formulation< M >::determine_model_time_offset () inline protected
Determine and set the offset time of the model in seconds, compared to forcing data.
BMI models frequently have their model start time be set to 0. As such, to know what the forcing time is compared to the model time, an offset value is needed. This becomes important in situations when the size of the time steps for forcing data versus model execution are not equal. This method will determine and set this value.
References realization::Bmi_Formulation::convert_model_time(), realization::Bmi_Module_Formulation< M >::get_bmi_model(), and realization::Bmi_Module_Formulation< M >::set_bmi_model_start_time_forcing_offset_s().
Referenced by realization::Bmi_Module_Formulation< M >::inner_create_formulation().
get_allow_model_exceed_end_time()
template<class M > const bool& realization::Bmi_Module_Formulation< M >::get_allow_model_exceed_end_time () const inline override protected virtual
Get whether a model may perform updates beyond its end_time.
Get whether model Update calls are allowed and handled in some way by the backing model for time steps after the model's end_time. Implementations of this type should use this function to safeguard against entering either an invalid or otherwise undesired state as a result of attempting to process a model beyond its available data.
As mentioned, even for models that are capable of validly handling processing beyond end time, it may be desired that they do not for some reason (e.g., the way they account for the lack of input data leads to valid but incorrect results for a specific application). Because of this, whether models are allowed to process beyond their end time is configuration-based.
Returns
Whether a model may perform updates beyond its end_time.
Implements realization::Bmi_Formulation.
References realization::Bmi_Module_Formulation< M >::allow_model_exceed_end_time.
get_available_forcing_outputs()
template<class M > const vector<std::string>& realization::Bmi_Module_Formulation< M >::get_available_forcing_outputs () inline override virtual
Get the collection of forcing output property names this instance can provide.
This is part of the ForcingProvider interface. This interface must be implemented for items of this type to be usable as "forcing" providers for situations when some other object needs to receive as an input (i.e., one of its forcings) a data property output from this object.
For this type, this is the collection of BMI output variables, plus any aliases included in the formulation config's output variable mapping.
Returns
The collection of forcing output property names this instance can provide.
See also
ForcingProvider
Implements forcing::ForcingProvider.
References realization::Bmi_Module_Formulation< M >::available_forcings, realization::Bmi_Module_Formulation< M >::bmi_var_names_map, realization::Bmi_Module_Formulation< M >::get_bmi_model(), and realization::Bmi_Module_Formulation< M >::is_model_initialized().
Referenced by realization::Bmi_Module_Formulation< M >::get_value().
get_bmi_init_config()
template<class M > const string& realization::Bmi_Module_Formulation< M >::get_bmi_init_config () const inline protected
References realization::Bmi_Module_Formulation< M >::bmi_init_config.
get_bmi_input_variables()
template<class M > const vector<string> realization::Bmi_Module_Formulation< M >::get_bmi_input_variables () inline override virtual
Implements realization::Bmi_Formulation.
References realization::Bmi_Module_Formulation< M >::get_bmi_model().
Referenced by realization::Bmi_Module_Formulation< M >::is_bmi_input_variable().
get_bmi_main_output_var()
const string& realization::Bmi_Formulation::get_bmi_main_output_var () const inline inherited
Referenced by realization::Bmi_C_Formulation::get_response(), and realization::Bmi_Multi_Formulation::get_response().
get_bmi_model()
template<class M > std::shared_ptr<M> realization::Bmi_Module_Formulation< M >::get_bmi_model () inline protected
Get the backing model object implementing the BMI.
Returns
Shared pointer to the backing model object that implements the BMI.
References realization::Bmi_Module_Formulation< M >::bmi_model.
Referenced by realization::Bmi_Module_Formulation< M >::calc_et(), realization::Bmi_Module_Formulation< M >::determine_model_time_offset(), realization::Bmi_Module_Formulation< M >::get_available_forcing_outputs(), realization::Bmi_Module_Formulation< M >::get_bmi_input_variables(), realization::Bmi_Module_Formulation< M >::get_bmi_output_variables(), realization::Bmi_Module_Formulation< M >::get_model_current_time(), realization::Bmi_Module_Formulation< M >::get_model_end_time(), realization::Bmi_Module_Formulation< M >::get_value(), realization::Bmi_Module_Formulation< M >::inner_create_formulation(), and realization::Bmi_Module_Formulation< M >::set_model_inputs_prior_to_update().
get_bmi_model_start_time_forcing_offset_s()
template<class M > const time_t& realization::Bmi_Module_Formulation< M >::get_bmi_model_start_time_forcing_offset_s () inline override protected virtual
Implements realization::Bmi_Formulation.
References realization::Bmi_Module_Formulation< M >::bmi_model_start_time_forcing_offset_s.
Referenced by realization::Bmi_Module_Formulation< M >::calc_et(), and realization::Bmi_Module_Formulation< M >::set_model_inputs_prior_to_update().
get_bmi_output_variables()
template<class M > const vector<string> realization::Bmi_Module_Formulation< M >::get_bmi_output_variables () inline override virtual
Implements realization::Bmi_Formulation.
References realization::Bmi_Module_Formulation< M >::get_bmi_model().
Referenced by realization::Bmi_Module_Formulation< M >::is_bmi_output_variable().
get_catchment_id()
std::string realization::Catchment_Formulation::get_catchment_id () inline override protected virtual inherited
Implements HY_CatchmentRealization.
References realization::Formulation::id.
Referenced by realization::Bmi_Multi_Formulation::create_multi_formulation().
get_config_mapped_variable_name()
template<class M > const std::string& realization::Bmi_Module_Formulation< M >::get_config_mapped_variable_name (const std::string & model_var_name) inline override virtual
When possible, translate a variable name for a BMI model to an internally recognized name.
Translate some BMI variable name to something recognized in some internal context for use within NGen. Do this according to the map of variable names supplied in the external formulation config. If no mapping for the given variable name was configured, return the variable name itself.
For example, perhaps a BMI model has the input variable "RAIN_RATE." Configuring this variable name to map to "precip_rate" will allow the formulation to understand that this particular forcing field should be used to set the model's "RAIN_RATE" variable.
Parameters
model_var_name The BMI variable name to translate so its purpose is recognized internally.
Returns
Either the internal equivalent variable name, or the provided name if there is not a mapping entry.
Implements realization::Bmi_Formulation.
References realization::Bmi_Module_Formulation< M >::bmi_var_names_map.
Referenced by realization::Bmi_Module_Formulation< M >::set_model_inputs_prior_to_update().
get_et_params()
virtual const pdm03_struct& realization::Et_Accountable::get_et_params () inline virtual inherited
Get a reference to the appropriate object holding ET parameters for use when executing the model calculations.
Returns
A reference object for model ET parameters.
References realization::Et_Accountable::et_params.
Referenced by Simple_Lumped_Model_Realization::get_response().
get_et_params_ptr()
virtual std::shared_ptr<pdm03_struct> realization::Et_Accountable::get_et_params_ptr () inline protected virtual inherited
References realization::Et_Accountable::et_params.
Referenced by realization::Tshirt_Realization::get_response().
get_forcing_file_path()
template<class M > const string& realization::Bmi_Module_Formulation< M >::get_forcing_file_path () const inline override protected virtual
Implements realization::Bmi_Formulation.
References realization::Bmi_Module_Formulation< M >::forcing_file_path.
get_forcing_output_time_begin()
template<class M > time_t realization::Bmi_Module_Formulation< M >::get_forcing_output_time_begin (const std::string & forcing_name) inline override virtual
Get the inclusive beginning of the period of time over which this instance can provide data for this forcing.
This is part of the ForcingProvider interface. This interface must be implemented for items of this type to be usable as "forcing" providers for situations when some other object needs to receive as an input (i.e., one of its forcings) a data property output from this object.
Returns
The inclusive beginning of the period of time over which this instance can provide this data.
Implements forcing::ForcingProvider.
get_forcing_output_time_end()
template<class M > time_t realization::Bmi_Module_Formulation< M >::get_forcing_output_time_end (const std::string & output_name) inline override virtual
Get the exclusive ending of the period of time over which this instance can provide data for this forcing.
This is part of the ForcingProvider interface. This interface must be implemented for items of this type to be usable as "forcing" providers for situations when some other object needs to receive as an input (i.e., one of its forcings) a data property output from this object.
Returns
The exclusive ending of the period of time over which this instance can provide this data.
Implements forcing::ForcingProvider.
get_formulation_type()
virtual std::string realization::Formulation::get_formulation_type () pure virtual inherited
Implemented in realization::Tshirt_Realization, realization::Tshirt_C_Realization, Simple_Lumped_Model_Realization, realization::Bmi_Multi_Formulation, and realization::Bmi_C_Formulation.
Referenced by realization::Bmi_Module_Formulation< M >::get_value(), and realization::Formulation::validate_parameters().
get_id()
std::string realization::Formulation::get_id () const inline inherited
References realization::Formulation::id.
Referenced by realization::Tshirt_C_Realization::create_formulation(), and realization::Tshirt_Realization::create_formulation().
get_model_current_time()
template<class M > const double realization::Bmi_Module_Formulation< M >::get_model_current_time () inline override virtual
Get the current time for the backing BMI model in its native format and units.
Returns
The current time for the backing BMI model in its native format and units.
Implements realization::Bmi_Formulation.
References realization::Bmi_Module_Formulation< M >::get_bmi_model().
get_model_end_time()
template<class M > const double realization::Bmi_Module_Formulation< M >::get_model_end_time () inline override virtual
Get the end time for the backing BMI model in its native format and units.
Returns
The end time for the backing BMI model in its native format and units.
Implements realization::Bmi_Formulation.
References realization::Bmi_Module_Formulation< M >::get_bmi_model().
get_model_type_name()
std::string realization::Bmi_Formulation::get_model_type_name () inline inherited
Get the name of the specific type of the backing model object.
Returns
The name of the backing model object's type.
Referenced by realization::Bmi_C_Formulation::construct_model(), realization::Bmi_Module_Formulation< M >::get_value_as_type(), and realization::Bmi_C_Formulation::get_var_value_as_double().
get_output_header_fields()
const vector<std::string>& realization::Bmi_Formulation::get_output_header_fields () const inline inherited
Get the values making up the header line from get_output_header_line(), but organized as a vector of strings.
Returns
The values making up the header line from get_output_header_line() organized as a vector.
Referenced by realization::Bmi_C_Formulation::get_output_header_line().
get_output_header_line()
string realization::Bmi_Formulation::get_output_header_line (string delimiter) inline override virtual inherited
Get a header line appropriate for a file made up of entries from this type's implementation of get_output_line_for_timestep.
Note that like the output generating function, this line does not include anything for time step.
Returns
An appropriate header line for this type.
Implements realization::Formulation.
get_output_line_for_timestep()
virtual std::string realization::Formulation::get_output_line_for_timestep (int timestep, std::string delimiter = DEFAULT_FORMULATION_OUTPUT_DELIMITER) pure virtual inherited
Get a formatted line of output values for the given time step as a delimited string.
This method is useful for preparing calculated data in a representation useful for output files, such as CSV files.
The resulting string will contain calculated values for applicable output variables for the particular formulation, as determined for the given time step. However, the string will not contain any representation of the time step itself.
An empty string is returned if the time step value is not in the range of valid time steps for which there are calculated values for all variables.
Parameters
timestep The time step for which data is desired.
delimiter The value delimiter for the string.
Returns
A delimited string with all the output variable values for the given time step.
Implemented in realization::Tshirt_Realization, realization::Tshirt_C_Realization, Simple_Lumped_Model_Realization, realization::Bmi_Multi_Formulation, and realization::Bmi_C_Formulation.
get_output_variable_names()
const vector<string>& realization::Bmi_Formulation::get_output_variable_names () const inline inherited
Get the names of variables in formulation output.
Get the names of the variables to include in the output from this formulation, which should be some ordered subset of the BMI module output variables accessible to this instance.
Returns
Referenced by realization::Bmi_Multi_Formulation::create_multi_formulation(), realization::Bmi_C_Formulation::get_output_line_for_timestep(), realization::Bmi_Multi_Formulation::get_output_line_for_timestep(), and realization::Bmi_Module_Formulation< M >::inner_create_formulation().
get_required_parameters()
template<class M > const vector<std::string>& realization::Bmi_Module_Formulation< M >::get_required_parameters () inline override virtual
Reimplemented from realization::Bmi_Formulation.
References realization::Bmi_Module_Formulation< M >::REQUIRED_PARAMETERS.
get_response()
double realization::Catchment_Formulation::get_response (time_step_t t_index, time_step_t t_delta) override pure virtual inherited
Execute the backing model formulation for the given time step, where it is of the specified size, and return the response output.
Any inputs and additional parameters must be made available as instance members.
Types should clearly document the details of their particular response output.
Parameters
t_index The index of the time step for which to run model calculations.
d_delta_s The duration, in seconds, of the time step for which to run model calculations.
Returns
The response output of the model for this time step.
Implements realization::Formulation.
Implemented in realization::Tshirt_Realization, realization::Tshirt_C_Realization, realization::Bmi_Multi_Formulation, realization::Bmi_C_Formulation, and Simple_Lumped_Model_Realization.
get_ts_index_for_time()
template<class M > size_t realization::Bmi_Module_Formulation< M >::get_ts_index_for_time (const time_t & epoch_time) inline override virtual
Get the index of the forcing time step that contains the given point in time.
This is part of the ForcingProvider interface. This interface must be implemented for items of this type to be usable as "forcing" providers for situations when some other object needs to receive as an input (i.e., one of its forcings) a data property output from this object.
An std::out_of_range exception should be thrown if the time is not in any time step.
Parameters
epoch_time The point in time, as a seconds-based epoch time.
Returns
The index of the forcing time step that contains the given point in time.
Exceptions
std::out_of_range If the given point is not in any time step.
Implements forcing::ForcingProvider.
get_value()
template<class M > double realization::Bmi_Module_Formulation< M >::get_value (const std::string & output_name, const time_t & init_time, const long & duration_s, const std::string & output_units) inline override virtual
Get the value of a forcing property for an arbitrary time period, converting units if needed.
This is part of the ForcingProvider interface. This interface must be implemented for items of this type to be usable as "forcing" providers for situations when some other object needs to receive as an input (i.e., one of its forcings) a data property output from this object.
An std::out_of_range exception should be thrown if the data for the time period is not available.
Parameters
output_name The name of the forcing property of interest.
init_time_epoch The epoch time (in seconds) of the start of the time period.
duration_seconds The length of the time period, in seconds.
output_units The expected units of the desired output value.
Returns
The value of the forcing property for the described time period, with units converted if needed.
Exceptions
std::out_of_range If data for the time period is not available.
See also
ForcingProvider::get_value
Implements forcing::ForcingProvider.
References realization::Bmi_Module_Formulation< M >::bmi_var_names_map, realization::Bmi_Module_Formulation< M >::calc_et(), realization::Bmi_Module_Formulation< M >::get_available_forcing_outputs(), realization::Bmi_Module_Formulation< M >::get_bmi_model(), UnitsHelper::get_converted_value(), realization::Formulation::get_formulation_type(), and realization::Bmi_Module_Formulation< M >::get_var_value_as_double().
get_value_as_type()
template<class M > template<typename T > std::shared_ptr<void> realization::Bmi_Module_Formulation< M >::get_value_as_type (std::string type, T value) inline protected
References realization::Bmi_Formulation::get_model_type_name().
Referenced by realization::Bmi_Module_Formulation< M >::set_model_inputs_prior_to_update().
get_var_value_as_double() [1/2]
template<class M > virtual double realization::Bmi_Module_Formulation< M >::get_var_value_as_double (const int & index, const std::string & var_name) protected pure virtual
Get value for some BMI model variable at a specific index.
Function gets the value for a provided variable, returned from the backing model as an array, and returns the specific value at the desired index cast as a double type.
The function makes several assumptions:
1. `index` is within array bounds
2. `var_name` is in the set of valid variable names for the model
3. the type for output variable allows the value to be cast to a `double` appropriately
It falls to user (functions) of this function to ensure these assumptions hold before invoking.
Parameters
index
var_name
Returns
Implemented in realization::Bmi_C_Formulation.
get_var_value_as_double() [2/2]
template<class M > virtual double realization::Bmi_Module_Formulation< M >::get_var_value_as_double (const std::string & var_name) protected pure virtual
Get value for some BMI model variable.
This function assumes that the given variable, while returned by the model within an array per the BMI spec, is actual a single, scalar value. Thus, it returns what is at index 0 of the array reference.
Parameters
index
var_name
Returns
Implemented in realization::Bmi_C_Formulation.
Referenced by realization::Bmi_Module_Formulation< M >::get_value().
inner_create_formulation()
template<class M > void realization::Bmi_Module_Formulation< M >::inner_create_formulation (geojson::PropertyMap properties, bool needs_param_validation) inline protected
Universal logic applied when creating a BMI-backed formulation from NGen config.
This performs all the necessary steps to initialize this formulation from provided configuration properties. It is written in such a way that it can be used in appropriately crafted nested calls from both public create_formulation implementations, thus allowing the primary formulation initialization logic to be centralized and not duplicated.
Parameters
properties
needs_param_validation
References realization::Bmi_Module_Formulation< M >::bmi_var_names_map, realization::Bmi_Module_Formulation< M >::construct_model(), realization::Bmi_Module_Formulation< M >::determine_model_time_offset(), realization::Bmi_Module_Formulation< M >::get_bmi_model(), realization::Bmi_Formulation::get_output_variable_names(), realization::Bmi_Module_Formulation< M >::input_forcing_providers, realization::Bmi_Module_Formulation< M >::is_bmi_using_forcing_file(), realization::Bmi_Module_Formulation< M >::model_initialized, realization::Bmi_Module_Formulation< M >::set_allow_model_exceed_end_time(), realization::Bmi_Module_Formulation< M >::set_bmi_init_config(), realization::Bmi_Formulation::set_bmi_main_output_var(), realization::Bmi_Module_Formulation< M >::set_bmi_model(), realization::Bmi_Module_Formulation< M >::set_bmi_model_time_step_fixed(), realization::Bmi_Module_Formulation< M >::set_bmi_using_forcing_file(), realization::Bmi_Module_Formulation< M >::set_forcing_file_path(), realization::Bmi_Formulation::set_model_type_name(), realization::Bmi_Formulation::set_output_header_fields(), realization::Bmi_Formulation::set_output_variable_names(), and realization::Formulation::validate_parameters().
Referenced by realization::Bmi_Module_Formulation< M >::create_formulation().
interpret_parameters()
virtual geojson::PropertyMap realization::Formulation::interpret_parameters (boost::property_tree::ptree & config, geojson::PropertyMap * global = nullptr) inline protected virtual inherited
References realization::Formulation::validate_parameters().
Referenced by realization::Bmi_Module_Formulation< M >::create_formulation(), Simple_Lumped_Model_Realization::create_formulation(), realization::Tshirt_C_Realization::create_formulation(), and realization::Tshirt_Realization::create_formulation().
is_bmi_input_variable()
template<class M > bool realization::Bmi_Module_Formulation< M >::is_bmi_input_variable (const std::string & var_name) inline override virtual
Implements realization::Bmi_Formulation.
References realization::Bmi_Module_Formulation< M >::get_bmi_input_variables(), and realization::Bmi_Module_Formulation< M >::is_var_name_in_collection().
is_bmi_model_time_step_fixed()
template<class M > bool realization::Bmi_Module_Formulation< M >::is_bmi_model_time_step_fixed () inline override protected virtual
Test whether backing model has fixed time step size.
Returns
Whether backing model has fixed time step size.
Implements realization::Bmi_Formulation.
References realization::Bmi_Module_Formulation< M >::bmi_model_time_step_fixed.
is_bmi_output_variable()
template<class M > bool realization::Bmi_Module_Formulation< M >::is_bmi_output_variable (const std::string & var_name) inline override virtual
Implements realization::Bmi_Formulation.
References realization::Bmi_Module_Formulation< M >::get_bmi_output_variables(), and realization::Bmi_Module_Formulation< M >::is_var_name_in_collection().
is_bmi_using_forcing_file()
template<class M > bool realization::Bmi_Module_Formulation< M >::is_bmi_using_forcing_file () const inline override protected virtual
Whether the backing model uses/reads the forcing file directly for getting input data.
Returns
Whether the backing model uses/reads the forcing file directly for getting input data.
Implements realization::Bmi_Formulation.
References realization::Bmi_Module_Formulation< M >::bmi_using_forcing_file.
Referenced by realization::Bmi_Module_Formulation< M >::inner_create_formulation().
is_et_params_set() [1/2]
bool realization::Et_Accountable::is_et_params_set () inline override virtual inherited
Test whether ET params have been set.
Returns
Whether ET params have been set.
Implements realization::Et_Aware.
References realization::Et_Accountable::et_params.
is_et_params_set() [2/2]
virtual bool realization::Et_Aware::is_et_params_set () pure virtual inherited
Test whether ET params have been set.
Returns
Whether ET params have been set.
Implemented in realization::Et_Accountable.
is_model_initialized()
template<class M > bool realization::Bmi_Module_Formulation< M >::is_model_initialized () inline override protected virtual
Test whether the backing model object has been initialize using the BMI standard Initialize function.
Returns
Whether backing model object has been initialize using the BMI standard Initialize function.
Implements realization::Bmi_Formulation.
References realization::Bmi_Module_Formulation< M >::model_initialized.
Referenced by realization::Bmi_Module_Formulation< M >::get_available_forcing_outputs().
is_property_sum_over_time_step()
template<class M > bool realization::Bmi_Module_Formulation< M >::is_property_sum_over_time_step (const std::string & name) inline override virtual
Get whether a property's per-time-step values are each an aggregate sum over the entire time step.
This is part of the ForcingProvider interface. This interface must be implemented for items of this type to be usable as "forcing" providers for situations when some other object needs to receive as an input (i.e., one of its forcings) a data property output from this object.
Certain properties, like rain fall, are aggregated sums over an entire time step. Others, such as pressure, are not such sums and instead something else like an instantaneous reading or an average value.
It may be the case that forcing data is needed for some discretization different than the forcing time step. This aspect must be known in such cases to perform the appropriate value interpolation.
For instances of this type, all output forcings fall under this category.
Parameters
name The name of the forcing property for which the current value is desired.
Returns
Whether the property's value is an aggregate sum, which is always true for this type.
Implements forcing::ForcingProvider.
is_var_name_in_collection()
template<class M > bool realization::Bmi_Module_Formulation< M >::is_var_name_in_collection (const std::vector< std::string > & all_names, const std::string & var_name) inline
Referenced by realization::Bmi_Module_Formulation< M >::is_bmi_input_variable(), and realization::Bmi_Module_Formulation< M >::is_bmi_output_variable().
set_allow_model_exceed_end_time()
template<class M > void realization::Bmi_Module_Formulation< M >::set_allow_model_exceed_end_time (bool allow_exceed_end) inline protected
References realization::Bmi_Module_Formulation< M >::allow_model_exceed_end_time.
Referenced by realization::Bmi_Module_Formulation< M >::inner_create_formulation().
set_bmi_init_config()
template<class M > void realization::Bmi_Module_Formulation< M >::set_bmi_init_config (const string & init_config) inline protected
References realization::Bmi_Module_Formulation< M >::bmi_init_config.
Referenced by realization::Bmi_Module_Formulation< M >::inner_create_formulation().
set_bmi_main_output_var()
void realization::Bmi_Formulation::set_bmi_main_output_var (const string & main_output_var) inline protected inherited
Referenced by realization::Bmi_Multi_Formulation::create_multi_formulation(), and realization::Bmi_Module_Formulation< M >::inner_create_formulation().
set_bmi_model()
template<class M > void realization::Bmi_Module_Formulation< M >::set_bmi_model (std::shared_ptr< M > model) inline protected
Set the backing model object implementing the BMI.
Parameters
model Shared pointer to the BMI model.
References realization::Bmi_Module_Formulation< M >::bmi_model.
Referenced by realization::Bmi_Module_Formulation< M >::inner_create_formulation().
set_bmi_model_start_time_forcing_offset_s()
template<class M > void realization::Bmi_Module_Formulation< M >::set_bmi_model_start_time_forcing_offset_s (const time_t & offset_s) inline protected
References realization::Bmi_Module_Formulation< M >::bmi_model_start_time_forcing_offset_s.
Referenced by realization::Bmi_Module_Formulation< M >::determine_model_time_offset().
set_bmi_model_time_step_fixed()
template<class M > void realization::Bmi_Module_Formulation< M >::set_bmi_model_time_step_fixed (bool is_fix_time_step) inline protected
References realization::Bmi_Module_Formulation< M >::bmi_model_time_step_fixed.
Referenced by realization::Bmi_Module_Formulation< M >::inner_create_formulation().
set_bmi_using_forcing_file()
template<class M > void realization::Bmi_Module_Formulation< M >::set_bmi_using_forcing_file (bool uses_forcing_file) inline protected
Set whether the backing model uses/reads the forcing file directly for getting input data.
Parameters
uses_forcing_file Whether the backing model uses/reads forcing file directly for getting input data.
References realization::Bmi_Module_Formulation< M >::bmi_using_forcing_file.
Referenced by realization::Bmi_Module_Formulation< M >::inner_create_formulation().
set_catchment_id()
void realization::Catchment_Formulation::set_catchment_id (std::string cat_id) inline override protected virtual inherited
Implements HY_CatchmentRealization.
set_et_params() [1/2]
void realization::Et_Accountable::set_et_params (std::shared_ptr< pdm03_struct > params) inline override virtual inherited
Set a reference for an appropriate object for holding ET parameters for use when executing the model calculations.
Implements realization::Et_Aware.
References realization::Et_Accountable::et_params.
set_et_params() [2/2]
virtual void realization::Et_Aware::set_et_params (std::shared_ptr< pdm03_struct > params) pure virtual inherited
Accept a reference for an appropriate object for holding ET parameters for use when executing the model calculations, if maintained by the type.
Implemented in realization::Et_Accountable.
set_forcing_file_path()
template<class M > void realization::Bmi_Module_Formulation< M >::set_forcing_file_path (const string & forcing_path) inline protected
References realization::Bmi_Module_Formulation< M >::forcing_file_path.
Referenced by realization::Bmi_Module_Formulation< M >::inner_create_formulation().
set_model_initialized()
template<class M > virtual void realization::Bmi_Module_Formulation< M >::set_model_initialized (bool is_initialized) inline protected virtual
Set whether the backing model object has been initialize using the BMI standard Initialize function.
Parameters
is_initialized Whether model object has been initialize using the BMI standard Initialize.
References realization::Bmi_Module_Formulation< M >::model_initialized.
set_model_inputs_prior_to_update()
template<class M > void realization::Bmi_Module_Formulation< M >::set_model_inputs_prior_to_update (const double & model_init_time, time_step_t t_delta) inline protected
Set BMI input variable values for the model appropriately prior to calling its BMIupdate()``.
Parameters
model_initial_time The model's time prior to the update, in its internal units and representation.
t_delta The size of the time step over which the formulation is going to update the model, which might be different than the model's internal time step.
References realization::Bmi_Formulation::convert_model_time(), realization::Bmi_Module_Formulation< M >::get_bmi_model(), realization::Bmi_Module_Formulation< M >::get_bmi_model_start_time_forcing_offset_s(), realization::Bmi_Module_Formulation< M >::get_config_mapped_variable_name(), forcing::ForcingProvider::get_value(), realization::Bmi_Module_Formulation< M >::get_value_as_type(), and realization::Bmi_Module_Formulation< M >::input_forcing_providers.
set_model_type_name()
virtual void realization::Bmi_Formulation::set_model_type_name (std::string type_name) inline protected virtual inherited
Set the name of the specific type of the backing model object.
Parameters
type_name The name of the backing model object's type.
Referenced by realization::Bmi_Multi_Formulation::create_multi_formulation(), and realization::Bmi_Module_Formulation< M >::inner_create_formulation().
set_output_header_fields()
void realization::Bmi_Formulation::set_output_header_fields (const vector< std::string > & output_headers) inline protected inherited
Referenced by realization::Bmi_Multi_Formulation::create_multi_formulation(), and realization::Bmi_Module_Formulation< M >::inner_create_formulation().
set_output_stream()
void HY_CatchmentArea::set_output_stream (std::string file_path) inline inherited
References HY_CatchmentArea::output.
set_output_variable_names()
void realization::Bmi_Formulation::set_output_variable_names (const vector< string > & out_var_names) inline protected inherited
Set the names of variables in formulation output.
Set the names of the variables to include in the output from this formulation, which should be some ordered subset of the output variables from the model.
Parameters
out_var_names the names of variables in formulation output, in the order they should appear.
Referenced by realization::Bmi_Multi_Formulation::create_multi_formulation(), and realization::Bmi_Module_Formulation< M >::inner_create_formulation().
validate_parameters()
virtual void realization::Formulation::validate_parameters (geojson::PropertyMap options) inline protected virtual inherited
References realization::Formulation::get_formulation_type(), and realization::Formulation::get_required_parameters().
Referenced by Simple_Lumped_Model_Realization::create_formulation(), realization::Tshirt_C_Realization::create_formulation(), realization::Tshirt_Realization::create_formulation(), realization::Bmi_Multi_Formulation::create_multi_formulation(), realization::Bmi_Module_Formulation< M >::inner_create_formulation(), and realization::Formulation::interpret_parameters().
write_output()
void HY_CatchmentArea::write_output (std::string out) inline inherited
References HY_CatchmentArea::output.
Friends And Related Function Documentation
::Bmi_C_Formulation_Test
template<class M > friend class ::Bmi_C_Formulation_Test friend
::Bmi_Formulation_Test
template<class M > friend class ::Bmi_Formulation_Test friend
Bmi_Multi_Formulation
template<class M > friend class Bmi_Multi_Formulation friend
Member Data Documentation
allow_model_exceed_end_time
template<class M > bool realization::Bmi_Module_Formulation< M >::allow_model_exceed_end_time = false private
Whether model Update calls are allowed and handled in some way by the backing model for time steps after the model's end_time.
Referenced by realization::Bmi_Module_Formulation< M >::get_allow_model_exceed_end_time(), and realization::Bmi_Module_Formulation< M >::set_allow_model_exceed_end_time().
available_forcings
template<class M > std::vector<std::string> realization::Bmi_Module_Formulation< M >::available_forcings private
The set of available "forcings" (output variables, plus their mapped aliases) that the model can provide.
Referenced by realization::Bmi_Module_Formulation< M >::get_available_forcing_outputs().
bmi_init_config
template<class M > std::string realization::Bmi_Module_Formulation< M >::bmi_init_config private
Referenced by realization::Bmi_Module_Formulation< M >::get_bmi_init_config(), and realization::Bmi_Module_Formulation< M >::set_bmi_init_config().
bmi_main_output_var
std::string realization::Bmi_Formulation::bmi_main_output_var private inherited
bmi_model
template<class M > std::shared_ptr<M> realization::Bmi_Module_Formulation< M >::bmi_model private
Referenced by realization::Bmi_Module_Formulation< M >::get_bmi_model(), and realization::Bmi_Module_Formulation< M >::set_bmi_model().
bmi_model_start_time_forcing_offset_s
template<class M > time_t realization::Bmi_Module_Formulation< M >::bmi_model_start_time_forcing_offset_s private
The offset, converted to seconds, from the model's start time to the start time of the initial forcing time step.
Referenced by realization::Bmi_Module_Formulation< M >::get_bmi_model_start_time_forcing_offset_s(), and realization::Bmi_Module_Formulation< M >::set_bmi_model_start_time_forcing_offset_s().
bmi_model_time_step_fixed
template<class M > bool realization::Bmi_Module_Formulation< M >::bmi_model_time_step_fixed = true private
Whether backing model has fixed time step size.
Referenced by realization::Bmi_Module_Formulation< M >::is_bmi_model_time_step_fixed(), and realization::Bmi_Module_Formulation< M >::set_bmi_model_time_step_fixed().
bmi_using_forcing_file
template<class M > bool realization::Bmi_Module_Formulation< M >::bmi_using_forcing_file private
Whether the backing model uses/reads the forcing file directly for getting input data.
Referenced by realization::Bmi_Module_Formulation< M >::is_bmi_using_forcing_file(), and realization::Bmi_Module_Formulation< M >::set_bmi_using_forcing_file().
bmi_var_names_map
template<class M > std::map<std::string, std::string> realization::Bmi_Module_Formulation< M >::bmi_var_names_map private
A configured mapping of BMI model variable names to standard names for use inside the framework.
Referenced by realization::Bmi_Module_Formulation< M >::get_available_forcing_outputs(), realization::Bmi_Module_Formulation< M >::get_config_mapped_variable_name(), realization::Bmi_Module_Formulation< M >::get_value(), and realization::Bmi_Module_Formulation< M >::inner_create_formulation().
bounds
polygon_t HY_CatchmentArea::bounds protected inherited
et_params
std::shared_ptr<pdm03_struct> realization::Et_Accountable::et_params private inherited
Referenced by realization::Bmi_Module_Formulation< M >::calc_et(), realization::Et_Accountable::get_et_params(), realization::Et_Accountable::get_et_params_ptr(), realization::Et_Accountable::is_et_params_set(), and realization::Et_Accountable::set_et_params().
forcing
std::unique_ptr<forcing::ForcingProvider> HY_CatchmentRealization::forcing protected inherited
forcing_file_path
template<class M > std::string realization::Bmi_Module_Formulation< M >::forcing_file_path private
Referenced by realization::Bmi_Module_Formulation< M >::get_forcing_file_path(), and realization::Bmi_Module_Formulation< M >::set_forcing_file_path().
id
std::string realization::Formulation::id protected inherited
Referenced by realization::Catchment_Formulation::get_catchment_id(), and realization::Formulation::get_id().
id_number
unsigned long HY_CatchmentRealization::id_number protected inherited
input_forcing_providers
template<class M > std::map<std::string, std::shared_ptr<forcing::ForcingProvider> > realization::Bmi_Module_Formulation< M >::input_forcing_providers protected
Referenced by realization::Bmi_Module_Formulation< M >::inner_create_formulation(), and realization::Bmi_Module_Formulation< M >::set_model_inputs_prior_to_update().
last_model_response_delta
template<class M > time_step_t realization::Bmi_Module_Formulation< M >::last_model_response_delta = 0 protected
The delta of the last model update execution (typically, this is time step size).
last_model_response_start_time
template<class M > time_t realization::Bmi_Module_Formulation< M >::last_model_response_start_time = 0 protected
The epoch time of the model at the beginning of its last update.
legacy_forcing
Forcing realization::Catchment_Formulation::legacy_forcing protected inherited
Referenced by Simple_Lumped_Model_Realization::Simple_Lumped_Model_Realization(), realization::Tshirt_C_Realization::get_response(), and realization::Tshirt_Realization::get_response().
model_initialized
template<class M > bool realization::Bmi_Module_Formulation< M >::model_initialized = false private
Referenced by realization::Bmi_Module_Formulation< M >::inner_create_formulation(), realization::Bmi_Module_Formulation< M >::is_model_initialized(), and realization::Bmi_Module_Formulation< M >::set_model_initialized().
model_type_name
std::string realization::Bmi_Formulation::model_type_name private inherited
OPTIONAL_PARAMETERS
template<class M > std::vector<std::string> realization::Bmi_Module_Formulation< M >::OPTIONAL_PARAMETERS private
Initial value:
= {
                BMI_REALIZATION_CFG_PARAM_OPT__FORCING_FILE,
                BMI_REALIZATION_CFG_PARAM_OPT__VAR_STD_NAMES,
                BMI_REALIZATION_CFG_PARAM_OPT__OUT_VARS,
                BMI_REALIZATION_CFG_PARAM_OPT__OUT_HEADER_FIELDS,
                BMI_REALIZATION_CFG_PARAM_OPT__ALLOW_EXCEED_END,
                BMI_REALIZATION_CFG_PARAM_OPT__FIXED_TIME_STEP,
                BMI_REALIZATION_CFG_PARAM_OPT__LIB_FILE
        }
output
utils::StreamHandler HY_CatchmentArea::output protected inherited
Referenced by realization::Bmi_C_Formulation::construct_model(), HY_CatchmentArea::set_output_stream(), and HY_CatchmentArea::write_output().
output_header_fields
std::vector<std::string> realization::Bmi_Formulation::output_header_fields private inherited
Output header field strings corresponding to the variables output by the realization, as defined in output_variable_names.
output_variable_names
std::vector<std::string> realization::Bmi_Formulation::output_variable_names private inherited
Names of the variables to include in the output from this formulation, which will be some ordered subset of the BMI module output variables accessible to the instance.
realized_catchment
shared_ptr<HY_Catchment> HY_CatchmentRealization::realized_catchment protected inherited
REQUIRED_PARAMETERS
template<class M > std::vector<std::string> realization::Bmi_Module_Formulation< M >::REQUIRED_PARAMETERS private
Initial value:
= {
                BMI_REALIZATION_CFG_PARAM_REQ__INIT_CONFIG,
                BMI_REALIZATION_CFG_PARAM_REQ__MAIN_OUT_VAR,
                BMI_REALIZATION_CFG_PARAM_REQ__MODEL_TYPE,
                BMI_REALIZATION_CFG_PARAM_REQ__USES_FORCINGS
        }
Referenced by realization::Bmi_Module_Formulation< M >::get_required_parameters().
The documentation for this class was generated from the following file:
include/realizations/catchment/Bmi_Module_Formulation.hpp