NGen: realization::Catchment_Formulation Class Reference
realization::Catchment_Formulation Class Reference abstract
#include <Catchment_Formulation.hpp>
Public Types
typedef long time_step_t
Public Member Functions
Catchment_Formulation (std::string id, std::shared_ptr< data_access::GenericDataProvider > forcing, utils::StreamHandler output_stream)
Catchment_Formulation (std::string id)
virtual std::string get_output_header_line (std::string delimiter=DEFAULT_FORMULATION_OUTPUT_DELIMITER) const
Get a header line appropriate for a file made up of entries from this type's implementation of get_output_line_for_timestep.
virtual std::string get_output_line_for_timestep (int timestep, std::string delimiter=DEFAULT_FORMULATION_OUTPUT_DELIMITER)=0
Get a formatted line of output values for the given time step as a delimited string.
virtual double get_response (time_step_t t_index, time_step_t t_delta) override=0
Execute the backing model formulation for the given time step, where it is of the specified size, and return the response output.
const std::vector< std::string > & get_required_parameters () const override=0
void create_formulation (boost::property_tree::ptree &config, geojson::PropertyMap *global=nullptr) override=0
void create_formulation (geojson::PropertyMap properties) override=0
virtual ~Catchment_Formulation ()
void finalize ()
Release resources of the given forcing provider.
virtual std::string get_formulation_type () const =0
std::string get_id () const
void set_output_stream (std::string file_path)
void write_output (std::string out)
Static Public Member Functions
static void config_pattern_substitution (geojson::PropertyMap &properties, const std::string &key, const std::string &pattern, const std::string &replacement)
Perform in-place substitution on the given config property item, if the item and the pattern are present.
Protected Member Functions
std::string get_catchment_id () const override
void set_catchment_id (std::string cat_id) override
geojson::PropertyMap interpret_parameters (boost::property_tree::ptree &config, geojson::PropertyMap *global=nullptr)
void validate_parameters (geojson::PropertyMap options)
Protected Attributes
std::shared_ptr< data_access::GenericDataProvider > forcing
std::string id
polygon_t bounds
utils::StreamHandler output
std::shared_ptr< HY_Catchment > realized_catchment
unsigned long id_number
Private Attributes
std::string cat_id
Member Typedef Documentation
time_step_t
long realization::Formulation::time_step_t inherited
Constructor & Destructor Documentation
Catchment_Formulation() [1/2]
realization::Catchment_Formulation::Catchment_Formulation (std::string id, std::shared_ptr< data_access::GenericDataProvider > forcing, utils::StreamHandler output_stream) inline
References set_catchment_id().
Catchment_Formulation() [2/2]
realization::Catchment_Formulation::Catchment_Formulation (std::string id) inline
References set_catchment_id().
~Catchment_Formulation()
virtual realization::Catchment_Formulation::~Catchment_Formulation () inline virtual
Member Function Documentation
config_pattern_substitution()
static void realization::Catchment_Formulation::config_pattern_substitution (geojson::PropertyMap & properties, const std::string & key, const std::string & pattern, const std::string & replacement) inline static
Perform in-place substitution on the given config property item, if the item and the pattern are present.
Any and all instances of the substring pattern are replaced by replacement, if key maps to a present string-type property value.
Parameters
properties A reference to the properties config object to be altered.
key The key for the configuration property to potentially adjust.
pattern The pattern substring to search for that, when present, should be replaced.
replacement The replacement substring to potentially insert.
References geojson::String.
Referenced by realization::Formulation_Manager::construct_missing_formulation(), and realization::Bmi_Multi_Formulation::init_nested_module().
create_formulation() [1/2]
void realization::Catchment_Formulation::create_formulation (boost::property_tree::ptree & config, geojson::PropertyMap * global = nullptr) override pure virtual
Implements realization::Formulation.
Implemented in realization::Bmi_Module_Formulation, and realization::Bmi_Multi_Formulation.
create_formulation() [2/2]
void realization::Catchment_Formulation::create_formulation (geojson::PropertyMap properties) override pure virtual
Implements realization::Formulation.
Implemented in realization::Bmi_Module_Formulation, and realization::Bmi_Multi_Formulation.
finalize()
void realization::Catchment_Formulation::finalize () inline
Release resources of the given forcing provider.
References forcing.
get_catchment_id()
std::string realization::Catchment_Formulation::get_catchment_id () const inline override protected virtual
Implements HY_CatchmentRealization.
References cat_id.
Referenced by realization::Bmi_Multi_Formulation::create_multi_formulation(), realization::Bmi_Multi_Formulation::get_value(), realization::Bmi_Multi_Formulation::get_values(), realization::Bmi_Multi_Formulation::get_var_value_as_double(), and realization::Bmi_Module_Formulation::set_model_inputs_prior_to_update().
get_formulation_type()
virtual std::string realization::Formulation::get_formulation_type () const pure virtual inherited
Implemented in realization::Bmi_C_Formulation, realization::Bmi_Cpp_Formulation, and realization::Bmi_Multi_Formulation.
Referenced by realization::Bmi_Module_Formulation::get_response(), realization::Bmi_Module_Formulation::get_value(), realization::Bmi_Module_Formulation::get_values(), and realization::Formulation::validate_parameters().
get_id()
std::string realization::Formulation::get_id () const inline inherited
References realization::Formulation::id.
get_output_header_line()
virtual std::string realization::Catchment_Formulation::get_output_header_line (std::string delimiter = DEFAULT_FORMULATION_OUTPUT_DELIMITER) const inline virtual
Get a header line appropriate for a file made up of entries from this type's implementation of get_output_line_for_timestep.
Note that like the output generating function, this line does not include anything for time step.
A default implementation is provided for inheritors of this type, which includes only "Total Discharge."
Returns
An appropriate header line for this type.
Reimplemented in realization::Bmi_Formulation.
Referenced by ngen::DomainLayer::DomainLayer().
get_output_line_for_timestep()
virtual std::string realization::Catchment_Formulation::get_output_line_for_timestep (int timestep, std::string delimiter = DEFAULT_FORMULATION_OUTPUT_DELIMITER) pure virtual
Get a formatted line of output values for the given time step as a delimited string.
This method is useful for preparing calculated data in a representation useful for output files, such as CSV files.
The resulting string will contain calculated values for applicable output variables for the particular formulation, as determined for the given time step. However, the string will not contain any representation of the time step itself.
An empty string is returned if the time step value is not in the range of valid time steps for which there are calculated values for all variables.
Parameters
timestep The time step for which data is desired.
delimiter The value delimiter for the string.
Returns
A delimited string with all the output variable values for the given time step.
Implemented in realization::Bmi_Module_Formulation, and realization::Bmi_Multi_Formulation.
Referenced by ngen::DomainLayer::update_models().
get_required_parameters()
const std::vector< std::string > & realization::Catchment_Formulation::get_required_parameters () const override pure virtual
Implements realization::Formulation.
Implemented in realization::Bmi_Formulation, and realization::Bmi_Module_Formulation.
get_response()
virtual double realization::Catchment_Formulation::get_response (time_step_t t_index, time_step_t t_delta) override pure virtual
Execute the backing model formulation for the given time step, where it is of the specified size, and return the response output.
Any inputs and additional parameters must be made available as instance members.
Types should clearly document the details of their particular response output.
Parameters
t_index The index of the time step for which to run model calculations.
t_delta The duration, in seconds, of the time step for which to run model calculations.
Returns
The response output of the model for this time step.
Implements HY_CatchmentRealization.
Implemented in realization::Bmi_Module_Formulation, and realization::Bmi_Multi_Formulation.
Referenced by ngen::DomainLayer::update_models().
interpret_parameters()
geojson::PropertyMap realization::Formulation::interpret_parameters (boost::property_tree::ptree & config, geojson::PropertyMap * global = nullptr) inline protected inherited
References realization::Formulation::validate_parameters().
Referenced by realization::Bmi_Module_Formulation::create_formulation(), and realization::Bmi_Multi_Formulation::create_formulation().
set_catchment_id()
void realization::Catchment_Formulation::set_catchment_id (std::string cat_id) inline override protected virtual
Implements HY_CatchmentRealization.
References cat_id.
Referenced by Catchment_Formulation(), and Catchment_Formulation().
set_output_stream()
void HY_CatchmentArea::set_output_stream (std::string file_path) inline inherited
References HY_CatchmentArea::output.
validate_parameters()
void realization::Formulation::validate_parameters (geojson::PropertyMap options) inline protected inherited
References realization::Formulation::get_formulation_type(), and realization::Formulation::get_required_parameters().
Referenced by realization::Bmi_Multi_Formulation::create_multi_formulation(), realization::Bmi_Module_Formulation::inner_create_formulation(), and realization::Formulation::interpret_parameters().
write_output()
void HY_CatchmentArea::write_output (std::string out) inline inherited
References HY_CatchmentArea::output.
Referenced by ngen::DomainLayer::DomainLayer(), and ngen::DomainLayer::update_models().
Member Data Documentation
bounds
polygon_t HY_CatchmentArea::bounds protected inherited
cat_id
std::string realization::Catchment_Formulation::cat_id private
Referenced by get_catchment_id(), and set_catchment_id().
forcing
std::shared_ptr<data_access::GenericDataProvider> realization::Catchment_Formulation::forcing protected
Referenced by realization::Bmi_Multi_Formulation::create_multi_formulation(), realization::Bmi_Module_Formulation::determine_model_time_offset(), finalize(), realization::Bmi_Multi_Formulation::get_variable_time_begin(), realization::Bmi_Multi_Formulation::get_variable_time_end(), and realization::Bmi_Module_Formulation::set_model_inputs_prior_to_update().
id
std::string realization::Formulation::id protected inherited
Referenced by realization::Formulation::get_id().
id_number
unsigned long HY_CatchmentRealization::id_number protected inherited
output
utils::StreamHandler HY_CatchmentArea::output protected inherited
Referenced by realization::Bmi_Multi_Formulation::init_nested_module(), HY_CatchmentArea::set_output_stream(), and HY_CatchmentArea::write_output().
realized_catchment
std::shared_ptr<HY_Catchment> HY_CatchmentRealization::realized_catchment protected inherited
The documentation for this class was generated from the following file:
include/realizations/catchment/Catchment_Formulation.hpp