NGen: geopackage::sqlite Class Reference
geopackage::sqlite Class Reference
Wrapper around a SQLite3 database.
#include <NGen_SQLite.hpp>
Public Member Functions
sqlite ()=delete
sqlite (const std::string &path)
Construct a new sqlite object from a path to database.
sqlite (sqlite &db)=delete
sqlite & operator= (sqlite &db)=delete
sqlite (sqlite &&db)=default
Take ownership of a sqlite3 database.
sqlite & operator= (sqlite &&db)=default
Move assignment operator.
sqlite3 * connection () const noexcept
Return the originating sqlite3 database pointer.
bool has_table (const std::string &table) noexcept
Check if SQLite database contains a given table.
sqlite_iter query (const std::string &statement)
Query the SQLite Database and get the result.
sqlite_iter query (const std::string &statement, const std::vector< std::string > &binds)
Query the SQLite Database with multiple boundable text parameters.
template<typename... T>
sqlite_iter query (const std::string &statement, T const &... params)
Query the SQLite Database with a bound statement and get the result.
Private Types
using sqlite_t = std::unique_ptr< sqlite3, sqlite_deleter >
Smart pointer (unique) type for sqlite3 database.
Private Attributes
sqlite_t conn = nullptr
Detailed Description
Wrapper around a SQLite3 database.
Member Typedef Documentation
sqlite_t
using geopackage::sqlite::sqlite_t = std::unique_ptr<sqlite3, sqlite_deleter> private
Smart pointer (unique) type for sqlite3 database.
Constructor & Destructor Documentation
sqlite() [1/4]
geopackage::sqlite::sqlite () delete
sqlite() [2/4]
sqlite::sqlite (const std::string & path)
Construct a new sqlite object from a path to database.
Parameters
path File path to sqlite3 database
References conn.
sqlite() [3/4]
geopackage::sqlite::sqlite (sqlite & db) delete
sqlite() [4/4]
geopackage::sqlite::sqlite (sqlite && db) default
Take ownership of a sqlite3 database.
Parameters
db sqlite3 database object
Member Function Documentation
connection()
sqlite3 * sqlite::connection () const noexcept
Return the originating sqlite3 database pointer.
Returns
sqlite3*
References conn.
Referenced by query().
has_table()
bool sqlite::has_table (const std::string & table) noexcept
Check if SQLite database contains a given table.
Parameters
table name of table
Returns
true if table does exist
false if table does not exist
operator=() [1/2]
sqlite & geopackage::sqlite::operator= (sqlite && db) default
Move assignment operator.
Parameters
db sqlite3 database object
Returns
sqlite& reference to sqlite3 database
operator=() [2/2]
sqlite & geopackage::sqlite::operator= (sqlite & db) delete
query() [1/3]
sqlite_iter sqlite::query (const std::string & statement)
Query the SQLite Database and get the result.
Parameters
statement String query
Returns
sqlite_iter SQLite row iterator
References connection().
query() [2/3]
sqlite_iter sqlite::query (const std::string & statement, const std::vector< std::string > & binds)
Query the SQLite Database with multiple boundable text parameters.
Parameters
statement String query with parameters
binds text parameters to bind to statement
Returns
sqlite_iter SQLite row iterator
References connection().
query() [3/3]
template<typename... T> sqlite_iter sqlite::query (const std::string & statement, T const &... params) inline
Query the SQLite Database with a bound statement and get the result.
Parameters
statement String query with parameters
params parameters to bind to statement
Returns
sqlite_iter SQLite row iterator
References connection().
Member Data Documentation
conn
sqlite_t geopackage::sqlite::conn = nullptr private
Referenced by sqlite(), and connection().
The documentation for this class was generated from the following files:
include/geopackage/NGen_SQLite.hpp
src/geopackage/sqlite/database.cpp