NGen: models::bmi::AbstractCLibBmiAdapter< C > Class Template Reference
models::bmi::AbstractCLibBmiAdapter< C > Class Template Reference abstract
#include <AbstractCLibBmiAdapter.hpp>
Public Member Functions
AbstractCLibBmiAdapter (const string &type_name, std::string library_file_path, std::string bmi_init_config, std::string forcing_file_path, bool allow_exceed_end, bool has_fixed_time_step, std::string registration_func, utils::StreamHandler output)
Main public constructor.
AbstractCLibBmiAdapter (AbstractCLibBmiAdapter &&adapter) noexcept
virtual ~AbstractCLibBmiAdapter ()
Class destructor.
void Finalize () override
Perform tear-down task for this object and its backing model.
void acquire_time_conversion_factor (double &time_convert_factor)
Determine backing model's time units and set the reference parameter to an appropriate conversion factor.
double convert_model_time_to_seconds (const double &model_time_val)
Convert model time value to value in seconds.
double convert_seconds_to_model_time (const double &seconds_val)
Convert a given number of seconds to equivalent in model time units.
virtual const std::string get_analogous_cxx_type (const std::string &external_type_name, const size_t item_size)=0
Get the name string for the C++ type analogous to the described type in the backing model.
void Initialize ()
Initialize the wrapped BMI model functionality using the value from the bmi_init_config member variable and the API's Initialize function.
void Initialize (string config_file) override
Initialize the wrapped BMI model object using the given config file and the object's Initialize function.
virtual void Initialize (std::string config_file)=0
bool isInitialized ()
Get whether this instance has been initialized properly.
std::string get_model_name ()
Get the model name.
virtual void Update ()=0
virtual void UpdateUntil (double time)=0
virtual std::string GetComponentName ()=0
virtual int GetInputItemCount ()=0
virtual int GetOutputItemCount ()=0
virtual std::vector< std::string > GetInputVarNames ()=0
virtual std::vector< std::string > GetOutputVarNames ()=0
virtual int GetVarGrid (std::string name)=0
virtual std::string GetVarType (std::string name)=0
virtual std::string GetVarUnits (std::string name)=0
virtual int GetVarItemsize (std::string name)=0
virtual int GetVarNbytes (std::string name)=0
virtual std::string GetVarLocation (std::string name)=0
virtual double GetCurrentTime ()=0
virtual double GetStartTime ()=0
virtual double GetEndTime ()=0
virtual std::string GetTimeUnits ()=0
virtual double GetTimeStep ()=0
virtual void GetValue (std::string name, void *dest)=0
virtual void * GetValuePtr (std::string name)=0
virtual void GetValueAtIndices (std::string name, void *dest, int *inds, int count)=0
virtual void SetValue (std::string name, void *src)=0
virtual void SetValueAtIndices (std::string name, int *inds, int count, void *src)=0
virtual int GetGridRank (const int grid)=0
virtual int GetGridSize (const int grid)=0
virtual std::string GetGridType (const int grid)=0
virtual void GetGridShape (const int grid, int *shape)=0
virtual void GetGridSpacing (const int grid, double *spacing)=0
virtual void GetGridOrigin (const int grid, double *origin)=0
virtual void GetGridX (const int grid, double *x)=0
virtual void GetGridY (const int grid, double *y)=0
virtual void GetGridZ (const int grid, double *z)=0
virtual int GetGridNodeCount (const int grid)=0
virtual int GetGridEdgeCount (const int grid)=0
virtual int GetGridFaceCount (const int grid)=0
virtual void GetGridEdgeNodes (const int grid, int *edge_nodes)=0
virtual void GetGridFaceEdges (const int grid, int *face_edges)=0
virtual void GetGridFaceNodes (const int grid, int *face_nodes)=0
virtual void GetGridNodesPerFace (const int grid, int *nodes_per_face)=0
Protected Member Functions
void dynamic_library_load ()
Dynamically load and obtain this instance's handle to the shared library.
void * dynamic_load_symbol (const std::string &symbol_name, bool is_null_valid)
Load and return the address of the given symbol from the loaded dynamic model shared library.
void * dynamic_load_symbol (const std::string &symbol_name)
Convenience for.
const std::string & get_bmi_registration_function ()
const void * get_dyn_lib_handle ()
virtual void construct_and_init_backing_model ()=0
Construct the backing BMI model object, then call its BMI-native Initialize() function.
Protected Attributes
bool allow_model_exceed_end_time
Whether model Update calls are allowed and handled in some way by the backing model.
string bmi_init_config
Path (as a string) to the BMI config file for initializing the backing model (empty if none).
shared_ptr< C > bmi_model
Pointer to backing BMI model instance.
bool bmi_model_has_fixed_time_step
Whether this particular model has a time step size that cannot be changed internally or externally.
double bmi_model_time_convert_factor
Conversion factor for converting values for model time in model's unit type to equivalent in seconds.
shared_ptr< double > bmi_model_time_step_size
Pointer to stored time step size value of backing model, if it is fixed and has been retrieved.
bool bmi_model_uses_forcing_file
Whether this particular model implementation directly reads input data from the forcing file.
string forcing_file_path
string init_exception_msg
Message from an exception (if encountered) on the first attempt to initialize the backing model.
shared_ptr< vector< string > > input_var_names
Pointer to collection of input variable names for backing model, used by GetInputVarNames().
bool model_initialized
Whether the backing model has been initialized yet, which is always initially false.
string model_name
utils::StreamHandler output
shared_ptr< vector< string > > output_var_names
Pointer to collection of output variable names for backing model, used by GetOutputVarNames().
Private Member Functions
void finalizeForLibAbstraction ()
A non-virtual equivalent for the virtual.
Private Attributes
std::string bmi_lib_file
Path to the BMI shared library file, for dynamic linking.
const std::string bmi_registration_function
Name of the function that registers BMI struct's function pointers to the right module functions.
void * dyn_lib_handle = nullptr
Handle for dynamically loaded library file.
Constructor & Destructor Documentation
AbstractCLibBmiAdapter() [1/2]
template<class C > models::bmi::AbstractCLibBmiAdapter< C >::AbstractCLibBmiAdapter (const string & type_name, std::string library_file_path, std::string bmi_init_config, std::string forcing_file_path, bool allow_exceed_end, bool has_fixed_time_step, std::string registration_func, utils::StreamHandler output) inline
Main public constructor.
Parameters
type_name The name of the backing BMI module/model type.
library_file_path The string path to the shared library file for external module.
bmi_init_config The string path to the BMI initialization config file for the module.
forcing_file_path The string path for the forcing file the module should use, empty if it does not use one directly.
allow_exceed_end Whether the backing model is allowed to execute beyond its advertised end_time.
has_fixed_time_step Whether the model has a fixed time step size.
registration_func The name for the
See also
bmi_registration_function.
Parameters
output The output stream handler.
AbstractCLibBmiAdapter() [2/2]
template<class C > models::bmi::AbstractCLibBmiAdapter< C >::AbstractCLibBmiAdapter (AbstractCLibBmiAdapter< C > && adapter) inline noexcept
~AbstractCLibBmiAdapter()
template<class C > virtual models::bmi::AbstractCLibBmiAdapter< C >::~AbstractCLibBmiAdapter () inline virtual
Class destructor.
Note that this performs the logic in the Finalize() function for cleaning up this object and its backing BMI model.
References models::bmi::AbstractCLibBmiAdapter< C >::finalizeForLibAbstraction().
Member Function Documentation
acquire_time_conversion_factor()
void models::bmi::Bmi_Adapter< C >::acquire_time_conversion_factor (double & time_convert_factor) inline inherited
Determine backing model's time units and set the reference parameter to an appropriate conversion factor.
A backing BMI model may use arbitrary units for time, but it will expose what those units are via the BMI GetTimeUnits function. This function retrieves (and interprets) its model's units and sets the given reference parameter to an appropriate factor for converting its internal time values to equivalent representations within the model, and vice versa.
Parameters
time_convert_factor A reference to set to the determined conversion factor.
construct_and_init_backing_model()
virtual void models::bmi::Bmi_Adapter< C >::construct_and_init_backing_model () protected pure virtual inherited
Construct the backing BMI model object, then call its BMI-native Initialize() function.
Implementations should return immediately without taking any further action if model_initialized is already true.
The call to the BMI native Initialize(string) should pass the value stored in bmi_init_config.
convert_model_time_to_seconds()
double models::bmi::Bmi_Adapter< C >::convert_model_time_to_seconds (const double & model_time_val) inline inherited
Convert model time value to value in seconds.
Performs necessary lookup and conversion of some given model time value - as from GetCurrentTime() or GetStartTime() - and returns the equivalent value when represented in seconds.
Parameters
model_time_val Arbitrary model time value in units provided by GetTimeUnits()
Returns
Equivalent model time value to value in seconds.
convert_seconds_to_model_time()
double models::bmi::Bmi_Adapter< C >::convert_seconds_to_model_time (const double & seconds_val) inline inherited
Convert a given number of seconds to equivalent in model time units.
Parameters
seconds_val
Returns
dynamic_library_load()
template<class C > void models::bmi::AbstractCLibBmiAdapter< C >::dynamic_library_load () inline protected
Dynamically load and obtain this instance's handle to the shared library.
References models::bmi::AbstractCLibBmiAdapter< C >::bmi_lib_file, models::bmi::AbstractCLibBmiAdapter< C >::bmi_registration_function, models::bmi::AbstractCLibBmiAdapter< C >::dyn_lib_handle, utils::FileChecker::file_is_readable(), models::bmi::Bmi_Adapter< C >::init_exception_msg, models::bmi::Bmi_Adapter< C >::model_name, models::bmi::Bmi_Adapter< C >::output, and utils::StreamHandler::put().
dynamic_load_symbol() [1/2]
template<class C > void * models::bmi::AbstractCLibBmiAdapter< C >::dynamic_load_symbol (const std::string & symbol_name) inline protected
Convenience for.
See also
dynamic_load_symbol(std::string, bool) where the symbol address must be found.
This serves as a convenience overload for the function of the same name, in cases when a sought symbol must be found and the return of a null address is not valid.
Parameters
symbol_name The name of the symbol to load.
Returns
A void pointer to the address of the desired symbol in memory.
Exceptions
``std::runtime_error`` If there is not a valid handle already to the shared library.
``::external::ExternalIntegrationException`` If symbol could not be found for the shared library.
See also
dynamic_load_symbol(std::string, bool)
References models::bmi::AbstractCLibBmiAdapter< C >::dynamic_load_symbol().
dynamic_load_symbol() [2/2]
template<class C > void * models::bmi::AbstractCLibBmiAdapter< C >::dynamic_load_symbol (const std::string & symbol_name, bool is_null_valid) inline protected
Load and return the address of the given symbol from the loaded dynamic model shared library.
The initial primary purpose for this is to obtain a function pointer for accessing the registration function for a dynamically loaded library, as done in
See also
dynamic_library_load. Other function pointers (or pointers to other valid symbols) can also be returned.
It is possible for a symbol pointer to actually be null in some cases. However, this may not be valid in the context in which a call to this function was made. To control whether this is treated as a valid case, and thus whether null should be returned (instead of an exception thrown), there is the is_null_valid parameter. When true, a null symbol will be returned by the function.
Typically, a call to
See also
dynamic_library_load must happen (though not necessarily have completed) before a call to this function to ensure
dyn_lib_handle is set. If it is not set, an exception is thrown.
Parameters
symbol_name The name of the symbol to load.
is_null_valid Whether a null address for the symbol is valid, as opposed to implying there was simply a failure finding it.
Returns
A void pointer to the address of the desired symbol in memory.
Exceptions
``std::runtime_error`` If there is not a valid handle already to the shared library.
``::external::ExternalIntegrationException`` If symbol could not be found for the shared library.
References models::bmi::AbstractCLibBmiAdapter< C >::dyn_lib_handle, models::bmi::Bmi_Adapter< C >::init_exception_msg, and models::bmi::Bmi_Adapter< C >::model_name.
Referenced by models::bmi::AbstractCLibBmiAdapter< C >::dynamic_load_symbol().
Finalize()
template<class C > void models::bmi::AbstractCLibBmiAdapter< C >::Finalize () inline override virtual
Perform tear-down task for this object and its backing model.
The function will simply return if either the pointer to the backing model is nullptr (e.g., after use in a move constructor) or if the model has not been initialized. Otherwise, it will execute its internal tear-down logic, including a nested call to finalize() for the backing model.
Note that because of how model initialization state is determined, regardless of whether the call to the model's finalize() function is successful (i.e., according to the function's return code value), the model will subsequently be consider not initialized. This essentially means that if backing model tear-down fails, it cannot be retried.
Exceptions
models::external::State_Exception Thrown if nested model finalize() call is not successful.
Implements bmi::Bmi.
References models::bmi::AbstractCLibBmiAdapter< C >::finalizeForLibAbstraction().
finalizeForLibAbstraction()
template<class C > void models::bmi::AbstractCLibBmiAdapter< C >::finalizeForLibAbstraction () inline private
A non-virtual equivalent for the virtual.
See also
Finalize.
This function should be kept private. If its logic needs to be invoked externally, that should be done via the destructor or via the public interface
See also
Finalize function.
Primarily, this exists to contain the functionality appropriate for
See also
Finalize in a function that is non-virtual, and can therefore be called by a destructor.
References models::bmi::AbstractCLibBmiAdapter< C >::dyn_lib_handle.
Referenced by models::bmi::AbstractCLibBmiAdapter< C >::~AbstractCLibBmiAdapter(), and models::bmi::AbstractCLibBmiAdapter< C >::Finalize().
get_analogous_cxx_type()
virtual const std::string models::bmi::Bmi_Adapter< C >::get_analogous_cxx_type (const std::string & external_type_name, const size_t item_size) pure virtual inherited
Get the name string for the C++ type analogous to the described type in the backing model.
The supported languages for BMI modules support different types than C++ in general, but it is necessary to map "external" types to the appropriate C++ type for certain interactions; e.g., setting a variable value. This function encapsulates the translation specific to the particular language.
Note that the size of an individual item is also required, as this can vary in certain situations depending on the implementation language of a backing model.
Implementations should all throw the same type of exception (currently, std::runtime_error) if/when an unrecognized external type name parameter is provided.
Parameters
external_type_name The string name of some type in backing model's implementation language.
item_size The particular size in bytes for items of the involved analogous types.
Returns
The name string for the C++ type analogous to the described type in the backing model.
Exceptions
std::runtime_error If an unrecognized external type name parameter is provided.
get_bmi_registration_function()
template<class C > const std::string & models::bmi::AbstractCLibBmiAdapter< C >::get_bmi_registration_function () inline protected
References models::bmi::AbstractCLibBmiAdapter< C >::bmi_registration_function.
get_dyn_lib_handle()
template<class C > const void * models::bmi::AbstractCLibBmiAdapter< C >::get_dyn_lib_handle () inline protected
References models::bmi::AbstractCLibBmiAdapter< C >::dyn_lib_handle.
get_model_name()
std::string models::bmi::Bmi_Adapter< C >::get_model_name () inline inherited
Get the model name.
Returns
The name of the model connected to the adapter.
GetComponentName()
virtual std::string bmi::Bmi::GetComponentName () pure virtual inherited
Implemented in models::bmi::Bmi_C_Adapter, and models::bmi::Bmi_Cpp_Adapter.
GetCurrentTime()
virtual double bmi::Bmi::GetCurrentTime () pure virtual inherited
Implemented in models::bmi::Bmi_C_Adapter, and models::bmi::Bmi_Cpp_Adapter.
GetEndTime()
virtual double bmi::Bmi::GetEndTime () pure virtual inherited
Implemented in models::bmi::Bmi_C_Adapter, and models::bmi::Bmi_Cpp_Adapter.
GetGridEdgeCount()
virtual int bmi::Bmi::GetGridEdgeCount (const int grid) pure virtual inherited
Implemented in models::bmi::Bmi_C_Adapter, and models::bmi::Bmi_Cpp_Adapter.
GetGridEdgeNodes()
virtual void bmi::Bmi::GetGridEdgeNodes (const int grid, int * edge_nodes) pure virtual inherited
Implemented in models::bmi::Bmi_C_Adapter, and models::bmi::Bmi_Cpp_Adapter.
GetGridFaceCount()
virtual int bmi::Bmi::GetGridFaceCount (const int grid) pure virtual inherited
Implemented in models::bmi::Bmi_C_Adapter, and models::bmi::Bmi_Cpp_Adapter.
GetGridFaceEdges()
virtual void bmi::Bmi::GetGridFaceEdges (const int grid, int * face_edges) pure virtual inherited
Implemented in models::bmi::Bmi_C_Adapter, and models::bmi::Bmi_Cpp_Adapter.
GetGridFaceNodes()
virtual void bmi::Bmi::GetGridFaceNodes (const int grid, int * face_nodes) pure virtual inherited
Implemented in models::bmi::Bmi_C_Adapter, and models::bmi::Bmi_Cpp_Adapter.
GetGridNodeCount()
virtual int bmi::Bmi::GetGridNodeCount (const int grid) pure virtual inherited
Implemented in models::bmi::Bmi_C_Adapter, and models::bmi::Bmi_Cpp_Adapter.
GetGridNodesPerFace()
virtual void bmi::Bmi::GetGridNodesPerFace (const int grid, int * nodes_per_face) pure virtual inherited
Implemented in models::bmi::Bmi_C_Adapter, and models::bmi::Bmi_Cpp_Adapter.
GetGridOrigin()
virtual void bmi::Bmi::GetGridOrigin (const int grid, double * origin) pure virtual inherited
Implemented in models::bmi::Bmi_C_Adapter, and models::bmi::Bmi_Cpp_Adapter.
GetGridRank()
virtual int bmi::Bmi::GetGridRank (const int grid) pure virtual inherited
Implemented in models::bmi::Bmi_C_Adapter, and models::bmi::Bmi_Cpp_Adapter.
GetGridShape()
virtual void bmi::Bmi::GetGridShape (const int grid, int * shape) pure virtual inherited
Implemented in models::bmi::Bmi_C_Adapter, and models::bmi::Bmi_Cpp_Adapter.
GetGridSize()
virtual int bmi::Bmi::GetGridSize (const int grid) pure virtual inherited
Implemented in models::bmi::Bmi_C_Adapter, and models::bmi::Bmi_Cpp_Adapter.
GetGridSpacing()
virtual void bmi::Bmi::GetGridSpacing (const int grid, double * spacing) pure virtual inherited
Implemented in models::bmi::Bmi_C_Adapter, and models::bmi::Bmi_Cpp_Adapter.
GetGridType()
virtual std::string bmi::Bmi::GetGridType (const int grid) pure virtual inherited
Implemented in models::bmi::Bmi_C_Adapter, and models::bmi::Bmi_Cpp_Adapter.
GetGridX()
virtual void bmi::Bmi::GetGridX (const int grid, double * x) pure virtual inherited
Implemented in models::bmi::Bmi_C_Adapter, and models::bmi::Bmi_Cpp_Adapter.
GetGridY()
virtual void bmi::Bmi::GetGridY (const int grid, double * y) pure virtual inherited
Implemented in models::bmi::Bmi_C_Adapter, and models::bmi::Bmi_Cpp_Adapter.
GetGridZ()
virtual void bmi::Bmi::GetGridZ (const int grid, double * z) pure virtual inherited
Implemented in models::bmi::Bmi_C_Adapter, and models::bmi::Bmi_Cpp_Adapter.
GetInputItemCount()
virtual int bmi::Bmi::GetInputItemCount () pure virtual inherited
Implemented in models::bmi::Bmi_C_Adapter, and models::bmi::Bmi_Cpp_Adapter.
GetInputVarNames()
virtual std::vector< std::string > bmi::Bmi::GetInputVarNames () pure virtual inherited
Implemented in models::bmi::Bmi_C_Adapter, and models::bmi::Bmi_Cpp_Adapter.
GetOutputItemCount()
virtual int bmi::Bmi::GetOutputItemCount () pure virtual inherited
Implemented in models::bmi::Bmi_C_Adapter, and models::bmi::Bmi_Cpp_Adapter.
GetOutputVarNames()
virtual std::vector< std::string > bmi::Bmi::GetOutputVarNames () pure virtual inherited
Implemented in models::bmi::Bmi_C_Adapter, and models::bmi::Bmi_Cpp_Adapter.
GetStartTime()
virtual double bmi::Bmi::GetStartTime () pure virtual inherited
Implemented in models::bmi::Bmi_C_Adapter, and models::bmi::Bmi_Cpp_Adapter.
GetTimeStep()
virtual double bmi::Bmi::GetTimeStep () pure virtual inherited
Implemented in models::bmi::Bmi_C_Adapter, and models::bmi::Bmi_Cpp_Adapter.
GetTimeUnits()
virtual std::string bmi::Bmi::GetTimeUnits () pure virtual inherited
Implemented in models::bmi::Bmi_C_Adapter, and models::bmi::Bmi_Cpp_Adapter.
Referenced by models::bmi::Bmi_Adapter< T >::acquire_time_conversion_factor().
GetValue()
virtual void bmi::Bmi::GetValue (std::string name, void * dest) pure virtual inherited
Implemented in models::bmi::Bmi_C_Adapter, and models::bmi::Bmi_Cpp_Adapter.
Referenced by models::bmi::GetValue().
GetValueAtIndices()
virtual void bmi::Bmi::GetValueAtIndices (std::string name, void * dest, int * inds, int count) pure virtual inherited
Implemented in models::bmi::Bmi_C_Adapter, and models::bmi::Bmi_Cpp_Adapter.
GetValuePtr()
virtual void * bmi::Bmi::GetValuePtr (std::string name) pure virtual inherited
Implemented in models::bmi::Bmi_C_Adapter, and models::bmi::Bmi_Cpp_Adapter.
GetVarGrid()
virtual int bmi::Bmi::GetVarGrid (std::string name) pure virtual inherited
Implemented in models::bmi::Bmi_C_Adapter, and models::bmi::Bmi_Cpp_Adapter.
GetVarItemsize()
virtual int bmi::Bmi::GetVarItemsize (std::string name) pure virtual inherited
Implemented in models::bmi::Bmi_C_Adapter, and models::bmi::Bmi_Cpp_Adapter.
Referenced by models::bmi::GetValue().
GetVarLocation()
virtual std::string bmi::Bmi::GetVarLocation (std::string name) pure virtual inherited
Implemented in models::bmi::Bmi_C_Adapter, and models::bmi::Bmi_Cpp_Adapter.
GetVarNbytes()
virtual int bmi::Bmi::GetVarNbytes (std::string name) pure virtual inherited
Implemented in models::bmi::Bmi_C_Adapter, and models::bmi::Bmi_Cpp_Adapter.
Referenced by models::bmi::GetValue().
GetVarType()
virtual std::string bmi::Bmi::GetVarType (std::string name) pure virtual inherited
Implemented in models::bmi::Bmi_C_Adapter, and models::bmi::Bmi_Cpp_Adapter.
Referenced by models::bmi::GetValue().
GetVarUnits()
virtual std::string bmi::Bmi::GetVarUnits (std::string name) pure virtual inherited
Implemented in models::bmi::Bmi_C_Adapter, and models::bmi::Bmi_Cpp_Adapter.
Initialize() [1/3]
void models::bmi::Bmi_Adapter< C >::Initialize () inline inherited
Initialize the wrapped BMI model functionality using the value from the bmi_init_config member variable and the API's Initialize function.
If no attempt to initialize the model has yet been made (i.e., model_initialized is false when this function is called), then an initialization is attempted for the model. This is handled by a nested call to the construct_and_init_backing_model function. If initialization fails, an exception will be raised, with it's message saved as part of this object's state. However, regardless of the success of initialization, model_initialized is set to true after the attempt.
Additionally, if a successful model initialization is performed, bmi_model_time_convert_factor is immediately thereafter set by passing it by reference in a call to acquire_time_conversion_factor.
If an attempt to initialize the model has already been made (i.e., model_initialized is true), this function will either simply return or will throw a runtime_error, with its message including the message of the exception from the earlier attempt.
Exceptions
runtime_error If called again after earlier call that resulted in an exception, or if BMI config file could not be read.
models::external::State_Exception If initialize() in nested model does not return successful.
Initialize() [2/3]
virtual void bmi::Bmi::Initialize (std::string config_file) pure virtual inherited
Implemented in models::bmi::Bmi_Adapter< T >.
Initialize() [3/3]
void models::bmi::Bmi_Adapter< C >::Initialize (string config_file) inline override inherited
Initialize the wrapped BMI model object using the given config file and the object's Initialize function.
If the given file is not the same as what is in bmi_init_config` and the model object has not already been initialized, this function will produce a warning message about the difference, then subsequently update bmi_init_config` to the given file. It will then proceed with initialization.
However, if the given file is not the same as what is in bmi_init_config`, but the model has already been initialized, a runtime_error exception is thrown.
This otherwise operates using the logic of Initialize().
Parameters
config_file
See also
Initialize()
Exceptions
models::external::State_Exception If initialize() in nested model is not successful.
runtime_error If already initialized but using a different file than the passed argument.
isInitialized()
bool models::bmi::Bmi_Adapter< C >::isInitialized () inline inherited
Get whether this instance has been initialized properly.
Returns
Whether this instance has been initialized properly.
SetValue()
virtual void bmi::Bmi::SetValue (std::string name, void * src) pure virtual inherited
Implemented in models::bmi::Bmi_C_Adapter, and models::bmi::Bmi_Cpp_Adapter.
SetValueAtIndices()
virtual void bmi::Bmi::SetValueAtIndices (std::string name, int * inds, int count, void * src) pure virtual inherited
Implemented in models::bmi::Bmi_C_Adapter, and models::bmi::Bmi_Cpp_Adapter.
Update()
virtual void bmi::Bmi::Update () pure virtual inherited
Implemented in models::bmi::Bmi_C_Adapter, and models::bmi::Bmi_Cpp_Adapter.
UpdateUntil()
virtual void bmi::Bmi::UpdateUntil (double time) pure virtual inherited
Implemented in models::bmi::Bmi_C_Adapter, and models::bmi::Bmi_Cpp_Adapter.
Member Data Documentation
allow_model_exceed_end_time
bool models::bmi::Bmi_Adapter< C >::allow_model_exceed_end_time protected inherited
Whether model Update calls are allowed and handled in some way by the backing model.
bmi_init_config
string models::bmi::Bmi_Adapter< C >::bmi_init_config protected inherited
Path (as a string) to the BMI config file for initializing the backing model (empty if none).
bmi_lib_file
template<class C > std::string models::bmi::AbstractCLibBmiAdapter< C >::bmi_lib_file private
Path to the BMI shared library file, for dynamic linking.
Referenced by models::bmi::AbstractCLibBmiAdapter< C >::dynamic_library_load().
bmi_model
shared_ptr<C > models::bmi::Bmi_Adapter< C >::bmi_model protected inherited
Pointer to backing BMI model instance.
bmi_model_has_fixed_time_step
bool models::bmi::Bmi_Adapter< C >::bmi_model_has_fixed_time_step protected inherited
Whether this particular model has a time step size that cannot be changed internally or externally.
bmi_model_time_convert_factor
double models::bmi::Bmi_Adapter< C >::bmi_model_time_convert_factor protected inherited
Conversion factor for converting values for model time in model's unit type to equivalent in seconds.
bmi_model_time_step_size
shared_ptr<double> models::bmi::Bmi_Adapter< C >::bmi_model_time_step_size protected inherited
Pointer to stored time step size value of backing model, if it is fixed and has been retrieved.
bmi_model_uses_forcing_file
bool models::bmi::Bmi_Adapter< C >::bmi_model_uses_forcing_file protected inherited
Whether this particular model implementation directly reads input data from the forcing file.
bmi_registration_function
template<class C > const std::string models::bmi::AbstractCLibBmiAdapter< C >::bmi_registration_function private
Name of the function that registers BMI struct's function pointers to the right module functions.
Referenced by models::bmi::AbstractCLibBmiAdapter< C >::dynamic_library_load(), and models::bmi::AbstractCLibBmiAdapter< C >::get_bmi_registration_function().
dyn_lib_handle
template<class C > void* models::bmi::AbstractCLibBmiAdapter< C >::dyn_lib_handle = nullptr private
Handle for dynamically loaded library file.
Referenced by models::bmi::AbstractCLibBmiAdapter< C >::dynamic_library_load(), models::bmi::AbstractCLibBmiAdapter< C >::dynamic_load_symbol(), models::bmi::AbstractCLibBmiAdapter< C >::finalizeForLibAbstraction(), and models::bmi::AbstractCLibBmiAdapter< C >::get_dyn_lib_handle().
forcing_file_path
string models::bmi::Bmi_Adapter< C >::forcing_file_path protected inherited
init_exception_msg
string models::bmi::Bmi_Adapter< C >::init_exception_msg protected inherited
Message from an exception (if encountered) on the first attempt to initialize the backing model.
input_var_names
shared_ptr<vector<string> > models::bmi::Bmi_Adapter< C >::input_var_names protected inherited
Pointer to collection of input variable names for backing model, used by GetInputVarNames().
model_initialized
bool models::bmi::Bmi_Adapter< C >::model_initialized protected inherited
Whether the backing model has been initialized yet, which is always initially false.
model_name
string models::bmi::Bmi_Adapter< C >::model_name protected inherited
output
utils::StreamHandler models::bmi::Bmi_Adapter< C >::output protected inherited
output_var_names
shared_ptr<vector<string> > models::bmi::Bmi_Adapter< C >::output_var_names protected inherited
Pointer to collection of output variable names for backing model, used by GetOutputVarNames().
The documentation for this class was generated from the following file:
include/realizations/catchment/AbstractCLibBmiAdapter.hpp