NGen: realization::Formulation Class Reference
realization::Formulation Class Reference abstract
#include <Formulation.hpp>
Public Types
typedef long time_step_t
Public Member Functions
Formulation (std::string id)
virtual ~Formulation ()
virtual std::string get_formulation_type ()=0
virtual double get_response (time_step_t t_index, time_step_t d_delta_s)=0
Execute the backing model formulation for the given time step, where it is of the specified size, and return the response output.
virtual void add_time (time_t t, double n)
std::string get_id () const
virtual std::string get_output_header_line (std::string delimiter=DEFAULT_FORMULATION_OUTPUT_DELIMITER)=0
Get a header line appropriate for a file made up of entries from this type's implementation of get_output_line_for_timestep.
virtual std::string get_output_line_for_timestep (int timestep, std::string delimiter=DEFAULT_FORMULATION_OUTPUT_DELIMITER)=0
Get a formatted line of output values for the given time step as a delimited string.
virtual void create_formulation (boost::property_tree::ptree &config, geojson::PropertyMap *global=nullptr)=0
virtual void create_formulation (geojson::PropertyMap properties)=0
Protected Member Functions
virtual const std::vector< std::string > & get_required_parameters ()=0
virtual geojson::PropertyMap interpret_parameters (boost::property_tree::ptree &config, geojson::PropertyMap *global=nullptr)
virtual void validate_parameters (geojson::PropertyMap options)
Protected Attributes
std::string id
Member Typedef Documentation
time_step_t
typedef long realization::Formulation::time_step_t
Constructor & Destructor Documentation
Formulation()
realization::Formulation::Formulation (std::string id) inline
~Formulation()
virtual realization::Formulation::~Formulation () inline virtual
Member Function Documentation
add_time()
virtual void realization::Formulation::add_time (time_t t, double n) inline virtual
create_formulation() [1/2]
virtual void realization::Formulation::create_formulation (boost::property_tree::ptree & config, geojson::PropertyMap * global = nullptr) pure virtual
Implemented in realization::Bmi_Module_Formulation< M >, realization::Bmi_Module_Formulation< models::bmi::Bmi_C_Adapter >, realization::Bmi_Module_Formulation< models::bmi::Bmi_Cpp_Adapter >, realization::Bmi_Multi_Formulation, and realization::Catchment_Formulation.
create_formulation() [2/2]
virtual void realization::Formulation::create_formulation (geojson::PropertyMap properties) pure virtual
Implemented in realization::Bmi_Module_Formulation< M >, realization::Bmi_Module_Formulation< models::bmi::Bmi_C_Adapter >, realization::Bmi_Module_Formulation< models::bmi::Bmi_Cpp_Adapter >, realization::Bmi_Multi_Formulation, and realization::Catchment_Formulation.
get_formulation_type()
virtual std::string realization::Formulation::get_formulation_type () pure virtual
Implemented in realization::Bmi_C_Formulation, realization::Bmi_Cpp_Formulation, and realization::Bmi_Multi_Formulation.
Referenced by realization::Bmi_Module_Formulation< M >::get_value(), realization::Bmi_Module_Formulation< M >::get_values(), and validate_parameters().
get_id()
std::string realization::Formulation::get_id () const inline
References id.
get_output_header_line()
virtual std::string realization::Formulation::get_output_header_line (std::string delimiter = DEFAULT_FORMULATION_OUTPUT_DELIMITER) pure virtual
Get a header line appropriate for a file made up of entries from this type's implementation of get_output_line_for_timestep.
Note that like the output generating function, this line does not include anything for time step.
Returns
An appropriate header line for this type.
Implemented in realization::Bmi_C_Formulation, realization::Bmi_Cpp_Formulation, realization::Bmi_Formulation, and realization::Catchment_Formulation.
get_output_line_for_timestep()
virtual std::string realization::Formulation::get_output_line_for_timestep (int timestep, std::string delimiter = DEFAULT_FORMULATION_OUTPUT_DELIMITER) pure virtual
Get a formatted line of output values for the given time step as a delimited string.
This method is useful for preparing calculated data in a representation useful for output files, such as CSV files.
The resulting string will contain calculated values for applicable output variables for the particular formulation, as determined for the given time step. However, the string will not contain any representation of the time step itself.
An empty string is returned if the time step value is not in the range of valid time steps for which there are calculated values for all variables.
Parameters
timestep The time step for which data is desired.
delimiter The value delimiter for the string.
Returns
A delimited string with all the output variable values for the given time step.
Implemented in realization::Bmi_C_Formulation, realization::Bmi_Cpp_Formulation, and realization::Bmi_Multi_Formulation.
get_required_parameters()
virtual const std::vector< std::string > & realization::Formulation::get_required_parameters () protected pure virtual
Implemented in realization::Bmi_Formulation, realization::Bmi_Module_Formulation< M >, realization::Bmi_Module_Formulation< models::bmi::Bmi_C_Adapter >, realization::Bmi_Module_Formulation< models::bmi::Bmi_Cpp_Adapter >, and realization::Catchment_Formulation.
Referenced by validate_parameters().
get_response()
virtual double realization::Formulation::get_response (time_step_t t_index, time_step_t d_delta_s) pure virtual
Execute the backing model formulation for the given time step, where it is of the specified size, and return the response output.
Any inputs and additional parameters must be made available as instance members.
Types should clearly document the details of their particular response output.
Parameters
t_index The index of the time step for which to run model calculations.
d_delta_s The duration, in seconds, of the time step for which to run model calculations.
Returns
The response output of the model for this time step.
Implemented in realization::Bmi_C_Formulation, realization::Bmi_Cpp_Formulation, realization::Bmi_Multi_Formulation, and realization::Catchment_Formulation.
interpret_parameters()
virtual geojson::PropertyMap realization::Formulation::interpret_parameters (boost::property_tree::ptree & config, geojson::PropertyMap * global = nullptr) inline protected virtual
References validate_parameters().
Referenced by realization::Bmi_Module_Formulation< M >::create_formulation(), and realization::Bmi_Multi_Formulation::create_formulation().
validate_parameters()
virtual void realization::Formulation::validate_parameters (geojson::PropertyMap options) inline protected virtual
References get_formulation_type(), and get_required_parameters().
Referenced by realization::Bmi_Multi_Formulation::create_multi_formulation(), realization::Bmi_Module_Formulation< M >::inner_create_formulation(), and interpret_parameters().
Member Data Documentation
id
std::string realization::Formulation::id protected
Referenced by get_id().
The documentation for this class was generated from the following file:
include/realizations/catchment/Formulation.hpp