NGen: realization::Tshirt_C_Realization Class Reference
realization::Tshirt_C_Realization Class Reference abstract
#include <Tshirt_C_Realization.hpp>
Public Types
typedef long time_step_t
Public Member Functions
Tshirt_C_Realization (forcing_params forcing_config, utils::StreamHandler output_stream, double soil_storage, double groundwater_storage, bool storage_values_are_ratios, std::string catchment_id, giuh::GiuhJsonReader &giuh_json_reader, tshirt::tshirt_params params, const std::vector< double > &nash_storage)
Constructor for initializing when a tshirt::tshirt_params struct is passed for parameters and a giuh::GiuhJsonReader is passed for obtaining GIUH ordinates.
Tshirt_C_Realization (forcing_params forcing_config, utils::StreamHandler output_stream, double soil_storage, double groundwater_storage, bool storage_values_are_ratios, std::string catchment_id, std::vector< double > giuh_ordinates, tshirt::tshirt_params params, const std::vector< double > &nash_storage)
Constructor for initializing when a tshirt::tshirt_params struct is passed for parameters and GIUH ordinates are available directly and passed within a vector.
Tshirt_C_Realization (forcing_params forcing_config, utils::StreamHandler output_stream, double soil_storage, double groundwater_storage, bool storage_values_are_ratios, std::string catchment_id, giuh::GiuhJsonReader &giuh_json_reader, double maxsmc, double wltsmc, double satdk, double satpsi, double slope, double b, double multiplier, double alpha_fc, double Klf, double Kn, int nash_n, double Cgw, double expon, double max_gw_storage, const std::vector< double > &nash_storage)
Constructor for when model parameters are provided individually instead of within encapsulating struct and a giuh::GiuhJsonReader is passed for obtaining GIUH ordinates.
Tshirt_C_Realization (std::string id, shared_ptr< data_access::GenericDataProvider > forcing_provider, utils::StreamHandler output_stream)
Tshirt_C_Realization (std::string id, forcing_params forcing_config, utils::StreamHandler output_stream)
virtual ~Tshirt_C_Realization ()
double calc_et () override
Return 0, as (for now) this type does not otherwise include ET within its calculations.
void create_formulation (boost::property_tree::ptree &config, geojson::PropertyMap *global=nullptr) override
void create_formulation (geojson::PropertyMap properties) override
int run_formulation_for_timestep (double input_flux, time_step_t t_delta_s)
Run model formulation calculations for the next time step using the given input flux value in meters per second.
int run_formulation_for_timesteps (std::vector< double > input_fluxes, std::vector< time_step_t > t_deltas_s)
Run model formulation calculations for a series of time steps using the given collection of input flux values in meters per second.
std::string get_formulation_type () override
double get_response (time_step_t t_index, time_step_t t_delta) override
Execute the backing model formulation for the given time step, where it is of the specified size, and return the total discharge.
double get_latest_flux_base_flow ()
double get_latest_flux_giuh_runoff ()
double get_latest_flux_lateral_flow ()
double get_latest_flux_surface_runoff ()
double get_latest_flux_total_discharge ()
int get_output_item_count ()
Get the number of output data variables made available from the calculations for enumerated time steps.
const std::vector< std::string > & get_output_var_names ()
Get the names of the output data variables that are available from calculations for enumerated time steps.
std::vector< double > get_value (const std::string &name)
Get a copy of the values for the given output variable at all available time steps.
std::string get_output_header_line (std::string delimiter=",") override
Get a header line appropriate for a file made up of entries from this type's implementation of get_output_line_for_timestep.
const std::vector< std::string > & get_output_header_fields ()
Get the values making up the header line from get_output_header_line(), but organized as a vector of strings.
std::string get_output_line_for_timestep (int timestep, std::string delimiter=",") override
Get a delimited string with all the output variable values for the given time step.
virtual void add_time (time_t t, double n)
std::string get_id () const
virtual bool is_et_params_set ()=0
Test whether ET params have been set.
bool is_et_params_set () override
Test whether ET params have been set.
virtual void set_et_params (std::shared_ptr< pdm03_struct > params)=0
Accept a reference for an appropriate object for holding ET parameters for use when executing the model calculations, if maintained by the type.
void set_et_params (std::shared_ptr< pdm03_struct > params) override
Set a reference for an appropriate object for holding ET parameters for use when executing the model calculations.
void set_output_stream (std::string file_path)
void write_output (std::string out)
virtual const pdm03_struct & get_et_params ()
Get a reference to the appropriate object holding ET parameters for use when executing the model calculations.
Static Public Member Functions
static void config_pattern_substitution (geojson::PropertyMap &properties, const std::string &key, const std::string &pattern, const std::string &replacement)
Perform in-place substitution on the given config property item, if the item and the pattern are present.
Protected Member Functions
std::string get_catchment_id () override
void set_catchment_id (std::string cat_id) override
virtual geojson::PropertyMap interpret_parameters (boost::property_tree::ptree &config, geojson::PropertyMap *global=nullptr)
virtual void validate_parameters (geojson::PropertyMap options)
virtual std::shared_ptr< pdm03_struct > get_et_params_ptr ()
Protected Attributes
std::string id
polygon_t bounds
utils::StreamHandler output
shared_ptr< HY_Catchment > realized_catchment
unsigned long id_number
std::shared_ptr< data_access::GenericDataProvider > forcing
Private Member Functions
std::function< double(tshirt_c_result_fluxes)> get_output_var_flux_extraction_func (const std::string &var_name)
const std::vector< std::string > & get_required_parameters () override
void init_ground_water_reservoir (double storage, bool storage_values_are_ratios)
void init_soil_reservoir (double storage, bool storage_values_are_ratios)
void sync_c_storage_params ()
Static Private Member Functions
static double init_reservoir_storage (bool is_ratio, double amount, double max_amount)
Private Attributes
std::string catchment_id
Id of associated catchment.
std::shared_ptr< tshirt::tshirt_params > params
Struct for containing model parameters for Tshirt model, using "internal" framework implementation for such a struct.
NWM_soil_parameters c_soil_params
Struct from C-style Tshirt formulation for holding soil parameter values.
std::vector< double > giuh_cdf_ordinates
Vector of GIUH CDF ordinates.
std::vector< double > giuh_runoff_queue_per_timestep
Vector to serve as runoff queue for GIUH convolution calculations.
std::vector< double > nash_storage
aorc_forcing_data c_aorc_params
std::vector< std::shared_ptr< tshirt_c_result_fluxes > > fluxes
conceptual_reservoir groundwater_conceptual_reservoir
std::vector< std::string > OUTPUT_VARIABLE_NAMES
std::vector< std::string > OUTPUT_HEADER_FIELDS
conceptual_reservoir soil_conceptual_reservoir
std::vector< std::string > REQUIRED_PARAMETERS
std::string cat_id
std::shared_ptr< pdm03_struct > et_params
Member Typedef Documentation
time_step_t
typedef long realization::Tshirt_C_Realization::time_step_t
Constructor & Destructor Documentation
Tshirt_C_Realization() [1/5]
Tshirt_C_Realization::Tshirt_C_Realization (forcing_params forcing_config, utils::StreamHandler output_stream, double soil_storage, double groundwater_storage, bool storage_values_are_ratios, std::string catchment_id, giuh::GiuhJsonReader & giuh_json_reader, tshirt::tshirt_params params, const std::vector< double > & nash_storage)
Constructor for initializing when a tshirt::tshirt_params struct is passed for parameters and a giuh::GiuhJsonReader is passed for obtaining GIUH ordinates.
Parameters
forcing_config
output_stream
soil_storage
groundwater_storage
storage_values_are_ratios Whether the storage values are given as proportional amounts of the max (or, when false, express amounts with units of meters).
catchment_id
giuh_json_reader
params
nash_storage
Tshirt_C_Realization() [2/5]
Tshirt_C_Realization::Tshirt_C_Realization (forcing_params forcing_config, utils::StreamHandler output_stream, double soil_storage, double groundwater_storage, bool storage_values_are_ratios, std::string catchment_id, std::vector< double > giuh_ordinates, tshirt::tshirt_params params, const std::vector< double > & nash_storage)
Constructor for initializing when a tshirt::tshirt_params struct is passed for parameters and GIUH ordinates are available directly and passed within a vector.
Parameters
forcing_config
output_stream
soil_storage
groundwater_storage
storage_values_are_ratios Whether the storage values are given as proportional amounts of the max (or, when false, express amounts with units of meters).
catchment_id
guih_ordinates
params
nash_storage
References fluxes, giuh_cdf_ordinates, giuh_runoff_queue_per_timestep, init_ground_water_reservoir(), init_soil_reservoir(), params, and sync_c_storage_params().
Tshirt_C_Realization() [3/5]
Tshirt_C_Realization::Tshirt_C_Realization (forcing_params forcing_config, utils::StreamHandler output_stream, double soil_storage, double groundwater_storage, bool storage_values_are_ratios, std::string catchment_id, giuh::GiuhJsonReader & giuh_json_reader, double maxsmc, double wltsmc, double satdk, double satpsi, double slope, double b, double multiplier, double alpha_fc, double Klf, double Kn, int nash_n, double Cgw, double expon, double max_gw_storage, const std::vector< double > & nash_storage)
Constructor for when model parameters are provided individually instead of within encapsulating struct and a giuh::GiuhJsonReader is passed for obtaining GIUH ordinates.
Parameters
forcing_config
output_stream
soil_storage
groundwater_storage
storage_values_are_ratios Whether the storage values are given as proportional amounts of the max (or, when false, express amounts with units of meters).
catchment_id
giuh_json_reader
maxsmc
wltsmc
satdk
satpsi
slope
b
multiplier
alpha_fc
Klf
Kn
nash_n
Cgw
expon
max_gw_storage
nash_storage
Tshirt_C_Realization() [4/5]
Tshirt_C_Realization::Tshirt_C_Realization (std::string id, shared_ptr< data_access::GenericDataProvider > forcing_provider, utils::StreamHandler output_stream)
References fluxes.
Tshirt_C_Realization() [5/5]
Tshirt_C_Realization::Tshirt_C_Realization (std::string id, forcing_params forcing_config, utils::StreamHandler output_stream)
References fluxes.
~Tshirt_C_Realization()
Tshirt_C_Realization::~Tshirt_C_Realization () virtual
Member Function Documentation
add_time()
virtual void realization::Formulation::add_time (time_t t, double n) inline virtual inherited
Reimplemented in Simple_Lumped_Model_Realization.
calc_et()
double Tshirt_C_Realization::calc_et () override virtual
Return 0, as (for now) this type does not otherwise include ET within its calculations.
Returns
0
Implements realization::Et_Accountable.
config_pattern_substitution()
static void realization::Catchment_Formulation::config_pattern_substitution (geojson::PropertyMap & properties, const std::string & key, const std::string & pattern, const std::string & replacement) inline static inherited
Perform in-place substitution on the given config property item, if the item and the pattern are present.
Any and all instances of the substring pattern are replaced by replacement, if key maps to a present string-type property value.
Parameters
properties A reference to the properties config object to be altered.
key The key for the configuration property to potentially adjust.
pattern The pattern substring to search for that, when present, should be replaced.
replacement The replacement substring to potentially insert.
References geojson::String.
Referenced by realization::Formulation_Manager::construct_missing_formulation(), and realization::Bmi_Multi_Formulation::init_nested_module().
create_formulation() [1/2]
void Tshirt_C_Realization::create_formulation (boost::property_tree::ptree & config, geojson::PropertyMap * global = nullptr) override virtual
Implements realization::Catchment_Formulation.
References catchment_id, realization::Formulation::get_id(), giuh_cdf_ordinates, giuh_runoff_queue_per_timestep, init_ground_water_reservoir(), init_soil_reservoir(), realization::Formulation::interpret_parameters(), nash_storage, params, and sync_c_storage_params().
create_formulation() [2/2]
void Tshirt_C_Realization::create_formulation (geojson::PropertyMap properties) override virtual
Implements realization::Catchment_Formulation.
References catchment_id, realization::Formulation::get_id(), giuh_cdf_ordinates, giuh_runoff_queue_per_timestep, init_ground_water_reservoir(), init_soil_reservoir(), nash_storage, params, sync_c_storage_params(), and realization::Formulation::validate_parameters().
get_catchment_id()
std::string realization::Catchment_Formulation::get_catchment_id () inline override protected virtual inherited
Implements HY_CatchmentRealization.
References realization::Catchment_Formulation::cat_id.
Referenced by realization::Bmi_Multi_Formulation::create_multi_formulation(), realization::Bmi_Multi_Formulation::get_value(), realization::Bmi_Multi_Formulation::get_values(), realization::Bmi_Multi_Formulation::get_var_value_as_double(), and realization::Bmi_Module_Formulation< M >::set_model_inputs_prior_to_update().
get_et_params()
virtual const pdm03_struct & realization::Et_Accountable::get_et_params () inline virtual inherited
Get a reference to the appropriate object holding ET parameters for use when executing the model calculations.
Returns
A reference object for model ET parameters.
References realization::Et_Accountable::et_params.
Referenced by Simple_Lumped_Model_Realization::get_response().
get_et_params_ptr()
virtual std::shared_ptr< pdm03_struct > realization::Et_Accountable::get_et_params_ptr () inline protected virtual inherited
References realization::Et_Accountable::et_params.
Referenced by realization::Tshirt_Realization::get_response().
get_formulation_type()
std::string Tshirt_C_Realization::get_formulation_type () override virtual
Implements realization::Formulation.
get_id()
std::string realization::Formulation::get_id () const inline inherited
References realization::Formulation::id.
Referenced by create_formulation(), and realization::Tshirt_Realization::create_formulation().
get_latest_flux_base_flow()
double Tshirt_C_Realization::get_latest_flux_base_flow ()
References fluxes.
get_latest_flux_giuh_runoff()
double Tshirt_C_Realization::get_latest_flux_giuh_runoff ()
References fluxes.
get_latest_flux_lateral_flow()
double Tshirt_C_Realization::get_latest_flux_lateral_flow ()
References fluxes.
get_latest_flux_surface_runoff()
double Tshirt_C_Realization::get_latest_flux_surface_runoff ()
References fluxes.
get_latest_flux_total_discharge()
double Tshirt_C_Realization::get_latest_flux_total_discharge ()
References fluxes.
get_output_header_fields()
const std::vector< std::string > & Tshirt_C_Realization::get_output_header_fields ()
Get the values making up the header line from get_output_header_line(), but organized as a vector of strings.
Returns
The values making up the header line from get_output_header_line() organized as a vector.
References OUTPUT_HEADER_FIELDS.
Referenced by get_output_header_line().
get_output_header_line()
std::string Tshirt_C_Realization::get_output_header_line (std::string delimiter = ",") override virtual
Get a header line appropriate for a file made up of entries from this type's implementation of get_output_line_for_timestep.
Note that like the output generating function, this line does not include anything for time step.
Returns
An appropriate header line for this type.
Reimplemented from realization::Catchment_Formulation.
References get_output_header_fields().
get_output_item_count()
int Tshirt_C_Realization::get_output_item_count ()
Get the number of output data variables made available from the calculations for enumerated time steps.
Returns
The number of output data variables made available from the calculations for enumerated time steps.
References get_output_var_names().
get_output_line_for_timestep()
std::string Tshirt_C_Realization::get_output_line_for_timestep (int timestep, std::string delimiter = ",") override virtual
Get a delimited string with all the output variable values for the given time step.
This method is useful for preparing calculated data in a representation useful for output files, such as CSV files.
The resulting string contains only the calculated output values for the time step, and not the time step index itself.
An empty string is returned if the time step value is not in the range of valid time steps for which there are calculated values for all variables.
The default delimiter is a comma.
Parameters
timestep The time step for which data is desired.
Returns
A delimited string with all the output variable values for the given time step.
Implements realization::Formulation.
References fluxes, get_output_var_flux_extraction_func(), and get_output_var_names().
get_output_var_flux_extraction_func()
std::function< double(tshirt_c_result_fluxes)> Tshirt_C_Realization::get_output_var_flux_extraction_func (const std::string & var_name) private
Referenced by get_output_line_for_timestep(), and get_value().
get_output_var_names()
const std::vector< std::string > & Tshirt_C_Realization::get_output_var_names ()
Get the names of the output data variables that are available from calculations for enumerated time steps.
The method must deterministically return output variable names in the same order each time.
Returns
The names of the output data variables that are available from calculations for enumerated time steps.
The names of the output data variables that are available from calculations for enumerated time steps.
References OUTPUT_VARIABLE_NAMES.
Referenced by get_output_item_count(), and get_output_line_for_timestep().
get_required_parameters()
const std::vector< std::string > & Tshirt_C_Realization::get_required_parameters () override private virtual
Implements realization::Catchment_Formulation.
References REQUIRED_PARAMETERS.
get_response()
double Tshirt_C_Realization::get_response (time_step_t t_index, time_step_t t_delta_s) override virtual
Execute the backing model formulation for the given time step, where it is of the specified size, and return the total discharge.
Any inputs and additional parameters must be made available as instance members.
Types should clearly document the details of their particular response output.
Parameters
t_index The index of the time step for which to run model calculations.
d_delta_s The duration, in seconds, of the time step for which to run model calculations.
Returns
The total discharge of the model for this time step.
Implements realization::Catchment_Formulation.
References catchment_id, fluxes, HY_CatchmentRealization::forcing, run_formulation_for_timestep(), and data_access::SUM.
get_value()
std::vector< double > Tshirt_C_Realization::get_value (const std::string & name)
Get a copy of the values for the given output variable at all available time steps.
Parameters
name
Returns
A vector containing copies of the output value of the variable, indexed by time step.
References fluxes, and get_output_var_flux_extraction_func().
init_ground_water_reservoir()
void Tshirt_C_Realization::init_ground_water_reservoir (double storage, bool storage_values_are_ratios) private
References conceptual_reservoir::coeff_primary, conceptual_reservoir::coeff_secondary, conceptual_reservoir::exponent_primary, conceptual_reservoir::exponent_secondary, groundwater_conceptual_reservoir, init_reservoir_storage(), conceptual_reservoir::is_exponential, params, conceptual_reservoir::storage_m, conceptual_reservoir::storage_max_m, conceptual_reservoir::storage_threshold_primary_m, and conceptual_reservoir::storage_threshold_secondary_m.
Referenced by Tshirt_C_Realization(), and create_formulation().
init_reservoir_storage()
double Tshirt_C_Realization::init_reservoir_storage (bool is_ratio, double amount, double max_amount) static private
Referenced by init_ground_water_reservoir(), and init_soil_reservoir().
init_soil_reservoir()
void Tshirt_C_Realization::init_soil_reservoir (double storage, bool storage_values_are_ratios) private
References NWM_soil_parameters::bb, c_soil_params, conceptual_reservoir::coeff_primary, conceptual_reservoir::coeff_secondary, NWM_soil_parameters::D, conceptual_reservoir::exponent_primary, conceptual_reservoir::exponent_secondary, init_reservoir_storage(), conceptual_reservoir::is_exponential, params, NWM_soil_parameters::satdk, NWM_soil_parameters::satpsi, NWM_soil_parameters::slop, NWM_soil_parameters::smcmax, soil_conceptual_reservoir, conceptual_reservoir::storage_m, conceptual_reservoir::storage_max_m, conceptual_reservoir::storage_threshold_primary_m, and conceptual_reservoir::storage_threshold_secondary_m.
Referenced by Tshirt_C_Realization(), and create_formulation().
interpret_parameters()
virtual geojson::PropertyMap realization::Formulation::interpret_parameters (boost::property_tree::ptree & config, geojson::PropertyMap * global = nullptr) inline protected virtual inherited
References realization::Formulation::validate_parameters().
Referenced by realization::Bmi_Module_Formulation< M >::create_formulation(), realization::Bmi_Multi_Formulation::create_formulation(), Simple_Lumped_Model_Realization::create_formulation(), create_formulation(), and realization::Tshirt_Realization::create_formulation().
is_et_params_set() [1/2]
bool realization::Et_Accountable::is_et_params_set () inline override virtual inherited
Test whether ET params have been set.
Returns
Whether ET params have been set.
Implements realization::Et_Aware.
References realization::Et_Accountable::et_params.
is_et_params_set() [2/2]
virtual bool realization::Et_Aware::is_et_params_set () pure virtual inherited
Test whether ET params have been set.
Returns
Whether ET params have been set.
Implemented in realization::Et_Accountable.
run_formulation_for_timestep()
int Tshirt_C_Realization::run_formulation_for_timestep (double input_flux, time_step_t t_delta_s)
Run model formulation calculations for the next time step using the given input flux value in meters per second.
The backing model works on a collection of time steps by receiving an associated collection of input fluxes. This is implemented by putting this input flux in a single-value vector and using it as the arg to a nested call to run_formulation_for_timesteps, returning that result code.
Parameters
input_flux Input flux (typically expected to be just precipitation) in meters per second.
t_delta_s The size of the time step in seconds
Returns
The result code from the execution of the model time step calculations.
References run_formulation_for_timesteps().
Referenced by get_response().
run_formulation_for_timesteps()
int Tshirt_C_Realization::run_formulation_for_timesteps (std::vector< double > input_fluxes, std::vector< time_step_t > t_deltas_s)
Run model formulation calculations for a series of time steps using the given collection of input flux values in meters per second.
Parameters
input_fluxes Ordered, per-time-step input flux (typically expected to be just precipitation) in meters per second.
t_delta_s The sizes of each of the time steps in seconds
Returns
The result code from the execution of the model time step calculations.
References c_soil_params, fluxes, giuh_cdf_ordinates, giuh_runoff_queue_per_timestep, groundwater_conceptual_reservoir, nash_storage, params, and soil_conceptual_reservoir.
Referenced by run_formulation_for_timestep().
set_catchment_id()
void realization::Catchment_Formulation::set_catchment_id (std::string cat_id) inline override protected virtual inherited
Implements HY_CatchmentRealization.
References realization::Catchment_Formulation::cat_id.
Referenced by realization::Catchment_Formulation::Catchment_Formulation().
set_et_params() [1/2]
void realization::Et_Accountable::set_et_params (std::shared_ptr< pdm03_struct > params) inline override virtual inherited
Set a reference for an appropriate object for holding ET parameters for use when executing the model calculations.
Implements realization::Et_Aware.
References realization::Et_Accountable::et_params.
set_et_params() [2/2]
virtual void realization::Et_Aware::set_et_params (std::shared_ptr< pdm03_struct > params) pure virtual inherited
Accept a reference for an appropriate object for holding ET parameters for use when executing the model calculations, if maintained by the type.
Implemented in realization::Et_Accountable.
set_output_stream()
void HY_CatchmentArea::set_output_stream (std::string file_path) inline inherited
References HY_CatchmentArea::output.
sync_c_storage_params()
void Tshirt_C_Realization::sync_c_storage_params () private
References NWM_soil_parameters::bb, c_soil_params, NWM_soil_parameters::D, NWM_soil_parameters::mult, params, NWM_soil_parameters::satdk, NWM_soil_parameters::satpsi, NWM_soil_parameters::slop, NWM_soil_parameters::smcmax, and NWM_soil_parameters::wltsmc.
Referenced by Tshirt_C_Realization(), and create_formulation().
validate_parameters()
virtual void realization::Formulation::validate_parameters (geojson::PropertyMap options) inline protected virtual inherited
References realization::Formulation::get_formulation_type(), and realization::Formulation::get_required_parameters().
Referenced by Simple_Lumped_Model_Realization::create_formulation(), create_formulation(), realization::Tshirt_Realization::create_formulation(), realization::Bmi_Multi_Formulation::create_multi_formulation(), realization::Bmi_Module_Formulation< M >::inner_create_formulation(), and realization::Formulation::interpret_parameters().
write_output()
void HY_CatchmentArea::write_output (std::string out) inline inherited
References HY_CatchmentArea::output.
Member Data Documentation
bounds
polygon_t HY_CatchmentArea::bounds protected inherited
c_aorc_params
aorc_forcing_data realization::Tshirt_C_Realization::c_aorc_params private
c_soil_params
NWM_soil_parameters realization::Tshirt_C_Realization::c_soil_params private
Struct from C-style Tshirt formulation for holding soil parameter values.
Referenced by init_soil_reservoir(), run_formulation_for_timesteps(), and sync_c_storage_params().
cat_id
std::string realization::Catchment_Formulation::cat_id private inherited
Referenced by realization::Catchment_Formulation::get_catchment_id(), and realization::Catchment_Formulation::set_catchment_id().
catchment_id
std::string realization::Tshirt_C_Realization::catchment_id private
Id of associated catchment.
Referenced by create_formulation(), and get_response().
et_params
std::shared_ptr<pdm03_struct> realization::Et_Accountable::et_params private inherited
Referenced by realization::Bmi_Module_Formulation< M >::calc_et(), realization::Et_Accountable::get_et_params(), realization::Et_Accountable::get_et_params_ptr(), realization::Et_Accountable::is_et_params_set(), and realization::Et_Accountable::set_et_params().
fluxes
std::vector<std::shared_ptr<tshirt_c_result_fluxes> > realization::Tshirt_C_Realization::fluxes private
Referenced by Tshirt_C_Realization(), get_latest_flux_base_flow(), get_latest_flux_giuh_runoff(), get_latest_flux_lateral_flow(), get_latest_flux_surface_runoff(), get_latest_flux_total_discharge(), get_output_line_for_timestep(), get_response(), get_value(), and run_formulation_for_timesteps().
forcing
std::shared_ptr<data_access::GenericDataProvider> HY_CatchmentRealization::forcing protected inherited
Referenced by realization::Bmi_Module_Formulation< M >::calc_et(), realization::Bmi_Multi_Formulation::create_multi_formulation(), realization::Bmi_Module_Formulation< M >::determine_model_time_offset(), Simple_Lumped_Model_Realization::get_response(), get_response(), realization::Tshirt_Realization::get_response(), and realization::Bmi_Module_Formulation< M >::set_model_inputs_prior_to_update().
giuh_cdf_ordinates
std::vector<double> realization::Tshirt_C_Realization::giuh_cdf_ordinates private
Vector of GIUH CDF ordinates.
Referenced by Tshirt_C_Realization(), create_formulation(), and run_formulation_for_timesteps().
giuh_runoff_queue_per_timestep
std::vector<double> realization::Tshirt_C_Realization::giuh_runoff_queue_per_timestep private
Vector to serve as runoff queue for GIUH convolution calculations.
Referenced by Tshirt_C_Realization(), create_formulation(), and run_formulation_for_timesteps().
groundwater_conceptual_reservoir
conceptual_reservoir realization::Tshirt_C_Realization::groundwater_conceptual_reservoir private
Referenced by init_ground_water_reservoir(), and run_formulation_for_timesteps().
id
std::string realization::Formulation::id protected inherited
Referenced by realization::Formulation::get_id().
id_number
unsigned long HY_CatchmentRealization::id_number protected inherited
nash_storage
std::vector<double> realization::Tshirt_C_Realization::nash_storage private
Referenced by create_formulation(), and run_formulation_for_timesteps().
output
utils::StreamHandler HY_CatchmentArea::output protected inherited
Referenced by realization::Bmi_C_Formulation::construct_model(), realization::Bmi_Cpp_Formulation::construct_model(), realization::Bmi_Multi_Formulation::init_nested_module(), HY_CatchmentArea::set_output_stream(), and HY_CatchmentArea::write_output().
OUTPUT_HEADER_FIELDS
std::vector<std::string> realization::Tshirt_C_Realization::OUTPUT_HEADER_FIELDS private
Initial value:
= {
                "Rainfall",
                "Direct Runoff",
                "GIUH Runoff",
                "Lateral Flow",
                "Base Flow",
                "Total Discharge"
        }
Referenced by get_output_header_fields().
OUTPUT_VARIABLE_NAMES
std::vector<std::string> realization::Tshirt_C_Realization::OUTPUT_VARIABLE_NAMES private
Initial value:
= {
                OUT_VAR_RAINFALL,
                OUT_VAR_SURFACE_RUNOFF,
                OUT_VAR_GIUH_RUNOFF,
                OUT_VAR_LATERAL_FLOW,
                OUT_VAR_BASE_FLOW,
                OUT_VAR_TOTAL_DISCHARGE
        }
Referenced by get_output_var_names().
params
std::shared_ptr<tshirt::tshirt_params> realization::Tshirt_C_Realization::params private
Struct for containing model parameters for Tshirt model, using "internal" framework implementation for such a struct.
Referenced by Tshirt_C_Realization(), create_formulation(), init_ground_water_reservoir(), init_soil_reservoir(), run_formulation_for_timesteps(), and sync_c_storage_params().
realized_catchment
shared_ptr<HY_Catchment> HY_CatchmentRealization::realized_catchment protected inherited
REQUIRED_PARAMETERS
std::vector<std::string> realization::Tshirt_C_Realization::REQUIRED_PARAMETERS private
Initial value:
= {
                "maxsmc",
                "wltsmc",
                "satdk",
                "satpsi",
                "slope",
                "scaled_distribution_fn_shape_parameter",
                "multiplier",
                "alpha_fc",
                "Klf",
                "Kn",
                "nash_n",
                "Cgw",
                "expon",
                "max_groundwater_storage_meters",
                "nash_storage",
                "soil_storage_percentage",
                "groundwater_storage_percentage",
                "giuh"
        }
Referenced by get_required_parameters().
soil_conceptual_reservoir
conceptual_reservoir realization::Tshirt_C_Realization::soil_conceptual_reservoir private
Referenced by init_soil_reservoir(), and run_formulation_for_timesteps().
The documentation for this class was generated from the following files:
include/realizations/catchment/Tshirt_C_Realization.hpp
src/realizations/catchment/Tshirt_C_Realization.cpp