NGen: UnitsHelper Class Reference
UnitsHelper Class Reference
#include <UnitsHelper.hpp>
Static Public Member Functions
static double get_converted_value (const std::string &in_units, const double &value, const std::string &out_units)
static double * convert_values (const std::string &in_units, double *values, const std::string &out_units, double *out_values, const size_t &count)
Static Private Member Functions
static void init_unit_system ()
static std::shared_ptr< cv_converter > get_converter (const std::string &in_units, const std::string &out_units, utEncoding in_encoding=UT_UTF8, utEncoding out_encoding=UT_UTF8)
Static Private Attributes
static ut_system * unit_system
static std::map< std::string, std::shared_ptr< cv_converter > > converters
static std::mutex converters_mutex
static std::once_flag unit_system_inited
Member Function Documentation
convert_values()
double * UnitsHelper::convert_values (const std::string & in_units, double * values, const std::string & out_units, double * out_values, const size_t & count) static
References get_converter(), init_unit_system(), and unit_system_inited.
Referenced by realization::Bmi_Module_Formulation::get_values().
get_converted_value()
double UnitsHelper::get_converted_value (const std::string & in_units, const double & value, const std::string & out_units) static
References get_converter(), init_unit_system(), and unit_system_inited.
Referenced by models::bmi::Bmi_Adapter::get_time_convert_factor(), CsvPerFeatureForcingProvider::get_value(), and realization::Bmi_Module_Formulation::get_value().
get_converter()
std::shared_ptr< cv_converter > UnitsHelper::get_converter (const std::string & in_units, const std::string & out_units, utEncoding in_encoding = UT_UTF8, utEncoding out_encoding = UT_UTF8) static private
References converters, converters_mutex, and unit_system.
Referenced by convert_values(), and get_converted_value().
init_unit_system()
static void UnitsHelper::init_unit_system () inline static private
References unit_system.
Referenced by convert_values(), and get_converted_value().
Member Data Documentation
converters
std::map< std::string, std::shared_ptr< cv_converter > > UnitsHelper::converters static private
Referenced by get_converter().
converters_mutex
std::mutex UnitsHelper::converters_mutex static private
Referenced by get_converter().
unit_system
ut_system * UnitsHelper::unit_system static private
Referenced by get_converter(), and init_unit_system().
unit_system_inited
std::once_flag UnitsHelper::unit_system_inited static private
Referenced by convert_values(), and get_converted_value().
The documentation for this class was generated from the following files:
include/core/mediator/UnitsHelper.hpp
src/core/mediator/UnitsHelper.cpp