NGen: data_access::DeferredWrappedProvider Class Reference
data_access::DeferredWrappedProvider Class Reference
A specialized @WrappedForcingProvider that is created without first knowing the backing source it wraps.
#include <DeferredWrappedProvider.hpp>
Public Member Functions
DeferredWrappedProvider (vector< string > providedOutputs)
Constructor for instance.
DeferredWrappedProvider (const string &outputName)
Convenience constructor for when there is only one provided output name.
DeferredWrappedProvider (DeferredWrappedProvider &&provider_to_move) noexcept
Move constructor.
const std::vector< std::string > & get_avaliable_variable_names ()
Get the names of the outputs that this instance is (or will be) able to provide.
const std::vector< std::string > & get_available_forcing_outputs ()
const string & getSetMessage ()
Get the message string for the last call to setWrappedProvider.
virtual bool isReadyToProvideData ()
Get whether the instance is initialized such that it can handle requests to provide data.
bool isWrappedProviderSet ()
Get whether the backing provider this instance wraps has been set yet.
virtual bool setWrappedProvider (GenericDataProvider *provider)
Set the wrapped provider, if the given arg is valid for doing so.
time_t get_forcing_output_time_begin (const std::string &output_name)
Get the inclusive beginning of the period of time over which this instance can provide data for this forcing.
long get_data_start_time () override
Get the inclusive beginning of the period of time over which this instance can provide data for this forcing.
time_t get_forcing_output_time_end (const std::string &output_name)
Get the exclusive ending of the period of time over which this instance can provide data for this forcing.
long get_data_stop_time () override
Get the exclusive ending of the period of time over which this instance can provide data for this forcing.
long record_duration () override
Return the stride in the time dimension.
size_t get_ts_index_for_time (const time_t &epoch_time) override
Get the index of the forcing time step that contains the given point in time.
double get_value (const CatchmentAggrDataSelector &selector, ReSampleMethod m) override
Get the value of a forcing property for an arbitrary time period, converting units if needed.
std::vector< double > get_values (const CatchmentAggrDataSelector &selector, ReSampleMethod m) override
Get the values of a forcing property for an arbitrary time period, converting units if needed.
bool is_property_sum_over_time_step (const std::string &name) override
Get whether a property's per-time-step values are each an aggregate sum over the entire time step.
Protected Attributes
vector< string > providedOutputs
The collection of names of the outputs this type can/will be able to provide from its wrapped source.
string setMessage
A message providing information from the last setWrappedProvider call.
GenericDataProvider * wrapped_provider
Detailed Description
A specialized @WrappedForcingProvider that is created without first knowing the backing source it wraps.
This type wraps another ForcingProvider, similarly to its parent. This is "optimistic," however, in that it is constructed without the backing data source it will wrap. It only requires the data output names it expects to eventually be able to provide.
This type allows for deferring reconciling of whether a provider for some data output is available. This is useful for situations when a required provider is not currently known, but is expected, and there will be ample time to validate the expectation and make the necessary associations before the data must be provided.
The runtime behavior of inherited functions depends on the type of the wrapped object. I.e., nested calls to the analogous function of the wrapped provider object are made, with those results returned. The one exception to this is get_available_forcing_outputs. A particular effect of this is that the type of the wrapped provider object will dictate how an instance behaves in cases when an unrecognized output name is supplied as a parameter to get_value.
As noted above, the get_available_forcing_outputs virtual function is overridden here. Instead of directly returning results from a nested call to the wrapped provider, this type's implementation ensures only the outputs set as provideable in this instance (i.e., the outer wrapper) are returned.
Constructor & Destructor Documentation
DeferredWrappedProvider() [1/3]
data_access::DeferredWrappedProvider::DeferredWrappedProvider (vector< string > providedOutputs) inline explicit
Constructor for instance.
Parameters
providedOutputs The collection of the names of outputs this instance will need to provide.
DeferredWrappedProvider() [2/3]
data_access::DeferredWrappedProvider::DeferredWrappedProvider (const string & outputName) inline explicit
Convenience constructor for when there is only one provided output name.
Parameters
outputName The name of the single output this instance will need to provide.
References providedOutputs.
DeferredWrappedProvider() [3/3]
data_access::DeferredWrappedProvider::DeferredWrappedProvider (DeferredWrappedProvider && provider_to_move) inline noexcept
Move constructor.
Parameters
provider_to_move
References data_access::WrappedForcingProvider::wrapped_provider.
Member Function Documentation
get_available_forcing_outputs()
const std::vector< std::string > & data_access::DeferredWrappedProvider::get_available_forcing_outputs () inline
References providedOutputs.
get_avaliable_variable_names()
const std::vector< std::string > & data_access::DeferredWrappedProvider::get_avaliable_variable_names () inline virtual
Get the names of the outputs that this instance is (or will be) able to provide.
Note that this function behaves the same regardless of whether the wrapped provider has been set.
Returns
The names of the outputs for which this instance is (or will be) able to provide values.
Implements data_access::DataProvider< double, CatchmentAggrDataSelector >.
References providedOutputs.
get_data_start_time()
long data_access::WrappedForcingProvider::get_data_start_time () inline override virtual inherited
Get the inclusive beginning of the period of time over which this instance can provide data for this forcing.
Returns
The inclusive beginning of the period of time over which this instance can provide this data.
Implements data_access::DataProvider< double, CatchmentAggrDataSelector >.
References data_access::DataProvider< data_type, selection_type >::get_data_start_time(), and data_access::WrappedForcingProvider::wrapped_provider.
get_data_stop_time()
long data_access::WrappedForcingProvider::get_data_stop_time () inline override virtual inherited
Get the exclusive ending of the period of time over which this instance can provide data for this forcing.
Returns
The exclusive ending of the period of time over which this instance can provide this data.
Implements data_access::DataProvider< double, CatchmentAggrDataSelector >.
References data_access::DataProvider< data_type, selection_type >::get_data_stop_time(), and data_access::WrappedForcingProvider::wrapped_provider.
get_forcing_output_time_begin()
time_t data_access::WrappedForcingProvider::get_forcing_output_time_begin (const std::string & output_name) inline inherited
Get the inclusive beginning of the period of time over which this instance can provide data for this forcing.
Returns
The inclusive beginning of the period of time over which this instance can provide this data.
References data_access::DataProvider< data_type, selection_type >::get_data_start_time(), and data_access::WrappedForcingProvider::wrapped_provider.
get_forcing_output_time_end()
time_t data_access::WrappedForcingProvider::get_forcing_output_time_end (const std::string & output_name) inline inherited
Get the exclusive ending of the period of time over which this instance can provide data for this forcing.
Returns
The exclusive ending of the period of time over which this instance can provide this data.
References data_access::DataProvider< data_type, selection_type >::get_data_stop_time(), and data_access::WrappedForcingProvider::wrapped_provider.
get_ts_index_for_time()
size_t data_access::WrappedForcingProvider::get_ts_index_for_time (const time_t & epoch_time) inline override virtual inherited
Get the index of the forcing time step that contains the given point in time.
An std::out_of_range exception should be thrown if the time is not in any time step.
Parameters
epoch_time The point in time, as a seconds-based epoch time.
Returns
The index of the forcing time step that contains the given point in time.
Exceptions
std::out_of_range If the given point is not in any time step.
Implements data_access::DataProvider< double, CatchmentAggrDataSelector >.
References data_access::DataProvider< data_type, selection_type >::get_ts_index_for_time(), and data_access::WrappedForcingProvider::wrapped_provider.
get_value()
double data_access::WrappedForcingProvider::get_value (const CatchmentAggrDataSelector & selector, ReSampleMethod m) inline override virtual inherited
Get the value of a forcing property for an arbitrary time period, converting units if needed.
An std::out_of_range exception should be thrown if the data for the time period is not available.
Parameters
output_name The name of the forcing property of interest.
init_time_epoch The epoch time (in seconds) of the start of the time period.
duration_seconds The length of the time period, in seconds.
output_units The expected units of the desired output value.
Returns
The value of the forcing property for the described time period, with units converted if needed.
Exceptions
std::out_of_range If data for the time period is not available.
Implements data_access::DataProvider< double, CatchmentAggrDataSelector >.
References data_access::DataProvider< data_type, selection_type >::get_value(), and data_access::WrappedForcingProvider::wrapped_provider.
get_values()
std::vector< double > data_access::WrappedForcingProvider::get_values (const CatchmentAggrDataSelector & selector, ReSampleMethod m) inline override virtual inherited
Get the values of a forcing property for an arbitrary time period, converting units if needed.
An std::out_of_range exception should be thrown if the data for the time period is not available.
If a provider doesn't implement this function, then by default, get_values will be a simple proxy to get_value with the result wrapped in a std::vector<double>
Parameters
output_name The name of the forcing property of interest.
init_time_epoch The epoch time (in seconds) of the start of the time period.
duration_seconds The length of the time period, in seconds.
output_units The expected units of the desired output value.
Returns
std::vector<double> The vector of values of the forcing property for the described time period, with units converted if needed.
Exceptions
std::out_of_range If data for the time period is not available.
Implements data_access::DataProvider< double, CatchmentAggrDataSelector >.
References data_access::DataProvider< data_type, selection_type >::get_values(), and data_access::WrappedForcingProvider::wrapped_provider.
getSetMessage()
const string & data_access::DeferredWrappedProvider::getSetMessage () inline
Get the message string for the last call to setWrappedProvider.
The value of the backing member for this function will be empty if the last call to setWrappedProvider returned true (or has not been called yet). If setWrappedProvider it returned false, then an info message will be saved in the member returned by this function, explaining more detail on the failure.
Returns
The message string for the last call to setWrappedProvider.
References setMessage.
is_property_sum_over_time_step()
bool data_access::WrappedForcingProvider::is_property_sum_over_time_step (const std::string & name) inline override virtual inherited
Get whether a property's per-time-step values are each an aggregate sum over the entire time step.
Certain properties, like rain fall, are aggregated sums over an entire time step. Others, such as pressure, are not such sums and instead something else like an instantaneous reading or an average value.
It may be the case that forcing data is needed for some discretization different than the forcing time step. This aspect must be known in such cases to perform the appropriate value interpolation.
Parameters
name The name of the forcing property for which the current value is desired.
Returns
Whether the property's value is an aggregate sum.
Reimplemented from data_access::DataProvider< double, CatchmentAggrDataSelector >.
References data_access::DataProvider< data_type, selection_type >::is_property_sum_over_time_step(), and data_access::WrappedForcingProvider::wrapped_provider.
isReadyToProvideData()
virtual bool data_access::DeferredWrappedProvider::isReadyToProvideData () inline virtual
Get whether the instance is initialized such that it can handle requests to provide data.
For this type, this is equivalent to whether the wrapped provider member has been set.
Returns
Whether the instance is initialized such that it can handle requests to provide data.
Reimplemented in data_access::OptionalWrappedProvider.
References isWrappedProviderSet().
isWrappedProviderSet()
bool data_access::DeferredWrappedProvider::isWrappedProviderSet () inline
Get whether the backing provider this instance wraps has been set yet.
Returns
Whether the backing provider this instance wraps has been set yet.
References data_access::WrappedForcingProvider::wrapped_provider.
Referenced by isReadyToProvideData(), data_access::OptionalWrappedProvider::isReadyToProvideData(), setWrappedProvider(), and data_access::OptionalWrappedProvider::setWrappedProvider().
record_duration()
long data_access::WrappedForcingProvider::record_duration () inline override virtual inherited
Return the stride in the time dimension.
Implements data_access::DataProvider< double, CatchmentAggrDataSelector >.
References data_access::DataProvider< data_type, selection_type >::record_duration(), and data_access::WrappedForcingProvider::wrapped_provider.
setWrappedProvider()
virtual bool data_access::DeferredWrappedProvider::setWrappedProvider (GenericDataProvider * provider) inline virtual
Set the wrapped provider, if the given arg is valid for doing so.
For a valid provider pointer argument, set the wrapped provider to it, clear the info message and return true. For an invalid arg, set the info message member to provide details on why it is invalid. Then return false without setting the wrapped provider.
There are several invalid argument cases:
an arg that is actually a null pointer
an arg that points to a provider that does not itself provide all the required outputs this must provide
any arg if there has already been a valid provider set
Parameters
provider A pointer for the wrapped provider.
Returns
Whether wrapped_provider was set to the given arg.
Reimplemented in data_access::OptionalWrappedProvider.
References data_access::DataProvider< data_type, selection_type >::get_avaliable_variable_names(), isWrappedProviderSet(), providedOutputs, setMessage, and data_access::WrappedForcingProvider::wrapped_provider.
Member Data Documentation
providedOutputs
vector<string> data_access::DeferredWrappedProvider::providedOutputs protected
The collection of names of the outputs this type can/will be able to provide from its wrapped source.
Referenced by DeferredWrappedProvider(), data_access::OptionalWrappedProvider::OptionalWrappedProvider(), get_available_forcing_outputs(), get_avaliable_variable_names(), data_access::OptionalWrappedProvider::get_value(), data_access::OptionalWrappedProvider::isReadyToProvideData(), setWrappedProvider(), and data_access::OptionalWrappedProvider::setWrappedProvider().
setMessage
string data_access::DeferredWrappedProvider::setMessage protected
A message providing information from the last setWrappedProvider call.
The value will be empty if the function returned true. If it returned false, this will have an info message set explaining more detail on the failure.
Referenced by getSetMessage(), setWrappedProvider(), and data_access::OptionalWrappedProvider::setWrappedProvider().
wrapped_provider
GenericDataProvider* data_access::WrappedForcingProvider::wrapped_provider protected inherited
Referenced by DeferredWrappedProvider(), data_access::OptionalWrappedProvider::OptionalWrappedProvider(), data_access::WrappedForcingProvider::get_available_forcing_outputs(), data_access::WrappedForcingProvider::get_avaliable_variable_names(), data_access::WrappedForcingProvider::get_data_start_time(), data_access::WrappedForcingProvider::get_data_stop_time(), data_access::WrappedForcingProvider::get_forcing_output_time_begin(), data_access::WrappedForcingProvider::get_forcing_output_time_end(), data_access::WrappedForcingProvider::get_ts_index_for_time(), data_access::OptionalWrappedProvider::get_value(), data_access::WrappedForcingProvider::get_value(), data_access::WrappedForcingProvider::get_values(), data_access::WrappedForcingProvider::is_property_sum_over_time_step(), data_access::OptionalWrappedProvider::isSuppliedByWrappedProvider(), isWrappedProviderSet(), data_access::WrappedForcingProvider::record_duration(), setWrappedProvider(), and data_access::OptionalWrappedProvider::setWrappedProvider().
The documentation for this class was generated from the following file:
include/forcing/DeferredWrappedProvider.hpp