NGen: giuh::giuh_kernel_impl Class Reference
giuh::giuh_kernel_impl Class Reference
A concrete implementation of a GIUH calculation kernel.
#include <GIUH.hpp>
Public Member Functions
giuh_kernel_impl (std::string catchment_id, std::string comid, std::vector< double > cdf_times, std::vector< double > cdf_cumulative_freqs)
virtual ~giuh_kernel_impl ()=default
Destructor.
double calc_giuh_output (double dt, double direct_runoff) override
Calculate the GIUH output for the given time step and runoff value, lazily generating the necessary regularized CDF ordinates if appropriate.
void set_interpolation_regularity_seconds (unsigned int regularity_seconds) override
Set the object's interpolation regularity value, also triggering recalculation of the interpolated, regularized CDF ordinates IFF the new regularity value is different from the previous.
std::string get_catchment_id ()
Accessor for the catchment id of the associated catchment.
std::string get_comid ()
Accessor for the associated COMID for the GIUH source data.
unsigned int get_interpolation_regularity_seconds () const
Get the object's interpolation regularity value - the difference in seconds between each regularized CDF.
Private Member Functions
void interpolate_regularized_cdf ()
Perform the interpolation of regularized CDF ordinates.
Private Attributes
std::vector< double > cdf_cumulative_freqs
Ranked order of time of travel cell values for CDF.
std::vector< double > cdf_times
CDF times in seconds.
std::vector< int > interpolated_ordinate_times_seconds
The corresponding, regular time values for each of the interpolated CDF ordinates.
std::vector< double > interpolated_regularized_ordinates
The regularized CDF ordinate interpolated values.
std::vector< double > interpolated_incremental_runoff_values
The incremental increases at each index of the interpolated, regularized CDF ordinate value, from the value at the previous index.
std::shared_ptr< giuh_carry_over > carry_overs_list_head
List to hold carry-over amounts from previous inputs, which didn't all flow out at that time step.
std::string catchment_id
Main catchment identifier, as a string.
std::string comid
Associated COMID that is the look-up key for the GIUH serial data used to create this object, as a string.
unsigned int interpolation_regularity_seconds
The regularity (i.e., time between each increment) used to interpolate and produce CDF ordinates, in seconds.
Detailed Description
A concrete implementation of a GIUH calculation kernel.
Constructor & Destructor Documentation
giuh_kernel_impl()
giuh::giuh_kernel_impl::giuh_kernel_impl (std::string catchment_id, std::string comid, std::vector< double > cdf_times, std::vector< double > cdf_cumulative_freqs) inline
References carry_overs_list_head, cdf_cumulative_freqs, cdf_times, and interpolate_regularized_cdf().
~giuh_kernel_impl()
virtual giuh::giuh_kernel_impl::~giuh_kernel_impl () virtual default
Destructor.
Member Function Documentation
calc_giuh_output()
double giuh_kernel_impl::calc_giuh_output (double dt, double direct_runoff) override virtual
Calculate the GIUH output for the given time step and runoff value, lazily generating the necessary regularized CDF ordinates if appropriate.
Parameters
dt Time step value, in seconds.
direct_runoff The runoff input for this time step.
Returns
The calculated output for this time step.
Reimplemented from giuh::giuh_kernel.
References carry_overs_list_head, interpolated_incremental_runoff_values, interpolated_ordinate_times_seconds, interpolated_regularized_ordinates, giuh::giuh_carry_over::last_outputted_cdf_index, giuh::giuh_carry_over::next, and giuh::giuh_carry_over::original_input_amount.
get_catchment_id()
std::string giuh::giuh_kernel::get_catchment_id () inline inherited
Accessor for the catchment id of the associated catchment.
Returns
the catchment id of the associated catchment.
References giuh::giuh_kernel::catchment_id.
get_comid()
std::string giuh::giuh_kernel::get_comid () inline inherited
Accessor for the associated COMID for the GIUH source data.
Returns
The associated COMID.
References giuh::giuh_kernel::comid.
get_interpolation_regularity_seconds()
unsigned int giuh::giuh_kernel::get_interpolation_regularity_seconds () const inline inherited
Get the object's interpolation regularity value - the difference in seconds between each regularized CDF.
Returns
The object's interpolation regularity value - the difference in seconds between each regularized CDF.
References giuh::giuh_kernel::interpolation_regularity_seconds.
Referenced by interpolate_regularized_cdf(), and set_interpolation_regularity_seconds().
interpolate_regularized_cdf()
void giuh_kernel_impl::interpolate_regularized_cdf () private
Perform the interpolation of regularized CDF ordinates.
References cdf_cumulative_freqs, cdf_times, giuh::giuh_kernel::get_interpolation_regularity_seconds(), interpolated_incremental_runoff_values, interpolated_ordinate_times_seconds, and interpolated_regularized_ordinates.
Referenced by giuh_kernel_impl(), and set_interpolation_regularity_seconds().
set_interpolation_regularity_seconds()
void giuh_kernel_impl::set_interpolation_regularity_seconds (unsigned int regularity_seconds) override virtual
Set the object's interpolation regularity value, also triggering recalculation of the interpolated, regularized CDF ordinates IFF the new regularity value is different from the previous.
Parameters
regularity_seconds The interpolation regularity value - i.e., the difference between each of the corresponding times of regularized CDF ordinate - in seconds
Reimplemented from giuh::giuh_kernel.
References giuh::giuh_kernel::get_interpolation_regularity_seconds(), interpolate_regularized_cdf(), and giuh::giuh_kernel::set_interpolation_regularity_seconds().
Member Data Documentation
carry_overs_list_head
std::shared_ptr<giuh_carry_over> giuh::giuh_kernel_impl::carry_overs_list_head private
List to hold carry-over amounts from previous inputs, which didn't all flow out at that time step.
Referenced by calc_giuh_output(), and giuh_kernel_impl().
catchment_id
std::string giuh::giuh_kernel::catchment_id private inherited
Main catchment identifier, as a string.
Referenced by giuh::giuh_kernel::get_catchment_id().
cdf_cumulative_freqs
std::vector<double> giuh::giuh_kernel_impl::cdf_cumulative_freqs private
Ranked order of time of travel cell values for CDF.
Referenced by giuh_kernel_impl(), and interpolate_regularized_cdf().
cdf_times
std::vector<double> giuh::giuh_kernel_impl::cdf_times private
CDF times in seconds.
Referenced by giuh_kernel_impl(), and interpolate_regularized_cdf().
comid
std::string giuh::giuh_kernel::comid private inherited
Associated COMID that is the look-up key for the GIUH serial data used to create this object, as a string.
Referenced by giuh::giuh_kernel::get_comid().
interpolated_incremental_runoff_values
std::vector<double> giuh::giuh_kernel_impl::interpolated_incremental_runoff_values private
The incremental increases at each index of the interpolated, regularized CDF ordinate value, from the value at the previous index.
Referenced by calc_giuh_output(), and interpolate_regularized_cdf().
interpolated_ordinate_times_seconds
std::vector<int> giuh::giuh_kernel_impl::interpolated_ordinate_times_seconds private
The corresponding, regular time values for each of the interpolated CDF ordinates.
Referenced by calc_giuh_output(), and interpolate_regularized_cdf().
interpolated_regularized_ordinates
std::vector<double> giuh::giuh_kernel_impl::interpolated_regularized_ordinates private
The regularized CDF ordinate interpolated values.
Referenced by calc_giuh_output(), and interpolate_regularized_cdf().
interpolation_regularity_seconds
unsigned int giuh::giuh_kernel::interpolation_regularity_seconds private inherited
The regularity (i.e., time between each increment) used to interpolate and produce CDF ordinates, in seconds.
Referenced by giuh::giuh_kernel::get_interpolation_regularity_seconds(), giuh::giuh_kernel::giuh_kernel(), and giuh::giuh_kernel::set_interpolation_regularity_seconds().
The documentation for this class was generated from the following files:
include/core/catchment/giuh/GIUH.hpp
src/core/catchment/giuh/GIUH.cpp