NGen: forcing::WrappedForcingProvider Class Reference
forcing::WrappedForcingProvider Class Reference
Simple implementation that basically wraps another instance.
#include <WrappedForcingProvider.hpp>
Public Member Functions
WrappedForcingProvider (ForcingProvider *provider)
Primary constructor for instances.
WrappedForcingProvider (WrappedForcingProvider &provider_to_copy)
Copy constructor.
WrappedForcingProvider (WrappedForcingProvider &&provider_to_move)
Move constructor.
const std::vector< std::string > & get_available_forcing_outputs () override
time_t get_forcing_output_time_begin (const std::string &output_name) override
Get the inclusive beginning of the period of time over which this instance can provide data for this forcing.
time_t get_forcing_output_time_end (const std::string &output_name) override
Get the exclusive ending of the period of time over which this instance can provide data for this forcing.
size_t get_ts_index_for_time (const time_t &epoch_time) override
Get the index of the forcing time step that contains the given point in time.
double get_value (const std::string &output_name, const time_t &init_time, const long &duration_s, const std::string &output_units) override
Get the value of a forcing property for an arbitrary time period, converting units if needed.
bool is_property_sum_over_time_step (const std::string &name) override
Get whether a property's per-time-step values are each an aggregate sum over the entire time step.
Private Attributes
ForcingProvider * wrapped_provider
Detailed Description
Simple implementation that basically wraps another instance.
The primary purpose is to support self-referencing as a forcing provider (e.g., for ET) without introducing any circular references in smart pointers.
Instances of this type must be used carefully, as they do not contain any mechanisms for making sure they actually point to a valid backing object.
Constructor & Destructor Documentation
WrappedForcingProvider() [1/3]
forcing::WrappedForcingProvider::WrappedForcingProvider (ForcingProvider * provider) inline explicit
Primary constructor for instances.
Parameters
provider Simple pointer to some existing ForcingProvider object for this new instance to wrap.
WrappedForcingProvider() [2/3]
forcing::WrappedForcingProvider::WrappedForcingProvider (WrappedForcingProvider & provider_to_copy) inline
Copy constructor.
Parameters
provider_to_copy
WrappedForcingProvider() [3/3]
forcing::WrappedForcingProvider::WrappedForcingProvider (WrappedForcingProvider && provider_to_move) inline
Move constructor.
Parameters
provider_to_move
Member Function Documentation
get_available_forcing_outputs()
const std::vector<std::string>& forcing::WrappedForcingProvider::get_available_forcing_outputs () inline override virtual
Implements forcing::ForcingProvider.
References forcing::ForcingProvider::get_available_forcing_outputs(), and wrapped_provider.
get_forcing_output_time_begin()
time_t forcing::WrappedForcingProvider::get_forcing_output_time_begin (const std::string & output_name) inline override virtual
Get the inclusive beginning of the period of time over which this instance can provide data for this forcing.
Returns
The inclusive beginning of the period of time over which this instance can provide this data.
Implements forcing::ForcingProvider.
References forcing::ForcingProvider::get_forcing_output_time_begin(), and wrapped_provider.
get_forcing_output_time_end()
time_t forcing::WrappedForcingProvider::get_forcing_output_time_end (const std::string & output_name) inline override virtual
Get the exclusive ending of the period of time over which this instance can provide data for this forcing.
Returns
The exclusive ending of the period of time over which this instance can provide this data.
Implements forcing::ForcingProvider.
References forcing::ForcingProvider::get_forcing_output_time_end(), and wrapped_provider.
get_ts_index_for_time()
size_t forcing::WrappedForcingProvider::get_ts_index_for_time (const time_t & epoch_time) inline override virtual
Get the index of the forcing time step that contains the given point in time.
An std::out_of_range exception should be thrown if the time is not in any time step.
Parameters
epoch_time The point in time, as a seconds-based epoch time.
Returns
The index of the forcing time step that contains the given point in time.
Exceptions
std::out_of_range If the given point is not in any time step.
Implements forcing::ForcingProvider.
References forcing::ForcingProvider::get_ts_index_for_time(), and wrapped_provider.
get_value()
double forcing::WrappedForcingProvider::get_value (const std::string & output_name, const time_t & init_time, const long & duration_s, const std::string & output_units) inline override virtual
Get the value of a forcing property for an arbitrary time period, converting units if needed.
An std::out_of_range exception should be thrown if the data for the time period is not available.
Parameters
output_name The name of the forcing property of interest.
init_time_epoch The epoch time (in seconds) of the start of the time period.
duration_seconds The length of the time period, in seconds.
output_units The expected units of the desired output value.
Returns
The value of the forcing property for the described time period, with units converted if needed.
Exceptions
std::out_of_range If data for the time period is not available.
Implements forcing::ForcingProvider.
References forcing::ForcingProvider::get_value(), and wrapped_provider.
is_property_sum_over_time_step()
bool forcing::WrappedForcingProvider::is_property_sum_over_time_step (const std::string & name) inline override virtual
Get whether a property's per-time-step values are each an aggregate sum over the entire time step.
Certain properties, like rain fall, are aggregated sums over an entire time step. Others, such as pressure, are not such sums and instead something else like an instantaneous reading or an average value.
It may be the case that forcing data is needed for some discretization different than the forcing time step. This aspect must be known in such cases to perform the appropriate value interpolation.
Parameters
name The name of the forcing property for which the current value is desired.
Returns
Whether the property's value is an aggregate sum.
Implements forcing::ForcingProvider.
References forcing::ForcingProvider::is_property_sum_over_time_step(), and wrapped_provider.
Member Data Documentation
wrapped_provider
ForcingProvider* forcing::WrappedForcingProvider::wrapped_provider private
Referenced by get_available_forcing_outputs(), get_forcing_output_time_begin(), get_forcing_output_time_end(), get_ts_index_for_time(), get_value(), and is_property_sum_over_time_step().
The documentation for this class was generated from the following file:
include/forcing/WrappedForcingProvider.hpp