NGen: giuh::GiuhJsonReader Class Reference
giuh::GiuhJsonReader Class Reference
#include <GiuhJsonReader.h>
Public Member Functions
GiuhJsonReader (std::string data_file_path, std::string id_map_path)
std::vector< double > extract_cumulative_frequency_ordinates (ptree catchment_data_node)
Extract the ordinate values from the deserialized JSON data.
std::vector< double > extract_cumulative_frequency_ordinates (std::string catchment_id)
Extract the ordinate values, getting the appropriate JSON node via lookup.
std::string get_associated_comid (std::string catchment_id)
std::shared_ptr< giuh_kernel_impl > get_giuh_kernel_for_id (std::string catchment_id)
bool is_giuh_kernel_for_id_exists (std::string catchment_id)
bool is_data_json_file_readable ()
Get whether a file at the path represented by data_json_file_path exists and is readable.
bool is_id_map_json_file_readable ()
Get whether a file at the path represented by id_map_json_file_path exists and is readable.
Private Member Functions
std::unique_ptr< ptree > find_data_node_for_comid (std::string comid)
std::string get_mapped_comid (std::string catchment_id)
std::shared_ptr< giuh_kernel_impl > build_giuh_kernel (std::string catchment_id, std::string comid, ptree catchment_data_node)
Private Attributes
bool data_json_file_readable
Whether a file at the path represented by data_json_file_path exists and is readable.
std::string data_json_file_path
The path to the JSON file containing GIUH data, as a string.
std::unique_ptr< ptree > data_json_tree
A ptree representation of the GIUH data from the data_json_file_path file.
bool id_map_json_file_readable
Whether a file at the path represented by id_map_json_file_path exists and is readable.
std::string id_map_json_file_path
The path to the JSON file containing map of catchment ids to COMIDs, as a string.
std::unique_ptr< std::map< std::string, std::string > > id_map
A ptree representation of the id mapping data from the id_map_json_file_path file.
Constructor & Destructor Documentation
GiuhJsonReader()
giuh::GiuhJsonReader::GiuhJsonReader (std::string data_file_path, std::string id_map_path) inline
References data_json_file_path, data_json_file_readable, data_json_tree, id_map, id_map_json_file_path, and id_map_json_file_readable.
Member Function Documentation
build_giuh_kernel()
std::shared_ptr< giuh_kernel_impl > GiuhJsonReader::build_giuh_kernel (std::string catchment_id, std::string comid, ptree catchment_data_node) private
References extract_cumulative_frequency_ordinates().
Referenced by get_giuh_kernel_for_id().
extract_cumulative_frequency_ordinates() [1/2]
std::vector< double > GiuhJsonReader::extract_cumulative_frequency_ordinates (ptree catchment_data_node)
Extract the ordinate values from the deserialized JSON data.
Parameters
catchment_data_node
Returns
Referenced by build_giuh_kernel(), and extract_cumulative_frequency_ordinates().
extract_cumulative_frequency_ordinates() [2/2]
std::vector< double > GiuhJsonReader::extract_cumulative_frequency_ordinates (std::string catchment_id)
Extract the ordinate values, getting the appropriate JSON node via lookup.
Parameters
catchment_id
Returns
References extract_cumulative_frequency_ordinates(), find_data_node_for_comid(), and get_associated_comid().
find_data_node_for_comid()
std::unique_ptr< ptree > GiuhJsonReader::find_data_node_for_comid (std::string comid) private
References data_json_tree.
Referenced by extract_cumulative_frequency_ordinates(), and get_giuh_kernel_for_id().
get_associated_comid()
std::string GiuhJsonReader::get_associated_comid (std::string catchment_id)
References id_map.
Referenced by extract_cumulative_frequency_ordinates(), get_giuh_kernel_for_id(), and is_giuh_kernel_for_id_exists().
get_giuh_kernel_for_id()
std::shared_ptr< giuh_kernel_impl > GiuhJsonReader::get_giuh_kernel_for_id (std::string catchment_id)
References build_giuh_kernel(), find_data_node_for_comid(), get_associated_comid(), and is_data_json_file_readable().
get_mapped_comid()
std::string giuh::GiuhJsonReader::get_mapped_comid (std::string catchment_id) private
is_data_json_file_readable()
bool GiuhJsonReader::is_data_json_file_readable ()
Get whether a file at the path represented by data_json_file_path exists and is readable.
Returns
Whether a file at the path represented by data_json_file_path exists and is readable.
References data_json_file_readable.
Referenced by get_giuh_kernel_for_id(), and is_giuh_kernel_for_id_exists().
is_giuh_kernel_for_id_exists()
bool GiuhJsonReader::is_giuh_kernel_for_id_exists (std::string catchment_id)
References data_json_tree, get_associated_comid(), is_data_json_file_readable(), and is_id_map_json_file_readable().
is_id_map_json_file_readable()
bool GiuhJsonReader::is_id_map_json_file_readable ()
Get whether a file at the path represented by id_map_json_file_path exists and is readable.
Returns
Whether a file at the path represented by id_map_json_file_path exists and is readable.
References id_map_json_file_readable.
Referenced by is_giuh_kernel_for_id_exists().
Member Data Documentation
data_json_file_path
std::string giuh::GiuhJsonReader::data_json_file_path private
The path to the JSON file containing GIUH data, as a string.
Referenced by GiuhJsonReader().
data_json_file_readable
bool giuh::GiuhJsonReader::data_json_file_readable private
Whether a file at the path represented by data_json_file_path exists and is readable.
Referenced by GiuhJsonReader(), and is_data_json_file_readable().
data_json_tree
std::unique_ptr<ptree> giuh::GiuhJsonReader::data_json_tree private
A ptree representation of the GIUH data from the data_json_file_path file.
Referenced by GiuhJsonReader(), find_data_node_for_comid(), and is_giuh_kernel_for_id_exists().
id_map
std::unique_ptr<std::map<std::string, std::string> > giuh::GiuhJsonReader::id_map private
A ptree representation of the id mapping data from the id_map_json_file_path file.
Referenced by GiuhJsonReader(), and get_associated_comid().
id_map_json_file_path
std::string giuh::GiuhJsonReader::id_map_json_file_path private
The path to the JSON file containing map of catchment ids to COMIDs, as a string.
Referenced by GiuhJsonReader().
id_map_json_file_readable
bool giuh::GiuhJsonReader::id_map_json_file_readable private
Whether a file at the path represented by id_map_json_file_path exists and is readable.
Referenced by GiuhJsonReader(), and is_id_map_json_file_readable().
The documentation for this class was generated from the following files:
include/core/catchment/giuh/GiuhJsonReader.h
src/core/catchment/giuh/GiuhJsonReader.cpp