NGen: realization::Bmi_Cpp_Formulation Class Reference
realization::Bmi_Cpp_Formulation Class Reference
Encapsulates a bmi::Bmi model in C++ such that it can be loaded as a formulation, as such also so that it can be dynamically loaded from a shared library file.
#include <Bmi_Cpp_Formulation.hpp>
Public Types
typedef long time_step_t
Public Member Functions
Bmi_Cpp_Formulation (std::string id, std::shared_ptr< data_access::GenericDataProvider > forcing_provider, utils::StreamHandler output_stream)
std::string get_formulation_type () override
std::string get_output_header_line (std::string delimiter) override
Get a header line appropriate for a file made up of entries from this type's implementation of get_output_line_for_timestep.
std::string get_output_line_for_timestep (int timestep, std::string delimiter) override
Get a formatted line of output values for the given time step as a delimited string.
double get_response (time_step_t t_index, time_step_t t_delta) override
Get the model response for a time step.
bool is_bmi_input_variable (const std::string &var_name) override
bool is_bmi_output_variable (const std::string &var_name) override
void create_formulation (boost::property_tree::ptree &config, geojson::PropertyMap *global=nullptr) override
void create_formulation (geojson::PropertyMap properties) override
boost::span< const std::string > get_available_variable_names () override
Get the collection of forcing output property names this instance can provide.
time_t get_variable_time_begin (const std::string &variable_name)
Get the inclusive beginning of the period of time over which this instance can provide data for this forcing.
long get_data_start_time () override
Get the inclusive beginning of the period of time over which this instance can provide data for this forcing.
time_t get_variable_time_end (const std::string &varibale_name)
Get the exclusive ending of the period of time over which this instance can provide data for this forcing.
long get_data_stop_time () override
Return the last valid time for which data from the requested variable can be requested.
long record_duration () override
Return the stride in the time dimension.
const double get_model_current_time () override
Get the current time for the backing BMI model in its native format and units.
const double get_model_end_time () override
Get the end time for the backing BMI model in its native format and units.
const std::vector< std::string > & get_required_parameters () override
const std::string & get_config_mapped_variable_name (const std::string &model_var_name) override
When possible, translate a variable name for a BMI model to an internally recognized name.
size_t get_ts_index_for_time (const time_t &epoch_time) override
Get the index of the forcing time step that contains the given point in time.
std::vector< double > get_values (const CatchmentAggrDataSelector &selector, data_access::ReSampleMethod m=SUM) override
Get the 1D values of a forcing property for an arbitrary time period, converting units if needed.
double get_value (const CatchmentAggrDataSelector &selector, data_access::ReSampleMethod m) override
Get the value of a forcing property for an arbitrary time period, converting units if needed.
bool is_var_name_in_collection (const std::vector< std::string > &all_names, const std::string &var_name)
bool is_property_sum_over_time_step (const std::string &name) override
Get whether a property's per-time-step values are each an aggregate sum over the entire time step.
const std::vector< std::string > get_bmi_input_variables () override
const std::vector< std::string > get_bmi_output_variables () override
const std::string & get_bmi_main_output_var () const
std::string get_model_type_name ()
Get the name of the specific type of the backing model object.
const std::vector< std::string > & get_output_header_fields () const
Get the values making up the header line from get_output_header_line(), but organized as a vector of strings.
const std::vector< std::string > & get_output_variable_names () const
Get the names of variables in formulation output.
void set_output_precision (int precision)
Set the precision of output values when converted to text.
virtual void add_time (time_t t, double n)
std::string get_id () const
void set_output_stream (std::string file_path)
void write_output (std::string out)
Static Public Member Functions
static void config_pattern_substitution (geojson::PropertyMap &properties, const std::string &key, const std::string &pattern, const std::string &replacement)
Perform in-place substitution on the given config property item, if the item and the pattern are present.
Protected Member Functions
std::shared_ptr< models::bmi::Bmi_Cpp_Adapter > construct_model (const geojson::PropertyMap &properties) override
Construct model and its shared pointer.
time_t convert_model_time (const double &model_time) override
Convert a time value from the model to an epoch time in seconds.
template<class T , class O >
T get_var_value_as (time_step_t t_index, const std::string &var_name)
double get_var_value_as_double (const std::string &var_name) override
Get value for some BMI model variable.
double get_var_value_as_double (const int &index, const std::string &var_name) override
Get value for some BMI model variable at a specific index.
bool is_model_initialized () override
Test whether the backing model object has been initialize using the BMI standard Initialize function.
void get_bmi_output_var_name (const std::string &name, std::string &bmi_var_name)
Get correct BMI variable name, which may be the output or something mapped to this output.
void determine_model_time_offset ()
Determine and set the offset time of the model in seconds, compared to forcing data.
const bool & get_allow_model_exceed_end_time () const override
Get whether a model may perform updates beyond its end_time.
const std::string & get_bmi_init_config () const
std::shared_ptr< models::bmi::Bmi_Cpp_Adapter > get_bmi_model ()
Get the backing model object implementing the BMI.
const std::string & get_forcing_file_path () const override
const time_t & get_bmi_model_start_time_forcing_offset_s () override
void inner_create_formulation (geojson::PropertyMap properties, bool needs_param_validation)
Universal logic applied when creating a BMI-backed formulation from NGen config.
void set_initial_bmi_parameters (geojson::PropertyMap properties)
Check configuration properties for model_params and attempt to set them in the bmi model.
bool is_bmi_model_time_step_fixed () override
Test whether backing model has fixed time step size.
bool is_bmi_using_forcing_file () const override
Whether the backing model uses/reads the forcing file directly for getting input data.
void set_allow_model_exceed_end_time (bool allow_exceed_end)
void set_bmi_init_config (const std::string &init_config)
void set_bmi_model (std::shared_ptr< models::bmi::Bmi_Cpp_Adapter > model)
Set the backing model object implementing the BMI.
void set_bmi_model_start_time_forcing_offset_s (const time_t &offset_s)
void set_bmi_model_time_step_fixed (bool is_fix_time_step)
void set_bmi_using_forcing_file (bool uses_forcing_file)
Set whether the backing model uses/reads the forcing file directly for getting input data.
void set_forcing_file_path (const std::string &forcing_path)
virtual void set_model_initialized (bool is_initialized)
Set whether the backing model object has been initialize using the BMI standard Initialize function.
std::shared_ptr< T > as_c_array (Iterator begin, Iterator end)
Template function for copying iterator range into contiguous array.
std::shared_ptr< void > get_values_as_type (std::string type, Iterator begin, Iterator end)
Gets values in iterator range, casted based on type then returned as typeless (void) pointer.
std::shared_ptr< void > get_value_as_type (std::string type, T value)
void set_model_inputs_prior_to_update (const double &model_init_time, time_step_t t_delta)
Set BMI input variable values for the model appropriately prior to calling its BMIupdate()``.
int get_output_precision ()
void set_bmi_main_output_var (const std::string &main_output_var)
virtual void set_model_type_name (std::string type_name)
Set the name of the specific type of the backing model object.
void set_output_header_fields (const std::vector< std::string > &output_headers)
void set_output_variable_names (const std::vector< std::string > &out_var_names)
Set the names of variables in formulation output.
std::string get_catchment_id () override
void set_catchment_id (std::string cat_id) override
virtual geojson::PropertyMap interpret_parameters (boost::property_tree::ptree &config, geojson::PropertyMap *global=nullptr)
virtual void validate_parameters (geojson::PropertyMap options)
Protected Attributes
time_step_t last_model_response_delta
The delta of the last model update execution (typically, this is time step size).
time_t last_model_response_start_time
The epoch time of the model at the beginning of its last update.
std::map< std::string, std::shared_ptr< data_access::GenericDataProvider > > input_forcing_providers
std::shared_ptr< std::ostringstream > output_text_stream
Object to help with converting numeric output values to text.
std::string id
polygon_t bounds
utils::StreamHandler output
shared_ptr< HY_Catchment > realized_catchment
unsigned long id_number
std::shared_ptr< data_access::GenericDataProvider > forcing
Private Attributes
int next_time_step_index = 0
bool allow_model_exceed_end_time
Whether model Update calls are allowed and handled in some way by the backing model for time steps after the model's end_time.
std::vector< std::string > available_forcings
The set of available "forcings" (output variables, plus their mapped aliases) that the model can provide.
std::string bmi_init_config
std::shared_ptr< models::bmi::Bmi_Cpp_Adapter > bmi_model
bool bmi_model_time_step_fixed
Whether backing model has fixed time step size.
time_t bmi_model_start_time_forcing_offset_s
The offset, converted to seconds, from the model's start time to the start time of the initial forcing time step.
std::map< std::string, std::string > bmi_var_names_map
A configured mapping of BMI model variable names to standard names for use inside the framework.
bool bmi_using_forcing_file
Whether the backing model uses/reads the forcing file directly for getting input data.
std::string forcing_file_path
bool model_initialized
std::vector< std::string > OPTIONAL_PARAMETERS
std::vector< std::string > REQUIRED_PARAMETERS
std::string bmi_main_output_var
std::string model_type_name
std::vector< std::string > output_header_fields
Output header field strings corresponding to the variables output by the realization, as defined in output_variable_names.
std::vector< std::string > output_variable_names
Names of the variables to include in the output from this formulation, which will be some ordered subset of the BMI module output variables accessible to the instance.
int output_precision
The degree of precision in output values when converting to text.
std::string cat_id
Friends
class Bmi_Multi_Formulation
class ::Bmi_Formulation_Test
class ::Bmi_Cpp_Formulation_Test
Detailed Description
Encapsulates a bmi::Bmi model in C++ such that it can be loaded as a formulation, as such also so that it can be dynamically loaded from a shared library file.
Member Typedef Documentation
time_step_t
typedef long realization::Formulation::time_step_t inherited
Constructor & Destructor Documentation
Bmi_Cpp_Formulation()
Bmi_Cpp_Formulation::Bmi_Cpp_Formulation (std::string id, std::shared_ptr< data_access::GenericDataProvider > forcing_provider, utils::StreamHandler output_stream)
Member Function Documentation
add_time()
virtual void realization::Formulation::add_time (time_t t, double n) inline virtual inherited
as_c_array()
std::shared_ptr< T > realization::Bmi_Module_Formulation< models::bmi::Bmi_Cpp_Adapter >::as_c_array (Iterator begin, Iterator end) inline protected inherited
Template function for copying iterator range into contiguous array.
This function will iterate the range and cast the iterator value to type T and copy that value into a C-like array of contiguous, dynamically allocated memory. This array is stored in a smart pointer with a custom array deleter.
Template Parameters
T
Iterator
Parameters
begin
end
Returns
std::shared_ptr<T>
config_pattern_substitution()
static void realization::Catchment_Formulation::config_pattern_substitution (geojson::PropertyMap & properties, const std::string & key, const std::string & pattern, const std::string & replacement) inline static inherited
Perform in-place substitution on the given config property item, if the item and the pattern are present.
Any and all instances of the substring pattern are replaced by replacement, if key maps to a present string-type property value.
Parameters
properties A reference to the properties config object to be altered.
key The key for the configuration property to potentially adjust.
pattern The pattern substring to search for that, when present, should be replaced.
replacement The replacement substring to potentially insert.
References geojson::String.
Referenced by realization::Formulation_Manager::construct_missing_formulation(), and realization::Bmi_Multi_Formulation::init_nested_module().
construct_model()
std::shared_ptr< Bmi_Cpp_Adapter > Bmi_Cpp_Formulation::construct_model (const geojson::PropertyMap & properties) override protected virtual
Construct model and its shared pointer.
Parameters
properties Configuration properties for the formulation.
Returns
A shared pointer to a newly constructed model adapter object.
Implements realization::Bmi_Module_Formulation< models::bmi::Bmi_Cpp_Adapter >.
References realization::Bmi_Module_Formulation< models::bmi::Bmi_Cpp_Adapter >::get_allow_model_exceed_end_time(), realization::Bmi_Module_Formulation< models::bmi::Bmi_Cpp_Adapter >::get_bmi_init_config(), realization::Bmi_Module_Formulation< models::bmi::Bmi_Cpp_Adapter >::get_forcing_file_path(), realization::Bmi_Formulation::get_model_type_name(), realization::Bmi_Module_Formulation< models::bmi::Bmi_Cpp_Adapter >::is_bmi_model_time_step_fixed(), realization::Bmi_Module_Formulation< models::bmi::Bmi_Cpp_Adapter >::is_bmi_using_forcing_file(), and HY_CatchmentArea::output.
convert_model_time()
time_t realization::Bmi_Cpp_Formulation::convert_model_time (const double & model_time) inline override protected virtual
Convert a time value from the model to an epoch time in seconds.
Model time values are typically (though not always) 0-based totals count upward as time progresses. The units are not necessarily seconds. This performs the necessary lookup and conversion for such units, and then shifts the value appropriately for epoch time representation.
Parameters
model_time
Returns
Implements realization::Bmi_Formulation.
References realization::Bmi_Module_Formulation< models::bmi::Bmi_Cpp_Adapter >::get_bmi_model().
create_formulation() [1/2]
void realization::Bmi_Module_Formulation< models::bmi::Bmi_Cpp_Adapter >::create_formulation (boost::property_tree::ptree & config, geojson::PropertyMap * global = nullptr) inline override virtual inherited
Implements realization::Catchment_Formulation.
create_formulation() [2/2]
void realization::Bmi_Module_Formulation< models::bmi::Bmi_Cpp_Adapter >::create_formulation (geojson::PropertyMap properties) inline override virtual inherited
Implements realization::Catchment_Formulation.
determine_model_time_offset()
void realization::Bmi_Module_Formulation< models::bmi::Bmi_Cpp_Adapter >::determine_model_time_offset () inline protected inherited
Determine and set the offset time of the model in seconds, compared to forcing data.
BMI models frequently have their model start time be set to 0. As such, to know what the forcing time is compared to the model time, an offset value is needed. This becomes important in situations when the size of the time steps for forcing data versus model execution are not equal. This method will determine and set this value.
get_allow_model_exceed_end_time()
const bool & realization::Bmi_Module_Formulation< models::bmi::Bmi_Cpp_Adapter >::get_allow_model_exceed_end_time () const inline override protected virtual inherited
Get whether a model may perform updates beyond its end_time.
Get whether model Update calls are allowed and handled in some way by the backing model for time steps after the model's end_time. Implementations of this type should use this function to safeguard against entering either an invalid or otherwise undesired state as a result of attempting to process a model beyond its available data.
As mentioned, even for models that are capable of validly handling processing beyond end time, it may be desired that they do not for some reason (e.g., the way they account for the lack of input data leads to valid but incorrect results for a specific application). Because of this, whether models are allowed to process beyond their end time is configuration-based.
Returns
Whether a model may perform updates beyond its end_time.
Implements realization::Bmi_Formulation.
get_available_variable_names()
boost::span< const std::string > realization::Bmi_Module_Formulation< models::bmi::Bmi_Cpp_Adapter >::get_available_variable_names () inline override virtual inherited
Get the collection of forcing output property names this instance can provide.
This is part of the ForcingProvider interface. This interface must be implemented for items of this type to be usable as "forcing" providers for situations when some other object needs to receive as an input (i.e., one of its forcings) a data property output from this object.
For this type, this is the collection of BMI output variables, plus any aliases included in the formulation config's output variable mapping.
Returns
The collection of forcing output property names this instance can provide.
See also
ForcingProvider
Implements data_access::DataProvider< double, CatchmentAggrDataSelector >.
get_bmi_init_config()
const std::string & realization::Bmi_Module_Formulation< models::bmi::Bmi_Cpp_Adapter >::get_bmi_init_config () const inline protected inherited
get_bmi_input_variables()
const std::vector< std::string > realization::Bmi_Module_Formulation< models::bmi::Bmi_Cpp_Adapter >::get_bmi_input_variables () inline override virtual inherited
Implements realization::Bmi_Formulation.
get_bmi_main_output_var()
const std::string & realization::Bmi_Formulation::get_bmi_main_output_var () const inline inherited
References realization::Bmi_Formulation::bmi_main_output_var.
Referenced by realization::Bmi_C_Formulation::get_response(), get_response(), and realization::Bmi_Multi_Formulation::get_response().
get_bmi_model()
std::shared_ptr< models::bmi::Bmi_Cpp_Adapter > realization::Bmi_Module_Formulation< models::bmi::Bmi_Cpp_Adapter >::get_bmi_model () inline protected inherited
Get the backing model object implementing the BMI.
Returns
Shared pointer to the backing model object that implements the BMI.
get_bmi_model_start_time_forcing_offset_s()
const time_t & realization::Bmi_Module_Formulation< models::bmi::Bmi_Cpp_Adapter >::get_bmi_model_start_time_forcing_offset_s () inline override protected virtual inherited
Implements realization::Bmi_Formulation.
get_bmi_output_var_name()
void realization::Bmi_Module_Formulation< models::bmi::Bmi_Cpp_Adapter >::get_bmi_output_var_name (const std::string & name, std::string & bmi_var_name) inline protected inherited
Get correct BMI variable name, which may be the output or something mapped to this output.
Parameters
name
bmi_var_name
get_bmi_output_variables()
const std::vector< std::string > realization::Bmi_Module_Formulation< models::bmi::Bmi_Cpp_Adapter >::get_bmi_output_variables () inline override virtual inherited
Implements realization::Bmi_Formulation.
get_catchment_id()
std::string realization::Catchment_Formulation::get_catchment_id () inline override protected virtual inherited
Implements HY_CatchmentRealization.
References realization::Catchment_Formulation::cat_id.
Referenced by realization::Bmi_Multi_Formulation::create_multi_formulation(), realization::Bmi_Multi_Formulation::get_value(), realization::Bmi_Multi_Formulation::get_values(), realization::Bmi_Multi_Formulation::get_var_value_as_double(), and realization::Bmi_Module_Formulation< M >::set_model_inputs_prior_to_update().
get_config_mapped_variable_name()
const std::string & realization::Bmi_Module_Formulation< models::bmi::Bmi_Cpp_Adapter >::get_config_mapped_variable_name (const std::string & model_var_name) inline override virtual inherited
When possible, translate a variable name for a BMI model to an internally recognized name.
Translate some BMI variable name to something recognized in some internal context for use within NGen. Do this according to the map of variable names supplied in the external formulation config. If no mapping for the given variable name was configured, return the variable name itself.
For example, perhaps a BMI model has the input variable "RAIN_RATE." Configuring this variable name to map to "precip_rate" will allow the formulation to understand that this particular forcing field should be used to set the model's "RAIN_RATE" variable.
Parameters
model_var_name The BMI variable name to translate so its purpose is recognized internally.
Returns
Either the internal equivalent variable name, or the provided name if there is not a mapping entry.
Implements realization::Bmi_Formulation.
get_data_start_time()
long realization::Bmi_Module_Formulation< models::bmi::Bmi_Cpp_Adapter >::get_data_start_time () inline override virtual inherited
Get the inclusive beginning of the period of time over which this instance can provide data for this forcing.
This is part of the DataProvider interface. This interface must be implemented for items of this type to be usable as "forcing" providers for situations when some other object needs to receive as an input (i.e., one of its forcings) a data property output from this object.
Returns
The inclusive beginning of the period of time over which this instance can provide this data.
Implements data_access::DataProvider< double, CatchmentAggrDataSelector >.
get_data_stop_time()
long realization::Bmi_Module_Formulation< models::bmi::Bmi_Cpp_Adapter >::get_data_stop_time () inline override virtual inherited
Return the last valid time for which data from the requested variable can be requested.
Implements data_access::DataProvider< double, CatchmentAggrDataSelector >.
get_forcing_file_path()
const std::string & realization::Bmi_Module_Formulation< models::bmi::Bmi_Cpp_Adapter >::get_forcing_file_path () const inline override protected virtual inherited
Implements realization::Bmi_Formulation.
get_formulation_type()
std::string Bmi_Cpp_Formulation::get_formulation_type () override virtual
Implements realization::Formulation.
get_id()
std::string realization::Formulation::get_id () const inline inherited
References realization::Formulation::id.
get_model_current_time()
const double realization::Bmi_Module_Formulation< models::bmi::Bmi_Cpp_Adapter >::get_model_current_time () inline override virtual inherited
Get the current time for the backing BMI model in its native format and units.
Returns
The current time for the backing BMI model in its native format and units.
Implements realization::Bmi_Formulation.
get_model_end_time()
const double realization::Bmi_Module_Formulation< models::bmi::Bmi_Cpp_Adapter >::get_model_end_time () inline override virtual inherited
Get the end time for the backing BMI model in its native format and units.
Returns
The end time for the backing BMI model in its native format and units.
Implements realization::Bmi_Formulation.
get_model_type_name()
std::string realization::Bmi_Formulation::get_model_type_name () inline inherited
Get the name of the specific type of the backing model object.
Returns
The name of the backing model object's type.
References realization::Bmi_Formulation::model_type_name.
Referenced by realization::Bmi_C_Formulation::construct_model(), construct_model(), realization::Bmi_Module_Formulation< M >::get_value_as_type(), realization::Bmi_Module_Formulation< M >::get_values_as_type(), realization::Bmi_C_Formulation::get_var_value_as_double(), and get_var_value_as_double().
get_output_header_fields()
const std::vector< std::string > & realization::Bmi_Formulation::get_output_header_fields () const inline inherited
Get the values making up the header line from get_output_header_line(), but organized as a vector of strings.
Returns
The values making up the header line from get_output_header_line() organized as a vector.
References realization::Bmi_Formulation::output_header_fields.
Referenced by realization::Bmi_C_Formulation::get_output_header_line(), get_output_header_line(), and realization::Bmi_Formulation::get_output_header_line().
get_output_header_line()
std::string Bmi_Cpp_Formulation::get_output_header_line (std::string delimiter) override virtual
Get a header line appropriate for a file made up of entries from this type's implementation of get_output_line_for_timestep.
Note that like the output generating function, this line does not include anything for time step.
Returns
An appropriate header line for this type.
Implements realization::Formulation.
References realization::Bmi_Formulation::get_output_header_fields().
get_output_line_for_timestep()
std::string Bmi_Cpp_Formulation::get_output_line_for_timestep (int timestep, std::string delimiter) override virtual
Get a formatted line of output values for the given time step as a delimited string.
This method is useful for preparing calculated data in a representation useful for output files, such as CSV files.
The resulting string will contain calculated values for applicable output variables for the particular formulation, as determined for the given time step. However, the string will not contain any representation of the time step itself.
An empty string is returned if the time step value is not in the range of valid time steps for which there are calculated values for all variables.
Parameters
timestep The time step for which data is desired.
delimiter The value delimiter for the string.
Returns
A delimited string with all the output variable values for the given time step.
Implements realization::Formulation.
References realization::Bmi_Formulation::get_output_variable_names(), get_var_value_as_double(), and next_time_step_index.
get_output_precision()
int realization::Bmi_Formulation::get_output_precision () inline protected inherited
References realization::Bmi_Formulation::output_precision.
get_output_variable_names()
const std::vector< std::string > & realization::Bmi_Formulation::get_output_variable_names () const inline inherited
Get the names of variables in formulation output.
Get the names of the variables to include in the output from this formulation, which should be some ordered subset of the BMI module output variables accessible to this instance.
Returns
References realization::Bmi_Formulation::output_variable_names.
Referenced by realization::Bmi_Multi_Formulation::check_output_var_names(), realization::Bmi_Multi_Formulation::create_multi_formulation(), realization::Bmi_C_Formulation::get_output_line_for_timestep(), get_output_line_for_timestep(), realization::Bmi_Multi_Formulation::get_output_line_for_timestep(), and realization::Bmi_Module_Formulation< M >::inner_create_formulation().
get_required_parameters()
const std::vector< std::string > & realization::Bmi_Module_Formulation< models::bmi::Bmi_Cpp_Adapter >::get_required_parameters () inline override virtual inherited
Implements realization::Catchment_Formulation.
get_response()
double Bmi_Cpp_Formulation::get_response (time_step_t t_index, time_step_t t_delta) override virtual
Get the model response for a time step.
Get the model response for the provided time step, executing the backing model formulation one or more times as needed.
Function assumes the backing model has been fully initialized and that any additional input values have been applied.
The function throws an error if the index of a previously processed time step is supplied, except if it is the last processed time step. In that case, the appropriate value is returned as described below, but without executing any model update.
Assuming updating to the implied time is valid for the model, the function executes one or more model updates to process future time steps for the necessary indexes. Multiple time steps updates occur when the given future time step index is not the next time step index to be processed. Regardless, all processed time steps have the size supplied in t_delta.
However, it is possible to provide t_index and t_delta values that would result in the aggregate updates taking the model's time beyond its end_time value. In such cases, if the formulation config indicates this model is not allow to exceed its set end_time, the function does not update the model and throws an error.
The function will return the value of the primary output variable (see get_bmi_main_output_var()) for the given time step after the model has been updated to that point. The type returned will always be a double, with other numeric types being cast if necessary.
The BMI spec requires for variable values to be passed to/from models via as arrays. This function essentially treats the variable array reference as if it were just a raw pointer and returns the 0-th array value.
Parameters
t_index The index of the time step for which to run model calculations.
d_delta_s The duration, in seconds, of the time step for which to run model calculations.
Returns
The total discharge of the model for the given time step.
Implements realization::Catchment_Formulation.
References realization::Bmi_Module_Formulation< models::bmi::Bmi_Cpp_Adapter >::get_allow_model_exceed_end_time(), realization::Bmi_Formulation::get_bmi_main_output_var(), realization::Bmi_Module_Formulation< models::bmi::Bmi_Cpp_Adapter >::get_bmi_model(), get_var_value_as_double(), next_time_step_index, and realization::Bmi_Module_Formulation< models::bmi::Bmi_Cpp_Adapter >::set_model_inputs_prior_to_update().
get_ts_index_for_time()
size_t realization::Bmi_Module_Formulation< models::bmi::Bmi_Cpp_Adapter >::get_ts_index_for_time (const time_t & epoch_time) inline override virtual inherited
Get the index of the forcing time step that contains the given point in time.
This is part of the ForcingProvider interface. This interface must be implemented for items of this type to be usable as "forcing" providers for situations when some other object needs to receive as an input (i.e., one of its forcings) a data property output from this object.
An std::out_of_range exception should be thrown if the time is not in any time step.
Parameters
epoch_time The point in time, as a seconds-based epoch time.
Returns
The index of the forcing time step that contains the given point in time.
Exceptions
std::out_of_range If the given point is not in any time step.
Implements data_access::DataProvider< double, CatchmentAggrDataSelector >.
get_value()
double realization::Bmi_Module_Formulation< models::bmi::Bmi_Cpp_Adapter >::get_value (const CatchmentAggrDataSelector & selector, data_access::ReSampleMethod m) inline override virtual inherited
Get the value of a forcing property for an arbitrary time period, converting units if needed.
This is part of the ForcingProvider interface. This interface must be implemented for items of this type to be usable as "forcing" providers for situations when some other object needs to receive as an input (i.e., one of its forcings) a data property output from this object.
An std::out_of_range exception should be thrown if the data for the time period is not available.
Parameters
output_name The name of the forcing property of interest.
init_time_epoch The epoch time (in seconds) of the start of the time period.
duration_seconds The length of the time period, in seconds.
output_units The expected units of the desired output value.
Returns
The value of the forcing property for the described time period, with units converted if needed.
Exceptions
std::out_of_range If data for the time period is not available.
See also
ForcingProvider::get_value
Implements data_access::DataProvider< double, CatchmentAggrDataSelector >.
get_value_as_type()
std::shared_ptr< void > realization::Bmi_Module_Formulation< models::bmi::Bmi_Cpp_Adapter >::get_value_as_type (std::string type, T value) inline protected inherited
get_values()
std::vector< double > realization::Bmi_Module_Formulation< models::bmi::Bmi_Cpp_Adapter >::get_values (const CatchmentAggrDataSelector & selector, data_access::ReSampleMethod m = SUM) inline override virtual inherited
Get the 1D values of a forcing property for an arbitrary time period, converting units if needed.
Parameters
output_name The name of the forcing property of interest.
init_time The epoch time (in seconds) of the start of the time period.
duration_s The length of the time period, in seconds.
output_units The expected units of the desired output value.
Returns
std::vector<double> The 1D values of the forcing property for the described time period, with units converted if needed.
Exceptions
std::out_of_range If data for the time period is not available.
std::runtime_error output_name is not one of the available outputs of this provider instance.
Implements data_access::DataProvider< double, CatchmentAggrDataSelector >.
get_values_as_type()
std::shared_ptr< void > realization::Bmi_Module_Formulation< models::bmi::Bmi_Cpp_Adapter >::get_values_as_type (std::string type, Iterator begin, Iterator end) inline protected inherited
Gets values in iterator range, casted based on type then returned as typeless (void) pointer.
Template Parameters
Iterator
Parameters
type
begin
end
Returns
std::shared_ptr<void>
get_var_value_as()
template<class T , class O > T realization::Bmi_Cpp_Formulation::get_var_value_as (time_step_t t_index, const std::string & var_name) inline protected
References realization::Bmi_Module_Formulation< models::bmi::Bmi_Cpp_Adapter >::get_bmi_model().
get_var_value_as_double() [1/2]
double Bmi_Cpp_Formulation::get_var_value_as_double (const int & index, const std::string & var_name) override protected virtual
Get value for some BMI model variable at a specific index.
Function gets the value for a provided variable, returned from the backing model as an array, and returns the specific value at the desired index cast as a double type.
The function makes several assumptions:
1. `index` is within array bounds
2. `var_name` is in the set of valid variable names for the model
3. the type for output variable allows the value to be cast to a `double` appropriately
It falls to user (functions) of this function to ensure these assumptions hold before invoking.
Parameters
index
var_name
Returns
Implements realization::Bmi_Formulation.
References realization::Bmi_Module_Formulation< models::bmi::Bmi_Cpp_Adapter >::get_bmi_model(), and realization::Bmi_Formulation::get_model_type_name().
get_var_value_as_double() [2/2]
double Bmi_Cpp_Formulation::get_var_value_as_double (const std::string & var_name) override protected virtual
Get value for some BMI model variable.
This function assumes that the given variable, while returned by the model within an array per the BMI spec, is actually a single, scalar value. Thus, it returns what is at index 0 of the array reference.
Parameters
index
var_name
Returns
Implements realization::Bmi_Formulation.
References get_var_value_as_double().
Referenced by get_output_line_for_timestep(), get_response(), and get_var_value_as_double().
get_variable_time_begin()
time_t realization::Bmi_Module_Formulation< models::bmi::Bmi_Cpp_Adapter >::get_variable_time_begin (const std::string & variable_name) inline inherited
Get the inclusive beginning of the period of time over which this instance can provide data for this forcing.
This is part of the ForcingProvider interface. This interface must be implemented for items of this type to be usable as "forcing" providers for situations when some other object needs to receive as an input (i.e., one of its forcings) a data property output from this object.
Returns
The inclusive beginning of the period of time over which this instance can provide this data.
get_variable_time_end()
time_t realization::Bmi_Module_Formulation< models::bmi::Bmi_Cpp_Adapter >::get_variable_time_end (const std::string & varibale_name) inline inherited
Get the exclusive ending of the period of time over which this instance can provide data for this forcing.
This is part of the ForcingProvider interface. This interface must be implemented for items of this type to be usable as "forcing" providers for situations when some other object needs to receive as an input (i.e., one of its forcings) a data property output from this object.
Returns
The exclusive ending of the period of time over which this instance can provide this data.
inner_create_formulation()
void realization::Bmi_Module_Formulation< models::bmi::Bmi_Cpp_Adapter >::inner_create_formulation (geojson::PropertyMap properties, bool needs_param_validation) inline protected inherited
Universal logic applied when creating a BMI-backed formulation from NGen config.
This performs all the necessary steps to initialize this formulation from provided configuration properties. It is written in such a way that it can be used in appropriately crafted nested calls from both public create_formulation implementations, thus allowing the primary formulation initialization logic to be centralized and not duplicated.
Parameters
properties
needs_param_validation
interpret_parameters()
virtual geojson::PropertyMap realization::Formulation::interpret_parameters (boost::property_tree::ptree & config, geojson::PropertyMap * global = nullptr) inline protected virtual inherited
References realization::Formulation::validate_parameters().
Referenced by realization::Bmi_Module_Formulation< M >::create_formulation(), and realization::Bmi_Multi_Formulation::create_formulation().
is_bmi_input_variable()
bool Bmi_Cpp_Formulation::is_bmi_input_variable (const std::string & var_name) override virtual
Reimplemented from realization::Bmi_Module_Formulation< models::bmi::Bmi_Cpp_Adapter >.
References realization::Bmi_Module_Formulation< models::bmi::Bmi_Cpp_Adapter >::get_bmi_model().
is_bmi_model_time_step_fixed()
bool realization::Bmi_Module_Formulation< models::bmi::Bmi_Cpp_Adapter >::is_bmi_model_time_step_fixed () inline override protected virtual inherited
Test whether backing model has fixed time step size.
Returns
Whether backing model has fixed time step size.
Implements realization::Bmi_Formulation.
is_bmi_output_variable()
bool Bmi_Cpp_Formulation::is_bmi_output_variable (const std::string & var_name) override virtual
Reimplemented from realization::Bmi_Module_Formulation< models::bmi::Bmi_Cpp_Adapter >.
References realization::Bmi_Module_Formulation< models::bmi::Bmi_Cpp_Adapter >::get_bmi_model().
is_bmi_using_forcing_file()
bool realization::Bmi_Module_Formulation< models::bmi::Bmi_Cpp_Adapter >::is_bmi_using_forcing_file () const inline override protected virtual inherited
Whether the backing model uses/reads the forcing file directly for getting input data.
Returns
Whether the backing model uses/reads the forcing file directly for getting input data.
Implements realization::Bmi_Formulation.
is_model_initialized()
bool Bmi_Cpp_Formulation::is_model_initialized () override protected virtual
Test whether the backing model object has been initialize using the BMI standard Initialize function.
Returns
Whether backing model object has been initialize using the BMI standard Initialize function.
Reimplemented from realization::Bmi_Module_Formulation< models::bmi::Bmi_Cpp_Adapter >.
References realization::Bmi_Module_Formulation< models::bmi::Bmi_Cpp_Adapter >::get_bmi_model().
is_property_sum_over_time_step()
bool realization::Bmi_Module_Formulation< models::bmi::Bmi_Cpp_Adapter >::is_property_sum_over_time_step (const std::string & name) inline override virtual inherited
Get whether a property's per-time-step values are each an aggregate sum over the entire time step.
This is part of the ForcingProvider interface. This interface must be implemented for items of this type to be usable as "forcing" providers for situations when some other object needs to receive as an input (i.e., one of its forcings) a data property output from this object.
Certain properties, like rain fall, are aggregated sums over an entire time step. Others, such as pressure, are not such sums and instead something else like an instantaneous reading or an average value.
It may be the case that forcing data is needed for some discretization different than the forcing time step. This aspect must be known in such cases to perform the appropriate value interpolation.
For instances of this type, all output forcings fall under this category.
Parameters
name The name of the forcing property for which the current value is desired.
Returns
Whether the property's value is an aggregate sum, which is always true for this type.
Reimplemented from data_access::DataProvider< double, CatchmentAggrDataSelector >.
is_var_name_in_collection()
bool realization::Bmi_Module_Formulation< models::bmi::Bmi_Cpp_Adapter >::is_var_name_in_collection (const std::vector< std::string > & all_names, const std::string & var_name) inline inherited
record_duration()
long realization::Bmi_Module_Formulation< models::bmi::Bmi_Cpp_Adapter >::record_duration () inline override virtual inherited
Return the stride in the time dimension.
Implements data_access::DataProvider< double, CatchmentAggrDataSelector >.
set_allow_model_exceed_end_time()
void realization::Bmi_Module_Formulation< models::bmi::Bmi_Cpp_Adapter >::set_allow_model_exceed_end_time (bool allow_exceed_end) inline protected inherited
set_bmi_init_config()
void realization::Bmi_Module_Formulation< models::bmi::Bmi_Cpp_Adapter >::set_bmi_init_config (const std::string & init_config) inline protected inherited
set_bmi_main_output_var()
void realization::Bmi_Formulation::set_bmi_main_output_var (const std::string & main_output_var) inline protected inherited
References realization::Bmi_Formulation::bmi_main_output_var.
Referenced by realization::Bmi_Multi_Formulation::create_multi_formulation(), and realization::Bmi_Module_Formulation< M >::inner_create_formulation().
set_bmi_model()
void realization::Bmi_Module_Formulation< models::bmi::Bmi_Cpp_Adapter >::set_bmi_model (std::shared_ptr< models::bmi::Bmi_Cpp_Adapter > model) inline protected inherited
Set the backing model object implementing the BMI.
Parameters
model Shared pointer to the BMI model.
set_bmi_model_start_time_forcing_offset_s()
void realization::Bmi_Module_Formulation< models::bmi::Bmi_Cpp_Adapter >::set_bmi_model_start_time_forcing_offset_s (const time_t & offset_s) inline protected inherited
set_bmi_model_time_step_fixed()
void realization::Bmi_Module_Formulation< models::bmi::Bmi_Cpp_Adapter >::set_bmi_model_time_step_fixed (bool is_fix_time_step) inline protected inherited
set_bmi_using_forcing_file()
void realization::Bmi_Module_Formulation< models::bmi::Bmi_Cpp_Adapter >::set_bmi_using_forcing_file (bool uses_forcing_file) inline protected inherited
Set whether the backing model uses/reads the forcing file directly for getting input data.
Parameters
uses_forcing_file Whether the backing model uses/reads forcing file directly for getting input data.
set_catchment_id()
void realization::Catchment_Formulation::set_catchment_id (std::string cat_id) inline override protected virtual inherited
Implements HY_CatchmentRealization.
References realization::Catchment_Formulation::cat_id.
Referenced by realization::Catchment_Formulation::Catchment_Formulation(), and realization::Catchment_Formulation::Catchment_Formulation().
set_forcing_file_path()
void realization::Bmi_Module_Formulation< models::bmi::Bmi_Cpp_Adapter >::set_forcing_file_path (const std::string & forcing_path) inline protected inherited
set_initial_bmi_parameters()
void realization::Bmi_Module_Formulation< models::bmi::Bmi_Cpp_Adapter >::set_initial_bmi_parameters (geojson::PropertyMap properties) inline protected inherited
Check configuration properties for model_params and attempt to set them in the bmi model.
This checks for a key named model_params in the parsed properties, and for each property it will attempt to call SetValue using the property's key as the BMI variable and the property's value as the value to set.
This function should only be called once bmi_model is properly constructed. If bmi_model is a nullptr, this function becomes a no-op.
set_model_initialized()
virtual void realization::Bmi_Module_Formulation< models::bmi::Bmi_Cpp_Adapter >::set_model_initialized (bool is_initialized) inline protected virtual inherited
Set whether the backing model object has been initialize using the BMI standard Initialize function.
Parameters
is_initialized Whether model object has been initialize using the BMI standard Initialize.
set_model_inputs_prior_to_update()
void realization::Bmi_Module_Formulation< models::bmi::Bmi_Cpp_Adapter >::set_model_inputs_prior_to_update (const double & model_init_time, time_step_t t_delta) inline protected inherited
Set BMI input variable values for the model appropriately prior to calling its BMIupdate()``.
Parameters
model_initial_time The model's time prior to the update, in its internal units and representation.
t_delta The size of the time step over which the formulation is going to update the model, which might be different than the model's internal time step.
set_model_type_name()
virtual void realization::Bmi_Formulation::set_model_type_name (std::string type_name) inline protected virtual inherited
Set the name of the specific type of the backing model object.
Parameters
type_name The name of the backing model object's type.
References realization::Bmi_Formulation::model_type_name.
Referenced by realization::Bmi_Multi_Formulation::create_multi_formulation(), and realization::Bmi_Module_Formulation< M >::inner_create_formulation().
set_output_header_fields()
void realization::Bmi_Formulation::set_output_header_fields (const std::vector< std::string > & output_headers) inline protected inherited
References realization::Bmi_Formulation::output_header_fields.
Referenced by realization::Bmi_Multi_Formulation::create_multi_formulation(), and realization::Bmi_Module_Formulation< M >::inner_create_formulation().
set_output_precision()
void realization::Bmi_Formulation::set_output_precision (int precision) inline inherited
Set the precision of output values when converted to text.
Parameters
precision The desired precision, as a number of decimal places.
References realization::Bmi_Formulation::output_precision, and realization::Bmi_Formulation::output_text_stream.
Referenced by realization::Bmi_Formulation::Bmi_Formulation(), realization::Bmi_Multi_Formulation::create_multi_formulation(), and realization::Bmi_Module_Formulation< M >::inner_create_formulation().
set_output_stream()
void HY_CatchmentArea::set_output_stream (std::string file_path) inline inherited
References HY_CatchmentArea::output.
set_output_variable_names()
void realization::Bmi_Formulation::set_output_variable_names (const std::vector< std::string > & out_var_names) inline protected inherited
Set the names of variables in formulation output.
Set the names of the variables to include in the output from this formulation, which should be some ordered subset of the output variables from the model.
Parameters
out_var_names the names of variables in formulation output, in the order they should appear.
References realization::Bmi_Formulation::output_variable_names.
Referenced by realization::Bmi_Multi_Formulation::create_multi_formulation(), and realization::Bmi_Module_Formulation< M >::inner_create_formulation().
validate_parameters()
virtual void realization::Formulation::validate_parameters (geojson::PropertyMap options) inline protected virtual inherited
References realization::Formulation::get_formulation_type(), and realization::Formulation::get_required_parameters().
Referenced by realization::Bmi_Multi_Formulation::create_multi_formulation(), realization::Bmi_Module_Formulation< M >::inner_create_formulation(), and realization::Formulation::interpret_parameters().
write_output()
void HY_CatchmentArea::write_output (std::string out) inline inherited
References HY_CatchmentArea::output.
Friends And Related Symbol Documentation
::Bmi_Cpp_Formulation_Test
friend class ::Bmi_Cpp_Formulation_Test friend
::Bmi_Formulation_Test
friend class ::Bmi_Formulation_Test friend
Bmi_Multi_Formulation
friend class Bmi_Multi_Formulation friend
Member Data Documentation
allow_model_exceed_end_time
bool realization::Bmi_Module_Formulation< models::bmi::Bmi_Cpp_Adapter >::allow_model_exceed_end_time private inherited
Whether model Update calls are allowed and handled in some way by the backing model for time steps after the model's end_time.
available_forcings
std::vector<std::string> realization::Bmi_Module_Formulation< models::bmi::Bmi_Cpp_Adapter >::available_forcings private inherited
The set of available "forcings" (output variables, plus their mapped aliases) that the model can provide.
bmi_init_config
std::string realization::Bmi_Module_Formulation< models::bmi::Bmi_Cpp_Adapter >::bmi_init_config private inherited
bmi_main_output_var
std::string realization::Bmi_Formulation::bmi_main_output_var private inherited
Referenced by realization::Bmi_Formulation::get_bmi_main_output_var(), and realization::Bmi_Formulation::set_bmi_main_output_var().
bmi_model
std::shared_ptr<models::bmi::Bmi_Cpp_Adapter > realization::Bmi_Module_Formulation< models::bmi::Bmi_Cpp_Adapter >::bmi_model private inherited
bmi_model_start_time_forcing_offset_s
time_t realization::Bmi_Module_Formulation< models::bmi::Bmi_Cpp_Adapter >::bmi_model_start_time_forcing_offset_s private inherited
The offset, converted to seconds, from the model's start time to the start time of the initial forcing time step.
bmi_model_time_step_fixed
bool realization::Bmi_Module_Formulation< models::bmi::Bmi_Cpp_Adapter >::bmi_model_time_step_fixed private inherited
Whether backing model has fixed time step size.
bmi_using_forcing_file
bool realization::Bmi_Module_Formulation< models::bmi::Bmi_Cpp_Adapter >::bmi_using_forcing_file private inherited
Whether the backing model uses/reads the forcing file directly for getting input data.
bmi_var_names_map
std::map<std::string, std::string> realization::Bmi_Module_Formulation< models::bmi::Bmi_Cpp_Adapter >::bmi_var_names_map private inherited
A configured mapping of BMI model variable names to standard names for use inside the framework.
bounds
polygon_t HY_CatchmentArea::bounds protected inherited
cat_id
std::string realization::Catchment_Formulation::cat_id private inherited
Referenced by realization::Catchment_Formulation::get_catchment_id(), and realization::Catchment_Formulation::set_catchment_id().
forcing
std::shared_ptr<data_access::GenericDataProvider> HY_CatchmentRealization::forcing protected inherited
Referenced by realization::Bmi_Multi_Formulation::create_multi_formulation(), realization::Bmi_Module_Formulation< M >::determine_model_time_offset(), realization::Bmi_Multi_Formulation::get_variable_time_begin(), realization::Bmi_Multi_Formulation::get_variable_time_end(), and realization::Bmi_Module_Formulation< M >::set_model_inputs_prior_to_update().
forcing_file_path
std::string realization::Bmi_Module_Formulation< models::bmi::Bmi_Cpp_Adapter >::forcing_file_path private inherited
id
std::string realization::Formulation::id protected inherited
Referenced by realization::Formulation::get_id().
id_number
unsigned long HY_CatchmentRealization::id_number protected inherited
input_forcing_providers
std::map<std::string, std::shared_ptr<data_access::GenericDataProvider> > realization::Bmi_Module_Formulation< models::bmi::Bmi_Cpp_Adapter >::input_forcing_providers protected inherited
last_model_response_delta
time_step_t realization::Bmi_Module_Formulation< models::bmi::Bmi_Cpp_Adapter >::last_model_response_delta protected inherited
The delta of the last model update execution (typically, this is time step size).
last_model_response_start_time
time_t realization::Bmi_Module_Formulation< models::bmi::Bmi_Cpp_Adapter >::last_model_response_start_time protected inherited
The epoch time of the model at the beginning of its last update.
model_initialized
bool realization::Bmi_Module_Formulation< models::bmi::Bmi_Cpp_Adapter >::model_initialized private inherited
model_type_name
std::string realization::Bmi_Formulation::model_type_name private inherited
Referenced by realization::Bmi_Formulation::get_model_type_name(), and realization::Bmi_Formulation::set_model_type_name().
next_time_step_index
int realization::Bmi_Cpp_Formulation::next_time_step_index = 0 private
Referenced by get_output_line_for_timestep(), and get_response().
OPTIONAL_PARAMETERS
std::vector<std::string> realization::Bmi_Module_Formulation< models::bmi::Bmi_Cpp_Adapter >::OPTIONAL_PARAMETERS private inherited
output
utils::StreamHandler HY_CatchmentArea::output protected inherited
Referenced by realization::Bmi_C_Formulation::construct_model(), construct_model(), realization::Bmi_Multi_Formulation::init_nested_module(), HY_CatchmentArea::set_output_stream(), and HY_CatchmentArea::write_output().
output_header_fields
std::vector<std::string> realization::Bmi_Formulation::output_header_fields private inherited
Output header field strings corresponding to the variables output by the realization, as defined in output_variable_names.
Referenced by realization::Bmi_Formulation::get_output_header_fields(), and realization::Bmi_Formulation::set_output_header_fields().
output_precision
int realization::Bmi_Formulation::output_precision private inherited
The degree of precision in output values when converting to text.
Referenced by realization::Bmi_Formulation::get_output_precision(), and realization::Bmi_Formulation::set_output_precision().
output_text_stream
std::shared_ptr<std::ostringstream> realization::Bmi_Formulation::output_text_stream protected inherited
Object to help with converting numeric output values to text.
Referenced by realization::Bmi_C_Formulation::get_output_line_for_timestep(), realization::Bmi_Multi_Formulation::get_output_line_for_timestep(), and realization::Bmi_Formulation::set_output_precision().
output_variable_names
std::vector<std::string> realization::Bmi_Formulation::output_variable_names private inherited
Names of the variables to include in the output from this formulation, which will be some ordered subset of the BMI module output variables accessible to the instance.
Referenced by realization::Bmi_Formulation::get_output_variable_names(), and realization::Bmi_Formulation::set_output_variable_names().
realized_catchment
shared_ptr<HY_Catchment> HY_CatchmentRealization::realized_catchment protected inherited
REQUIRED_PARAMETERS
std::vector<std::string> realization::Bmi_Module_Formulation< models::bmi::Bmi_Cpp_Adapter >::REQUIRED_PARAMETERS private inherited
The documentation for this class was generated from the following files:
include/realizations/catchment/Bmi_Cpp_Formulation.hpp
src/realizations/catchment/Bmi_Cpp_Formulation.cpp