NGen: geojson::JSONProperty Class Reference
geojson::JSONProperty Class Reference
@TODO: Convert JSONProperty into a variant of the supported types
#include <JSONProperty.hpp>
Classes
struct AsVectorVisitor
Visitor to filter boost variants by type T into a vector of type T.
Public Member Functions
JSONProperty (std::string value_key, const boost::property_tree::ptree &property_tree)
JSONProperty (std::string value_key, short value)
Create a JSONProperty that stores a natural number.
JSONProperty (std::string value_key, int value)
Create a JSONProperty that stores a natural number.
JSONProperty (std::string value_key, long value)
Create a JSONProperty that stores a natural number.
JSONProperty (std::string value_key, float value)
Create a JSONProperty that stores a floating point number.
JSONProperty (std::string value_key, double value)
Create a JSONProperty that stores a floating point number.
JSONProperty (std::string value_key, const char *value)
Create a JSONProperty that stores text.
JSONProperty (std::string value_key, std::string value)
Create a JSONProperty that stores text.
JSONProperty (std::string value_key, std::vector< JSONProperty > properties)
JSONProperty (const JSONProperty &original)
virtual ~JSONProperty ()
A basic destructor.
JSONProperty (std::string value_key, bool value)
Create a JSONProperty that stores a true or false value.
JSONProperty (std::string value_key, PropertyMap &value)
Create a JSONProperty that stores a nested map of properties.
PropertyType get_type () const
Get the type of the property (Natural, Real, String, etc)
long as_natural_number () const
Attempt to get the natural numeric value stored within the property.
double as_real_number () const
bool as_boolean () const
template<typename T >
void as_vector (std::vector< T > &vector) const
Populates a std::vector<T> with PropertyVariant values.
std::vector< JSONProperty > as_list () const
std::vector< long > as_natural_vector () const
std::vector< double > as_real_vector () const
std::vector< std::string > as_string_vector () const
std::vector< bool > as_boolean_vector () const
std::string as_string () const
JSONProperty at (std::string key) const
std::vector< std::string > keys () const
std::map< std::string, JSONProperty > get_values () const
std::string get_key () const
bool has_key (std::string key) const
bool operator== (const JSONProperty &other) const
bool operator!= (const JSONProperty &other)
Private Attributes
std::string key
PropertyType type
PropertyMap values
std::vector< JSONProperty > value_list
PropertyVariant data
Detailed Description
@TODO: Convert JSONProperty into a variant of the supported types
Object used to store basic geojson property data
Constructor & Destructor Documentation
JSONProperty() [1/12]
geojson::JSONProperty::JSONProperty (std::string value_key, const boost::property_tree::ptree & property_tree) inline
References geojson::Boolean, data, geojson::List, geojson::Natural, geojson::Object, geojson::Real, geojson::String, type, value_list, and values.
JSONProperty() [2/12]
geojson::JSONProperty::JSONProperty (std::string value_key, short value) inline
Create a JSONProperty that stores a natural number.
Parameters
value_key The name of the key that stores this value
value The natural number that will be stored
JSONProperty() [3/12]
geojson::JSONProperty::JSONProperty (std::string value_key, int value) inline
Create a JSONProperty that stores a natural number.
Parameters
value_key The name of the key that stores this value
value The natural number that will be stored
JSONProperty() [4/12]
geojson::JSONProperty::JSONProperty (std::string value_key, long value) inline
Create a JSONProperty that stores a natural number.
Parameters
value_key The name of the key that stores this value
value The natural number that will be stored
JSONProperty() [5/12]
geojson::JSONProperty::JSONProperty (std::string value_key, float value) inline
Create a JSONProperty that stores a floating point number.
Parameters
value_key The name of the key that stores this value
value The floating point number that will be stored
JSONProperty() [6/12]
geojson::JSONProperty::JSONProperty (std::string value_key, double value) inline
Create a JSONProperty that stores a floating point number.
Parameters
value_key The name of the key that stores this value
value The floating point number that will be stored
JSONProperty() [7/12]
geojson::JSONProperty::JSONProperty (std::string value_key, const char * value) inline
Create a JSONProperty that stores text.
Parameters
value_key The name of the key that stores this value
value The text that will be stored
JSONProperty() [8/12]
geojson::JSONProperty::JSONProperty (std::string value_key, std::string value) inline
Create a JSONProperty that stores text.
Parameters
value_key The name of the key that stores this value
value The text that will be stored
References geojson::Boolean, data, geojson::Natural, geojson::Real, geojson::String, and type.
JSONProperty() [9/12]
geojson::JSONProperty::JSONProperty (std::string value_key, std::vector< JSONProperty > properties) inline
References data, and value_list.
JSONProperty() [10/12]
geojson::JSONProperty::JSONProperty (const JSONProperty & original) inline
References data, key, geojson::List, geojson::Object, type, value_list, and values.
~JSONProperty()
virtual geojson::JSONProperty::~JSONProperty () inline virtual
A basic destructor.
JSONProperty() [11/12]
geojson::JSONProperty::JSONProperty (std::string value_key, bool value) inline
Create a JSONProperty that stores a true or false value.
Parameters
value_key The name of the key that stores this value
value The true or false value that will be stored
JSONProperty() [12/12]
geojson::JSONProperty::JSONProperty (std::string value_key, PropertyMap & value) inline
Create a JSONProperty that stores a nested map of properties.
Parameters
value_key The name of the key that stores this value
value A map of nested properties that will be stored
References data, and values.
Member Function Documentation
as_boolean()
bool JSONProperty::as_boolean () const
References geojson::Boolean, data, geojson::get_propertytype_name(), get_type(), key, and type.
as_boolean_vector()
std::vector< bool > JSONProperty::as_boolean_vector () const
References as_vector(), and values.
as_list()
std::vector< JSONProperty > JSONProperty::as_list () const
References geojson::get_propertytype_name(), get_type(), key, geojson::List, geojson::Object, type, and value_list.
as_natural_number()
long JSONProperty::as_natural_number () const
Attempt to get the natural numeric value stored within the property.
An exception will be thrown if this property doesn't store a natural number
Returns
The natural number that is stored within the property
An exception will be thrown if this property doesn't store a natural number
Returns
The natural number that is stored within the property
References data, geojson::get_propertytype_name(), get_type(), key, geojson::Natural, and type.
Referenced by realization::Formulation_Manager::read().
as_natural_vector()
std::vector< long > JSONProperty::as_natural_vector () const
References as_vector(), and values.
as_real_number()
double JSONProperty::as_real_number () const
References data, geojson::get_propertytype_name(), get_type(), key, geojson::Natural, geojson::Real, and type.
Referenced by realization::Bmi_Multi_Formulation::create_multi_formulation().
as_real_vector()
std::vector< double > JSONProperty::as_real_vector () const
References as_vector(), and values.
as_string()
std::string JSONProperty::as_string () const
References geojson::Boolean, data, geojson::get_propertytype_name(), get_type(), key, geojson::List, geojson::Natural, geojson::Real, geojson::String, type, and value_list.
Referenced by nexus::Nexus_Manager::construct_nexus(), realization::Bmi_Multi_Formulation::create_multi_formulation(), geojson::FeatureBase::get_id(), and realization::Formulation_Manager::read().
as_string_vector()
std::vector< std::string > JSONProperty::as_string_vector () const
References as_vector(), and values.
as_vector()
template<typename T > void geojson::JSONProperty::as_vector (std::vector< T > & vector) const inline
Populates a std::vector<T> with PropertyVariant values.
Scalar properties will yeild a vector of size 1.
List properties will yield a vector of compatible types. E.g. a List with [1, 2.1, 3] can upcast the Natural number 1 and 3 iff a container is provided with sufficient datatype (double)
std::vector<double> double_vec; as_vector(double_vec);
Will give a vector of doubles = {1.0, 2.1, 3.0}.
However, if a vector of long is used, only the Natural numbers will be extracted
std::vector<long> long_vec; as_vector(long_vec);
Will give a vector of longs = {1, 3}.
Other than this caveat, as_vector effetively filters the property list for types representable by T.
Template Parameters
T
Parameters
vector
References data.
Referenced by as_boolean_vector(), as_natural_vector(), as_real_vector(), and as_string_vector().
at()
JSONProperty JSONProperty::at (std::string key) const
References geojson::get_propertytype_name(), get_type(), key, geojson::Object, type, and values.
Referenced by nexus::Nexus_Manager::construct_nexus(), realization::Bmi_Multi_Formulation::create_multi_formulation(), operator==(), and realization::Formulation_Manager::read().
get_key()
std::string JSONProperty::get_key () const
References key.
get_type()
PropertyType JSONProperty::get_type () const
Get the type of the property (Natural, Real, String, etc)
Returns
The type of the property
Returns
The type of the property
References type.
Referenced by as_boolean(), as_list(), as_natural_number(), as_real_number(), as_string(), at(), get_values(), and keys().
get_values()
PropertyMap JSONProperty::get_values () const
References geojson::get_propertytype_name(), get_type(), key, geojson::Object, type, and values.
Referenced by realization::Bmi_Multi_Formulation::create_multi_formulation().
has_key()
bool JSONProperty::has_key (std::string key) const
References key, and keys().
Referenced by realization::Formulation_Manager::construct_formulation_from_tree(), nexus::Nexus_Manager::construct_nexus(), operator==(), and realization::Formulation_Manager::read().
keys()
std::vector< std::string > JSONProperty::keys () const
References geojson::get_propertytype_name(), get_type(), key, geojson::Object, type, and values.
Referenced by has_key(), and operator==().
operator!=()
bool geojson::JSONProperty::operator!= (const JSONProperty & other) inline
References operator==().
operator==()
bool geojson::JSONProperty::operator== (const JSONProperty & other) const inline
References at(), data, has_key(), keys(), geojson::Object, type, and values.
Referenced by operator!=().
Member Data Documentation
data
PropertyVariant geojson::JSONProperty::data private
Referenced by JSONProperty(), as_boolean(), as_natural_number(), as_real_number(), as_string(), as_vector(), and operator==().
key
std::string geojson::JSONProperty::key private
Referenced by JSONProperty(), as_boolean(), as_list(), as_natural_number(), as_real_number(), as_string(), at(), get_key(), get_values(), has_key(), and keys().
type
PropertyType geojson::JSONProperty::type private
Referenced by JSONProperty(), as_boolean(), as_list(), as_natural_number(), as_real_number(), as_string(), at(), get_type(), get_values(), keys(), and operator==().
value_list
std::vector<JSONProperty> geojson::JSONProperty::value_list private
Referenced by JSONProperty(), as_list(), and as_string().
values
PropertyMap geojson::JSONProperty::values private
Referenced by JSONProperty(), as_boolean_vector(), as_natural_vector(), as_real_vector(), as_string_vector(), at(), get_values(), keys(), geojson::JSONProperty::AsVectorVisitor< T >::operator()(), and operator==().
The documentation for this class was generated from the following files:
include/geojson/JSONProperty.hpp
src/geojson/JSONProperty.cpp