NGen: CsvPerFeatureForcingProvider Class Reference
CsvPerFeatureForcingProvider Class Reference
Forcing class providing time-series precipiation forcing data to the model.
#include <CsvPerFeatureForcingProvider.hpp>
Public Types
typedef struct tm time_type
Public Member Functions
CsvPerFeatureForcingProvider (forcing_params forcing_config)
long get_data_start_time () override
the inclusive beginning of the period of time over which this instance can provide data for this forcing.
long get_data_stop_time () override
the exclusive ending of the period of time over which this instance can provide data for this forcing.
long record_duration () override
the duration of one record of this forcing source
size_t get_ts_index_for_time (const time_t &epoch_time) override
Get the index of the forcing time step that contains the given point in time.
double get_value (const CatchmentAggrDataSelector &selector, data_access::ReSampleMethod m) override
Get the value of a forcing property for an arbitrary time period, converting units if needed.
virtual std::vector< double > get_values (const CatchmentAggrDataSelector &selector, data_access::ReSampleMethod m) override
Get the values of a forcing property for an arbitrary time period, converting units if needed.
bool is_param_sum_over_time_step (const std::string &name)
Get whether a param's value is an aggregate sum over the entire time step.
bool is_property_sum_over_time_step (const std::string &name) override
Get whether a property's per-time-step values are each an aggregate sum over the entire time step.
const std::vector< std::string > & get_available_variable_names () override
Return the variables that are accessable by this data provider.
Private Member Functions
void check_forcing_vector_index_bounds ()
Checks forcing vector index bounds and adjusts index if out of vector bounds ///.
double get_value_for_param_name (const std::string &name, int index)
Get the current value of a forcing param identified by its name.
void read_csv (std::string file_name)
Read Forcing Data from CSV Reads only data within the specified model start and end date-times.
Private Attributes
std::vector< std::string > available_forcings
std::unordered_map< std::string, std::string > available_forcings_units
std::unordered_map< std::string, std::vector< double > > forcing_vectors
std::vector< time_t > time_epoch_vector
int forcing_vector_index
double precipitation_rate_meters_per_second
double air_temperature_fahrenheit
double latitude
double longitude
int catchment_id
int day_of_year
std::string forcing_file_name
std::shared_ptr< time_type > start_date_time
std::shared_ptr< time_type > end_date_time
time_t start_date_time_epoch
time_t end_date_time_epoch
time_t current_date_time_epoch
Detailed Description
Forcing class providing time-series precipiation forcing data to the model.
Member Typedef Documentation
time_type
typedef struct tm CsvPerFeatureForcingProvider::time_type
Constructor & Destructor Documentation
CsvPerFeatureForcingProvider()
CsvPerFeatureForcingProvider::CsvPerFeatureForcingProvider (forcing_params forcing_config) inline
References forcing_params::path, and read_csv().
Member Function Documentation
check_forcing_vector_index_bounds()
void CsvPerFeatureForcingProvider::check_forcing_vector_index_bounds () inline private
Checks forcing vector index bounds and adjusts index if out of vector bounds ///.
Todo:
: Bounds checking is based on precipitation vector. Consider potential for vectors of different sizes and indices.
Todo:
: Return appropriate warning
Todo:
: Return appropriate warning
References forcing_vector_index, and time_epoch_vector.
get_available_variable_names()
const std::vector< std::string > & CsvPerFeatureForcingProvider::get_available_variable_names () inline override virtual
Return the variables that are accessable by this data provider.
Implements data_access::DataProvider< double, CatchmentAggrDataSelector >.
References available_forcings.
get_data_start_time()
long CsvPerFeatureForcingProvider::get_data_start_time () inline override virtual
the inclusive beginning of the period of time over which this instance can provide data for this forcing.
Returns
The inclusive beginning of the period of time over which this instance can provide this data.
Implements data_access::DataProvider< double, CatchmentAggrDataSelector >.
References start_date_time_epoch.
get_data_stop_time()
long CsvPerFeatureForcingProvider::get_data_stop_time () inline override virtual
the exclusive ending of the period of time over which this instance can provide data for this forcing.
Returns
The exclusive ending of the period of time over which this instance can provide this data.
Implements data_access::DataProvider< double, CatchmentAggrDataSelector >.
References end_date_time_epoch.
get_ts_index_for_time()
size_t CsvPerFeatureForcingProvider::get_ts_index_for_time (const time_t & epoch_time) inline override virtual
Get the index of the forcing time step that contains the given point in time.
An std::out_of_range exception should be thrown if the time is not in any time step.
Parameters
epoch_time The point in time, as a seconds-based epoch time.
Returns
The index of the forcing time step that contains the given point in time.
Exceptions
std::out_of_range If the given point is not in any time step.
Implements data_access::DataProvider< double, CatchmentAggrDataSelector >.
References end_date_time_epoch, and start_date_time_epoch.
Referenced by get_value().
get_value()
double CsvPerFeatureForcingProvider::get_value (const CatchmentAggrDataSelector & selector, data_access::ReSampleMethod m) inline override virtual
Get the value of a forcing property for an arbitrary time period, converting units if needed.
An std::out_of_range exception should be thrown if the data for the time period is not available.
Parameters
selector Object storing information about the data to be queried
m methode to resample data if needed
Returns
The value of the forcing property for the described time period, with units converted if needed.
Exceptions
std::out_of_range If data for the time period is not available.
Implements data_access::DataProvider< double, CatchmentAggrDataSelector >.
References available_forcings_units, UnitsHelper::get_converted_value(), CatchmentAggrDataSelector::get_duration_secs(), CatchmentAggrDataSelector::get_init_time(), CatchmentAggrDataSelector::get_output_units(), get_ts_index_for_time(), get_value_for_param_name(), CatchmentAggrDataSelector::get_variable_name(), is_param_sum_over_time_step(), start_date_time_epoch, and time_epoch_vector.
Referenced by get_values().
get_value_for_param_name()
double CsvPerFeatureForcingProvider::get_value_for_param_name (const std::string & name, int index) inline private
Get the current value of a forcing param identified by its name.
Parameters
name The name of the forcing param for which the current value is desired.
index The index of the desired forcing time step from which to obtain the value.
Returns
The particular param's value at the given forcing time step.
References forcing_vectors, time_epoch_vector, and data_access::WellKnownFields.
Referenced by get_value().
get_values()
virtual std::vector< double > CsvPerFeatureForcingProvider::get_values (const CatchmentAggrDataSelector & selector, data_access::ReSampleMethod m) inline override virtual
Get the values of a forcing property for an arbitrary time period, converting units if needed.
An std::out_of_range exception should be thrown if the data for the time period is not available.
If a provider doesn't implement this function, then by default, get_values will be a simple proxy to get_value with the result wrapped in a std::vector<double>
Parameters
output_name The name of the forcing property of interest.
init_time_epoch The epoch time (in seconds) of the start of the time period.
duration_seconds The length of the time period, in seconds.
output_units The expected units of the desired output value.
Returns
std::vector<double> The vector of values of the forcing property for the described time period, with units converted if needed.
Exceptions
std::out_of_range If data for the time period is not available.
Implements data_access::DataProvider< double, CatchmentAggrDataSelector >.
References get_value().
is_param_sum_over_time_step()
bool CsvPerFeatureForcingProvider::is_param_sum_over_time_step (const std::string & name) inline
Get whether a param's value is an aggregate sum over the entire time step.
Certain params, like rain fall, are aggregated sums over an entire time step. Others, such as pressure, are not such sums and instead something else like an instantaneous reading or an average value over the time step.
It may be the case that forcing data is needed for some discretization different than the forcing time step. These values can be calculated (or at least approximated), but doing so requires knowing which values are summed versus not.
Parameters
name The name of the forcing param for which the current value is desired.
Returns
Whether the param's value is an aggregate sum.
Referenced by get_value(), and is_property_sum_over_time_step().
is_property_sum_over_time_step()
bool CsvPerFeatureForcingProvider::is_property_sum_over_time_step (const std::string & name) inline override virtual
Get whether a property's per-time-step values are each an aggregate sum over the entire time step.
Certain properties, like rain fall, are aggregated sums over an entire time step. Others, such as pressure, are not such sums and instead something else like an instantaneous reading or an average value.
It may be the case that forcing data is needed for some discretization different than the forcing time step. This aspect must be known in such cases to perform the appropriate value interpolation.
Parameters
name The name of the forcing property for which the current value is desired.
Returns
Whether the property's value is an aggregate sum.
Reimplemented from data_access::DataProvider< double, CatchmentAggrDataSelector >.
References is_param_sum_over_time_step().
read_csv()
void CsvPerFeatureForcingProvider::read_csv (std::string file_name) inline private
Read Forcing Data from CSV Reads only data within the specified model start and end date-times.
Parameters
file_name Forcing file name
Todo:
TODO: Return appropriate error
References available_forcings, available_forcings_units, end_date_time_epoch, forcing_vectors, CSVReader::getData(), start_date_time_epoch, time_epoch_vector, and data_access::WellKnownFields.
Referenced by CsvPerFeatureForcingProvider().
record_duration()
long CsvPerFeatureForcingProvider::record_duration () inline override virtual
the duration of one record of this forcing source
Returns
The duration of one record of this forcing source
Implements data_access::DataProvider< double, CatchmentAggrDataSelector >.
References time_epoch_vector.
Member Data Documentation
air_temperature_fahrenheit
double CsvPerFeatureForcingProvider::air_temperature_fahrenheit private
available_forcings
std::vector<std::string> CsvPerFeatureForcingProvider::available_forcings private
Referenced by get_available_variable_names(), and read_csv().
available_forcings_units
std::unordered_map<std::string, std::string> CsvPerFeatureForcingProvider::available_forcings_units private
Referenced by get_value(), and read_csv().
catchment_id
int CsvPerFeatureForcingProvider::catchment_id private
current_date_time_epoch
time_t CsvPerFeatureForcingProvider::current_date_time_epoch private
day_of_year
int CsvPerFeatureForcingProvider::day_of_year private
end_date_time
std::shared_ptr<time_type> CsvPerFeatureForcingProvider::end_date_time private
end_date_time_epoch
time_t CsvPerFeatureForcingProvider::end_date_time_epoch private
Referenced by get_data_stop_time(), get_ts_index_for_time(), and read_csv().
forcing_file_name
std::string CsvPerFeatureForcingProvider::forcing_file_name private
forcing_vector_index
int CsvPerFeatureForcingProvider::forcing_vector_index private
Referenced by check_forcing_vector_index_bounds().
forcing_vectors
std::unordered_map<std::string, std::vector<double> > CsvPerFeatureForcingProvider::forcing_vectors private
Todo:
: Look into aggregation of data, relevant libraries, and storing frequency information
Referenced by get_value_for_param_name(), and read_csv().
latitude
double CsvPerFeatureForcingProvider::latitude private
longitude
double CsvPerFeatureForcingProvider::longitude private
precipitation_rate_meters_per_second
double CsvPerFeatureForcingProvider::precipitation_rate_meters_per_second private
Todo:
: Are these used?
start_date_time
std::shared_ptr<time_type> CsvPerFeatureForcingProvider::start_date_time private
start_date_time_epoch
time_t CsvPerFeatureForcingProvider::start_date_time_epoch private
Referenced by get_data_start_time(), get_ts_index_for_time(), get_value(), and read_csv().
time_epoch_vector
std::vector<time_t> CsvPerFeatureForcingProvider::time_epoch_vector private
Todo:
: Consider making epoch time the iterator
Referenced by check_forcing_vector_index_bounds(), get_value(), get_value_for_param_name(), read_csv(), and record_duration().
The documentation for this class was generated from the following file:
include/forcing/CsvPerFeatureForcingProvider.hpp