NGen: Reservoir Class Reference
Reservoir Class Reference
Reservoir that has zero, one, or multiple outlets.
#include <Reservoir.hpp>
Public Types
typedef std::vector< std::shared_ptr< Reservoir_Outlet > > outlet_vector_type
typedef std::shared_ptr< Reservoir_Outlet > outlet_type
Public Member Functions
Reservoir (double minimum_storage_meters=0.0, double maximum_storage_meters=1.0, double current_storage_height_meters=0.0)
Default Constructor building a reservoir with no outlets.
Reservoir (double minimum_storage_meters, double maximum_storage_meters, double current_storage_height_meters, double a, double b, double activation_threshold_meters, double max_velocity_meters_per_second)
Parameterized Constructor building a reservoir with only one standard base outlet.
Reservoir (double minimum_storage_meters, double maximum_storage_meters, double current_storage_height_meters, double a, double activation_threshold_meters, double max_velocity_meters_per_second)
Parameterized Constructor building a reservoir with only one linear outlet.
Reservoir (double minimum_storage_meters, double maximum_storage_meters, double current_storage_height_meters, outlet_vector_type &outlets)
Parameterized Constructor building a reservoir with one or multiple outlets of the base standard and/or exponential type.
double response_meters_per_second (double in_flux_meters_per_second, int delta_time_seconds, double &excess_water_meters)
Function to update the reservoir storage in meters and return a response in meters per second to an influx and time step.
void add_outlet (outlet_type &outlet)
Adds a preconstructed outlet of any type to the reservoir.
void add_outlet (double a, double b, double activation_threshold_meters, double max_velocity_meters_per_second)
Adds a parameterized standard nonlinear outlet to the reservoir.
void add_outlet (double a, double activation_threshold_meters, double max_velocity_meters_per_second)
Adds a parameterized linear outlet to the reservoir.
void sort_outlets ()
Sorts the outlets from lowest to highest acitivation threshold height.
void check_highest_outlet_against_max_storage ()
Ensures that the activation threshold is less than the maximum storage by checking the highest outlet.
double get_storage_height_meters ()
Accessor to return storage.
double velocity_meters_per_second_for_outlet (int outlet_index)
Return velocity in meters per second of discharge through the specified outlet.
Private Attributes
reservoir_parameters parameters
///
reservoir_state state
outlet_vector_type outlets
Detailed Description
Reservoir that has zero, one, or multiple outlets.
The reservoir has parameters of minimum and maximum storage height in meters and a state variable of current storage height in meters. A vector will be created that stores pointers to the reservoir outlet objects. This class will also sort multiple outlets from lowest to highest activation thresholds in the vector. The response_meters_per_second function takes an inflow and cycles through the outlets from lowest to highest activation thresholds and calls the outlet's function to return the discharge velocity in meters per second through the outlet. The reservoir's storage is updated from velocities of each outlet and the delta time for the given timestep.
Member Typedef Documentation
outlet_type
typedef std::shared_ptr<Reservoir_Outlet> Reservoir::outlet_type
outlet_vector_type
typedef std::vector<std::shared_ptr<Reservoir_Outlet> > Reservoir::outlet_vector_type
Constructor & Destructor Documentation
Reservoir() [1/4]
Reservoir::Reservoir (double minimum_storage_meters = 0.0, double maximum_storage_meters = 1.0, double current_storage_height_meters = 0.0)
Default Constructor building a reservoir with no outlets.
Parameters
minimum_storage_meters
maximum_storage_meters
current_storage_height_meters
Reservoir() [2/4]
Reservoir::Reservoir (double minimum_storage_meters, double maximum_storage_meters, double current_storage_height_meters, double a, double b, double activation_threshold_meters, double max_velocity_meters_per_second)
Parameterized Constructor building a reservoir with only one standard base outlet.
Parameters
minimum_storage_meters minimum storage in meters
maximum_storage_meters maximum storage in meters
current_storage_height_meters current storage height in meters
a outlet velocity calculation coefficient
b outlet velocity calculation exponent
activation_threshold_meters meters from the bottom of the reservoir to the bottom of the outlet
max_velocity_meters_per_second max outlet velocity in meters per second
Todo:
TODO: Return appropriate error
References outlets.
Reservoir() [3/4]
Reservoir::Reservoir (double minimum_storage_meters, double maximum_storage_meters, double current_storage_height_meters, double a, double activation_threshold_meters, double max_velocity_meters_per_second)
Parameterized Constructor building a reservoir with only one linear outlet.
Parameters
minimum_storage_meters minimum storage in meters
maximum_storage_meters maximum storage in meters
current_storage_height_meters current storage height in meters
a outlet velocity calculation coefficient
activation_threshold_meters meters from the bottom of the reservoir to the bottom of the outlet
max_velocity_meters_per_second max outlet velocity in meters per second
Todo:
TODO: Return appropriate error
References outlets.
Reservoir() [4/4]
Reservoir::Reservoir (double minimum_storage_meters, double maximum_storage_meters, double current_storage_height_meters, outlet_vector_type & outlets)
Parameterized Constructor building a reservoir with one or multiple outlets of the base standard and/or exponential type.
A reservoir with an exponential outlet can only be instantiated with this constructor.
Parameters
minimum_storage_meters minimum storage in meters
maximum_storage_meters maximum storage in meters
current_storage_height_meters current storage height in meters
outlets vector of reservoir outlets
References check_highest_outlet_against_max_storage(), outlets, and sort_outlets().
Member Function Documentation
add_outlet() [1/3]
void Reservoir::add_outlet (double a, double activation_threshold_meters, double max_velocity_meters_per_second)
Adds a parameterized linear outlet to the reservoir.
Parameters
a outlet velocity calculation coefficient
activation_threshold_meters meters from the bottom of the reservoir to the bottom of the outlet
max_velocity_meters_per_second max outlet velocity in meters per second
References check_highest_outlet_against_max_storage(), outlets, and sort_outlets().
add_outlet() [2/3]
void Reservoir::add_outlet (double a, double b, double activation_threshold_meters, double max_velocity_meters_per_second)
Adds a parameterized standard nonlinear outlet to the reservoir.
Parameters
a outlet velocity calculation coefficient
b outlet velocity calculation exponent
activation_threshold_meters meters from the bottom of the reservoir to the bottom of the outlet
max_velocity_meters_per_second max outlet velocity in meters per second
References check_highest_outlet_against_max_storage(), outlets, and sort_outlets().
add_outlet() [3/3]
void Reservoir::add_outlet (outlet_type & outlet)
Adds a preconstructed outlet of any type to the reservoir.
Parameters
outlet single reservoir outlet
References check_highest_outlet_against_max_storage(), outlets, and sort_outlets().
check_highest_outlet_against_max_storage()
void Reservoir::check_highest_outlet_against_max_storage ()
Ensures that the activation threshold is less than the maximum storage by checking the highest outlet.
Todo:
TODO: Return appropriate error
References reservoir_parameters::maximum_storage_meters, outlets, and parameters.
Referenced by add_outlet(), and Reservoir().
get_storage_height_meters()
double Reservoir::get_storage_height_meters ()
Accessor to return storage.
Returns
state.current_storage_height_meters current storage height in meters
References reservoir_state::current_storage_height_meters, and state.
Referenced by hymod_kernel::run(), and tshirt::tshirt_model::run().
response_meters_per_second()
double Reservoir::response_meters_per_second (double in_flux_meters_per_second, int delta_time_seconds, double & excess_water_meters)
Function to update the reservoir storage in meters and return a response in meters per second to an influx and time step.
Note that the function also takes a reference parameter for holding the amount of excess water for the reservoir beyond its maximum storage after accounting for the input amount. All calls to this function will initialize this parameter, without accounting for any previous value, so any usage should ensure the passed reference does not contain a value that is still needed but not stored elsewhere.
Parameters
in_flux_meters_per_second influx in meters per second
delta_time_seconds delta time in seconds
excess_water_meters Reference to an amount of excess water in meters, after considering input and max storage.
Returns
sum_of_outlet_velocities_meters_per_second sum of the outlet velocities in meters per second
Todo:
TODO: Return appropriate warning
Todo:
TODO: Return appropriate warning
Todo:
TODO: Return appropriate error
References reservoir_state::current_storage_height_meters, reservoir_parameters::maximum_storage_meters, reservoir_parameters::minimum_storage_meters, outlets, parameters, and state.
Referenced by hymod_kernel::run(), and tshirt::tshirt_model::run().
sort_outlets()
void Reservoir::sort_outlets ()
Sorts the outlets from lowest to highest acitivation threshold height.
Sorts the outlets from lowest to highest activation threshold height.
References outlets.
Referenced by add_outlet(), and Reservoir().
velocity_meters_per_second_for_outlet()
double Reservoir::velocity_meters_per_second_for_outlet (int outlet_index)
Return velocity in meters per second of discharge through the specified outlet.
Essentially a wrapper for Reservoir_Outlet#velocity_meters_per_second, where the args for that come from the reservoir anyway.
Parameters
outlet_index The index of the desired outlet in this instance's vector of outlets
Returns
Todo:
: Implement unordered_map outlet_map
References outlets.
Referenced by tshirt::tshirt_model::run().
Member Data Documentation
outlets
outlet_vector_type Reservoir::outlets private
Referenced by add_outlet(), check_highest_outlet_against_max_storage(), Reservoir(), response_meters_per_second(), sort_outlets(), and velocity_meters_per_second_for_outlet().
parameters
reservoir_parameters Reservoir::parameters private
///
Todo:
TODO: Potential Additions
Local sub-timestep to see if storage level crosses threshold below activation height of an outlet or above top of outlet.
Correct for water level falling below an activation threshold and return a flag to possibly call another function that calls a partial timestep.
Return total velocity or individual outlet velocities and these would be multiplied by a watershed area to get discharge in cubic meters per second.
Referenced by check_highest_outlet_against_max_storage(), and response_meters_per_second().
state
reservoir_state Reservoir::state private
Referenced by get_storage_height_meters(), and response_meters_per_second().
The documentation for this class was generated from the following files:
models/kernels/reservoir/Reservoir.hpp
src/models/kernels/reservoir/Reservoir.cpp