NGen: realization::Bmi_Multi_Formulation Class Reference
realization::Bmi_Multi_Formulation Class Reference abstract
Abstraction of a formulation with multiple backing model object that implements the BMI.
#include <Bmi_Multi_Formulation.hpp>
Public Types
typedef Bmi_Formulation nested_module_type
typedef std::shared_ptr< nested_module_type > nested_module_ptr
typedef long time_step_t
Public Member Functions
Bmi_Multi_Formulation (string id, std::shared_ptr< data_access::GenericDataProvider > forcing_provider, utils::StreamHandler output_stream)
Minimal constructor for objects initialize using the Formulation_Manager and subsequent calls to create_formulation.
virtual ~Bmi_Multi_Formulation ()
double calc_et () override
Perform ET (or PET) calculations.
time_t convert_model_time (const double &model_time) override
Convert a time value from the model to an epoch time in seconds.
time_t convert_model_time (const double &model_time, int module_index)
Convert a time value from the model to an epoch time in seconds.
void create_formulation (boost::property_tree::ptree &config, geojson::PropertyMap *global=nullptr) override
void create_formulation (geojson::PropertyMap properties) override
size_t determine_et_formulation_index ()
Determine the index of the correct sub-module formulation from which ET values should be obtain.
const bool & get_allow_model_exceed_end_time () const override
Get whether a model may perform updates beyond its end_time.
const vector< std::string > & get_available_variable_names () override
Get the collection of forcing output property names this instance can provide.
const vector< string > get_bmi_input_variables () override
Get the input variables of the first nested BMI model.
const time_t & get_bmi_model_start_time_forcing_offset_s () override
const vector< string > get_bmi_output_variables () override
Get the output variables of the last nested BMI model.
const string & get_config_mapped_variable_name (const string &model_var_name) override
When possible, translate a variable name for a BMI model to an internally recognized name.
const string & get_config_mapped_variable_name (const string &model_var_name, bool check_first, bool check_last)
When possible, translate a variable name for the first or last BMI model to an internally recognized name.
const string & get_config_mapped_variable_name (const string &output_var_name, const shared_ptr< Bmi_Formulation > &out_module, const shared_ptr< Bmi_Formulation > &in_module)
When possible, translate the name of an output variable for one BMI model to an input variable for another.
const string & get_forcing_file_path () const override
long get_data_start_time () override
Get the inclusive beginning of the period of time over which this instance can provide data for this forcing.
time_t get_variable_time_begin (const std::string &variable_name)
Get the inclusive beginning of the period of time over which this instance can provide data for this forcing.
long get_data_stop_time () override
Get the exclusive ending of the period of time over which this instance can provide data for this forcing.
time_t get_variable_time_end (const std::string &variable_name)
Get the exclusive ending of the period of time over which this instance can provide data for this forcing.
long record_duration () override
Return the stride in the time dimension.
std::string get_formulation_type () override
const double get_model_current_time () override
Get the current time for the primary nested BMI model in its native format and units.
const double get_model_end_time () override
Get the end time for the primary nested BMI model in its native format and units.
const double get_model_start_time ()
Get the end time for the primary nested BMI model in its native format and units.
string get_output_line_for_timestep (int timestep, std::string delimiter) override
Get a formatted line of output values for the given time step as a delimited string.
double get_response (time_step_t t_index, time_step_t t_delta) override
Execute the backing model formulation for the given time step, where it is of the specified size, and return the response output.
size_t get_ts_index_for_time (const time_t &epoch_time) override
Get the index of the forcing time step that contains the given point in time.
double get_value (const CatchmentAggrDataSelector &selector, data_access::ReSampleMethod m) override
Get the value of a forcing property for an arbitrary time period, converting units if needed.
std::vector< double > get_values (const CatchmentAggrDataSelector &selector, data_access::ReSampleMethod m) override
Get the values of a forcing property for an arbitrary time period, converting units if needed.
bool is_bmi_input_variable (const string &var_name) override
bool is_bmi_model_time_step_fixed () override
Test whether all backing models have fixed time step size.
bool is_bmi_output_variable (const string &var_name) override
bool is_bmi_using_forcing_file () const override
Whether the backing model uses/reads the forcing file directly for getting input data.
bool is_model_initialized () override
Test whether all backing models have been initialize using the BMI standard Initialize function.
bool is_property_sum_over_time_step (const string &name) override
Get whether a property's per-time-step values are each an aggregate sum over the entire time step.
bool is_time_step_beyond_end_time (time_step_t t_index)
Get whether this time step goes beyond this formulations (i.e., any of it's modules') end time.
int get_index_for_primary_module ()
Get the index of the primary module.
void set_index_for_primary_module (int index)
Set the index of the primary module.
const string & get_bmi_main_output_var () const
std::string get_model_type_name ()
Get the name of the specific type of the backing model object.
const vector< std::string > & get_output_header_fields () const
Get the values making up the header line from get_output_header_line(), but organized as a vector of strings.
string get_output_header_line (string delimiter) override
Get a header line appropriate for a file made up of entries from this type's implementation of get_output_line_for_timestep.
const vector< string > & get_output_variable_names () const
Get the names of variables in formulation output.
const vector< std::string > & get_required_parameters () override
void set_output_precision (int precision)
Set the precision of output values when converted to text.
virtual void add_time (time_t t, double n)
std::string get_id () const
virtual bool is_et_params_set ()=0
Test whether ET params have been set.
bool is_et_params_set () override
Test whether ET params have been set.
virtual void set_et_params (std::shared_ptr< pdm03_struct > params)=0
Accept a reference for an appropriate object for holding ET parameters for use when executing the model calculations, if maintained by the type.
void set_et_params (std::shared_ptr< pdm03_struct > params) override
Set a reference for an appropriate object for holding ET parameters for use when executing the model calculations.
void set_output_stream (std::string file_path)
void write_output (std::string out)
virtual const pdm03_struct & get_et_params ()
Get a reference to the appropriate object holding ET parameters for use when executing the model calculations.
Static Public Member Functions
static void config_pattern_substitution (geojson::PropertyMap &properties, const std::string &key, const std::string &pattern, const std::string &replacement)
Perform in-place substitution on the given config property item, if the item and the pattern are present.
Protected Member Functions
void create_multi_formulation (geojson::PropertyMap properties, bool needs_param_validation)
Creating a multi-BMI-module formulation from NGen config.
template<class T >
double get_module_var_value_as_double (const std::string &var_name, std::shared_ptr< Bmi_Formulation > mod)
double get_var_value_as_double (const std::string &var_name)
Get value for some BMI model variable.
double get_var_value_as_double (const int &index, const std::string &var_name)
Get value for some BMI model variable at a specific index.
void init_deferred_associations ()
Initialize the deferred associations with the providers in deferredProviders.
template<class T >
std::shared_ptr< T > init_nested_module (int mod_index, std::string identifier, geojson::PropertyMap properties)
Initialize a nested formulation from the given properties and update multi formulation metadata.
int get_output_precision ()
void set_bmi_main_output_var (const string &main_output_var)
virtual void set_model_type_name (std::string type_name)
Set the name of the specific type of the backing model object.
void set_output_header_fields (const vector< std::string > &output_headers)
void set_output_variable_names (const vector< string > &out_var_names)
Set the names of variables in formulation output.
std::string get_catchment_id () override
void set_catchment_id (std::string cat_id) override
virtual geojson::PropertyMap interpret_parameters (boost::property_tree::ptree &config, geojson::PropertyMap *global=nullptr)
virtual void validate_parameters (geojson::PropertyMap options)
virtual std::shared_ptr< pdm03_struct > get_et_params_ptr ()
Protected Attributes
std::map< std::string, std::shared_ptr< data_access::GenericDataProvider > > availableData
A mapping of data properties to their providers.
std::shared_ptr< std::ostringstream > output_text_stream
Object to help with converting numeric output values to text.
std::string id
polygon_t bounds
utils::StreamHandler output
shared_ptr< HY_Catchment > realized_catchment
unsigned long id_number
std::shared_ptr< data_access::GenericDataProvider > forcing
Private Member Functions
template<class T >
void setup_nested_deferred_provider (const std::string &bmi_input_var_name, const std::string &framework_output_name, std::shared_ptr< T > mod, int mod_index)
Setup a deferred provider for a nested module, tracking the class as needed.
Private Attributes
std::vector< std::string > available_forcings
The set of available "forcings" (output variables, plus their mapped aliases) this instance can provide.
std::map< std::string, double > default_output_values
Any configured default values for outputs, keyed by framework alias (or var name if this is globally unique).
std::vector< std::shared_ptr< data_access::OptionalWrappedDataProvider > > deferredProviders
A collection of wrappers to nested formulations providing some output to an earlier nested formulation.
std::vector< int > deferredProviderModuleIndices
The module indices for the modules associated with each item in deferredProviders.
bool is_out_vars_from_last_mod = false
Whether the Bmi_Formulation::output_variable_names value is just the analogous value from this instance's final nested module.
std::vector< nested_module_ptr > modules
The nested BMI modules composing this multi-module formulation, in their order of execution.
std::vector< std::string > module_types
std::vector< std::shared_ptr< std::map< std::string, std::string > > > module_variable_maps
Per-module maps (ordered as in modules) of configuration-mapped names to BMI variable names.
int next_time_step_index = 0
Index value (0-based) of the time step that will be processed by the next update of the model.
int primary_module_index = -1
The index of the "primary" nested module, used when functionality is deferred to a particular module's behavior.
friend Bmi_Multi_Formulation_Test
std::string bmi_main_output_var
std::string model_type_name
std::vector< std::string > output_header_fields
Output header field strings corresponding to the variables output by the realization, as defined in output_variable_names.
std::vector< std::string > output_variable_names
Names of the variables to include in the output from this formulation, which will be some ordered subset of the BMI module output variables accessible to the instance.
int output_precision
The degree of precision in output values when converting to text.
std::vector< std::string > OPTIONAL_PARAMETERS
std::vector< std::string > REQUIRED_PARAMETERS
std::string cat_id
std::shared_ptr< pdm03_struct > et_params
Friends
class ::Bmi_Cpp_Multi_Array_Test
Detailed Description
Abstraction of a formulation with multiple backing model object that implements the BMI.
Member Typedef Documentation
nested_module_ptr
typedef std::shared_ptr<nested_module_type> realization::Bmi_Multi_Formulation::nested_module_ptr
nested_module_type
typedef Bmi_Formulation realization::Bmi_Multi_Formulation::nested_module_type
time_step_t
typedef long realization::Formulation::time_step_t inherited
Constructor & Destructor Documentation
Bmi_Multi_Formulation()
realization::Bmi_Multi_Formulation::Bmi_Multi_Formulation (string id, std::shared_ptr< data_access::GenericDataProvider > forcing_provider, utils::StreamHandler output_stream) inline
Minimal constructor for objects initialize using the Formulation_Manager and subsequent calls to create_formulation.
Parameters
id
forcing_config
output_stream
~Bmi_Multi_Formulation()
virtual realization::Bmi_Multi_Formulation::~Bmi_Multi_Formulation () inline virtual
Member Function Documentation
add_time()
virtual void realization::Formulation::add_time (time_t t, double n) inline virtual inherited
calc_et()
double realization::Bmi_Multi_Formulation::calc_et () inline override virtual
Perform ET (or PET) calculations.
This function defers to the analogous function of the appropriate nested submodule, using determine_et_formulation_index to determine which one that is.
Returns
The ET calculation from the appropriate module from this instance's collection of BMI nested modules.
Implements realization::Et_Accountable.
References determine_et_formulation_index(), and modules.
config_pattern_substitution()
static void realization::Catchment_Formulation::config_pattern_substitution (geojson::PropertyMap & properties, const std::string & key, const std::string & pattern, const std::string & replacement) inline static inherited
Perform in-place substitution on the given config property item, if the item and the pattern are present.
Any and all instances of the substring pattern are replaced by replacement, if key maps to a present string-type property value.
Parameters
properties A reference to the properties config object to be altered.
key The key for the configuration property to potentially adjust.
pattern The pattern substring to search for that, when present, should be replaced.
replacement The replacement substring to potentially insert.
References geojson::String.
Referenced by realization::Formulation_Manager::construct_missing_formulation(), and init_nested_module().
convert_model_time() [1/2]
time_t realization::Bmi_Multi_Formulation::convert_model_time (const double & model_time) inline override virtual
Convert a time value from the model to an epoch time in seconds.
Model time values are typically (though not always) 0-based totals count upward as time progresses. The units are not necessarily seconds. This performs the necessary lookup and conversion for such units, and then shifts the value appropriately for epoch time representation.
For this type, this function will behave in the same manner as the analogous function of the current "primary" nested formulation, which is found in the instance's ordered collection of nested module formulations at the index returned by get_index_for_primary_module.
Parameters
model_time The time value in a model's representation that is to be converted.
Returns
The equivalent epoch time.
Implements realization::Bmi_Formulation.
References convert_model_time(), and get_index_for_primary_module().
Referenced by convert_model_time().
convert_model_time() [2/2]
time_t realization::Bmi_Multi_Formulation::convert_model_time (const double & model_time, int module_index) inline
Convert a time value from the model to an epoch time in seconds.
Model time values are typically (though not always) 0-based totals count upward as time progresses. The units are not necessarily seconds. This performs the necessary lookup and conversion for such units, and then shifts the value appropriately for epoch time representation.
For this type, this function will behave in the same manner as the analogous function of nested formulation found at the provided index within the instance's ordered collection of nested module formulations.
Parameters
model_time The time value in a model's representation that is to be converted.
Returns
The equivalent epoch time.
References modules.
create_formulation() [1/2]
void realization::Bmi_Multi_Formulation::create_formulation (boost::property_tree::ptree & config, geojson::PropertyMap * global = nullptr) inline override virtual
Implements realization::Catchment_Formulation.
References create_multi_formulation(), and realization::Formulation::interpret_parameters().
create_formulation() [2/2]
void realization::Bmi_Multi_Formulation::create_formulation (geojson::PropertyMap properties) inline override virtual
Implements realization::Catchment_Formulation.
References create_multi_formulation().
create_multi_formulation()
void Bmi_Multi_Formulation::create_multi_formulation (geojson::PropertyMap properties, bool needs_param_validation) protected
Creating a multi-BMI-module formulation from NGen config.
Parameters
properties
needs_param_validation
References geojson::JSONProperty::as_real_number(), geojson::JSONProperty::as_string(), geojson::JSONProperty::at(), availableData, default_output_values, HY_CatchmentRealization::forcing, realization::Catchment_Formulation::get_catchment_id(), get_formulation_type(), realization::Bmi_Formulation::get_output_variable_names(), geojson::JSONProperty::get_values(), init_deferred_associations(), is_out_vars_from_last_mod, module_types, module_variable_maps, modules, primary_module_index, realization::Bmi_Formulation::set_bmi_main_output_var(), realization::Bmi_Formulation::set_model_type_name(), realization::Bmi_Formulation::set_output_header_fields(), realization::Bmi_Formulation::set_output_precision(), realization::Bmi_Formulation::set_output_variable_names(), and realization::Formulation::validate_parameters().
Referenced by create_formulation().
determine_et_formulation_index()
size_t realization::Bmi_Multi_Formulation::determine_et_formulation_index () inline
Determine the index of the correct sub-module formulation from which ET values should be obtain.
This is primarily used to determine the correct module in the multi-module collection for getting the ET value when calls to calc_et are made on this "outer" multi-module formulation.
The function first attempts to find the nested module that makes available either NGEN_STD_NAME_POTENTIAL_ET_FOR_TIME_STEP or CSDMS_STD_NAME_POTENTIAL_ET available, if any does. It then provides the index of this module.
Otherwise, the function iterates through the nested modules in order performing a search for one that provides a value with either the name defined in NGEN_STD_NAME_POTENTIAL_ET_FOR_TIME_STEP or defined in CSDMS_STD_NAME_POTENTIAL_ET. It return the index of the first having either.
If neither means finds the appropriate module, at default value DEFAULT_ET_FORMULATION_INDEX is returned.
Returns
The index of correct sub-module formulation from which ET values should be obtain.
References availableData, and modules.
Referenced by calc_et().
get_allow_model_exceed_end_time()
const bool & Bmi_Multi_Formulation::get_allow_model_exceed_end_time () const override virtual
Get whether a model may perform updates beyond its end_time.
Get whether model Update calls are allowed and handled in some way by the backing model for time steps after the model's end_time. Implementations of this type should use this function to safeguard against entering either an invalid or otherwise undesired state as a result of attempting to process a model beyond its available data.
As mentioned, even for models that are capable of validly handling processing beyond end time, it may be desired that they do not for some reason (e.g., the way they account for the lack of input data leads to valid but incorrect results for a specific application). Because of this, whether models are allowed to process beyond their end time is configuration-based.
Returns
Whether a model may perform updates beyond its end_time.
Implements realization::Bmi_Formulation.
References modules.
get_available_variable_names()
const vector< std::string > & Bmi_Multi_Formulation::get_available_variable_names () override virtual
Get the collection of forcing output property names this instance can provide.
For this type, this is the collection of the names/aliases of the BMI output variables for nested modules; i.e., the config-mapped alias for the variable when set in the realization config, or just the name when no alias was included in the configuration.
This is part of the ForcingProvider interface. This interface must be implemented for items of this type to be usable as "forcing" providers for situations when some other object needs to receive as an input (i.e., one of its forcings) a data property output from this object.
Returns
The collection of forcing output property names this instance can provide.
See also
ForcingProvider
Implements data_access::DataProvider< double, CatchmentAggrDataSelector >.
References available_forcings, is_model_initialized(), and modules.
get_bmi_input_variables()
const vector< string > realization::Bmi_Multi_Formulation::get_bmi_input_variables () inline override virtual
Get the input variables of the first nested BMI model.
Returns
The input variables of the first nested BMI model.
Implements realization::Bmi_Formulation.
References modules.
get_bmi_main_output_var()
const string & realization::Bmi_Formulation::get_bmi_main_output_var () const inline inherited
References realization::Bmi_Formulation::bmi_main_output_var.
Referenced by realization::Bmi_C_Formulation::get_response(), realization::Bmi_Cpp_Formulation::get_response(), and get_response().
get_bmi_model_start_time_forcing_offset_s()
const time_t & Bmi_Multi_Formulation::get_bmi_model_start_time_forcing_offset_s () override virtual
Implements realization::Bmi_Formulation.
References modules.
get_bmi_output_variables()
const vector< string > realization::Bmi_Multi_Formulation::get_bmi_output_variables () inline override virtual
Get the output variables of the last nested BMI model.
Returns
The output variables of the last nested BMI model.
Implements realization::Bmi_Formulation.
References modules.
get_catchment_id()
std::string realization::Catchment_Formulation::get_catchment_id () inline override protected virtual inherited
Implements HY_CatchmentRealization.
References realization::Catchment_Formulation::cat_id.
Referenced by create_multi_formulation(), get_value(), get_values(), get_var_value_as_double(), and realization::Bmi_Module_Formulation< M >::set_model_inputs_prior_to_update().
get_config_mapped_variable_name() [1/3]
const string & Bmi_Multi_Formulation::get_config_mapped_variable_name (const string & model_var_name) override virtual
When possible, translate a variable name for a BMI model to an internally recognized name.
Because of the implementation of this type, this function can only translate variable names for input or output variables of either the first or last nested BMI module. In cases when this is not possible, it will return the original parameter.
The function will only check input variable names for the first module and output variable names for the last module. Further, it will always check the first module first, returning if it finds a translation. Only then will it check the last module. This can be controlled by using the overloaded function get_config_mapped_variable_name(string, bool, bool).
To perform a similar translation between modules, see the overloaded function get_config_mapped_variable_name(string, shared_ptr, shared_ptr).
Parameters
model_var_name The BMI variable name to translate so its purpose is recognized internally.
Returns
Either the translated equivalent variable name, or the provided name if there is not a mapping entry.
See also
get_config_mapped_variable_name(string, bool, bool)
get_config_mapped_variable_name(string, shared_ptr, shared_ptr)
Because of the implementation of this type, this function can only translate variable names for input or output variables of either the first or last nested BMI module. In cases when this is not possible, it will return the original parameter.
The function will check the first module first, returning if it finds a translation. Only then will it check the last module.
To perform a similar translation between modules, see the overloaded function get_config_mapped_variable_name(string, shared_ptr, shared_ptr).
Parameters
model_var_name The BMI variable name to translate so its purpose is recognized internally.
Returns
Either the translated equivalent variable name, or the provided name if there is not a mapping entry.
See also
get_config_mapped_variable_name(string, shared_ptr, shared_ptr)
Implements realization::Bmi_Formulation.
References get_config_mapped_variable_name().
Referenced by get_config_mapped_variable_name().
get_config_mapped_variable_name() [2/3]
const string & Bmi_Multi_Formulation::get_config_mapped_variable_name (const string & model_var_name, bool check_first, bool check_last)
When possible, translate a variable name for the first or last BMI model to an internally recognized name.
Because of the implementation of this type, this function can only translate variable names for input or output variables of either the first or last nested BMI module. In cases when this is not possible, it will return the original parameter.
The function can only check input variable names for the first module and output variable names for the last module. Parameters control whether each is actually checked. When both are true, it will always check the first module first, returning if it finds a translation without checking the last.
Parameters
model_var_name The BMI variable name to translate so its purpose is recognized internally.
check_first Whether an input variable mapping for the first module should sought.
check_last Whether an output variable mapping for the last module should sought.
Returns
Either the translated equivalent variable name, or the provided name if there is not a mapping entry.
References is_bmi_input_variable(), and modules.
get_config_mapped_variable_name() [3/3]
const string & Bmi_Multi_Formulation::get_config_mapped_variable_name (const string & output_var_name, const shared_ptr< Bmi_Formulation > & out_module, const shared_ptr< Bmi_Formulation > & in_module)
When possible, translate the name of an output variable for one BMI model to an input variable for another.
This function behaves similarly to get_config_mapped_variable_name(string), except that is performs the translation between modules (rather than between a module and the framework). As such, it is designed for translation between two sequential models, although this is not a requirement for valid execution.
The function will first request the mapping for the parameter name from the outputting module, which will either return a mapped name or the original param. It will check if the returned value is one of the advertised BMI input variable names of the inputting module; if so, it returns that name. Otherwise, it proceeds.
The function then iterates through all the BMI input variable names for the inputting module. If it finds any that maps to either the original parameter or the mapped name from the outputting module, it returns it.
If neither of those find a mapping, then the original parameter is returned.
Note that if this is not an output variable name of the outputting module, the function treats this as a no-mapping condition and returns the parameter.
Parameters
output_var_name The output variable to be translated.
out_module The module having the output variable.
in_module The module needing a translation of output_var_name to one of its input variable names.
Returns
Either the translated equivalent variable name, or the provided name if there is not a mapping entry.
get_data_start_time()
long realization::Bmi_Multi_Formulation::get_data_start_time () inline override virtual
Get the inclusive beginning of the period of time over which this instance can provide data for this forcing.
This is part of the ForcingProvider interface. This interface must be implemented for items of this type to be usable as "forcing" providers for situations when some other object needs to receive as an input (i.e., one of its forcings) a data property output from this object.
Returns
The inclusive beginning of the period of time over which this instance can provide this data.
Implements data_access::DataProvider< double, CatchmentAggrDataSelector >.
References get_variable_time_begin().
get_data_stop_time()
long realization::Bmi_Multi_Formulation::get_data_stop_time () inline override virtual
Get the exclusive ending of the period of time over which this instance can provide data for this forcing.
This is part of the ForcingProvider interface. This interface must be implemented for items of this type to be usable as "forcing" providers for situations when some other object needs to receive as an input (i.e., one of its forcings) a data property output from this object.
Returns
The exclusive ending of the period of time over which this instance can provide this data.
Implements data_access::DataProvider< double, CatchmentAggrDataSelector >.
References get_variable_time_end().
get_et_params()
virtual const pdm03_struct & realization::Et_Accountable::get_et_params () inline virtual inherited
Get a reference to the appropriate object holding ET parameters for use when executing the model calculations.
Returns
A reference object for model ET parameters.
References realization::Et_Accountable::et_params.
get_et_params_ptr()
virtual std::shared_ptr< pdm03_struct > realization::Et_Accountable::get_et_params_ptr () inline protected virtual inherited
References realization::Et_Accountable::et_params.
get_forcing_file_path()
const string & Bmi_Multi_Formulation::get_forcing_file_path () const override virtual
Implements realization::Bmi_Formulation.
References modules.
get_formulation_type()
std::string realization::Bmi_Multi_Formulation::get_formulation_type () inline override virtual
Implements realization::Formulation.
Referenced by create_multi_formulation(), get_response(), get_value(), get_values(), get_variable_time_begin(), get_variable_time_end(), is_property_sum_over_time_step(), and record_duration().
get_id()
std::string realization::Formulation::get_id () const inline inherited
References realization::Formulation::id.
get_index_for_primary_module()
int realization::Bmi_Multi_Formulation::get_index_for_primary_module () inline
Get the index of the primary module.
Returns
The index of the primary module.
References primary_module_index.
Referenced by convert_model_time(), get_model_current_time(), get_model_end_time(), get_model_start_time(), and get_response().
get_model_current_time()
const double realization::Bmi_Multi_Formulation::get_model_current_time () inline override virtual
Get the current time for the primary nested BMI model in its native format and units.
Returns
The current time for the primary nested BMI model in its native format and units.
Implements realization::Bmi_Formulation.
References get_index_for_primary_module(), and modules.
Referenced by get_response(), and get_var_value_as_double().
get_model_end_time()
const double realization::Bmi_Multi_Formulation::get_model_end_time () inline override virtual
Get the end time for the primary nested BMI model in its native format and units.
Returns
The end time for the primary nested BMI model in its native format and units.
Implements realization::Bmi_Formulation.
References get_index_for_primary_module(), and modules.
get_model_start_time()
const double realization::Bmi_Multi_Formulation::get_model_start_time () inline
Get the end time for the primary nested BMI model in its native format and units.
Returns
The end time for the primary nested BMI model in its native format and units.
References get_index_for_primary_module(), and modules.
Referenced by get_var_value_as_double().
get_model_type_name()
std::string realization::Bmi_Formulation::get_model_type_name () inline inherited
Get the name of the specific type of the backing model object.
Returns
The name of the backing model object's type.
References realization::Bmi_Formulation::model_type_name.
Referenced by realization::Bmi_C_Formulation::construct_model(), realization::Bmi_Cpp_Formulation::construct_model(), realization::Bmi_Module_Formulation< M >::get_value_as_type(), realization::Bmi_Module_Formulation< M >::get_values_as_type(), realization::Bmi_C_Formulation::get_var_value_as_double(), and realization::Bmi_Cpp_Formulation::get_var_value_as_double().
get_module_var_value_as_double()
template<class T > double realization::Bmi_Multi_Formulation::get_module_var_value_as_double (const std::string & var_name, std::shared_ptr< Bmi_Formulation > mod) inline protected
get_output_header_fields()
const vector< std::string > & realization::Bmi_Formulation::get_output_header_fields () const inline inherited
Get the values making up the header line from get_output_header_line(), but organized as a vector of strings.
Returns
The values making up the header line from get_output_header_line() organized as a vector.
References realization::Bmi_Formulation::output_header_fields.
Referenced by realization::Bmi_C_Formulation::get_output_header_line(), realization::Bmi_Cpp_Formulation::get_output_header_line(), and realization::Bmi_Formulation::get_output_header_line().
get_output_header_line()
string realization::Bmi_Formulation::get_output_header_line (string delimiter) inline override virtual inherited
Get a header line appropriate for a file made up of entries from this type's implementation of get_output_line_for_timestep.
Note that like the output generating function, this line does not include anything for time step.
Returns
An appropriate header line for this type.
Implements realization::Formulation.
References realization::Bmi_Formulation::get_output_header_fields().
get_output_line_for_timestep()
string Bmi_Multi_Formulation::get_output_line_for_timestep (int timestep, std::string delimiter) override virtual
Get a formatted line of output values for the given time step as a delimited string.
This method is useful for preparing calculated data in a representation useful for output files, such as CSV files.
The resulting string will contain calculated values for applicable output variables for the particular formulation, as determined for the given time step. However, the string will not contain any representation of the time step itself.
An empty string is returned if the time step value is not in the range of valid time steps for which there are calculated values for all variables.
Parameters
timestep The time step for which data is desired.
delimiter The value delimiter for the string.
Returns
A delimited string with all the output variable values for the given time step.
Implements realization::Formulation.
References availableData, realization::Bmi_Formulation::get_output_variable_names(), get_var_value_as_double(), is_out_vars_from_last_mod, modules, next_time_step_index, and realization::Bmi_Formulation::output_text_stream.
get_output_precision()
int realization::Bmi_Formulation::get_output_precision () inline protected inherited
References realization::Bmi_Formulation::output_precision.
get_output_variable_names()
const vector< string > & realization::Bmi_Formulation::get_output_variable_names () const inline inherited
Get the names of variables in formulation output.
Get the names of the variables to include in the output from this formulation, which should be some ordered subset of the BMI module output variables accessible to this instance.
Returns
References realization::Bmi_Formulation::output_variable_names.
Referenced by create_multi_formulation(), realization::Bmi_C_Formulation::get_output_line_for_timestep(), realization::Bmi_Cpp_Formulation::get_output_line_for_timestep(), get_output_line_for_timestep(), and realization::Bmi_Module_Formulation< M >::inner_create_formulation().
get_required_parameters()
const vector< std::string > & realization::Bmi_Formulation::get_required_parameters () inline override virtual inherited
Implements realization::Catchment_Formulation.
Reimplemented in realization::Bmi_Module_Formulation< M >, realization::Bmi_Module_Formulation< models::bmi::Bmi_C_Adapter >, and realization::Bmi_Module_Formulation< models::bmi::Bmi_Cpp_Adapter >.
References realization::Bmi_Formulation::REQUIRED_PARAMETERS.
get_response()
double Bmi_Multi_Formulation::get_response (time_step_t t_index, time_step_t t_delta) override virtual
Execute the backing model formulation for the given time step, where it is of the specified size, and return the response output.
Any inputs and additional parameters must be made available as instance members.
Types should clearly document the details of their particular response output.
Parameters
t_index The index of the time step for which to run model calculations.
d_delta_s The duration, in seconds, of the time step for which to run model calculations.
Returns
The response output of the model for this time step.
Implements realization::Catchment_Formulation.
References realization::Bmi_Formulation::get_bmi_main_output_var(), get_formulation_type(), get_index_for_primary_module(), get_model_current_time(), is_time_step_beyond_end_time(), module_types, modules, and next_time_step_index.
get_ts_index_for_time()
size_t realization::Bmi_Multi_Formulation::get_ts_index_for_time (const time_t & epoch_time) inline override virtual
Get the index of the forcing time step that contains the given point in time.
This is part of the ForcingProvider interface. This interface must be implemented for items of this type to be usable as "forcing" providers for situations when some other object needs to receive as an input (i.e., one of its forcings) a data property output from this object.
An std::out_of_range exception should be thrown if the time is not in any time step.
Parameters
epoch_time The point in time, as a seconds-based epoch time.
Returns
The index of the forcing time step that contains the given point in time.
Exceptions
std::out_of_range If the given point is not in any time step.
Implements data_access::DataProvider< double, CatchmentAggrDataSelector >.
get_value()
double realization::Bmi_Multi_Formulation::get_value (const CatchmentAggrDataSelector & selector, data_access::ReSampleMethod m) inline override virtual
Get the value of a forcing property for an arbitrary time period, converting units if needed.
This is part of the ForcingProvider interface. This interface must be implemented for items of this type to be usable as "forcing" providers for situations when some other object needs to receive as an input (i.e., one of its forcings) a data property output from this object.
For this type, the availableData map contains available properties and either the external forcing provider or the internal nested module that provides that output property. That member is set during creation, within the create_multi_formulation function. This function implementation simply defers to the function of the same name in the appropriate nested forcing provider.
An std::out_of_range exception should be thrown if the data for the time period is not available.
Parameters
output_name The name of the forcing property of interest.
init_time_epoch The epoch time (in seconds) of the start of the time period.
duration_seconds The length of the time period, in seconds.
output_units The expected units of the desired output value.
Returns
The value of the forcing property for the described time period, with units converted if needed.
Exceptions
std::out_of_range If data for the time period is not available.
Implements data_access::DataProvider< double, CatchmentAggrDataSelector >.
References availableData, realization::Catchment_Formulation::get_catchment_id(), CatchmentAggrDataSelector::get_duration_secs(), get_formulation_type(), CatchmentAggrDataSelector::get_init_time(), CatchmentAggrDataSelector::get_output_units(), and CatchmentAggrDataSelector::get_variable_name().
get_values()
std::vector< double > realization::Bmi_Multi_Formulation::get_values (const CatchmentAggrDataSelector & selector, data_access::ReSampleMethod m) inline override virtual
Get the values of a forcing property for an arbitrary time period, converting units if needed.
An std::out_of_range exception should be thrown if the data for the time period is not available.
If a provider doesn't implement this function, then by default, get_values will be a simple proxy to get_value with the result wrapped in a std::vector<double>
Parameters
output_name The name of the forcing property of interest.
init_time_epoch The epoch time (in seconds) of the start of the time period.
duration_seconds The length of the time period, in seconds.
output_units The expected units of the desired output value.
Returns
std::vector<double> The vector of values of the forcing property for the described time period, with units converted if needed.
Exceptions
std::out_of_range If data for the time period is not available.
Implements data_access::DataProvider< double, CatchmentAggrDataSelector >.
References availableData, realization::Catchment_Formulation::get_catchment_id(), CatchmentAggrDataSelector::get_duration_secs(), get_formulation_type(), CatchmentAggrDataSelector::get_init_time(), CatchmentAggrDataSelector::get_output_units(), and CatchmentAggrDataSelector::get_variable_name().
get_var_value_as_double() [1/2]
double realization::Bmi_Multi_Formulation::get_var_value_as_double (const int & index, const std::string & var_name) inline protected
Get value for some BMI model variable at a specific index.
Function gets the value for a provided variable, retrieving the variable array from the backing model of the appropriate nested formulation. The function then returns the specific value at the desired index, cast as a double type.
The function makes several assumptions:
1. `index` is within array bounds
2. `var_name` corresponds to a BMI variable for some nested module.
3. `var_name` is sufficient to identify what value needs to be retrieved
4. the type for output variable allows the value to be cast to a `double` appropriately
Item 3. here can be inferred from 2. for non-multi formulations. For multi formulations, this means the provided var_name must either be a unique BMI variable name among all nested module, or a unique mapped alias to a specific variable in a specific module.
It falls to users of this function (i.e., other functions) to ensure these assumptions hold before invoking.
Parameters
index
var_name
Returns
References availableData, realization::Catchment_Formulation::get_catchment_id(), get_model_current_time(), get_model_start_time(), and record_duration().
get_var_value_as_double() [2/2]
double realization::Bmi_Multi_Formulation::get_var_value_as_double (const std::string & var_name) inline protected
Get value for some BMI model variable.
This function assumes that the given variable, while returned by the model within an array per the BMI spec, is actual a single, scalar value. Thus, it returns what is at index 0 of the array reference.
Parameters
index
var_name
Returns
References get_var_value_as_double().
Referenced by get_output_line_for_timestep(), and get_var_value_as_double().
get_variable_time_begin()
time_t realization::Bmi_Multi_Formulation::get_variable_time_begin (const std::string & variable_name) inline
Get the inclusive beginning of the period of time over which this instance can provide data for this forcing.
This is part of the ForcingProvider interface. This interface must be implemented for items of this type to be usable as "forcing" providers for situations when some other object needs to receive as an input (i.e., one of its forcings) a data property output from this object.
Returns
The inclusive beginning of the period of time over which this instance can provide this data.
References availableData, and get_formulation_type().
Referenced by get_data_start_time().
get_variable_time_end()
time_t realization::Bmi_Multi_Formulation::get_variable_time_end (const std::string & variable_name) inline
Get the exclusive ending of the period of time over which this instance can provide data for this forcing.
This is part of the ForcingProvider interface. This interface must be implemented for items of this type to be usable as "forcing" providers for situations when some other object needs to receive as an input (i.e., one of its forcings) a data property output from this object.
Returns
The exclusive ending of the period of time over which this instance can provide this data.
References availableData, and get_formulation_type().
Referenced by get_data_stop_time().
init_deferred_associations()
void realization::Bmi_Multi_Formulation::init_deferred_associations () inline protected
Initialize the deferred associations with the providers in deferredProviders.
During nested formulation creation, when a nested formulation requires as input some output expected from soon-to-be-created (i.e., later in execution order) formulation (e.g., in a look-back scenario to an earlier time step), then a deferred provider gets registered with the nested module and has a reference added to the deferredProviders member. This function goes through all such the deferred providers, ensures there is something available that can serve as the backing wrapped provider, and associates them.
References availableData, deferredProviderModuleIndices, and deferredProviders.
Referenced by create_multi_formulation().
init_nested_module()
template<class T > std::shared_ptr< T > realization::Bmi_Multi_Formulation::init_nested_module (int mod_index, std::string identifier, geojson::PropertyMap properties) inline protected
Initialize a nested formulation from the given properties and update multi formulation metadata.
This function creates a new formulation, processes the mapping of BMI variables, and adds outputs to the outer module's provideable data items.
Note that it is VERY IMPORTANT that properties argument`` is provided by value, as this copy is potentially updated to perform per-feature pattern substitution for certain property element values.
Template Parameters
T The particular type for the nested formulation object.
Parameters
mod_index The index for the new formulation in this instance's collection of nested formulations.
identifier The id of for the represented feature.
properties A COPY of the nested module config properties for the nested formulation of interest.
Returns
References availableData, realization::Catchment_Formulation::config_pattern_substitution(), module_variable_maps, HY_CatchmentArea::output, and setup_nested_deferred_provider().
interpret_parameters()
virtual geojson::PropertyMap realization::Formulation::interpret_parameters (boost::property_tree::ptree & config, geojson::PropertyMap * global = nullptr) inline protected virtual inherited
References realization::Formulation::validate_parameters().
Referenced by realization::Bmi_Module_Formulation< M >::create_formulation(), and create_formulation().
is_bmi_input_variable()
bool Bmi_Multi_Formulation::is_bmi_input_variable (const string & var_name) override virtual
Implements realization::Bmi_Formulation.
References modules.
Referenced by get_config_mapped_variable_name().
is_bmi_model_time_step_fixed()
bool Bmi_Multi_Formulation::is_bmi_model_time_step_fixed () override virtual
Test whether all backing models have fixed time step size.
Returns
Whether all backing models has fixed time step size.
Implements realization::Bmi_Formulation.
References modules.
is_bmi_output_variable()
bool Bmi_Multi_Formulation::is_bmi_output_variable (const string & var_name) override virtual
Implements realization::Bmi_Formulation.
References modules.
is_bmi_using_forcing_file()
bool Bmi_Multi_Formulation::is_bmi_using_forcing_file () const override virtual
Whether the backing model uses/reads the forcing file directly for getting input data.
Returns
Whether the backing model uses/reads the forcing file directly for getting input data.
Implements realization::Bmi_Formulation.
References modules.
is_et_params_set() [1/2]
bool realization::Et_Accountable::is_et_params_set () inline override virtual inherited
Test whether ET params have been set.
Returns
Whether ET params have been set.
Implements realization::Et_Aware.
References realization::Et_Accountable::et_params.
is_et_params_set() [2/2]
virtual bool realization::Et_Aware::is_et_params_set () pure virtual inherited
Test whether ET params have been set.
Returns
Whether ET params have been set.
Implemented in realization::Et_Accountable.
is_model_initialized()
bool Bmi_Multi_Formulation::is_model_initialized () override virtual
Test whether all backing models have been initialize using the BMI standard Initialize function.
Returns
Whether all backing models have been initialize using the BMI standard Initialize function.
Implements realization::Bmi_Formulation.
References modules.
Referenced by get_available_variable_names().
is_property_sum_over_time_step()
bool realization::Bmi_Multi_Formulation::is_property_sum_over_time_step (const string & name) inline override virtual
Get whether a property's per-time-step values are each an aggregate sum over the entire time step.
Certain properties, like rain fall, are aggregated sums over an entire time step. Others, such as pressure, are not such sums and instead something else like an instantaneous reading or an average value.
It may be the case that forcing data is needed for some discretization different than the forcing time step. This aspect must be known in such cases to perform the appropriate value interpolation.
For instances of this type, all output forcings fall under this category.
This is part of the ForcingProvider interface. This interface must be implemented for items of this type to be usable as "forcing" providers for situations when some other object needs to receive as an input (i.e., one of its forcings) a data property output from this object.
Parameters
name The name of the forcing property for which the current value is desired.
Returns
Whether the property's value is an aggregate sum.
Reimplemented from data_access::DataProvider< double, CatchmentAggrDataSelector >.
References availableData, and get_formulation_type().
is_time_step_beyond_end_time()
bool Bmi_Multi_Formulation::is_time_step_beyond_end_time (time_step_t t_index)
Get whether this time step goes beyond this formulations (i.e., any of it's modules') end time.
Get whether this time step goes beyond this formulation's (i.e., any of it's modules') end time.
Parameters
t_index The time step index in question.
Returns
Whether this time step goes beyond this formulations (i.e., any of it's modules') end time.
Referenced by get_response().
record_duration()
long realization::Bmi_Multi_Formulation::record_duration () inline override virtual
Return the stride in the time dimension.
Implements data_access::DataProvider< double, CatchmentAggrDataSelector >.
References availableData, and get_formulation_type().
Referenced by get_var_value_as_double().
set_bmi_main_output_var()
void realization::Bmi_Formulation::set_bmi_main_output_var (const string & main_output_var) inline protected inherited
References realization::Bmi_Formulation::bmi_main_output_var.
Referenced by create_multi_formulation(), and realization::Bmi_Module_Formulation< M >::inner_create_formulation().
set_catchment_id()
void realization::Catchment_Formulation::set_catchment_id (std::string cat_id) inline override protected virtual inherited
Implements HY_CatchmentRealization.
References realization::Catchment_Formulation::cat_id.
Referenced by realization::Catchment_Formulation::Catchment_Formulation().
set_et_params() [1/2]
void realization::Et_Accountable::set_et_params (std::shared_ptr< pdm03_struct > params) inline override virtual inherited
Set a reference for an appropriate object for holding ET parameters for use when executing the model calculations.
Implements realization::Et_Aware.
References realization::Et_Accountable::et_params.
set_et_params() [2/2]
virtual void realization::Et_Aware::set_et_params (std::shared_ptr< pdm03_struct > params) pure virtual inherited
Accept a reference for an appropriate object for holding ET parameters for use when executing the model calculations, if maintained by the type.
Implemented in realization::Et_Accountable.
set_index_for_primary_module()
void realization::Bmi_Multi_Formulation::set_index_for_primary_module (int index) inline
Set the index of the primary module.
Note that this function does not alter the state of the class, or produce an error, if the index is out of range.
Parameters
index The index for the module.
References modules, and primary_module_index.
set_model_type_name()
virtual void realization::Bmi_Formulation::set_model_type_name (std::string type_name) inline protected virtual inherited
Set the name of the specific type of the backing model object.
Parameters
type_name The name of the backing model object's type.
References realization::Bmi_Formulation::model_type_name.
Referenced by create_multi_formulation(), and realization::Bmi_Module_Formulation< M >::inner_create_formulation().
set_output_header_fields()
void realization::Bmi_Formulation::set_output_header_fields (const vector< std::string > & output_headers) inline protected inherited
References realization::Bmi_Formulation::output_header_fields.
Referenced by create_multi_formulation(), and realization::Bmi_Module_Formulation< M >::inner_create_formulation().
set_output_precision()
void realization::Bmi_Formulation::set_output_precision (int precision) inline inherited
Set the precision of output values when converted to text.
Parameters
precision The desired precision, as a number of decimal places.
References realization::Bmi_Formulation::output_precision, and realization::Bmi_Formulation::output_text_stream.
Referenced by realization::Bmi_Formulation::Bmi_Formulation(), create_multi_formulation(), and realization::Bmi_Module_Formulation< M >::inner_create_formulation().
set_output_stream()
void HY_CatchmentArea::set_output_stream (std::string file_path) inline inherited
References HY_CatchmentArea::output.
set_output_variable_names()
void realization::Bmi_Formulation::set_output_variable_names (const vector< string > & out_var_names) inline protected inherited
Set the names of variables in formulation output.
Set the names of the variables to include in the output from this formulation, which should be some ordered subset of the output variables from the model.
Parameters
out_var_names the names of variables in formulation output, in the order they should appear.
References realization::Bmi_Formulation::output_variable_names.
Referenced by create_multi_formulation(), and realization::Bmi_Module_Formulation< M >::inner_create_formulation().
setup_nested_deferred_provider()
template<class T > void realization::Bmi_Multi_Formulation::setup_nested_deferred_provider (const std::string & bmi_input_var_name, const std::string & framework_output_name, std::shared_ptr< T > mod, int mod_index) inline private
Setup a deferred provider for a nested module, tracking the class as needed.
Create an optional wrapped provider for use with a nested module and some required variable it needs provided. Track this and the index of the nested modules in the member collections necessary for later initializing associations to backing providers that were originally deferred. Then, assign the created deferred wrapper provider as the provider for the variable in the nested module.
Template Parameters
T
Parameters
bmi_input_var_name The name of the required input variable a nested module needs provided.
framework_output_name The framework alias of the required output variable that will be provided to the aforementioned input variable (which may be the same as bmi_input_var_name).
mod The nested module requiring a deferred wrapped provider for a variable.
mod_index The index of the given nested module in the ordering of all this instance's nested modules.
References default_output_values, deferredProviderModuleIndices, and deferredProviders.
Referenced by init_nested_module().
validate_parameters()
virtual void realization::Formulation::validate_parameters (geojson::PropertyMap options) inline protected virtual inherited
References realization::Formulation::get_formulation_type(), and realization::Formulation::get_required_parameters().
Referenced by create_multi_formulation(), realization::Bmi_Module_Formulation< M >::inner_create_formulation(), and realization::Formulation::interpret_parameters().
write_output()
void HY_CatchmentArea::write_output (std::string out) inline inherited
References HY_CatchmentArea::output.
Friends And Related Function Documentation
::Bmi_Cpp_Multi_Array_Test
friend class ::Bmi_Cpp_Multi_Array_Test friend
Member Data Documentation
available_forcings
std::vector<std::string> realization::Bmi_Multi_Formulation::available_forcings private
The set of available "forcings" (output variables, plus their mapped aliases) this instance can provide.
Referenced by get_available_variable_names().
availableData
std::map<std::string, std::shared_ptr<data_access::GenericDataProvider> > realization::Bmi_Multi_Formulation::availableData protected
A mapping of data properties to their providers.
Keys for the data properties are unique, name-like identifiers. These could be a BMI output variable name for a module, or a configuration-mapped alias of such a variable. The intent is for any module needing any input data to also have either an input variable name or input variable name mapping identical to one of these keys (and though ordering is important at a higher level, it is not handled directly by this member).
Referenced by create_multi_formulation(), determine_et_formulation_index(), get_output_line_for_timestep(), get_value(), get_values(), get_var_value_as_double(), get_variable_time_begin(), get_variable_time_end(), init_deferred_associations(), init_nested_module(), is_property_sum_over_time_step(), and record_duration().
bmi_main_output_var
std::string realization::Bmi_Formulation::bmi_main_output_var private inherited
Referenced by realization::Bmi_Formulation::get_bmi_main_output_var(), and realization::Bmi_Formulation::set_bmi_main_output_var().
Bmi_Multi_Formulation_Test
friend realization::Bmi_Multi_Formulation::Bmi_Multi_Formulation_Test private
bounds
polygon_t HY_CatchmentArea::bounds protected inherited
cat_id
std::string realization::Catchment_Formulation::cat_id private inherited
Referenced by realization::Catchment_Formulation::get_catchment_id(), and realization::Catchment_Formulation::set_catchment_id().
default_output_values
std::map<std::string, double> realization::Bmi_Multi_Formulation::default_output_values private
Any configured default values for outputs, keyed by framework alias (or var name if this is globally unique).
Referenced by create_multi_formulation(), and setup_nested_deferred_provider().
deferredProviderModuleIndices
std::vector<int> realization::Bmi_Multi_Formulation::deferredProviderModuleIndices private
The module indices for the modules associated with each item in deferredProviders.
E.g., the value in this vector at index 0 is the index of a module within modules. That module is what required the deferred provider in the deferredProviders collection at its index 0.
Referenced by init_deferred_associations(), and setup_nested_deferred_provider().
deferredProviders
std::vector<std::shared_ptr<data_access::OptionalWrappedDataProvider> > realization::Bmi_Multi_Formulation::deferredProviders private
A collection of wrappers to nested formulations providing some output to an earlier nested formulation.
During formulation creation, when a nested formulation requires as input some output from a later formulation (e.g., in a look-back scenario to an earlier time step), then an "optimistic" wrapper gets put into place. It assumes that the necessary provider will be available and associated once all nested formulations have been created. This member tracks these so that this deferred association can be done.
Referenced by init_deferred_associations(), and setup_nested_deferred_provider().
et_params
std::shared_ptr<pdm03_struct> realization::Et_Accountable::et_params private inherited
Referenced by realization::Bmi_Module_Formulation< M >::calc_et(), realization::Et_Accountable::get_et_params(), realization::Et_Accountable::get_et_params_ptr(), realization::Et_Accountable::is_et_params_set(), and realization::Et_Accountable::set_et_params().
forcing
std::shared_ptr<data_access::GenericDataProvider> HY_CatchmentRealization::forcing protected inherited
Referenced by realization::Bmi_Module_Formulation< M >::calc_et(), create_multi_formulation(), realization::Bmi_Module_Formulation< M >::determine_model_time_offset(), and realization::Bmi_Module_Formulation< M >::set_model_inputs_prior_to_update().
id
std::string realization::Formulation::id protected inherited
Referenced by realization::Formulation::get_id().
id_number
unsigned long HY_CatchmentRealization::id_number protected inherited
is_out_vars_from_last_mod
bool realization::Bmi_Multi_Formulation::is_out_vars_from_last_mod = false private
Whether the Bmi_Formulation::output_variable_names value is just the analogous value from this instance's final nested module.
Referenced by create_multi_formulation(), and get_output_line_for_timestep().
model_type_name
std::string realization::Bmi_Formulation::model_type_name private inherited
Referenced by realization::Bmi_Formulation::get_model_type_name(), and realization::Bmi_Formulation::set_model_type_name().
module_types
std::vector<std::string> realization::Bmi_Multi_Formulation::module_types private
Referenced by create_multi_formulation(), and get_response().
module_variable_maps
std::vector<std::shared_ptr<std::map<std::string, std::string> > > realization::Bmi_Multi_Formulation::module_variable_maps private
Per-module maps (ordered as in modules) of configuration-mapped names to BMI variable names.
Referenced by create_multi_formulation(), and init_nested_module().
modules
std::vector<nested_module_ptr> realization::Bmi_Multi_Formulation::modules private
The nested BMI modules composing this multi-module formulation, in their order of execution.
Referenced by calc_et(), convert_model_time(), create_multi_formulation(), determine_et_formulation_index(), get_allow_model_exceed_end_time(), get_available_variable_names(), get_bmi_input_variables(), get_bmi_model_start_time_forcing_offset_s(), get_bmi_output_variables(), get_config_mapped_variable_name(), get_forcing_file_path(), get_model_current_time(), get_model_end_time(), get_model_start_time(), get_output_line_for_timestep(), get_response(), is_bmi_input_variable(), is_bmi_model_time_step_fixed(), is_bmi_output_variable(), is_bmi_using_forcing_file(), is_model_initialized(), and set_index_for_primary_module().
next_time_step_index
int realization::Bmi_Multi_Formulation::next_time_step_index = 0 private
Index value (0-based) of the time step that will be processed by the next update of the model.
Referenced by get_output_line_for_timestep(), and get_response().
OPTIONAL_PARAMETERS
std::vector<std::string> realization::Bmi_Formulation::OPTIONAL_PARAMETERS private inherited
Initial value:
= {
                BMI_REALIZATION_CFG_PARAM_OPT__FORCING_FILE,
                BMI_REALIZATION_CFG_PARAM_OPT__VAR_STD_NAMES,
                BMI_REALIZATION_CFG_PARAM_OPT__OUT_VARS,
                BMI_REALIZATION_CFG_PARAM_OPT__OUT_HEADER_FIELDS,
                BMI_REALIZATION_CFG_PARAM_OPT__ALLOW_EXCEED_END,
                BMI_REALIZATION_CFG_PARAM_OPT__FIXED_TIME_STEP,
                BMI_REALIZATION_CFG_PARAM_OPT__LIB_FILE
        }
output
utils::StreamHandler HY_CatchmentArea::output protected inherited
Referenced by realization::Bmi_C_Formulation::construct_model(), realization::Bmi_Cpp_Formulation::construct_model(), init_nested_module(), HY_CatchmentArea::set_output_stream(), and HY_CatchmentArea::write_output().
output_header_fields
std::vector<std::string> realization::Bmi_Formulation::output_header_fields private inherited
Output header field strings corresponding to the variables output by the realization, as defined in output_variable_names.
Referenced by realization::Bmi_Formulation::get_output_header_fields(), and realization::Bmi_Formulation::set_output_header_fields().
output_precision
int realization::Bmi_Formulation::output_precision private inherited
The degree of precision in output values when converting to text.
Referenced by realization::Bmi_Formulation::get_output_precision(), and realization::Bmi_Formulation::set_output_precision().
output_text_stream
std::shared_ptr<std::ostringstream> realization::Bmi_Formulation::output_text_stream protected inherited
Object to help with converting numeric output values to text.
Referenced by realization::Bmi_C_Formulation::get_output_line_for_timestep(), get_output_line_for_timestep(), and realization::Bmi_Formulation::set_output_precision().
output_variable_names
std::vector<std::string> realization::Bmi_Formulation::output_variable_names private inherited
Names of the variables to include in the output from this formulation, which will be some ordered subset of the BMI module output variables accessible to the instance.
Referenced by realization::Bmi_Formulation::get_output_variable_names(), and realization::Bmi_Formulation::set_output_variable_names().
primary_module_index
int realization::Bmi_Multi_Formulation::primary_module_index = -1 private
The index of the "primary" nested module, used when functionality is deferred to a particular module's behavior.
Referenced by create_multi_formulation(), get_index_for_primary_module(), and set_index_for_primary_module().
realized_catchment
shared_ptr<HY_Catchment> HY_CatchmentRealization::realized_catchment protected inherited
REQUIRED_PARAMETERS
std::vector<std::string> realization::Bmi_Formulation::REQUIRED_PARAMETERS private inherited
Initial value:
= {
                BMI_REALIZATION_CFG_PARAM_REQ__INIT_CONFIG,
                BMI_REALIZATION_CFG_PARAM_REQ__MAIN_OUT_VAR,
                BMI_REALIZATION_CFG_PARAM_REQ__MODEL_TYPE,
                BMI_REALIZATION_CFG_PARAM_REQ__USES_FORCINGS
        }
Referenced by realization::Bmi_Formulation::get_required_parameters().
The documentation for this class was generated from the following files:
include/realizations/catchment/Bmi_Multi_Formulation.hpp
src/realizations/catchment/Bmi_Multi_Formulation.cpp