NGen: Simple_Lumped_Model_Realization Class Reference
Simple_Lumped_Model_Realization Class Reference abstract
#include <Simple_Lumped_Model_Realization.hpp>
Public Types
typedef long time_step_t
Public Member Functions
Simple_Lumped_Model_Realization (std::string id, forcing_params forcing_config, utils::StreamHandler output_stream, double storage, double gw_storage, double gw_max_storage, double nash_max_storage, double smax, double a, double b, double Ks, double Kq, long n, const std::vector< double > &Sr, time_step_t t)
Simple_Lumped_Model_Realization (std::string id, shared_ptr< data_access::GenericDataProvider > forcing_provider, utils::StreamHandler output_stream)
Simple_Lumped_Model_Realization (std::string id)
Simple_Lumped_Model_Realization (Simple_Lumped_Model_Realization &&)
Explicit move constructor This constuctor explicitly moves a Simple_Lumped_Model_Realization and is required to properly move the HY_CatchmentRealization forcing object.
Simple_Lumped_Model_Realization (const Simple_Lumped_Model_Realization &)
Explicit copy constructor This constuctor explicitly copies Simple_Lumped_Model_Realization and is required to properly copy the HY_CatchmentRealization forcing object as well connectet the hymod_state.Sr* to the copied cascade_backing_storage vector.
virtual ~Simple_Lumped_Model_Realization ()
std::string get_output_line_for_timestep (int timestep, std::string delimiter=",") override
Get a formatted line of output values for the given time step as a delimited string.
double get_response (time_step_t t, time_step_t dt) override
Execute the backing model formulation for the given time step, where it is of the specified size, and return the total discharge.
double calc_et () override
void create_formulation (boost::property_tree::ptree &config, geojson::PropertyMap *global=nullptr) override
void create_formulation (geojson::PropertyMap properties) override
std::string get_formulation_type () override
void add_time (time_t t, double n) override
std::string get_output_header_line (std::string delimiter) override
Get a header line appropriate for a file made up of entries from this type's implementation of get_output_line_for_timestep.
std::string get_id () const
virtual bool is_et_params_set ()=0
Test whether ET params have been set.
bool is_et_params_set () override
Test whether ET params have been set.
virtual void set_et_params (std::shared_ptr< pdm03_struct > params)=0
Accept a reference for an appropriate object for holding ET parameters for use when executing the model calculations, if maintained by the type.
void set_et_params (std::shared_ptr< pdm03_struct > params) override
Set a reference for an appropriate object for holding ET parameters for use when executing the model calculations.
void set_output_stream (std::string file_path)
void write_output (std::string out)
virtual const pdm03_struct & get_et_params ()
Get a reference to the appropriate object holding ET parameters for use when executing the model calculations.
Static Public Member Functions
static void config_pattern_substitution (geojson::PropertyMap &properties, const std::string &key, const std::string &pattern, const std::string &replacement)
Perform in-place substitution on the given config property item, if the item and the pattern are present.
Protected Member Functions
const std::vector< std::string > & get_required_parameters () override
std::string get_catchment_id () override
void set_catchment_id (std::string cat_id) override
virtual geojson::PropertyMap interpret_parameters (boost::property_tree::ptree &config, geojson::PropertyMap *global=nullptr)
virtual void validate_parameters (geojson::PropertyMap options)
virtual std::shared_ptr< pdm03_struct > get_et_params_ptr ()
Protected Attributes
std::vector< std::string > REQUIRED_PARAMETERS
std::string id
polygon_t bounds
utils::StreamHandler output
shared_ptr< HY_Catchment > realized_catchment
unsigned long id_number
std::shared_ptr< data_access::GenericDataProvider > forcing
Private Attributes
std::unordered_map< time_step_t, hymod_state > state
std::unordered_map< time_step_t, hymod_fluxes > fluxes
std::unordered_map< time_step_t, std::vector< double > > cascade_backing_storage
hymod_params params
std::string cat_id
std::shared_ptr< pdm03_struct > et_params
Member Typedef Documentation
time_step_t
typedef long Simple_Lumped_Model_Realization::time_step_t
Constructor & Destructor Documentation
Simple_Lumped_Model_Realization() [1/5]
Simple_Lumped_Model_Realization::Simple_Lumped_Model_Realization (std::string id, forcing_params forcing_config, utils::StreamHandler output_stream, double storage, double gw_storage, double gw_max_storage, double nash_max_storage, double smax, double a, double b, double Ks, double Kq, long n, const std::vector< double > & Sr, time_step_t t)
Simple_Lumped_Model_Realization() [2/5]
Simple_Lumped_Model_Realization::Simple_Lumped_Model_Realization (std::string id, shared_ptr< data_access::GenericDataProvider > forcing_provider, utils::StreamHandler output_stream) inline
Simple_Lumped_Model_Realization() [3/5]
Simple_Lumped_Model_Realization::Simple_Lumped_Model_Realization (std::string id) inline
Simple_Lumped_Model_Realization() [4/5]
Simple_Lumped_Model_Realization::Simple_Lumped_Model_Realization (Simple_Lumped_Model_Realization &&)
Explicit move constructor This constuctor explicitly moves a Simple_Lumped_Model_Realization and is required to properly move the HY_CatchmentRealization forcing object.
Simple_Lumped_Model_Realization() [5/5]
Simple_Lumped_Model_Realization::Simple_Lumped_Model_Realization (const Simple_Lumped_Model_Realization & other)
Explicit copy constructor This constuctor explicitly copies Simple_Lumped_Model_Realization and is required to properly copy the HY_CatchmentRealization forcing object as well connectet the hymod_state.Sr* to the copied cascade_backing_storage vector.
References cascade_backing_storage, and state.
~Simple_Lumped_Model_Realization()
Simple_Lumped_Model_Realization::~Simple_Lumped_Model_Realization () virtual
Member Function Documentation
add_time()
void Simple_Lumped_Model_Realization::add_time (time_t t, double n) override virtual
Reimplemented from realization::Formulation.
References cascade_backing_storage, fluxes, hymod_params::n, params, and state.
Referenced by get_response().
calc_et()
double Simple_Lumped_Model_Realization::calc_et () override virtual
Implements realization::Et_Accountable.
config_pattern_substitution()
static void realization::Catchment_Formulation::config_pattern_substitution (geojson::PropertyMap & properties, const std::string & key, const std::string & pattern, const std::string & replacement) inline static inherited
Perform in-place substitution on the given config property item, if the item and the pattern are present.
Any and all instances of the substring pattern are replaced by replacement, if key maps to a present string-type property value.
Parameters
properties A reference to the properties config object to be altered.
key The key for the configuration property to potentially adjust.
pattern The pattern substring to search for that, when present, should be replaced.
replacement The replacement substring to potentially insert.
References geojson::String.
Referenced by realization::Formulation_Manager::construct_missing_formulation(), and realization::Bmi_Multi_Formulation::init_nested_module().
create_formulation() [1/2]
void Simple_Lumped_Model_Realization::create_formulation (boost::property_tree::ptree & config, geojson::PropertyMap * global = nullptr) override virtual
Implements realization::Catchment_Formulation.
References create_formulation(), and realization::Formulation::interpret_parameters().
Referenced by create_formulation().
create_formulation() [2/2]
void Simple_Lumped_Model_Realization::create_formulation (geojson::PropertyMap properties) override virtual
Implements realization::Catchment_Formulation.
References hymod_params::a, hymod_params::activation_threshold_meters_groundwater_reservoir, hymod_params::activation_threshold_meters_nash_cascade_reservoir, hymod_params::b, cascade_backing_storage, fluxes, hymod_params::gw_max_storage_meters, hymod_params::Kq, hymod_params::Ks, hymod_params::min_storage_meters, hymod_params::n, hymod_params::nash_max_storage_meters, params, hymod_params::reservoir_max_velocity_meters_per_second, hymod_params::smax, state, and realization::Formulation::validate_parameters().
get_catchment_id()
std::string realization::Catchment_Formulation::get_catchment_id () inline override protected virtual inherited
Implements HY_CatchmentRealization.
References realization::Catchment_Formulation::cat_id.
Referenced by realization::Bmi_Multi_Formulation::create_multi_formulation(), realization::Bmi_Multi_Formulation::get_value(), realization::Bmi_Multi_Formulation::get_values(), realization::Bmi_Multi_Formulation::get_var_value_as_double(), and realization::Bmi_Module_Formulation< M >::set_model_inputs_prior_to_update().
get_et_params()
virtual const pdm03_struct & realization::Et_Accountable::get_et_params () inline virtual inherited
Get a reference to the appropriate object holding ET parameters for use when executing the model calculations.
Returns
A reference object for model ET parameters.
References realization::Et_Accountable::et_params.
Referenced by get_response().
get_et_params_ptr()
virtual std::shared_ptr< pdm03_struct > realization::Et_Accountable::get_et_params_ptr () inline protected virtual inherited
References realization::Et_Accountable::et_params.
Referenced by realization::Tshirt_Realization::get_response().
get_formulation_type()
std::string Simple_Lumped_Model_Realization::get_formulation_type () inline override virtual
Implements realization::Formulation.
get_id()
std::string realization::Formulation::get_id () const inline inherited
References realization::Formulation::id.
Referenced by realization::Tshirt_C_Realization::create_formulation(), and realization::Tshirt_Realization::create_formulation().
get_output_header_line()
std::string realization::Catchment_Formulation::get_output_header_line (std::string delimiter) inline override virtual inherited
Get a header line appropriate for a file made up of entries from this type's implementation of get_output_line_for_timestep.
Note that like the output generating function, this line does not include anything for time step.
A default implementation is provided for inheritors of this type, which includes only "Total Discharge."
Returns
An appropriate header line for this type.
Implements realization::Formulation.
Reimplemented in realization::Tshirt_C_Realization.
get_output_line_for_timestep()
std::string Simple_Lumped_Model_Realization::get_output_line_for_timestep (int timestep, std::string delimiter = ",") override virtual
Get a formatted line of output values for the given time step as a delimited string.
For this type, the output consists of only the total discharge amount per time step; i.e., the same value that was returned by get_response.
This method is useful for preparing calculated data in a representation useful for output files, such as CSV files.
The resulting string will contain calculated values for applicable output variables for the particular formulation, as determined for the given time step. However, the string will not contain any representation of the time step itself.
An empty string is returned if the time step value is not in the range of valid time steps for which there are calculated values for all variables.
The default delimiter is a comma.
Parameters
timestep The time step for which data is desired.
Returns
A delimited string with all the output variable values for the given time step.
Implements realization::Formulation.
References fluxes.
get_required_parameters()
const std::vector< std::string > & Simple_Lumped_Model_Realization::get_required_parameters () inline override protected virtual
Implements realization::Catchment_Formulation.
References REQUIRED_PARAMETERS.
get_response()
double Simple_Lumped_Model_Realization::get_response (time_step_t t_index, time_step_t t_delta_s) override virtual
Execute the backing model formulation for the given time step, where it is of the specified size, and return the total discharge.
Function reads input precipitation from forcing member variable. It also makes use of the params struct for ET params accessible via get_et_params.
Parameters
t_index The index of the time step for which to run model calculations.
d_delta_s The duration, in seconds, of the time step for which to run model calculations.
Returns
The total discharge for this time step.
Implements realization::Catchment_Formulation.
References add_time(), fluxes, HY_CatchmentRealization::forcing, realization::Et_Accountable::get_et_params(), hymod_params::n, params, hymod_kernel::run(), state, and data_access::SUM.
interpret_parameters()
virtual geojson::PropertyMap realization::Formulation::interpret_parameters (boost::property_tree::ptree & config, geojson::PropertyMap * global = nullptr) inline protected virtual inherited
References realization::Formulation::validate_parameters().
Referenced by realization::Bmi_Module_Formulation< M >::create_formulation(), realization::Bmi_Multi_Formulation::create_formulation(), create_formulation(), realization::Tshirt_C_Realization::create_formulation(), and realization::Tshirt_Realization::create_formulation().
is_et_params_set() [1/2]
bool realization::Et_Accountable::is_et_params_set () inline override virtual inherited
Test whether ET params have been set.
Returns
Whether ET params have been set.
Implements realization::Et_Aware.
References realization::Et_Accountable::et_params.
is_et_params_set() [2/2]
virtual bool realization::Et_Aware::is_et_params_set () pure virtual inherited
Test whether ET params have been set.
Returns
Whether ET params have been set.
Implemented in realization::Et_Accountable.
set_catchment_id()
void realization::Catchment_Formulation::set_catchment_id (std::string cat_id) inline override protected virtual inherited
Implements HY_CatchmentRealization.
References realization::Catchment_Formulation::cat_id.
Referenced by realization::Catchment_Formulation::Catchment_Formulation().
set_et_params() [1/2]
void realization::Et_Accountable::set_et_params (std::shared_ptr< pdm03_struct > params) inline override virtual inherited
Set a reference for an appropriate object for holding ET parameters for use when executing the model calculations.
Implements realization::Et_Aware.
References realization::Et_Accountable::et_params.
set_et_params() [2/2]
virtual void realization::Et_Aware::set_et_params (std::shared_ptr< pdm03_struct > params) pure virtual inherited
Accept a reference for an appropriate object for holding ET parameters for use when executing the model calculations, if maintained by the type.
Implemented in realization::Et_Accountable.
set_output_stream()
void HY_CatchmentArea::set_output_stream (std::string file_path) inline inherited
References HY_CatchmentArea::output.
validate_parameters()
virtual void realization::Formulation::validate_parameters (geojson::PropertyMap options) inline protected virtual inherited
References realization::Formulation::get_formulation_type(), and realization::Formulation::get_required_parameters().
Referenced by create_formulation(), realization::Tshirt_C_Realization::create_formulation(), realization::Tshirt_Realization::create_formulation(), realization::Bmi_Multi_Formulation::create_multi_formulation(), realization::Bmi_Module_Formulation< M >::inner_create_formulation(), and realization::Formulation::interpret_parameters().
write_output()
void HY_CatchmentArea::write_output (std::string out) inline inherited
References HY_CatchmentArea::output.
Member Data Documentation
bounds
polygon_t HY_CatchmentArea::bounds protected inherited
cascade_backing_storage
std::unordered_map<time_step_t, std::vector<double> > Simple_Lumped_Model_Realization::cascade_backing_storage private
Referenced by Simple_Lumped_Model_Realization(), add_time(), and create_formulation().
cat_id
std::string realization::Catchment_Formulation::cat_id private inherited
Referenced by realization::Catchment_Formulation::get_catchment_id(), and realization::Catchment_Formulation::set_catchment_id().
et_params
std::shared_ptr<pdm03_struct> realization::Et_Accountable::et_params private inherited
Referenced by realization::Bmi_Module_Formulation< M >::calc_et(), realization::Et_Accountable::get_et_params(), realization::Et_Accountable::get_et_params_ptr(), realization::Et_Accountable::is_et_params_set(), and realization::Et_Accountable::set_et_params().
fluxes
std::unordered_map<time_step_t, hymod_fluxes> Simple_Lumped_Model_Realization::fluxes private
Referenced by add_time(), create_formulation(), get_output_line_for_timestep(), and get_response().
forcing
std::shared_ptr<data_access::GenericDataProvider> HY_CatchmentRealization::forcing protected inherited
Referenced by realization::Bmi_Module_Formulation< M >::calc_et(), realization::Bmi_Multi_Formulation::create_multi_formulation(), realization::Bmi_Module_Formulation< M >::determine_model_time_offset(), get_response(), realization::Tshirt_C_Realization::get_response(), realization::Tshirt_Realization::get_response(), and realization::Bmi_Module_Formulation< M >::set_model_inputs_prior_to_update().
id
std::string realization::Formulation::id protected inherited
Referenced by realization::Formulation::get_id().
id_number
unsigned long HY_CatchmentRealization::id_number protected inherited
output
utils::StreamHandler HY_CatchmentArea::output protected inherited
Referenced by realization::Bmi_C_Formulation::construct_model(), realization::Bmi_Cpp_Formulation::construct_model(), realization::Bmi_Multi_Formulation::init_nested_module(), HY_CatchmentArea::set_output_stream(), and HY_CatchmentArea::write_output().
params
hymod_params Simple_Lumped_Model_Realization::params private
Referenced by add_time(), create_formulation(), and get_response().
realized_catchment
shared_ptr<HY_Catchment> HY_CatchmentRealization::realized_catchment protected inherited
REQUIRED_PARAMETERS
std::vector<std::string> Simple_Lumped_Model_Realization::REQUIRED_PARAMETERS protected
Initial value:
= {
            "sr",
            "storage",
            "gw_storage",
            "gw_max_storage",
            "nash_max_storage",
            "smax",
            "a",
            "b",
            "Ks",
            "Kq",
            "n",
            "t"
        }
Referenced by get_required_parameters().
state
std::unordered_map<time_step_t, hymod_state> Simple_Lumped_Model_Realization::state private
Referenced by Simple_Lumped_Model_Realization(), add_time(), create_formulation(), and get_response().
The documentation for this class was generated from the following files:
include/realizations/catchment/Simple_Lumped_Model_Realization.hpp
src/realizations/catchment/Simple_Lumped_Model_Realization.cpp