NGen: ngen::mdarray< T > Class Template Reference
ngen::mdarray< T > Class Template Reference
#include <mdarray.hpp>
Classes
struct iterator
Public Types
using value_type = T
using container_type = std::vector< value_type >
using size_type = typename container_type::size_type
using difference_type = typename container_type::difference_type
using reference = typename container_type::reference
using const_reference = typename container_type::const_reference
using pointer = typename container_type::pointer
using const_pointer = typename container_type::const_pointer
Public Member Functions
mdarray ()=default
mdarray (const boost::span< const size_type > dsizes)
constexpr mdarray (std::initializer_list< size_type > dsizes)
reference at (const boost::span< const size_type > n)
reference operator[] (const boost::span< const size_type > n) noexcept
const_reference at (const boost::span< const size_type > n) const
const_reference operator[] (const boost::span< const size_type > n) const noexcept
void insert (const boost::span< const size_type > n, value_type value)
Insert a multi-dimensonal value at the given index.
void insert (std::initializer_list< std::pair< const boost::span< const size_type >, value_type > > args)
size_type size () const noexcept
Get the size of allocated values in this mdarray (aka the allocated elements in the backing vector)
iterator begin () const noexcept
iterator end () const noexcept
size_type rank () const noexcept
Get the rank of this mdarray.
boost::span< const size_t > shape () const noexcept
Get the shape of this mdarray.
size_type index (const boost::span< const size_type > n) const
Index a multi-dimensional set of indices to a single address index.
void deindex (size_type idx, boost::span< size_type > n) const
Retrieve the multi-dimensional index from a given address index.
Public Attributes
friend iterator
Private Member Functions
template<typename Tp >
size_type max_size (Tp shape)
void bounds_check (const boost::span< const size_type > n) const
Private Attributes
std::vector< size_type > m_shape
container_type m_data
Member Typedef Documentation
const_pointer
template<typename T > using ngen::mdarray< T >::const_pointer = typename container_type::const_pointer
Examples
/github/workspace/include/utilities/mdarray/mdarray.hpp.
const_reference
template<typename T > using ngen::mdarray< T >::const_reference = typename container_type::const_reference
Examples
/github/workspace/include/utilities/mdarray/mdarray.hpp.
container_type
template<typename T > using ngen::mdarray< T >::container_type = std::vector<value_type>
Examples
/github/workspace/include/utilities/mdarray/mdarray.hpp.
difference_type
template<typename T > using ngen::mdarray< T >::difference_type = typename container_type::difference_type
Examples
/github/workspace/include/utilities/mdarray/mdarray.hpp.
pointer
template<typename T > using ngen::mdarray< T >::pointer = typename container_type::pointer
Examples
/github/workspace/include/utilities/mdarray/mdarray.hpp.
reference
template<typename T > using ngen::mdarray< T >::reference = typename container_type::reference
Examples
/github/workspace/include/utilities/mdarray/mdarray.hpp.
size_type
template<typename T > using ngen::mdarray< T >::size_type = typename container_type::size_type
Examples
/github/workspace/include/utilities/mdarray/mdarray.hpp.
value_type
template<typename T > using ngen::mdarray< T >::value_type = T
Examples
/github/workspace/include/utilities/mdarray/mdarray.hpp.
Constructor & Destructor Documentation
mdarray() [1/3]
template<typename T > ngen::mdarray< T >::mdarray () default
Examples
/github/workspace/include/utilities/mdarray/mdarray.hpp.
mdarray() [2/3]
template<typename T > ngen::mdarray< T >::mdarray (const boost::span< const size_type > dsizes) inline
mdarray() [3/3]
template<typename T > constexpr ngen::mdarray< T >::mdarray (std::initializer_list< size_type > dsizes) inline constexpr
Member Function Documentation
at() [1/2]
template<typename T > reference ngen::mdarray< T >::at (const boost::span< const size_type > n) inline
References ngen::mdarray< T >::bounds_check(), ngen::mdarray< T >::index(), and ngen::mdarray< T >::m_data.
at() [2/2]
template<typename T > const_reference ngen::mdarray< T >::at (const boost::span< const size_type > n) const inline
References ngen::mdarray< T >::bounds_check(), ngen::mdarray< T >::index(), and ngen::mdarray< T >::m_data.
begin()
template<typename T > iterator ngen::mdarray< T >::begin () const inline noexcept
Examples
/github/workspace/include/utilities/mdarray/mdarray.hpp.
bounds_check()
template<typename T > void ngen::mdarray< T >::bounds_check (const boost::span< const size_type > n) const inline private
Examples
/github/workspace/include/utilities/mdarray/mdarray.hpp.
References ngen::mdarray< T >::m_shape.
Referenced by ngen::mdarray< T >::at(), and ngen::mdarray< T >::insert().
deindex()
template<typename T > void ngen::mdarray< T >::deindex (size_type idx, boost::span< size_type > n) const inline
Retrieve the multi-dimensional index from a given address index.
Parameters
[in] idx Address index (aka flat index)
[out] n outputted index
Examples
/github/workspace/include/utilities/mdarray/mdarray.hpp.
References ngen::mdarray< T >::m_shape, ngen::mdarray< T >::rank(), ngen::mdarray< T >::size(), and boost::span< T, E >::size().
end()
template<typename T > iterator ngen::mdarray< T >::end () const inline noexcept
Examples
/github/workspace/include/utilities/mdarray/mdarray.hpp.
References ngen::mdarray< T >::m_data.
index()
template<typename T > size_type ngen::mdarray< T >::index (const boost::span< const size_type > n) const inline
Index a multi-dimensional set of indices to a single address index.
Parameters
n
Returns
size_type
Examples
/github/workspace/include/utilities/mdarray/mdarray.hpp.
References ngen::mdarray< T >::index(), ngen::mdarray< T >::m_shape, ngen::mdarray< T >::rank(), and ngen::mdarray< T >::size().
Referenced by ngen::mdarray< T >::at(), ngen::mdarray< T >::index(), ngen::mdarray< T >::insert(), and ngen::mdarray< T >::operator[]().
insert() [1/2]
template<typename T > void ngen::mdarray< T >::insert (const boost::span< const size_type > n, value_type value) inline
Insert a multi-dimensonal value at the given index.
Parameters
n A multi-dimensional index with the same size as m_shape.
value The value to set at the given index.
Examples
/github/workspace/include/utilities/mdarray/mdarray.hpp.
References ngen::mdarray< T >::bounds_check(), ngen::mdarray< T >::index(), and ngen::mdarray< T >::m_data.
Referenced by ngen::mdarray< T >::insert().
insert() [2/2]
template<typename T > void ngen::mdarray< T >::insert (std::initializer_list< std::pair< const boost::span< const size_type >, value_type > > args) inline
References ngen::mdarray< T >::insert().
max_size()
template<typename T > template<typename Tp > size_type ngen::mdarray< T >::max_size (Tp shape) inline private
Examples
/github/workspace/include/utilities/mdarray/mdarray.hpp.
References ngen::mdarray< T >::shape().
operator[]() [1/2]
template<typename T > const_reference ngen::mdarray< T >::operator[] (const boost::span< const size_type > n) const inline noexcept
References ngen::mdarray< T >::index(), and ngen::mdarray< T >::m_data.
operator[]() [2/2]
template<typename T > reference ngen::mdarray< T >::operator[] (const boost::span< const size_type > n) inline noexcept
Examples
/github/workspace/include/utilities/mdarray/mdarray.hpp.
References ngen::mdarray< T >::index(), and ngen::mdarray< T >::m_data.
rank()
template<typename T > size_type ngen::mdarray< T >::rank () const inline noexcept
Get the rank of this mdarray.
Returns
size_type
Examples
/github/workspace/include/utilities/mdarray/mdarray.hpp.
References ngen::mdarray< T >::m_shape.
Referenced by ngen::mdarray< T >::deindex(), and ngen::mdarray< T >::index().
shape()
template<typename T > boost::span< const size_t > ngen::mdarray< T >::shape () const inline noexcept
Get the shape of this mdarray.
Returns
span of the extents per dimension
Examples
/github/workspace/include/utilities/mdarray/mdarray.hpp.
References ngen::mdarray< T >::m_shape.
Referenced by ngen::mdarray< T >::max_size().
size()
template<typename T > size_type ngen::mdarray< T >::size () const inline noexcept
Get the size of allocated values in this mdarray (aka the allocated elements in the backing vector)
Returns
size_type
Examples
/github/workspace/include/utilities/mdarray/mdarray.hpp.
References ngen::mdarray< T >::m_data.
Referenced by ngen::mdarray< T >::deindex(), and ngen::mdarray< T >::index().
Member Data Documentation
iterator
template<typename T > friend ngen::mdarray< T >::iterator
m_data
template<typename T > container_type ngen::mdarray< T >::m_data private
Examples
/github/workspace/include/utilities/mdarray/mdarray.hpp.
Referenced by ngen::mdarray< T >::at(), ngen::mdarray< T >::end(), ngen::mdarray< T >::insert(), ngen::mdarray< T >::operator[](), and ngen::mdarray< T >::size().
m_shape
template<typename T > std::vector<size_type> ngen::mdarray< T >::m_shape private
Examples
/github/workspace/include/utilities/mdarray/mdarray.hpp.
Referenced by ngen::mdarray< T >::bounds_check(), ngen::mdarray< T >::deindex(), ngen::mdarray< T >::index(), ngen::mdarray< T >::rank(), and ngen::mdarray< T >::shape().
The documentation for this class was generated from the following file:
include/utilities/mdarray/mdarray.hpp