NGen: ngen Namespace Reference
ngen Namespace Reference
Namespaces
namespace detail
namespace geopackage
namespace sqlite
namespace srs
namespace traits
Classes
class Layer
class LayerDataStorage
A class to hold and manage layer metadata for the system.
struct LayerDescription
A simple structure to hold meta data related to a computational layer.
class mdarray
class mdframe
A multi-dimensional, tagged data frame.
class SurfaceLayer
Functions
void cartesian_indices_recurse (boost::span< const std::size_t > shape, std::size_t current_dimension_index, std::vector< std::size_t > &index_buffer, std::vector< std::vector< std::size_t > > &output)
void cartesian_indices (const boost::span< const std::size_t > shape, std::vector< std::vector< std::size_t > > &output)
Function Documentation
cartesian_indices()
void ngen::cartesian_indices (const boost::span< const std::size_t > shape, std::vector< std::vector< std::size_t > > & output)
References cartesian_indices_recurse().
Referenced by ngen::mdframe::to_csv().
cartesian_indices_recurse()
void ngen::cartesian_indices_recurse (boost::span< const std::size_t > shape, std::size_t current_dimension_index, std::vector< std::size_t > & index_buffer, std::vector< std::vector< std::size_t > > & output)
Parameters
shape
index
dimension
output
References cartesian_indices_recurse().
Referenced by cartesian_indices(), and cartesian_indices_recurse().