NGen: geopackage Namespace Reference
geopackage Namespace Reference
Classes
class sqlite
Wrapper around a SQLite3 database.
struct sqlite_deleter
Deleter used to provide smart pointer support for sqlite3 structs.
class sqlite_iter
SQLite3 row iterator.
struct wkb
A recursive WKB reader.
Typedefs
using stmt_t = std::unique_ptr< sqlite3_stmt, sqlite_deleter >
Smart pointer (shared) type for sqlite3 prepared statements.
Functions
geojson::geometry build_geometry (const sqlite_iter &row, const std::string &geom_col, std::vector< double > &bounding_box)
Build a geometry object from GeoPackage WKB.
geojson::PropertyMap build_properties (const sqlite_iter &row, const std::string &geom_col)
Build properties from GeoPackage table columns.
geojson::Feature build_feature (const sqlite_iter &row, const std::string &id_col, const std::string &geom_col)
Build a feature from a GPKG table row.
std::shared_ptr< geojson::FeatureCollection > read (const std::string &gpkg_path, const std::string &layer, const std::vector< std::string > &ids)
Build a feature collection from a GPKG layer.
Typedef Documentation
stmt_t
using geopackage::stmt_t = typedef std::unique_ptr<sqlite3_stmt, sqlite_deleter>
Smart pointer (shared) type for sqlite3 prepared statements.
Function Documentation
build_feature()
geojson::Feature geopackage::build_feature (const sqlite_iter & row, const std::string & id_col, const std::string & geom_col)
Build a feature from a GPKG table row.
Parameters
[in] row SQLite iterator at the row to build a feature from
[in] geom_col Name of geometry column containing GPKG WKB
Returns
geojson::Feature Feature containing geometry and properties from the given row
References build_geometry(), build_properties(), geojson::GeometryCollection, geopackage::sqlite_iter::get(), geojson::LineString, geojson::MultiLineString, geojson::MultiPoint, geojson::MultiPolygon, geojson::Point, and geojson::Polygon.
build_geometry()
geojson::geometry geopackage::build_geometry (const sqlite_iter & row, const std::string & geom_col, std::vector< double > & bounding_box)
Build a geometry object from GeoPackage WKB.
Parameters
[in] row SQLite iterator at the row containing a geometry column
[in] geom_col Name of geometry column containing GPKG WKB
[out] bounding_box Bounding box of the geometry to output
Returns
geojson::geometry GPKG WKB converted and projected to a boost geometry model
References utils::copy_from(), and geopackage::sqlite_iter::get().
Referenced by build_feature().
build_properties()
geojson::PropertyMap geopackage::build_properties (const sqlite_iter & row, const std::string & geom_col)
Build properties from GeoPackage table columns.
Parameters
[in] row SQLite iterator at the row containing the data columns
[in] geom_col Name of geometry column containing GPKG WKB to ignore
Returns
geojson::PropertyMap PropertyMap of properties from the given row
References geopackage::sqlite_iter::columns(), and geopackage::sqlite_iter::types().
Referenced by build_feature().
read()
std::shared_ptr< geojson::FeatureCollection > geopackage::read (const std::string & gpkg_path, const std::string & layer = "", const std::vector< std::string > & ids = {})
Build a feature collection from a GPKG layer.
Parameters
[in] gpkg_path Path to GPKG file
[in] layer Layer name within GPKG file to create a collection from
[in] ids optional subset of feature IDs to capture (if empty, the entire layer is converted)
Returns
std::shared_ptr<geojson::FeatureCollection>