NGen: utils Namespace Reference
utils Namespace Reference
Classes
class FileChecker
Simple utility class for testing things about one or more files.
class FileStreamHandler
class StreamHandler
This class provides a copyable interface to a std::ostream or std::ostream like object that may not support being copied.
Functions
template<typename S >
void copy_from (const boost::span< const uint8_t > src, int &index, S &dst, uint8_t order)
Copies bytes from.
template<>
void copy_from< double > (const boost::span< const uint8_t > src, int &index, double &dst, uint8_t order)
static StreamHandler getStdOut ()
static StreamHandler getStdErr ()
Function Documentation
copy_from()
template<typename S > void utils::copy_from (const boost::span< const uint8_t > src, int & index, S & dst, uint8_t order)
Copies bytes from.
Parameters
to
param , converts the endianness to native, and increments
Parameters
by the number of bytes used to store
Template Parameters
S}
Template Parameters
S a primitive type
Parameters
src a vector of bytes
index an integral type tracking the starting position of
's memory
dst output primitive
order endianness value (0x01 == Little; 0x00 == Big)
References boost::span< T, E >::data().
Referenced by ngen::geopackage::build_geometry(), copy_from< double >(), ngen::geopackage::wkb::read(), ngen::geopackage::wkb::read_linestring(), ngen::geopackage::wkb::read_multilinestring(), ngen::geopackage::wkb::read_multipoint(), ngen::geopackage::wkb::read_multipolygon(), ngen::geopackage::wkb::read_point(), and ngen::geopackage::wkb::read_polygon().
copy_from< double >()
template<> void utils::copy_from< double > (const boost::span< const uint8_t > src, int & index, double & dst, uint8_t order) inline
References copy_from().
getStdErr()
static StreamHandler utils::getStdErr () static
getStdOut()
static StreamHandler utils::getStdOut () static