NGen: realization Namespace Reference
realization Namespace Reference
Classes
class Bmi_C_Formulation
class Bmi_Cpp_Formulation
Encapsulates a bmi::Bmi model in C++ such that it can be loaded as a formulation, as such also so that it can be dynamically loaded from a shared library file.
class Bmi_Formulation
Abstraction of formulation with backing model object(s) that implements the BMI.
class Bmi_Module_Formulation
Abstraction of a formulation with a single backing model object that implements the BMI.
class Bmi_Multi_Formulation
Abstraction of a formulation with multiple backing model object that implements the BMI.
class Catchment_Formulation
class ConfigurationException
Custom exception indicating a problem when integrating with the provided realization configuration.
class Et_Accountable
Interface for type that is able to account for evapotranspiration in certain calculations, and thus maintains a set of parameters for ET.
class Et_Aware
Interface for type that is aware of parameters for evapotranspiration in certain calculations, and can accept such parameters being provided.
class Formulation
class Formulation_Manager
Typedefs
typedef std::shared_ptr< Catchment_Formulation >(* constructor) (std::string, shared_ptr< data_access::GenericDataProvider >, utils::StreamHandler)
Functions
template<class T >
static constructor create_formulation_constructor ()
static bool formulation_exists (std::string formulation_type)
static std::shared_ptr< Catchment_Formulation > construct_formulation (std::string formulation_type, std::string identifier, forcing_params &forcing_config, utils::StreamHandler output_stream)
static std::string get_formulation_key (const boost::property_tree::ptree &tree)
Variables
static std::map< std::string, constructor > formulations
Typedef Documentation
constructor
typedef std::shared_ptr< Catchment_Formulation >(* realization::constructor) (std::string, shared_ptr< data_access::GenericDataProvider >, utils::StreamHandler)
Function Documentation
construct_formulation()
static std::shared_ptr< Catchment_Formulation > realization::construct_formulation (std::string formulation_type, std::string identifier, forcing_params & forcing_config, utils::StreamHandler output_stream) static
References formulations, forcing_params::path, forcing_params::provider, forcing_params::simulation_end_t, and forcing_params::simulation_start_t.
Referenced by realization::Formulation_Manager::construct_formulation_from_tree(), and realization::Formulation_Manager::construct_missing_formulation().
create_formulation_constructor()
template<class T > static constructor realization::create_formulation_constructor () static
formulation_exists()
static bool realization::formulation_exists (std::string formulation_type) static
References formulations.
Referenced by get_formulation_key().
get_formulation_key()
static std::string realization::get_formulation_key (const boost::property_tree::ptree & tree) static
References formulation_exists().
Referenced by realization::Formulation_Manager::construct_formulation_from_tree(), and realization::Formulation_Manager::construct_missing_formulation().
Variable Documentation
formulations
std::map<std::string, constructor> realization::formulations static
Initial value:
= {
        {"bmi_c++", create_formulation_constructor<Bmi_Cpp_Formulation>()},
        {"bmi_multi", create_formulation_constructor<Bmi_Multi_Formulation>()},
    }
Referenced by construct_formulation(), and formulation_exists().