NGen: GridDataSelector Struct Reference
GridDataSelector Struct Reference
#include <GridDataSelector.hpp>
Public Member Functions
GridDataSelector (SelectorConfig config, boost::span< const Cell > cells)
Cell-based constructor.
GridDataSelector (SelectorConfig config, const GridSpecification &grid, boost::span< const geojson::coordinate_t > points)
Point-based constructor.
GridDataSelector (SelectorConfig config, const GridSpecification &grid, const geojson::polygon_t &polygon)
Boundary-based constructor.
GridDataSelector (SelectorConfig config, const GridSpecification &grid, const BoundingBox &extent)
Extent-based constructor.
GridDataSelector () noexcept=default
virtual ~GridDataSelector ()=default
time_t & initial_time () noexcept
time_t initial_time () const noexcept
long & duration () noexcept
long duration () const noexcept
std::string & variable () noexcept
const std::string & variable () const noexcept
std::string & units () noexcept
const std::string & units () const noexcept
boost::span< Cell > cells () noexcept
boost::span< const Cell > cells () const noexcept
Static Private Member Functions
static std::uint64_t position_ (double position, double min, double max, std::uint64_t upper_bound)
Private Attributes
SelectorConfig config_
General selector configuration.
std::vector< Cell > cells_
Cells to gather.
Constructor & Destructor Documentation
GridDataSelector() [1/5]
GridDataSelector::GridDataSelector (SelectorConfig config, boost::span< const Cell > cells) inline
Cell-based constructor.
GridDataSelector() [2/5]
GridDataSelector::GridDataSelector (SelectorConfig config, const GridSpecification & grid, boost::span< const geojson::coordinate_t > points) inline
Point-based constructor.
Constructs a selector taking only the cells from grid that correspond to coordinates in points.
Parameters
config Selector configuration options
grid Source grid specification
points Target points used for extraction
Todo
Implementation
References cells(), cells_, GridSpecification::columns, GridSpecification::extent, position_(), GridSpecification::rows, BoundingBox::xmax(), BoundingBox::xmin(), BoundingBox::ymax(), and BoundingBox::ymin().
GridDataSelector() [3/5]
GridDataSelector::GridDataSelector (SelectorConfig config, const GridSpecification & grid, const geojson::polygon_t & polygon) inline
Boundary-based constructor.
Constructs a selector taking only the cells from grid that intersect polygon.
Parameters
config Selector configuration options
grid Source grid specification
polygon Target polygon used as mask
References GridSpecification::columns, GridSpecification::extent, GridSpecification::rows, BoundingBox::xmax(), BoundingBox::xmin(), BoundingBox::ymax(), and BoundingBox::ymin().
GridDataSelector() [4/5]
GridDataSelector::GridDataSelector (SelectorConfig config, const GridSpecification & grid, const BoundingBox & extent) inline
Extent-based constructor.
Parameters
config Selector configuration options
grid Source grid specification
extent Target bounding box used as mask
References GridSpecification::columns, GridSpecification::extent, GridSpecification::rows, BoundingBox::xmax(), BoundingBox::xmin(), BoundingBox::ymax(), and BoundingBox::ymin().
GridDataSelector() [5/5]
GridDataSelector::GridDataSelector () default noexcept
~GridDataSelector()
virtual GridDataSelector::~GridDataSelector () virtual default
Member Function Documentation
cells() [1/2]
boost::span< const Cell > GridDataSelector::cells () const inline noexcept
cells() [2/2]
boost::span< Cell > GridDataSelector::cells () inline noexcept
Referenced by GridDataSelector().
duration() [1/2]
long GridDataSelector::duration () const inline noexcept
duration() [2/2]
long & GridDataSelector::duration () inline noexcept
initial_time() [1/2]
time_t GridDataSelector::initial_time () const inline noexcept
initial_time() [2/2]
time_t & GridDataSelector::initial_time () inline noexcept
position_()
static std::uint64_t GridDataSelector::position_ (double position, double min, double max, std::uint64_t upper_bound) inline static private
Referenced by GridDataSelector().
units() [1/2]
const std::string & GridDataSelector::units () const inline noexcept
units() [2/2]
std::string & GridDataSelector::units () inline noexcept
variable() [1/2]
const std::string & GridDataSelector::variable () const inline noexcept
variable() [2/2]
std::string & GridDataSelector::variable () inline noexcept
Member Data Documentation
cells_
std::vector<Cell> GridDataSelector::cells_ private
Cells to gather.
Referenced by GridDataSelector().
config_
SelectorConfig GridDataSelector::config_ private
General selector configuration.
The documentation for this struct was generated from the following file:
include/forcing/GridDataSelector.hpp