NGen: BoundingBox Struct Reference
BoundingBox Struct Reference
#include <GridDataSelector.hpp>
Public Member Functions
BoundingBox (box_t box)
double xmin () const noexcept
double xmax () const noexcept
double ymin () const noexcept
double ymax () const noexcept
geojson::polygon_t as_polygon () const noexcept
Private Attributes
box_t box_
Constructor & Destructor Documentation
BoundingBox()
BoundingBox::BoundingBox (box_t box) inline
Member Function Documentation
as_polygon()
geojson::polygon_t BoundingBox::as_polygon () const inline noexcept
References box_.
xmax()
double BoundingBox::xmax () const inline noexcept
References box_.
Referenced by GridDataSelector::GridDataSelector(), GridDataSelector::GridDataSelector(), and GridDataSelector::GridDataSelector().
xmin()
double BoundingBox::xmin () const inline noexcept
References box_.
Referenced by GridDataSelector::GridDataSelector(), GridDataSelector::GridDataSelector(), and GridDataSelector::GridDataSelector().
ymax()
double BoundingBox::ymax () const inline noexcept
References box_.
Referenced by GridDataSelector::GridDataSelector(), GridDataSelector::GridDataSelector(), and GridDataSelector::GridDataSelector().
ymin()
double BoundingBox::ymin () const inline noexcept
References box_.
Referenced by GridDataSelector::GridDataSelector(), GridDataSelector::GridDataSelector(), and GridDataSelector::GridDataSelector().
Member Data Documentation
box_
box_t BoundingBox::box_ private
Referenced by as_polygon(), xmax(), xmin(), ymax(), and ymin().
The documentation for this struct was generated from the following file:
include/forcing/GridDataSelector.hpp