NGen: realization::config::Layer Struct Reference
realization::config::Layer Struct Reference
Layer configuration information.
#include <layer.hpp>
Public Member Functions
Layer ()
Construct a new default surface layer.
Layer (const boost::property_tree::ptree &tree)
Construct a new Layer from a property tree.
const ngen::LayerDescription & get_descriptor ()
Get the descriptor associated with this layer configuration.
bool has_formulation ()
Determines if the layer has a valid configured formulation.
const std::string & get_domain ()
Get the domain description.
Public Attributes
Config formulation
The formulation configuration associated with the layer.
Private Attributes
std::string domain
ngen::LayerDescription descriptor
Detailed Description
Layer configuration information.
Constructor & Destructor Documentation
Layer() [1/2]
realization::config::Layer::Layer () inline
Construct a new default surface layer.
Default layers are surface layers (0) with 3600 second time steps
Layer() [2/2]
realization::config::Layer::Layer (const boost::property_tree::ptree & tree) inline
Construct a new Layer from a property tree.
Parameters
tree
References descriptor, and domain.
Member Function Documentation
get_descriptor()
const ngen::LayerDescription & realization::config::Layer::get_descriptor () inline
Get the descriptor associated with this layer configuration.
Returns
const ngen::LayerDescription&
References descriptor.
Referenced by realization::Formulation_Manager::read().
get_domain()
const std::string & realization::config::Layer::get_domain () inline
Get the domain description.
Returns
const std::string&
References domain.
Referenced by realization::Formulation_Manager::read().
has_formulation()
bool realization::config::Layer::has_formulation () inline
Determines if the layer has a valid configured formulation.
Returns
true
false
References formulation, and realization::config::Config::has_formulation().
Referenced by realization::Formulation_Manager::read().
Member Data Documentation
descriptor
ngen::LayerDescription realization::config::Layer::descriptor private
Referenced by Layer(), and get_descriptor().
domain
std::string realization::config::Layer::domain private
Referenced by Layer(), and get_domain().
formulation
Config realization::config::Layer::formulation
The formulation configuration associated with the layer.
Referenced by has_formulation(), and realization::Formulation_Manager::read().
The documentation for this struct was generated from the following file:
include/realizations/config/layer.hpp