NGen: geopackage::wkb Struct Reference
geopackage::wkb Struct Reference
A recursive WKB reader.
#include <WKB.hpp>
Classes
struct wgs84
Public Types
using point_t = bg::model::point< double, 2, bg::cs::cartesian >
using linestring_t = bg::model::linestring< point_t >
using polygon_t = bg::model::polygon< point_t >
using multipoint_t = bg::model::multi_point< point_t >
using multilinestring_t = bg::model::multi_linestring< linestring_t >
using multipolygon_t = bg::model::multi_polygon< polygon_t >
using geometry = boost::variant< point_t, linestring_t, polygon_t, multipoint_t, multilinestring_t, multipolygon_t >
using byte_t = uint8_t
using byte_vector = std::vector< byte_t >
Public Member Functions
wkb ()=delete
Static Public Member Functions
static geometry read (const boost::span< const uint8_t > buffer)
Read WKB from a given buffer.
static bg::srs::dpar::parameters get_prj (uint32_t srid)
Static Private Member Functions
static point_t read_point (const boost::span< const uint8_t >, int &, uint8_t)
Read a WKB point into a cartesian model.
static linestring_t read_linestring (const boost::span< const uint8_t >, int &, uint8_t)
Read a WKB linestring into a cartesian model.
static polygon_t read_polygon (const boost::span< const uint8_t >, int &, uint8_t)
Read a WKB polygon into a cartesian model.
static multipoint_t read_multipoint (const boost::span< const uint8_t >, int &, uint8_t)
Read a WKB multipoint into a cartesian model.
static multilinestring_t read_multilinestring (const boost::span< const uint8_t >, int &, uint8_t)
Read a WKB multilinestring into a cartesian model.
static multipolygon_t read_multipolygon (const boost::span< const uint8_t >, int &, uint8_t)
Read a WKB multipolygon into a cartesian model.
Detailed Description
A recursive WKB reader.
Note
This WKB implementation follows a subset of the OGC Specification found in https://www.ogc.org/standard/sfa/. This is a strict WKB implementation and does not support Extended WKB (EWKB) or Tiny WKB (TWKB).
Member Typedef Documentation
byte_t
using geopackage::wkb::byte_t = uint8_t
byte_vector
using geopackage::wkb::byte_vector = std::vector<byte_t>
geometry
using geopackage::wkb::geometry = boost::variant< point_t, linestring_t, polygon_t, multipoint_t, multilinestring_t, multipolygon_t >
linestring_t
using geopackage::wkb::linestring_t = bg::model::linestring<point_t>
multilinestring_t
using geopackage::wkb::multilinestring_t = bg::model::multi_linestring<linestring_t>
multipoint_t
using geopackage::wkb::multipoint_t = bg::model::multi_point<point_t>
multipolygon_t
using geopackage::wkb::multipolygon_t = bg::model::multi_polygon<polygon_t>
point_t
using geopackage::wkb::point_t = bg::model::point<double, 2, bg::cs::cartesian>
polygon_t
using geopackage::wkb::polygon_t = bg::model::polygon<point_t>
Constructor & Destructor Documentation
wkb()
geopackage::wkb::wkb () delete
Member Function Documentation
get_prj()
bg::srs::dpar::parameters wkb::get_prj (uint32_t srid) static
EPSG 5070 and 3857 projection definitions for use with boost::geometry.
Note
these are required because boost 1.72.0 does not have an EPSG definition for 5070 or 3857 in boost::srs::epsg.
read()
wkb::geometry wkb::read (const boost::span< const uint8_t > buffer) static
Read WKB from a given buffer.
Parameters
[in] buffer byte vector buffer
Returns
geometry wkb::geometry struct containing the geometry data from the buffer
References utils::copy_from(), read_linestring(), read_multilinestring(), read_multipoint(), read_multipolygon(), read_point(), read_polygon(), and boost::span< T, E >::size().
read_linestring()
wkb::linestring_t wkb::read_linestring (const boost::span< const uint8_t > buffer, int & index, uint8_t order) static private
Read a WKB linestring into a cartesian model.
Returns
linestring_t
References utils::copy_from(), and read_point().
Referenced by read(), read_multilinestring(), and read_polygon().
read_multilinestring()
wkb::multilinestring_t wkb::read_multilinestring (const boost::span< const uint8_t > buffer, int & index, uint8_t order) static private
Read a WKB multilinestring into a cartesian model.
Returns
multilinestring_t
References utils::copy_from(), and read_linestring().
Referenced by read().
read_multipoint()
wkb::multipoint_t wkb::read_multipoint (const boost::span< const uint8_t > buffer, int & index, uint8_t order) static private
Read a WKB multipoint into a cartesian model.
Returns
multipoint_t
References utils::copy_from(), and read_point().
Referenced by read().
read_multipolygon()
wkb::multipolygon_t wkb::read_multipolygon (const boost::span< const uint8_t > buffer, int & index, uint8_t order) static private
Read a WKB multipolygon into a cartesian model.
Returns
multipolygon_t
References utils::copy_from(), and read_polygon().
Referenced by read().
read_point()
wkb::point_t wkb::read_point (const boost::span< const uint8_t > buffer, int & index, uint8_t order) static private
Read a WKB point into a cartesian model.
Returns
point_t
References utils::copy_from().
Referenced by read(), read_linestring(), and read_multipoint().
read_polygon()
wkb::polygon_t wkb::read_polygon (const boost::span< const uint8_t > buffer, int & index, uint8_t order) static private
Read a WKB polygon into a cartesian model.
Returns
polygon_t
References utils::copy_from(), and read_linestring().
Referenced by read(), and read_multipolygon().
The documentation for this struct was generated from the following files:
include/geopackage/WKB.hpp
src/geopackage/wkb.cpp