name: bmi_test
channels:
  - defaults
  - anaconda
  - conda-forge
dependencies:
  - bmipy
  - bokeh
  - pandas
  - python=3.7
  - ruamel.yaml
  - netCDF4
  - mpi4py
  - ESMF
  - datetime
  - netCDF4
  - os
  - time
  - pathlib
