name: bmi_test
channels:
  - defaults
  - anaconda
  - conda-forge
dependencies:
  - bmipy
  - jinjabmi
  - bokeh
  - pandas
  - python=3.7
  - ruamel.yaml
  - netCDF4
  - numpy
  - ssl
  - wget
  - pathlib
  - os
