NGen: NonlinearReservoirKernelTest Class Reference
NonlinearReservoirKernelTest Class Reference
Protected Member Functions
void SetUp () override
void TearDown () override
void setupNoOutletNonlinearReservoir ()
void setupOneOutletNonlinearReservoir ()
void setupOneOutletHighStorageNonlinearReservoir ()
void setupMultipleOutletNonlinearReservoir ()
void setupMultipleOutletOutOfOrderNonlinearReservoir ()
Protected Attributes
std::shared_ptr< Nonlinear_Reservoir > NoOutletReservoir
std::shared_ptr< Nonlinear_Reservoir > OneOutletReservoir
std::shared_ptr< Nonlinear_Reservoir > OneOutletHighStorageReservoir
std::shared_ptr< Nonlinear_Reservoir > MultipleOutletReservoir
std::shared_ptr< Nonlinear_Reservoir > MultipleOutletOutOfOrderNonlinearReservoir
std::shared_ptr< Reservoir_Outlet > ReservoirOutlet1
std::shared_ptr< Reservoir_Outlet > ReservoirOutlet2
std::shared_ptr< Reservoir_Outlet > ReservoirOutlet3
std::vector< Reservoir_Outlet > ReservoirOutletsVector
std::vector< Reservoir_Outlet > ReservoirOutletsVectorOutOfOrder
Member Function Documentation
SetUp()
void NonlinearReservoirKernelTest::SetUp () override protected
References setupMultipleOutletNonlinearReservoir(), setupMultipleOutletOutOfOrderNonlinearReservoir(), setupNoOutletNonlinearReservoir(), setupOneOutletHighStorageNonlinearReservoir(), and setupOneOutletNonlinearReservoir().
setupMultipleOutletNonlinearReservoir()
void NonlinearReservoirKernelTest::setupMultipleOutletNonlinearReservoir () protected
References MultipleOutletReservoir, ReservoirOutlet1, ReservoirOutlet2, ReservoirOutlet3, and ReservoirOutletsVector.
Referenced by SetUp().
setupMultipleOutletOutOfOrderNonlinearReservoir()
void NonlinearReservoirKernelTest::setupMultipleOutletOutOfOrderNonlinearReservoir () protected
References MultipleOutletOutOfOrderNonlinearReservoir, ReservoirOutlet1, ReservoirOutlet2, ReservoirOutlet3, and ReservoirOutletsVectorOutOfOrder.
Referenced by SetUp().
setupNoOutletNonlinearReservoir()
void NonlinearReservoirKernelTest::setupNoOutletNonlinearReservoir () protected
References NoOutletReservoir.
Referenced by SetUp().
setupOneOutletHighStorageNonlinearReservoir()
void NonlinearReservoirKernelTest::setupOneOutletHighStorageNonlinearReservoir () protected
References OneOutletHighStorageReservoir.
Referenced by SetUp().
setupOneOutletNonlinearReservoir()
void NonlinearReservoirKernelTest::setupOneOutletNonlinearReservoir () protected
References OneOutletReservoir.
Referenced by SetUp().
TearDown()
void NonlinearReservoirKernelTest::TearDown () override protected
Member Data Documentation
MultipleOutletOutOfOrderNonlinearReservoir
std::shared_ptr<Nonlinear_Reservoir> NonlinearReservoirKernelTest::MultipleOutletOutOfOrderNonlinearReservoir protected
Referenced by setupMultipleOutletOutOfOrderNonlinearReservoir().
MultipleOutletReservoir
std::shared_ptr<Nonlinear_Reservoir> NonlinearReservoirKernelTest::MultipleOutletReservoir protected
Referenced by setupMultipleOutletNonlinearReservoir().
NoOutletReservoir
std::shared_ptr<Nonlinear_Reservoir> NonlinearReservoirKernelTest::NoOutletReservoir protected
Referenced by setupNoOutletNonlinearReservoir().
OneOutletHighStorageReservoir
std::shared_ptr<Nonlinear_Reservoir> NonlinearReservoirKernelTest::OneOutletHighStorageReservoir protected
Referenced by setupOneOutletHighStorageNonlinearReservoir().
OneOutletReservoir
std::shared_ptr<Nonlinear_Reservoir> NonlinearReservoirKernelTest::OneOutletReservoir protected
Referenced by setupOneOutletNonlinearReservoir().
ReservoirOutlet1
std::shared_ptr<Reservoir_Outlet> NonlinearReservoirKernelTest::ReservoirOutlet1 protected
Referenced by setupMultipleOutletNonlinearReservoir(), and setupMultipleOutletOutOfOrderNonlinearReservoir().
ReservoirOutlet2
std::shared_ptr<Reservoir_Outlet> NonlinearReservoirKernelTest::ReservoirOutlet2 protected
Referenced by setupMultipleOutletNonlinearReservoir(), and setupMultipleOutletOutOfOrderNonlinearReservoir().
ReservoirOutlet3
std::shared_ptr<Reservoir_Outlet> NonlinearReservoirKernelTest::ReservoirOutlet3 protected
Referenced by setupMultipleOutletNonlinearReservoir(), and setupMultipleOutletOutOfOrderNonlinearReservoir().
ReservoirOutletsVector
std::vector<Reservoir_Outlet> NonlinearReservoirKernelTest::ReservoirOutletsVector protected
Referenced by setupMultipleOutletNonlinearReservoir().
ReservoirOutletsVectorOutOfOrder
std::vector<Reservoir_Outlet> NonlinearReservoirKernelTest::ReservoirOutletsVectorOutOfOrder protected
Referenced by setupMultipleOutletOutOfOrderNonlinearReservoir().
The documentation for this class was generated from the following file:
test/models/hymod/include/Nonlinear_Reservoir_Test.cpp