NGen: realization::Realization_Config_Base Class Reference
realization::Realization_Config_Base Class Reference
#include <Realization_Config.hpp>
Public Member Functions
Realization_Config_Base (std::string id, boost::property_tree::ptree &config, Realization_Config global=nullptr)
Realization_Config assign_id (std::string new_id)
Realization_Type get_realization_type ()
std::shared_ptr< HY_CatchmentRealization > get_realization ()
std::shared_ptr< Simple_Lumped_Model_Realization > get_simple_lumped ()
std::shared_ptr< Tshirt_Realization > get_tshirt ()
geojson::JSONProperty get_option (std::string option_name) const
forcing_params get_forcing_parameters ()
bool has_option (std::string option_name) const
bool has_giuh ()
bool has_forcing ()
std::string get_id () const
double get_response (double input_flux, time_step_t t, time_step_t dt, void *et_params)
Private Member Functions
Realization_Config_Base (std::string new_id, Realization_Config_Base *original)
std::shared_ptr< giuh::GiuhJsonReader > get_giuh_reader ()
Private Attributes
geojson::PropertyMap options
Realization_Type realization_type = Realization_Type::NONE
geojson::PropertyMap forcing_parameters
geojson::PropertyMap giuh
std::string id
std::shared_ptr< HY_CatchmentRealization > realization = NULL
Constructor & Destructor Documentation
Realization_Config_Base() [1/2]
realization::Realization_Config_Base::Realization_Config_Base (std::string id, boost::property_tree::ptree & config, Realization_Config global = nullptr) inline
References forcing_parameters, realization::get_realization_type(), has_forcing(), options, and realization_type.
Referenced by assign_id().
Realization_Config_Base() [2/2]
realization::Realization_Config_Base::Realization_Config_Base (std::string new_id, Realization_Config_Base * original) inline private
References forcing_parameters, giuh, options, and realization_type.
Member Function Documentation
assign_id()
Realization_Config realization::Realization_Config_Base::assign_id (std::string new_id) inline
References Realization_Config_Base().
get_forcing_parameters()
forcing_params Realization_Config_Base::get_forcing_parameters ()
References forcing_parameters, and has_forcing().
Referenced by get_simple_lumped(), and get_tshirt().
get_giuh_reader()
std::shared_ptr< giuh::GiuhJsonReader > Realization_Config_Base::get_giuh_reader () private
References has_giuh().
Referenced by get_tshirt().
get_id()
std::string Realization_Config_Base::get_id () const
References id.
get_option()
geojson::JSONProperty Realization_Config_Base::get_option (std::string option_name) const
References has_option(), and options.
Referenced by get_simple_lumped(), and get_tshirt().
get_realization()
std::shared_ptr< HY_CatchmentRealization > Realization_Config_Base::get_realization ()
References get_realization_type(), realization::get_realization_type_name(), get_simple_lumped(), get_tshirt(), realization, and realization_type.
Referenced by get_response().
get_realization_type()
Realization_Type realization::Realization_Config_Base::get_realization_type () inline
References realization_type.
Referenced by get_realization().
get_response()
double Realization_Config_Base::get_response (double input_flux, time_step_t t, time_step_t dt, void * et_params)
References get_realization().
get_simple_lumped()
std::shared_ptr< Simple_Lumped_Model_Realization > Realization_Config_Base::get_simple_lumped ()
References geojson::JSONProperty::as_natural_number(), geojson::JSONProperty::as_real_number(), get_forcing_parameters(), get_option(), has_option(), and realization::REQUIRED_HYMOD_PARAMETERS.
Referenced by get_realization().
get_tshirt()
std::shared_ptr< Tshirt_Realization > Realization_Config_Base::get_tshirt ()
References geojson::JSONProperty::as_natural_number(), geojson::JSONProperty::as_real_number(), get_forcing_parameters(), get_giuh_reader(), get_option(), has_option(), and realization::REQUIRED_TSHIRT_PARAMETERS.
Referenced by get_realization().
has_forcing()
bool Realization_Config_Base::has_forcing ()
References forcing_parameters.
Referenced by get_forcing_parameters(), and Realization_Config_Base().
has_giuh()
bool Realization_Config_Base::has_giuh ()
Referenced by get_giuh_reader().
has_option()
bool Realization_Config_Base::has_option (std::string option_name) const
References options.
Referenced by get_option(), get_simple_lumped(), and get_tshirt().
Member Data Documentation
forcing_parameters
geojson::PropertyMap realization::Realization_Config_Base::forcing_parameters private
Referenced by get_forcing_parameters(), has_forcing(), and Realization_Config_Base().
giuh
geojson::PropertyMap realization::Realization_Config_Base::giuh private
Referenced by Realization_Config_Base().
id
std::string realization::Realization_Config_Base::id private
Referenced by get_id().
options
geojson::PropertyMap realization::Realization_Config_Base::options private
Referenced by get_option(), has_option(), and Realization_Config_Base().
realization
std::shared_ptr<HY_CatchmentRealization> realization::Realization_Config_Base::realization = NULL private
Referenced by get_realization().
realization_type
Realization_Type realization::Realization_Config_Base::realization_type = Realization_Type::NONE private
Referenced by get_realization(), get_realization_type(), and Realization_Config_Base().
The documentation for this class was generated from the following files:
include/realizations/catchment/Realization_Config.hpp
src/realizations/catchment/Realization_Config.cpp