#include <NGenConfig.h>

#if NGEN_WITH_NETCDF
#include <vector>
#include <cstdio>
#include <netcdf>
#include "gtest/gtest.h"
#include "NetCDFPerFeatureDataProvider.hpp"
#include "StreamHandler.hpp"
#include "FileChecker.h"
#include <memory>
#include <vector>
#include <string>
#include <unistd.h>
#include <stdio.h>
#include <limits.h>
#include <ctime>
#include <time.h>


using data_access::NetCDFPerFeatureDataProvider;

class NetCDFPerFeatureDataProviderTest : public ::testing::Test {

    protected:

    void SetUp() override;

    void TearDown() override;

    void setupForcing();

    std::string forcing_file_name;
    std::unique_ptr<forcing_params> forcing_p;
    std::shared_ptr<data_access::NetCDFPerFeatureDataProvider> nc_provider;
    typedef struct tm time_type;
    std::shared_ptr<time_type> start_date_time;
    std::shared_ptr<time_type> end_date_time;
};

void NetCDFPerFeatureDataProviderTest::SetUp() {
    setupForcing();
}


void NetCDFPerFeatureDataProviderTest::TearDown() {
}

//Construct a forcing object
void NetCDFPerFeatureDataProviderTest::setupForcing() {

	//Updated to load sample file generated by forcings engine - KSL
    std::vector<std::string> forcing_file_names = { 
        "data/forcing/NextGen_Forcings_Engine_HYDROFABRIC_output_202410180600.nc",
        "../data/forcing/NextGen_Forcings_Engine_HYDROFABRIC_output_202410180600.nc",
        "../../data/forcing/NextGen_Forcings_Engine_HYDROFABRIC_output_202410180600.nc"
        };

    forcing_file_name = utils::FileChecker::find_first_readable(forcing_file_names);

    // Using this to compute epoch times... this is what's done in Formulation_Constructors.hpp, FWIW...
    forcing_p = std::make_unique<forcing_params>(forcing_file_name, NetCDF", "2024-10-18 07:00:00", "2024-10-18 21:00:00");

    nc_provider = std::make_shared<data_access::NetCDFPerFeatureDataProvider>(forcing_file_name, forcing_p.simulation_start_t, forcing_p.simulation_end_t, utils::getStdErr() );
    start_date_time = std::make_shared<time_type>();
    end_date_time = std::make_shared<time_type>();
}

///Test AORC Forcing Object
TEST_F(NetCDFPerFeatureDataProviderTest, TestForcingDataReadUsingIds)
{
    std::vector<std::string> ids = {"cat-27", "cat-52", "cat-67"};

    NetCDFPerFeatureDataProvider nc_provider(forcing_file_name, forcing_p->simulation_start_t, forcing_p->simulation_end_t, utils::getStdErr() );
    for(const std::string& id: ids){
        nc_provider.hint_shared_provider_id(id);
    }

    auto start_time = nc_provider.get_data_start_time();
    auto duration = nc_provider.record_duration();

    double tol = 0.00002;
    std::array<double, 3> expected = {285.8, 285.9, 285.7};
    size_t i = 0;
    // read exactly one time step correctly aligned
    for (const double expect: expected){
        double result = nc_provider.get_value(CatchmentAggrDataSelector(ids[i], CSDMS_STD_NAME_SURFACE_TEMP, start_time, duration, "K"), data_access::MEAN);
        EXPECT_NEAR(result, expect, tol);
        i++;
    }

    ASSERT_EQ(ids, nc_provider.get_ids());
}

TEST_F(NetCDFPerFeatureDataProviderTest, TestForcingDataReadUsingIdsIsNotReverse)
{
    std::vector<std::string> ids = {"cat-27", "cat-52", "cat-67"};
    auto rev = ids;
    std::reverse(rev.begin(), rev.end());

    NetCDFPerFeatureDataProvider nc_provider(forcing_file_name, forcing_p->simulation_start_t, forcing_p->simulation_end_t, utils::getStdErr() );
    for(const std::string& id: ids){
        nc_provider.hint_shared_provider_id(id);
    }

    auto start_time = nc_provider.get_data_start_time();
    auto duration = nc_provider.record_duration();

    double tol = 0.00002;
    std::array<double, 3> expected = {285.8, 285.9, 285.7};
    size_t i = 0;
    // read exactly one time step correctly aligned
    for (const double expect: expected){
        double result = nc_provider.get_value(CatchmentAggrDataSelector(ids[i], CSDMS_STD_NAME_SURFACE_TEMP, start_time, duration, "K"), data_access::MEAN);
        EXPECT_NEAR(result, expect, tol);
        i++;
    }
    auto ids_out = nc_provider.get_ids();
    ASSERT_NE(rev, ids_out);
    ASSERT_EQ(ids, ids_out);
}

TEST_F(NetCDFPerFeatureDataProviderTest, TestForcingDataReadUsingIdsSingle)
{
    std::vector<std::string> ids = {"cat-52"};
    NetCDFPerFeatureDataProvider nc_provider(forcing_file_name, forcing_p->simulation_start_t, forcing_p->simulation_end_t, utils::getStdErr() );
    nc_provider.hint_shared_provider_id(ids[0]);

    auto start_time = nc_provider.get_data_start_time();
    auto duration = nc_provider.record_duration();

    double tol = 0.00002;
    double value = nc_provider.get_value(CatchmentAggrDataSelector(ids[0], CSDMS_STD_NAME_SURFACE_TEMP, start_time, duration, "K"), data_access::MEAN);
    EXPECT_NEAR(value, 285.9, tol);
    ASSERT_EQ(ids, nc_provider.get_ids());
}

TEST_F(NetCDFPerFeatureDataProviderTest, TestForcingDataReadSpan)
{
    std::vector<std::string> ids = {"cat-52", "cat-67"};
    NetCDFPerFeatureDataProvider nc_provider(forcing_file_name, forcing_p->simulation_start_t, forcing_p->simulation_end_t, utils::getStdErr() );
    for (const std::string& id: ids){
        nc_provider.hint_shared_provider_id(id);
    }

    auto start_time = nc_provider.get_data_start_time();
    auto duration = nc_provider.record_duration();

    double tol = 0.00002;
    std::array<double, 2> expected = {285.9, 285.7};
    size_t i = 0;
    // read exactly one time step correctly aligned
    for (const double expect: expected){
        double result = nc_provider.get_value(CatchmentAggrDataSelector(ids[i], CSDMS_STD_NAME_SURFACE_TEMP, start_time, duration, "K"), data_access::MEAN);
        EXPECT_NEAR(result, expect, tol);
        i++;
    }
    ASSERT_EQ(ids, nc_provider.get_ids());
}

TEST_F(NetCDFPerFeatureDataProviderTest, TestForcingDataReadMultiSpan)
{
    std::vector<std::string> ids = {"cat-27", "cat-67"};
    NetCDFPerFeatureDataProvider nc_provider(forcing_file_name, forcing_p->simulation_start_t, forcing_p->simulation_end_t, utils::getStdErr() );
    for (const std::string& id: ids){
        nc_provider.hint_shared_provider_id(id);
    }

    auto start_time = nc_provider.get_data_start_time();
    auto duration = nc_provider.record_duration();

    double tol = 0.00002;
    std::array<double, 2> expected = {285.8, 285.7};
    size_t i = 0;
    // read exactly one time step correctly aligned
    for (const double expect: expected){
        double result = nc_provider.get_value(CatchmentAggrDataSelector(ids[i], CSDMS_STD_NAME_SURFACE_TEMP, start_time, duration, "K"), data_access::MEAN);
        EXPECT_NEAR(result, expect, tol);
        i++;
    }
    ASSERT_EQ(ids, nc_provider.get_ids());
}

///Test AORC Forcing Object
TEST_F(NetCDFPerFeatureDataProviderTest, TestForcingDataRead)
{
    // check to see that the variable "T2D" exists
    auto var_names = nc_provider->get_available_variable_names();

    auto pos = std::find(var_names.begin(), var_names.end(), CSDMS_STD_NAME_SURFACE_TEMP);
    if ( pos != var_names.end() )
    {
        //std::cout << "Found variable "<<CSDMS_STD_NAME_SURFACE_TEMP<<"\n";
    }
    else
    {
        //std::cout << "The variable "<<CSDMS_STD_NAME_SURFACE_TEMP<<" is missing\n";
        FAIL();
    }

    auto start_time = nc_provider->get_data_start_time();

    auto ids = nc_provider->get_ids();

    auto duration = nc_provider->record_duration();

    //std::cout << "Checking values in catchment "<<ids[0]<<" at time "<<start_time<<" with duration "<<duration<<"..."<<std::endl;

    // read exactly one time step correctly aligned
    double val1 = nc_provider->get_value(CatchmentAggrDataSelector(ids[0], CSDMS_STD_NAME_SURFACE_TEMP, start_time, duration, "K"), data_access::MEAN);

    //double tol = 0.00000612;
    double tol = 0.00002;

	// Updated value to match sample file. Note that raw values are altered by add_offset and scale_factor to convert to K - KSL
    EXPECT_NEAR(val1, 17743, tol);

    // read 1/2 of a time step correctly aligned
    double val2 = nc_provider->get_value(CatchmentAggrDataSelector(ids[0], CSDMS_STD_NAME_SURFACE_TEMP, start_time, duration / 2, "K"), data_access::MEAN);

	// Updated value to match sample file. Note that raw values are altered by add_offset and scale_factor to convert to K - KSL
    EXPECT_NEAR(val2, 17743, tol);

	// Updated value to match sample file. Note that raw values are altered by add_offset and scale_factor to convert to K - KSL
    // read 4 time steps correctly aligned
    double val3 = nc_provider->get_value(CatchmentAggrDataSelector(ids[0], CSDMS_STD_NAME_SURFACE_TEMP, start_time, duration * 4, "K"), data_access::MEAN);

    EXPECT_NEAR(val3, 17842.5, tol);

    // read exactly one time step correctly aligned but with a incorrect variable
    EXPECT_THROW(
        double val4 = nc_provider->get_value(CatchmentAggrDataSelector(ids[0], "T3D", start_time, duration, "K"), data_access::MEAN);, 
        std::runtime_error);

}

// Regression tests for the paged value cache in get_value().
// Files are generated on the fly so the time dimension size and the NetCDF
// chunking (which determines the cache line size) can be controlled exactly.
class NetCDFCacheLayoutTest : public ::testing::Test {
  protected:
    void TearDown() override {
        for (const auto& p : temp_files) {
            std::remove(p.c_str());
        }
    }

    static double cellValue(std::size_t cat, std::size_t t) {
        return 100.0 * cat + t;
    }

    // Creates a forcing file with n_cats catchments ("cat-0".."cat-N"), n_times
    // hourly timesteps starting at kStartEpoch, and one variable "temp" (units K)
    // holding cellValue(cat, t). time_chunk == 0 leaves the variable contiguous.
    std::string makeForcing(const std::string& name, std::size_t n_cats, std::size_t n_times, std::size_t time_chunk) {
        std::string path = "./" + name;
        temp_files.push_back(path);

        netCDF::NcFile out(path, netCDF::NcFile::replace, netCDF::NcFile::nc4);
        auto cat_dim = out.addDim("catchment-id", n_cats);
        auto time_dim = out.addDim("time", n_times);
        std::vector<netCDF::NcDim> dims = {cat_dim, time_dim};

        std::vector<std::string> id_strs;
        std::vector<const char*> id_ptrs;
        for (std::size_t i = 0; i < n_cats; ++i) {
            id_strs.push_back("cat-" + std::to_string(i));
        }
        for (const auto& s : id_strs) {
            id_ptrs.push_back(s.c_str());
        }
        auto ids_var = out.addVar("ids", netCDF::ncString, cat_dim);
        ids_var.putVar(id_ptrs.data());

        auto time_var = out.addVar("Time", netCDF::ncDouble, dims);
        time_var.putAtt("units", "seconds since 1970-01-01 00:00:00");
        std::vector<double> times(n_cats * n_times);
        for (std::size_t i = 0; i < n_cats; ++i) {
            for (std::size_t t = 0; t < n_times; ++t) {
                times[i * n_times + t] = kStartEpoch + t * kStride;
            }
        }
        time_var.putVar(times.data());

        auto temp_var = out.addVar("temp", netCDF::ncDouble, dims);
        temp_var.putAtt("units", "K");
        if (time_chunk > 0) {
            std::vector<std::size_t> chunk_sizes = {n_cats, time_chunk};
            temp_var.setChunking(netCDF::NcVar::nc_CHUNKED, chunk_sizes);
        }
        std::vector<double> vals(n_cats * n_times);
        for (std::size_t i = 0; i < n_cats; ++i) {
            for (std::size_t t = 0; t < n_times; ++t) {
                vals[i * n_times + t] = cellValue(i, t);
            }
        }
        temp_var.putVar(vals.data());

        return path;
    }

    static double readStep(NetCDFPerFeatureDataProvider& p, std::size_t cat, std::size_t t) {
        CatchmentAggrDataSelector sel("cat-" + std::to_string(cat), "temp",
                                      kStartEpoch + t * kStride, kStride, "K");
        return p.get_value(sel, data_access::MEAN);
    }

    static constexpr time_t kStartEpoch = 1500000000;
    static constexpr time_t kStride = 3600;
    std::vector<std::string> temp_files;
};

// A file with fewer timesteps than the default cache line size (24) produces a
// single page whose line length is the whole time dimension.
TEST_F(NetCDFCacheLayoutTest, SinglePageShorterThanCacheLine)
{
    const std::size_t n_cats = 3, n_times = 10;
    auto path = makeForcing("nc_cache_single_page.nc", n_cats, n_times, 0);
    NetCDFPerFeatureDataProvider provider(path, kStartEpoch, kStartEpoch + n_times * kStride, utils::getStdErr());

    for (std::size_t cat = 0; cat < n_cats; ++cat) {
        for (std::size_t t = 0; t < n_times; ++t) {
            EXPECT_DOUBLE_EQ(readStep(provider, cat, t), cellValue(cat, t))
                << "cat=" << cat << " t=" << t;
        }
    }

    // whole-range aggregate read within the single page
    CatchmentAggrDataSelector all("cat-1", "temp", kStartEpoch, n_times * kStride, "K");
    double expected_sum = 0;
    for (std::size_t t = 0; t < n_times; ++t) {
        expected_sum += cellValue(1, t);
    }
    EXPECT_DOUBLE_EQ(provider.get_value(all, data_access::SUM), expected_sum);
}

// A time dimension not divisible by the cache line size leaves a shorter final
// page; per-catchment reads there must use the final page's row stride.
TEST_F(NetCDFCacheLayoutTest, PartialLastPageRead)
{
    const std::size_t n_cats = 3, n_times = 50, chunk = 24; // pages: 24, 24, 2
    auto path = makeForcing("nc_cache_partial_page.nc", n_cats, n_times, chunk);
    NetCDFPerFeatureDataProvider provider(path, kStartEpoch, kStartEpoch + n_times * kStride, utils::getStdErr());

    for (std::size_t cat = 0; cat < n_cats; ++cat) {
        for (std::size_t t = 0; t < n_times; ++t) {
            EXPECT_DOUBLE_EQ(readStep(provider, cat, t), cellValue(cat, t))
                << "cat=" << cat << " t=" << t;
        }
    }
}

// A multi-timestep read whose range starts mid-page and crosses a page
// boundary must access every page the range spans.
TEST_F(NetCDFCacheLayoutTest, ReadStraddlesPageBoundary)
{
    const std::size_t n_cats = 3, n_times = 50, chunk = 24; // pages: 24, 24, 2
    auto path = makeForcing("nc_cache_straddle.nc", n_cats, n_times, chunk);
    NetCDFPerFeatureDataProvider provider(path, kStartEpoch, kStartEpoch + n_times * kStride, utils::getStdErr());

    double tol = 1e-9;

    // timesteps 23..24 straddle the boundary between pages 0 and 1
    CatchmentAggrDataSelector two("cat-1", "temp", kStartEpoch + 23 * kStride, 2 * kStride, "K");
    EXPECT_NEAR(provider.get_value(two, data_access::MEAN),
                (cellValue(1, 23) + cellValue(1, 24)) / 2.0, tol);

    // timesteps 44..49 span page 1 and the partial final page
    CatchmentAggrDataSelector six("cat-2", "temp", kStartEpoch + 44 * kStride, 6 * kStride, "K");
    double expected_mean = 0;
    for (std::size_t t = 44; t < 50; ++t) {
        expected_mean += cellValue(2, t);
    }
    expected_mean /= 6.0;
    EXPECT_NEAR(provider.get_value(six, data_access::MEAN), expected_mean, tol);

    // the whole series spans all three pages
    CatchmentAggrDataSelector all("cat-0", "temp", kStartEpoch, n_times * kStride, "K");
    double expected_sum = 0;
    for (std::size_t t = 0; t < n_times; ++t) {
        expected_sum += cellValue(0, t);
    }
    EXPECT_NEAR(provider.get_value(all, data_access::SUM), expected_sum, tol);
}

// Each recognized time `units` token maps to the expected unit and scale factor,
// and a bare units string reports no reference epoch.
TEST(NetCDFTimeMetadata, InterpretTimeUnitsRecognized)
{
    using P = NetCDFPerFeatureDataProvider;
    struct Case { const char* str; P::TimeUnit unit; double scale; };
    const std::vector<Case> cases = {
        {"h",            P::TIME_HOURS,        3600},
        {"hours",        P::TIME_HOURS,        3600},
        {"m",            P::TIME_MINUTES,      60},
        {"minutes",      P::TIME_MINUTES,      60},
        {"s",            P::TIME_SECONDS,      1},
        {"seconds",      P::TIME_SECONDS,      1},
        {"ms",           P::TIME_MILLISECONDS, .001},
        {"milliseconds", P::TIME_MILLISECONDS, .001},
        {"us",           P::TIME_MICROSECONDS, .000001},
        {"microseconds", P::TIME_MICROSECONDS, .000001},
        {"ns",           P::TIME_NANOSECONDS,  .000000001},
        {"nanoseconds",  P::TIME_NANOSECONDS,  .000000001},
    };
    for (const auto& c : cases) {
        auto info = P::interpret_time_units(c.str);
        ASSERT_TRUE(info.has_value()) << "expected to recognize unit '" << c.str << "'";
        EXPECT_EQ(info->unit, c.unit) << "unit mismatch for '" << c.str << "'";
        EXPECT_DOUBLE_EQ(info->scale_factor, c.scale) << "scale mismatch for '" << c.str << "'";
        EXPECT_FALSE(info->epoch_start_time.has_value()) << "bare units must not set an epoch for '" << c.str << "'";
    }
}

// CF "<unit> since <date>" units yield the base unit plus the embedded reference epoch.
TEST(NetCDFTimeMetadata, InterpretTimeUnitsCFSinceEpoch)
{
    using P = NetCDFPerFeatureDataProvider;
    auto secs = P::interpret_time_units("seconds since 1970-01-01 00:00:00");
    ASSERT_TRUE(secs.has_value());
    EXPECT_EQ(secs->unit, P::TIME_SECONDS);
    EXPECT_DOUBLE_EQ(secs->scale_factor, 1);
    ASSERT_TRUE(secs->epoch_start_time.has_value());
    EXPECT_EQ(*secs->epoch_start_time, 0);

    auto hrs = P::interpret_time_units("hours since 2000-01-01 00:00:00");
    ASSERT_TRUE(hrs.has_value());
    EXPECT_EQ(hrs->unit, P::TIME_HOURS);
    EXPECT_DOUBLE_EQ(hrs->scale_factor, 3600);
    ASSERT_TRUE(hrs->epoch_start_time.has_value());
    EXPECT_EQ(*hrs->epoch_start_time, 946684800);
}

// Unrecognized or empty unit strings yield no value, so callers keep their defaults.
TEST(NetCDFTimeMetadata, InterpretTimeUnitsUnrecognized)
{
    using P = NetCDFPerFeatureDataProvider;
    EXPECT_FALSE(P::interpret_time_units("").has_value());
    EXPECT_FALSE(P::interpret_time_units("days").has_value());
    EXPECT_FALSE(P::interpret_time_units("fortnights").has_value());
}

// parse_epoch converts a timestamp to UTC epoch seconds and honors the supplied format.
TEST(NetCDFTimeMetadata, ParseEpoch)
{
    using P = NetCDFPerFeatureDataProvider;
    // unambiguous 4-digit-year format
    EXPECT_EQ(P::parse_epoch("1970-01-01 00:00:00", "%Y-%m-%d %H:%M:%S"), 0);
    EXPECT_EQ(P::parse_epoch("1970-01-02 00:00:00", "%Y-%m-%d %H:%M:%S"), 86400);
    EXPECT_EQ(P::parse_epoch("2000-01-01 00:00:00", "%Y-%m-%d %H:%M:%S"), 946684800);
    // the provider's default epoch string and format
    EXPECT_EQ(P::parse_epoch("01/01/1970 00:00:00", "%D %T"), 0);
    // a timestamp that doesn't match the format is an error, not a silent zero
    EXPECT_THROW(P::parse_epoch("not a date", "%Y-%m-%d %H:%M:%S"), std::runtime_error);
}
#endif
