name: C/C++ CI

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master    
jobs:
  build:

    runs-on: self-hosted
# host needs: g++, boost, boost-devel and cmake    
    steps:
    - name: clear previous temp dirs
      run: for i in $(seq 8 0); do [ -d temp_${i} ] && mv temp_${i} temp_$((i+1)) ; done
    - name: mkdir temp_0
      run: mkdir temp_0 && cd temp_0
    - uses: actions/checkout@v2
    - name: git submodule
      run: git submodule update --init --recursive -- test/googletest
    - name: cmake_init_build
      run: cmake -DCMAKE_BUILD_TYPE=Debug -B cmake-build-debug -S .
    - name: build_tests
      run: cmake --build cmake-build-debug --target test_all -- -j 4
      timeout-minutes: 15
    - name: run_tests
      run: ./cmake_build/test/test_all
      timeout-minutes: 15
    #- name: make check
    #  run: make check
    #- name: make distcheck
    #  run: make distcheck
    - name: cleanup 
      run: cd /home/Z/ && rm -rf /temp_0
