name: C/C++ CI

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master    
jobs:
  build:

    runs-on: self-hosted
    
    steps:
    - name: mkdir temp
      run: mkdir temp && cd temp
    - uses: actions/checkout@v2
    - name: git submodule
      run: git submodule update --init --recursive 
    - name: cmake_init_build
      run: cmake -D CMAKE_CXX_COMPILER=/usr/bin/gcc -B cmake_build-S .
    - name: build_tests
      run: cmake --build cmake_build --target test_all
      timeout-minutes: 15    
    - name: run tests
      run: ./cmake_build/test/test_all
      timeout-minutes: 15
    #- name: make check
    #  run: make check
    #- name: make distcheck
    #  run: make distcheck
    - name: cleanup 
      run: cd /home/Z/ && rm -rf /temp
